### PR TITLE
[CYS Woo Express] Update large footer

### LINKED ISSUE #11395: [CYS Woo Express] Large footer
Please review `Large Footer`.

How it currently looks like:

image

image

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2313-131651&mode=design&t=qkpAGsXW7rY6XBmF-4)

image

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2313-131475&mode=design&t=qkpAGsXW7rY6XBmF-4)

image

### PR DESCRIPTION
**Pull request by albarin**
## What
This PR:
- Fixes the general padding of the pattern.
- Removes some unnecessary spacing blocks.
- Adds the third menu.
- Fixes the `Powered by...` row.
- Adds the Twitch icon to the social menu.

## Why

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11395

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new page or post.
2. Insert the `Large Footer` pattern.
3. Check that it looks like the design.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Desktop |
| ------ | 
|     Screenshot 2023-10-23 at 14 52 19   |  

| Mobile |
| ------ | 
|     Screenshot 2023-10-23 at 14 54 43   |  

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Update the "Large footer" pattern.

### CODE REVIEW

**Comment by albarin** [comment]
@verofasulo Could you have a look before we merge? 🙏 (sorry the comments are a bit repetitive, most of the issues are the same as in the other PRs). 

Some considerations/limitations we found:
1. I haven't changed the icons color to black since we don't want to hardcode colors.
2. The font size of the `Powered by..`. is a bit bigger than in the designs, because we are not hardcoding font sizes, it's the default font.

On mobile:
1. The `Powered by...` is shown in two lines (because of point 2), it's aligned to the center because we cannot choose a different alignment in mobile, so this is a consequence of having it centered on desktop.

**Comment by verofasulo** [comment]
Thanks, @albarin!

As mentioned in another issue, could we please update the logo size (from 100x100px to 60x60px)? 

Can we review the spacing between social icons and update it to 16px as in the design (it might already be this way, but I can't check from the screenshot)? 🙏 

Also, can we review if the spacing between these three blocks is actually 40px?

image

It looks bigger in the screenshot above but it might be just an optical effect. Thank you 🙏

**Comment by albarin** [comment]
> Thanks, @albarin!
> 
> As mentioned in another issue, could we please update the logo size (from 100x100px to 60x60px)?

Is 60px wide check https://github.com/woocommerce/woocommerce-blocks/pull/11413/files#diff-417a85752bf9bbb3d5661759769505c0f0ad501379176cd531564102aac1881cR18, sorry the dummy image I used is misleading 🙏 

> Can we review the spacing between social icons and update it to 16px as in the design (it might already be this way, but I can't check from the screenshot)? 🙏

Done, you can see here https://github.com/woocommerce/woocommerce-blocks/pull/11413/files#diff-417a85752bf9bbb3d5661759769505c0f0ad501379176cd531564102aac1881cR32

> Also, can we review if the spacing between these three blocks is actually 40px?
> image
> 
> It looks bigger in the screenshot above but it might be just an optical effect. Thank you 🙏

I can confirm 👇 
Screenshot 2023-10-23 at 16 49 52

**Comment by verofasulo** [comment]
@albarin, you're awesome! Thank you 💜

**Review by tjcafferkey — APPROVED** [review]

**Pull request merged**
