### PR TITLE
Fix Stylebook filter blocks preview

### LINKED ISSUE #8175: Style Book: old versions of the Filter by Attribute, Stock and Price are displayed
## To reproduce

0. With WordPress 6.2 (or a previous version with GB installed) and a block theme like [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) enabled.
1. Go to Appearance > Editor and edit a template.
2. In the toolbar, select Styles (black and white circle) and then, Open Style Book (eye icon).
3. Go to the WooCommerce tab.
4. Notice the Filter by Attribute block displays an old version of the block with the option to Upgrade.

Filter by Attribute block in the Style Book

## Expected behavior

The most recent version of Filter by Attribute should be displayed, so there the banner to 'upgrade' the block is not displayed.

### PR DESCRIPTION
**Pull request by gigitux**
This PR fixes the filter blocks preview on Stylebook. The error was caused by the filter wrapper and the logic to render the notice. It isn't necessary to render the notice when the `isPreview` attribute is set to true.

All the filter blocks have the `isPreview` attribute, except for the Price Filter block. This PR fixes this too.

Fixes #8175

### Screenshots

| Before | After |
| ------ | ----- |
|image|image|
|image|image|
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

0. With WordPress 6.2 (or a previous version with GB installed) and a block theme like [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) enabled.
1. Go to Appearance > Editor and edit a template.
2. In the toolbar, select Styles (black and white circle) and then, Open Style Book (eye icon).
3. Go to the WooCommerce tab.
4. Be sure that the `Filter Attributes`, `Filter Price` and `Filter Stock` blocks preview don't have any notice

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Filter blocks: Fix preview on Stylebook

### CODE REVIEW

**Comment by nefeline** [comment]
Thanks for working on this @gigitux !

I see the PR was moved back to draft, but sharing my insights as I worked through this issue last week:

> The error was caused by the filter wrapper and the logic to render the notice. It isn't necessary to render the notice when the isPreview attribute is set to true.

IMO hiding the notice is not the solution for this problem, as we are still rendering the older version of these blocks on Stylebook. In other words, the preview displayed in the editor currently differs from what is displayed on Stylebook.

I've explored many different avenues for solving this last week. Still, I couldn't find a path that wouldn't involve a bigger change, or even a refactor of these blocks given [the way they are currently structured](https://github.com/woocommerce/woocommerce-blocks/pull/6978): I was curious about what would be your approach/thoughts on this as the Porter this week: looks like we are converging to the same conclusions regarding the need of a bigger change.

**Comment by gigitux** [comment]
Hi @nefeline, thanks for your great feedback!
This is the reason why I put the PR in draft status :'( 

I will explain what I discovered, I will use the `Filter by Stock Controls` as an example, but the concept is the same for all the blocks.

I noticed that the Style Book previews the `Filter by Stock Controls`. In the editor, `Filter by Stock Controls` corresponds to the checkbox list. The wrapper (that it is another block) adds the header ([source code](https://github.com/woocommerce/woocommerce-blocks/blob/09e942b32d83b46e18c9a15851eb23fdec265d2c/assets/js/blocks/filter-wrapper/index.tsx)).

We have two options:
- hide the header in the edit.js of the `Filter by Stock Controls`, so it will be visible the checkbox list.
- hide the preview of the `Filter by Stock Controls` and show the preview of the `Filter Wrapper` block (I don't understand why the filter wrapper isn't rendered on the Style Book, also I don't think that it supports multiple variations of the same block).

image
image


Also, I noticed another issue. At the current stage, some blocks are ready to use the [example property](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#example) in the block.json  , while others no. So, for example, the filter blocks (except for the Filter Attribute) fetch the WP Rest API to get the data. Theoretically, the blocks in “preview mode” should use the attributes in the examples property. Rewrite the logic to use the attributes in the example property could require some time. Should we do this in this first iteration or should we postpone this?

**Comment by gigitux** [comment]
I think that the right approach is to show the preview of the `Filter Wrapper`. Unfortunately, it seems that Style Book doesn't support the preview of multiple variations of the same block. I opened an issue https://github.com/WordPress/gutenberg/issues/47443

cc @Aljullu

**Comment by gigitux** [comment]
Since that https://github.com/woocommerce/woocommerce-blocks/pull/8309 has been merged, I'm going to close this PR.

**Pull request closed without merging**
