### PR TITLE
New custom endpoints

### LINKED ISSUE #153: Products & product info are not available to editors, block cannot show live preview
Users with role=editor or lower (author, contributor, etc) don't have the capabilities to edit/manage products or product categories, so the API doesn't let them list products. This causes the block preview to appear broken, never loading products or product categories (probably attributes too). The API response for these users is:

```
{
	"code":"woocommerce_rest_cannot_view",
	"message":"Sorry, you cannot list resources.",
	"data":{"status":403}
}
```

Should we…

- change the API to allow any logged in user to view products/product categories/attributes?
- Or should we only register the product block for admins & shop_managers (who already have permissions to see products etc)?

### PR DESCRIPTION
**Pull request by claudiosanches**
Introduced 4 new endpoints, where we only check for `edit_posts` capability, so should allow any contributor or high role user to work with this endpoints.

New endpoints:

- `/wc-pb/v3/products`
- `/wc-pb/v3/products/categories`
- `/wc-pb/v3/products/attributes`
- `/wc-pb/v3/products/attributes/<id>/terms`

Also included PHPCS and pre-commit hook.

Fixes #153

### How to test the changes in this Pull Request:

1. Try create product blocks
2. Try create using filters per attributes
3. Try with categories

### CODE REVIEW

**Comment by claudiosanches** [comment]
@ryelle done.

**Comment by claudiulodro** [comment]
Works great in my testing. Just the couple issues mentioned already. Good work, and thanks for getting this done in a hurry! 🏆

**Comment by claudiosanches** [comment]
@ryelle I just fixed the unit tests. I'll include more unit tests after we merge the `composer.json`.

**Comment by ryelle** [comment]
@claudiosanches Looks like there's a conflict here now– do you want to fix it & wrap up anything else before merge, or do you want me to take over?

**Comment by claudiosanches** [comment]
@ryelle All fixed now.

**Pull request merged**
