### PR TITLE
Remove Single Product Block

### PR DESCRIPTION
**Pull request by gigitux**
Since we are working on the new Single Product block (#8610), it makes sense to clean up the codebase removing some blocks that are under the experimental flag.

This PR removes:
- Single Product Block.
- Category List Block.
- Tag List Block.

#### User Facing Testing

1. Be sure that E2E tests pass.
2. Run `npm run build`.
3. Open the Post Editor and be sure that any 404 error is visible in the console.
4. Open the Site Editor and be sure that any 404 error is visible in the console.

* [x] Do not include in the Testing Notes

### CODE REVIEW

**Comment by roykho** [comment]
I am seeing some console errors with this change.

```
GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-summary.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
post-new.php:2296          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-category-list.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
post-new.php:2317          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/single-product.js?ver=9.9.0-dev 404 (Not Found)
post-new.php:2303          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-tag-list.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
```

**Comment by gigitux** [comment]
Thanks for the review!
In my env, I saw only the 404 error for the Product Single block. I fixed it via c57f2650067ad29493a540b338b41edfa7f50f5b. Can you check again?

**Comment by roykho** [comment]
While the `single-product.js` error is now gone, I am still seeing the other three errors and only in this PR branch. If I checkout `trunk` error goes away. I am seeing it just by going to `Pages->Add new`.

```
post-new.php:2296          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-category-list.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
post-new.php:2301          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-summary.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
post-new.php:2303          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-tag-list.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
```

**Comment by gigitux** [comment]
> While the `single-product.js` error is now gone, I am still seeing the other three errors and only in this PR branch. If I checkout `trunk` error goes away. I am seeing it just by going to `Pages->Add new`.
> 
> ```
> post-new.php:2296          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-category-list.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
> post-new.php:2301          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-summary.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
> post-new.php:2303          GET http://gitwooplugins.test/wp-content/plugins/woocommerce-blocks/build/product-tag-list.js?ver=9.9.0-dev net::ERR_ABORTED 404 (Not Found)
> ```

Did you try to re-run the build from scratch?

**Comment by roykho** [comment]
Yeah I did.

**Comment by roykho** [comment]
Ok after more testing here is what I've found. If you run `npm run start` it seems to work. But if you run `npm run build`, it doesn't.

**Review by thealexandrelara — APPROVED** [review]
LGTM! 🚀

**Comment by gigitux** [comment]
Thanks for the review, @roykho! I updated the PR and the description too. Could you do another review, please?

**Review by roykho — APPROVED** [review]
LGTM! The initially reported errors seems to be gone now. Good job!

**Pull request merged**
