### PR TITLE
Adjust `Follow us on social media` pattern icon alignment

### LINKED ISSUE #10667: Follow us in social media Pattern > check if its possible to align the social icons to the left on mobile
Following up on the feedback received from the design team on pdnLyh-3Tv-p2#comment-2860, we need to check if its possible to align the social icons to the left on mobile for the "Follow us in social media" pattern and update it if possible:

Screenshot 2023-08-18 at 16 54 16

### PR DESCRIPTION
**Pull request by danielwrobert**
## What

This adjusts the alignment of the social media icons for the **Follow us in social media** pattern, improving the layout on mobile.

Additionally, the name and heading in the pattern is adjusted from **Follow us in social media** to **Follow us on social media** (subtle grammar update).

Note that, due to the limitations we have with mobile and media queries in patterns, this is not the _ideal_ fix. However, it seems to be an improvement from the current layout.

Fixes #10667 

## Why

This is being done as a follow-up from design feedback in pdnLyh-3Tv-p2#comment-2860. As noted in #10667, the right alignment of the icon list on mobile looks broken.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new post or page.
2. Insert the **Follow us on social media** Pattern.
3. Confirm the pattern is correctly displayed in the editor.
4. Save the post and head over to the front end and confirm the pattern is correctly displayed both on desktop and mobile view (the layout should match the one demonstrated in the above screenshots in the After column and in the screencast under the Updated section).

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots

| Before | After |
| ------ | ----- |
| CleanShot 2023-08-22 at 21 49 02 | CleanShot 2023-08-22 at 21 50 42 |

## Screencast

https://github.com/woocommerce/woocommerce-blocks/assets/481776/a4aaab81-97a0-4b6c-9ba6-51ed7a28c409

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Adjust the alignment of the social media icons for the **Follow us in social media** pattern, improving the layout on mobile.

### CODE REVIEW

**Review by danieldudzic — APPROVED** [review]
The pattern displays correctly both in the editor and frontend ✅ 

The tiniest of things:

The testing steps still are referring to `Follow us in social media` instead of `Follow us on social media`.

**Comment by danielwrobert** [comment]
> The testing steps still are referring to `Follow us in social media` instead of `Follow us on social media`.

@danieldudzic nice catch, thanks. Updated!

**Comment by nefeline** [comment]
LGTM! I'm bumping the milestone since we are awaiting a design review.

**Comment by shaunandrews** [comment]
Hmmm, not ideal, but slightly better. Feel free to ship. Is there specific feedback we can provide to Gutenberg around this? I guess its the usual "we need viewport or responsive options..."

**Comment by danielwrobert** [comment]
@shaunandrews agreed, not ideal. But, with the limitations we have around media queries in this context, I couldn't really come up with anything better.

> I guess its the usual "we need viewport or responsive options..."

Exactly.

Thanks for the review, I'll ship it for now. Hopefully we can revisit in the future with better control options!

**Pull request merged**
