### PR TITLE
Refactor Aliases for Internal Imports

### LINKED ISSUE #5396: Module aliases conflict with eslint `dependency-group` rule
We currently use this custom ESLint rule: eslint(@woocommerce/dependency-group) which makes us group internal and external dependencies in import statements separately.

The rule, however, considers our aliased module starting with `@woocommerce/` to be external, which not only defeats the purpose of the rule, but it actually makes it worse, because now people reading the code are explicitly told that something internal is actually an external dependency. This is confusing for newcomers and just people reading the codebase alike.

Luckily, the rule allows for an option to include a RegEx for module paths that should be considered internal.

However, in our repo, sometimes the `@woocommerce/` prefix indicates internal modules, sometimes external. This issue was already brought up in a [P2 Post](pca54o-19D-p2) by @ralucaStan in March 2021.

The proposal is thus to rename our internal aliases and add the RegEx to the ESLint rule.

Slack conversation: p1639581735170200-slack-C8X6Q7XQU
P2 Post: pca54o-19D-p2

### LINKED ISSUE #42658: Module aliases conflict with eslint `dependency-group` rule
We currently use this custom ESLint rule: eslint(@woocommerce/dependency-group) which makes us group internal and external dependencies in import statements separately.

The rule, however, considers our aliased module starting with `@woocommerce/` to be external, which not only defeats the purpose of the rule, but it actually makes it worse, because now people reading the code are explicitly told that something internal is actually an external dependency. This is confusing for newcomers and just people reading the codebase alike.

Luckily, the rule allows for an option to include a RegEx for module paths that should be considered internal.

However, in our repo, sometimes the `@woocommerce/` prefix indicates internal modules, sometimes external. This issue was already brought up in a [P2 Post](pca54o-19D-p2) by @ralucaStan in March 2021.

The proposal is thus to rename our internal aliases and add the RegEx to the ESLint rule.

Slack conversation: p1639581735170200-slack-C8X6Q7XQU
P2 Post: pca54o-19D-p2

### PR DESCRIPTION
**Pull request by mikejolley**
## What

This PR renames aliases and moves them to the `Internal Dependencies` section. This obviously touches many of the files and is a large change so we should be sure tests pass and smoke tests are successful before merging, but shouldn't leave it too long to merge because it will quickly become stale.

In general this PR:

1. Removes aliases that map to paths in favour of `~/` prefixed paths. For example, `@woocommerce/base-components` becomes `~/base/components`.
2. Leaves `packages` imports as-is.
3. Leaves externals (handled by dependency extraction) as-is.

I implemented to `~/` prefix because this is compatible with the linting rules for internal imports. If we use a different prefix, the package which implements this linting rule will need supporting changes.

Fixes woocommerce/woocommerce#42658

## Why

Removing and renaming the aliases makes it clearer which imports are actually internal.

> The rule, however, considers our aliased module starting with @woocommerce/ to be external, which not only defeats the purpose of the rule, but it actually makes it worse, because now people reading the code are explicitly told that something internal is actually an external dependency. This is confusing for newcomers and just people reading the codebase alike.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Successfully perform a dev build without errors.
2. Smoke test a cross section of block functionality.
3. Successfully perform a production build without errors.
5. Smoke test a cross section of block functionality using the built zip file.

Tests should also all pass before approval.

* [ ] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by nerrad** [comment]
Any concerns about the incorrect assumption that consumers might make about the `~/` prefix and how it is usually resolved to user directories in bash/zsh? I wonder if we should use something more "special" instead?

**Comment by mikejolley** [comment]
@nerrad The p2 suggested either `@alias` or `~`. I don't think there is a standard. I chose `~/` because it would also support the linting rules here:

https://github.com/woocommerce/woocommerce/blob/b6657403f83e5e7e058542d5100a6edac1a2d804/packages/js/eslint-plugin/rules/dependency-group.js#L35-L40

If we change the prefix, we'll need to update the above linting rule as well, or support custom rules.

**Comment by nerrad** [comment]
> If we change the prefix, we'll need to update the above linting rule as well, or support custom rules.

I understand and that's something I'd prefer.

Using `~/` seems too similar to an expected path construct as opposed to something special. The [equivalent ESLint rule in the WordPress package](https://github.com/WordPress/gutenberg/blob/1fb0d7b557f60ec23e3a956c2ee0b90d36ac53b4/packages/eslint-plugin/rules/dependency-group.js#L55-L63) doesn't lint for `~/` so I did some look up to see why this was added to the Woo lint rules came up with https://github.com/woocommerce/woocommerce-admin/pull/6517. Doing a quick Google search for `~` (tilde) symbol used in imports indicates it has specific meaning in different contexts.

**Comment by mikejolley** [comment]
@nerrad Looking at the admin PR it says `Allow files to import items from the root client directory by using ~.`.

Isn't that what I've done here? Instead of `client` its from the `assets/js` directory. You can see that all the alias rules were replaced by this one rule, and everything follows our directory structure from there:

https://github.com/woocommerce/woocommerce-blocks/pull/11935/files?file-filters%5B%5D=.json&show-viewed-files=true#diff-0b280a445be167f54cd916c0718c952b8e0d4ca9621903d05eec25efd4c6ed6dR26

```
"~/*": [ "assets/js/*" ],
```

So there seems to be precedent already for this.

**Comment by nerrad** [comment]
> Isn't that what I've done here? Instead of client its from the assets/js directory. 

Yup, it's effectively the same (just a different path in the config). 

> So there seems to be precedent already for this.

While I agree there is precedent in the Woo Core repo, I still had concerns about the overloaded meaning for `~` in different contexts from a brief search (example [parcel](https://parceljs.org/features/dependency-resolution/#tilde-specifiers) - although the meaning is similar in Parcel). However, in the end, it doesn't look like there's any real standard about this. Since this is more applicable to the internal build process, maybe it's not a big deal 🤷🏻.

To be clear, my comments shouldn't be construed as a blocker.

**Pull request closed without merging**
