### PR TITLE
Product Query: Remove the “Products on Sale” Product Query variation

### PR DESCRIPTION
**Pull request by sunyatasattva**
Given that we are using quick presets (#7621) as opposed to specific block variations, we are removing this from the repo to avoid pollution and unused code.

See more context here: pdnLyh-2jZ-p2#comment-1685

#### User Facing Testing

1. Go to the editor and type `/` to summon the inserter.
2. Look for the “Products on Sale“ block (not the “On Sale Products” -_-") and notice it's not there.
3. Look for the “Products (Beta)” block and notice it's there and it can still be added without errors.

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### CODE REVIEW

**Review by danieldudzic — CHANGES_REQUESTED** [review]
I have found the following leftover references to the "Products on Sale" block. Should we also remove them, as a part of this PR?

https://github.com/woocommerce/woocommerce-blocks/blob/8397832c1ca9bbfd149d56b1a9176ee857f47d4e/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md?plain=1#L52

https://github.com/woocommerce/woocommerce-blocks/blob/8397832c1ca9bbfd149d56b1a9176ee857f47d4e/assets/js/blocks/product-query/types.ts#L116

https://github.com/woocommerce/woocommerce-blocks/blob/8397832c1ca9bbfd149d56b1a9176ee857f47d4e/tests/e2e/specs/backend/product-query.test.ts#L74

**Comment by sunyatasattva** [comment]
Excellent finds! Thank you @danieldudzic !

**Comment by thealexandrelara** [comment]
I tested and confirmed the changes are working! One thing that I realized is that there is a mention to the deleted file in: `docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md`, on line 49:
```
-   Products on Sale ([JS flag](https://github.com/woocommerce/woocommerce-blocks/blob/6547881939b1aa4825562d05fb06808515bf33c2/assets/js/blocks/product-query/variations/products-on-sale.tsx/#L22-L23)).
```
I think we may need to remove it from there

**Comment by sunyatasattva** [comment]
🤦‍♀️  I thought I did but I had removed it from the wrong branch! Thanks Ali!

**Review by thealexandrelara — APPROVED** [review]
Great! Approving the PR!

**Pull request merged**
