### PR TITLE
Product-details: Add margin spacing controls

### LINKED ISSUE #10337: Single Product Template (FSE) > Product Detail Block > margin / padding not available
There is no way to add margin / padding on this block, controls are missing
i had to add a spacer instead, which is not gently :-)

image

Add the missing controls, actually we cannot fine tune it

image

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10337

This PR adds the Dimensions control (margins) to the product details.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

#### User Facing Testing

1. Go to Site Editor->Templates->Single Product.
2. Click on Edit.
3. Focus on the `Product Details` block.
4. You should see `Dimensions` controls in the Inspector controls panel.
5. Click `+` and add some top/bottom/left/right margins and witness the preview is changing accordingly. Then click Save.
6. In the frontend, go to your single product page and ensure you see the added margins from step 5.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Product-details: Add margin spacing controls

### CODE REVIEW

**Review by imanish003 — COMMENTED** [review]
Looks like `margin-left` and `margin-right` aren't working on the frontend as they are being overridden by other styles, as you can see in the screenshot below:

image


Are you able to reproduce this issue? 🙂

**Comment by roykho** [comment]
Hi @imanish003 - yes sorry I forgot to mention that in the PR (now updated). I don't think we can get around that unless we impose an even more specific selector and also with `!important` which seems silly. Perhaps we remove `margin-left` and `margin-right` only? What do you think?

**Comment by imanish003** [comment]
Hey @roykho 👋 

> Hi [@imanish003](https://github.com/imanish003) - yes sorry I forgot to mention that in the PR (now updated). I don't think we can get around that unless we impose an even more specific selector and also with `!important` which seems silly. Perhaps we remove `margin-left` and `margin-right` only? What do you think?
> 

IMHO if it's possible to achieve this without using `!important`, then we should definitely try to avoid it. But if it's not possible, then it makes sense to remove the left and right margins.

I have one idea and would like to hear your thoughts on this. What if we add `margin-left` and `margin-right` to the children of `woocommerce/product-details`, as shown in the screenshot below:

image

As you can see, the children are Woocommerce tabs, which are calculated [here](https://github.com/woocommerce/woocommerce-blocks/blob/4090b9fbcede1c3fa0638e7406461f708cab45a8/src/BlockTypes/ProductDetails.php#L34):

```tsx
$tabs = $this->render_tabs();
```

To add styles to `$tabs`, we may use [WP_HTML_Tag_Processor](https://developer.wordpress.org/reference/classes/wp_html_tag_processor/).

What do you think? Does it make sense to add styles to the children to avoid using `!important`?

**Comment by roykho** [comment]
Hi @imanish003 thanks for the suggestion. I explored your idea however I found two issues.

- It was added since WP 6.2. Which means we probably have to write additional code to account for WP < 6.2.
- We have to refactor the AbstractBlock class to hook in at a different time because at the time of the render method, [WP_HTML_Tag_Processor](https://developer.wordpress.org/reference/classes/wp_html_tag_processor/) is not available yet.

So I came up with another solution which is just to add an additional div. Its not as semantic but it does the job without too much effort.

Please see:
https://github.com/woocommerce/woocommerce-blocks/pull/10440/commits/e444b0d8549ecbcb65434ed898cf43a3ccf53c31

**Review by imanish003 — APPROVED** [review]
Hey @roykho, I tested the PR & margin control is working as expected therefore I am approving the PR 🚀 

Here are some of my thoughts on the comment you left:

> It was added since WP 6.2. Which means we probably have to write additional code to account for WP < 6.2.
> 

I'm not entirely convinced of this since you can refer to the code **[here](https://github.com/woocommerce/woocommerce-blocks/blob/31bf9dbf5c4293477a93ba8c173736e693bf55b6/woocommerce-gutenberg-products-block.php#L10)**:

```jsx
* Requires at least: 6.2
```

This clearly indicates that our existing plugin version mandates WP 6.2 or above. As a result, we're at liberty to utilize any feature/API introduced in WP 6.2. Is there something I'm overlooking? 🤔

> We have to refactor the AbstractBlock class to hook in at a different time because at the time of the render method, [WP_HTML_Tag_Processor](https://developer.wordpress.org/reference/classes/wp_html_tag_processor/) is not available yet.
> 

Oh, interesting. We're already using it [here](https://github.com/woocommerce/woocommerce-blocks/blob/31bf9dbf5c4293477a93ba8c173736e693bf55b6/src/BlockTypes/ProductQuery.php#L100) within our codebase, so I assumed we could employ it in this context as well.

> So I came up with another solution which is just to add an additional div. Its not as semantic but it does the job without too much effort.
> 

I find this idea appealing.

- Have you pondered over any scenarios in which it might disrupt a theme?
    - I think it shouldn’t break any theme because, on additional div, we are just adding the styles added by user using Global styles. Right?

**Pull request merged**
