### PR TITLE
Move usage of wordpress-components to editor and replace with @wordpress/components (checkout-shipping-methods)

### PR DESCRIPTION
**Pull request by kmanijak**
There are two versions of a library used in the repo:
- `@wordpress-components` - dedicated to use in the editor
- `wordpress-components` - dedicated to use in the frontend.

However the library itself is not intended to be used in the frontend, hence the movement to remove such dependency.

This PR is a step towards that goal. (Issue: https://github.com/woocommerce/woocommerce-blocks/issues/8452)

`NoShippingPlaceholder` component uses `Placeholder` and `Button` from `wordpress-components`. Component is supposed be rendered ONLY in the editor, hence it made sense to move the usage to editor only.

No new feature was added, hence testing steps are to confirm there's no regression.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Make sure you didn't setup any shipping methods. It can be checked in here: `wp-admin/admin.php?page=wc-settings&tab=shipping&section`
2. Create new post
3. Add a Checkout block.

**Expected:** Placeholder is displayed in a Shipping Options section
image

4. Save the post and go to frontend

**Expected:** Shipping options are not displayed

5. Add a shipping option (`wp-admin/admin.php?page=wc-settings&tab=shipping&section`, Add Shipping Zone -> Go through the form)
6. Go back to the post in editor

**Expected:** There's no Placeholder in Shipping Options
image

7. Go to the frontend

**Expected:** Shipping options are there

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

**Changelog skipped on purpose**

### CODE REVIEW

**Comment by nefeline** [comment]
Nice improvement 🎉 !

Test results:

> Make sure you didn't setup any shipping methods. It can be checked in here: wp-admin/admin.php?page=wc-settings&tab=shipping&section
> Create new post
> Add a Checkout block.
> Expected: Placeholder is displayed in a Shipping Options section

✅ Confirmed the placeholder is displayed.

> Save the post and go to frontend
> Expected: Shipping options are not displayed

✅ Confirmed the shipping options are not displayed

> Add a shipping option (wp-admin/admin.php?page=wc-settings&tab=shipping&section, Add Shipping Zone -> Go through the form)
> Go back to the post in editor
> Expected: There's no Placeholder in Shipping Options

✅ ❔  Confirmed that the shipping options are displayed, not the placeholder. One oddity observed, which might not be related to the changes done here, is that even though I had the Local Pickup option enabled, it didn't show up in the editor, only on the FE:

Editor:
Screenshot 2023-02-21 at 21 51 26

FE:
Screenshot 2023-02-21 at 21 51 38

> Go to the frontend
> Expected: Shipping options are there

✅  Confirmed the shipping options are there

Apart from the oddity with the Local Pickup shipping option (there's a mismatch of what is displayed in the editor x what is displayed on the FE), everything else seems a-ok here! I'm deferring the approval to Rubik 👍

**Comment by kmanijak** [comment]
Thanks @nefeline for the review!

> One oddity observed, which might not be related to the changes done here, is that even though I had the Local Pickup option enabled, it didn't show up in the editor, only on the FE

I think in the Editor there's just a preview displaying a fixed set of methods. But yes, let's have it confirmed by Rubik 🙌

**Comment by opr** [comment]
> One oddity observed, which might not be related to the changes done here, is that even though I had the Local Pickup option enabled, it didn't show up in the editor, only on the FE

I am not seeing this, I can see it in the editor.
image


I also see options in the editor despite having no shipping options set up.

image
<hr> 
image

**Review by opr — COMMENTED** [review]
> One oddity observed, which might not be related to the changes done here, is that even though I had the Local Pickup option enabled, it didn't show up in the editor, only on the FE

I am not seeing this, I can see it in the editor.
image


I also see options in the editor despite having no shipping options set up.

image
<hr> 
image

**Comment by nefeline** [comment]
> I am not seeing this, I can see it in the editor.

@opr The difference is not in the shipping method (I see the same as you do). The difference noted was when comparing the Shipping Options between the editor x the FE while having Local pickup enabled:

Screenshot 2023-02-23 at 23 11 48

> I think in the Editor there's just a preview displaying a fixed set of methods.

@kmanijak Yeah, it looks like it! I don't think this is coming from this PR in any way, but figured it could be worth flagging (and perhaps opening a separate issue later on, if needed (unless this is intentional)).

**Review by opr — APPROVED** [review]
@nefeline OK thanks for confirming!

@kmanijak I did a fresh clone of the repo and retried, looks like it's working well now!

> Make sure you didn't setup any shipping methods. It can be checked in here: wp-admin/admin.php?page=wc-settings&tab=shipping&section
Create new post
Add a Checkout block.
Expected: Placeholder is displayed in a Shipping Options section

✅  I see the placeholder!

> Save the post and go to frontend
Expected: Shipping options are not displayed

image

✅  Looks good to me!

> Add a shipping option (wp-admin/admin.php?page=wc-settings&tab=shipping&section, Add Shipping Zone -> Go through the form)
Go back to the post in editor
Expected: There's no Placeholder in Shipping Options

image

✅  looks good!

> Go to the frontend
Expected: Shipping options are there

✅ They appear, looking good!

I also confirm I see the local pickup selectors in the editor **and** the front end. Not sure why @nefeline doesn't see that in the editor though 🤔

**Comment by nefeline** [comment]
> I also confirm I see the local pickup selectors in the editor and the front end. Not sure why @nefeline doesn't see that in the editor though 🤔

Interesting! I guess you will have to break the tie, @kmanijak ! :)

**Comment by kmanijak** [comment]
> Interesting! I guess you will have to break the tie, @kmanijak ! :)

I'm afraid I won't break a tie. I see two "Local pickups" in Editor 😂 

| Editor | FE |
| ------| ----|
| image | image |

With this setup of Shipping Zones:
image

So... I'm not sure what's exactly expected 😅
To sum up:
- I think we all agree it's unlikely to be caused by this PR, so I'll go ahead and merge this
- I'm happy to open an issue, but @opr, can you confirm what's expected to be displayed in the Editor?

**Pull request merged**
