### PR TITLE
Fix todo bot config and remove unnecessary todo from code.

### PR DESCRIPTION
**Pull request by nerrad**
Fixes: #2385 
Also is a continuance of #2384

### CODE REVIEW

**Comment by nerrad** [comment]
Nope still autoassigning :(.  Looks like the `config.yml` isn't being read and it's possible that might be a permissions issue.

**Comment by nerrad** [comment]
Although I've done this:

Image 2020-05-02 at 4 16 56 PM

I'm guessing since I don't have the right privileges for `woocommerce` it's still not granting the needed permissions for the app in the woocommerce org. It doesn't look like the configuration I've added for this bot is getting read and overriding defaults.

**Comment by nerrad** [comment]
Weeelll, looks like I can't remove the app either. It shows up in the integrations for the repository but I can't remove it (and this is the only place I can see the app).

Image 2020-05-02 at 4 21 18 PM

So I guess I'll have to wait until @mikejolley can see if it needs approved for the woocommerce org, or remove it from there if it has the permissions but it's buggy - we can't have it pinging the entire `woocommerce` org.

**Comment by nerrad** [comment]
@mikejolley when you see this, just remove the app please. I've decided to give a go at working on an action for this and I think (hope) it'll work better (and allow us to more easily add improvements along the way).

**Comment by mikejolley** [comment]
Looks like it may have worked when auto assign was false looking at https://github.com/JasonEtco/todo/blob/b4bf28cea7191b4f6094c4da6b7ba8f05554cbba/lib/utils/generate-assigned-to.js#L15

I've uninstalled it anyhow.

**Comment by nerrad** [comment]
Ya the code is clear is _should_ work, but the configuration I set was not getting read in testing. I _almost_ got the github action done, I'll resume it on my evenings.

**Comment by nerrad** [comment]
Closing this, I've created a new [automations repository](https://github.com/woocommerce/automations) that is ready for testing in our repo.

**Pull request closed without merging**
