### PR TITLE
[Store Customization MVP] Add image alts to the ai prompt if available

### LINKED ISSUE #11084: Store Customization > Fine-tune the prompts to AI so the generated content can be consistent with the displayed images
When patterns were initially developed, predefined titles and descriptions were used to compose the content. Now that AI generates this content, it has been verified that they do not always match the image displayed.

To solve this problem, the prompt for generating the content via AI for a given image should be updated to include the description of the image (this information is provided by the verticals API, see this request as an example: https://public-api.wordpress.com/wpcom/v2/site-verticals/3/images )

## Scope

- Identify all patterns that have a combination of Image + a text to describe it
- Update the prompt to AI for such cases to include the meta alt field:

Screenshot 2023-10-02 at 14 55 40

## Expected outcome

The content in a pattern should be aligned with whatever is displayed in the images: if we display the image of an apple, the associated content should describe the apple.

### PR DESCRIPTION
**Pull request by albarin**
## What

Uses the `alt` available in some of the Verticals API images to build the prompt so the content makes sense with the image.

Also includes a pattern update which was not loading the right content.

Fixes #11084 

## Why

Since content is AI-generated, we need to avoid some images not matching the image displayed as much as possible.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new [JN install](https://jurassic.ninja/) with both Jetpack and Woocommerce installed and activated.
2. Install and activate WooCommerce Blocks from this zip file: [woocommerce-gutenberg-products-block.zip](https://wcblocks.wpcomstaging.com/wp-content/uploads/woocommerce-gutenberg-products-block-11101.zip).
3. In your wp-admin, set up the JetPack connection, make sure it's successful.
4. From your admin screen, click on Tools > Plugin editor:

    Select the WooCommerce Blocks plugin and add the following within your woocommerce-blocks/woocommerce-gutenberg-products-block.php file and save:

```php
function connect_to_endpoint() {
	update_option( 'woocommerce_blocks_allow_ai_connection', true );

	$request = new WP_REST_Request( 'POST', '/wc/store/patterns' );

	$request->set_param( 'business_description', 'A store that sells organic food' );

	$response = rest_do_request( $request )->get_data();

	error_log( print_r( $response, true ) );
}

add_action( 'admin_init', 'connect_to_endpoint' );
```

5. Create a new post.
6. Insert the Featured Category Triple pattern (or any other you want with at least one image).
7. Make sure the images and content on the pattern match the business description you provided: 'A store that sells organic food'.
8. Go back to the plugin editor and update the business description over there to something else (e.g. books, clothes, sports gear etc.) and save.
9. Return to your post editor, save it, and refresh the page.
10. Test other patterns and make sure the images and their associated content makes sense.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
Thanks @albarin. I can see the problem we're trying to solve here but I am wondering what other approaches we have considered? I'm not sure what I'm about to suggest is _the right way_ but I was wondering do you think it would be worth moving the ALT text to the dictionary file and using that text to build the prompt & the image alt. In the case of `woocommerce-blocks/featured-category-focus` the alt text isn't really describing the image so I'm unsure on how this would benefit the returned result "_Placeholder image used to represent products being showcased in a featured category section._"

What about if we did the following:

```json
{
	"name": "Featured Category Focus",
	"slug": "woocommerce-blocks/featured-category-focus",
	"images_total": 1,
	"images_format": "landscape",
	"content": {
		"titles": [
			{
				"default": "Announcing our newest collection",
				"ai_prompt": "The title of the featured category: {image.0}"
			}
		],
		"image_description": [
			"An image of a cosy living room showing contemporary decoration with a fireplace"
		]
	}
}
```

We could then use the `image_description` that to generate the prompt `$content['titles'][0]['ai_prompt'] . $content[image_description][0]`

And the alt text: `'Placeholder image used to represent '. $content[image_description][0]`

Again I'm not saying my suggestion is the right one, but it feels a _little bit_ more intuitive. What do you think?

**Comment by tjcafferkey** [comment]
After Step 8 I updated the business description to `A store that sells sports gear` and when I inserted another pattern it produced accurate images but the associated content remained similar to the previous description.

Screenshot 2023-10-09 at 11 10 00

**Review by nefeline — COMMENTED** [review]
@albarin I think we will have to fine-tune the logic here a bit. Here are the test results on my end: 

- On https://advisory-tarsier.jurassic.ninja/ we have the store description set as:

> I'm selling merchandise with branding by local breweries. I have a small catalogue of about 10 products. I plan to sell to people who like craft beer. My business is all about beer.

- And in this particular case, since the Verticals API doesn't have any specific images for beers, this was the output received:
Screenshot 2023-10-09 at 15 45 34

- The `"alt"` description does exist for all of these images within the verticals API:

Screenshot 2023-10-09 at 16 16 16

Ref: https://public-api.wordpress.com/wpcom/v2/site-verticals/1512/images

But because we are concatenating these with the store description within the PatternsUpdater class, `get_patterns_with_content` method, the output is still related to the breweries or beers (in this particular example), rather than the images.

As a workaround I would suggest that: for all patterns that display products, if the provided images have an alt description, rely exclusively on those to generate the content rather than a combination between store description + image description to ensure better accuracy. WDYT?

**Comment by albarin** [comment]
> As a workaround I would suggest that: for all patterns that display products, if the provided images have an alt description, rely exclusively on those to generate the content rather than a combination between store description + image description to ensure better accuracy. WDYT?

I agree it's not ideal, but when the Verticals API returns an unrelated vertical, even if we only use the image `alt` it will feel unrelated to the actual store. My thinking is: is it better to show a text related to the store description even if the images do not correspond or a text that matches the image but is unrelated to the store description? 🤔 

For example, with the current implementation, I used as a description: "A store that sells drugs and medicines" and got this:
Screenshot 2023-10-10 at 14 55 12
Would it make more sense to get something related to the images as text when the images are that random and unrelated? I'm not sure at all which is the best option tbh 😅

**Comment by nefeline** [comment]
> I agree it's not ideal, but when the Verticals API returns an unrelated vertical, even if we only use the image alt it will feel unrelated to the actual store. My thinking is: is it better to show a text related to the store description even if the images do not correspond or a text that matches the image but is unrelated to the store description? 🤔

> Would it make more sense to get something related to the images as text when the images are that random and unrelated? I'm not sure at all which is the best option tbh 😅

Yeah, you are right; this is a very tricky scenario, especially considering our limitations regarding the number of images available. Let's keep the logic as-is for now and work on additional fine-tuning as part of a separate task so we can spend more time discussing/brainstorming before implementing and unblock this work :)

**Review by nefeline — APPROVED** [review]
Thanks for working on this @albarin , LGTM! 🚀 

✅ Confirmed patterns are working as expected with these changes in place and descriptions are more accurate whenever the alt description is available for the image.

**Pull request merged**
