### PR TITLE
Use className parameter to set wrapper class for product details

### LINKED ISSUE #7235: Add a classname field to woocommerce_get_item_data filter
## Is your feature request related to a problem? Please describe.
Based on the discussion in #6512 and #6914, especially [this comment](https://github.com/woocommerce/woocommerce-blocks/pull/6914#issuecomment-1259273551) in particular, we want to enable the use of a custom class name within the product-details [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/cart-checkout/product-details/index.tsx#L35). At the moment, this is derived from the `key` or `name` properties, which can be translated, and so the name of the class would change when the language changes.

## Describe the solution you'd like
To avoid this, we would like users of the `woocommerce_get_item_data` filter to specify an explicit classname that they want to be applied for each product variant detail. This classname should be applied instead of deriving the class name from the `key` or `name` props.

## Describe alternatives you've considered
Removing the class, but this breaks other people's code who rely on it

## Additional context

This screenshot shows where the product details are displayed in the UI on the cart page, and the corresponding DOM
Screenshot 2022-09-27 at 10 48 05

### PR DESCRIPTION
**Pull request by helgatheviking**
This PR adds the ability to add a custom class to the product details on the Cart Block. If the `className` property is provided, it will be used, otherwise the class name will be derived from the `name`. 

Fixes #7235

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Add this snippet to filter the `woocommerce_get_item_data`
```
function kia_test_cart_item_data( $data, $cart_item ) {

    $data[] = array(
                'key'   => esc_html__( 'Color', 'your-textdomain' ),
                'value' => esc_html__( 'Blue', 'your-textdomain' ),
                'className' => esc_html__( 'wc-block-components-product-details__AAAcolor', 'your-textdomain' ),

	);
    return $data;
}
add_filter( 'woocommerce_get_item_data', 'kia_test_cart_item_data', 10, 2 );
```

Add a product to the cart and go view the cart block. The color: blue detail will now have the specified `className`

image

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Adds the option of providing a custom class for the product details on the Cart Block

### CODE REVIEW

**Review by alexflorisca — APPROVED** [review]
HI @helgatheviking, thanks a lot for this and sorry it's taken me so long to review it. It's great you preserved the previous logic in case `className` isn't set. Looks good, let's ship it 🚢

**Comment by alexflorisca** [comment]
Hey @helgatheviking, was just about to merge this but noticed the [linting job](https://github.com/woocommerce/woocommerce-blocks/actions/runs/3345494641/jobs/5541106328) is failing. Could you fix the errors on there and push the changes? You can run `npm run lint` locally to see the errors. Thanks

**Comment by alexflorisca** [comment]
> Hey @helgatheviking, was just about to merge this but noticed the [linting job](https://github.com/woocommerce/woocommerce-blocks/actions/runs/3345494641/jobs/5541106328) is failing. Could you fix the errors on there and push the changes? You can run npm run lint locally to see the errors. Thanks

@helgatheviking  just pinging again about this so we can merge it. I was going to do it but I realised the PR is from a forked version of the repo so I won't have write access to it.

**Comment by helgatheviking** [comment]
@alexflorisca I'm at sports training camp right now and have very little time. I ran `npm run lint` and here's the result:

```
helga@helgasmachine:~/Sites/sandbox/wp-content/plugins/woocommerce-blocks$ npm run lint

> @woocommerce/block-library@8.7.0-dev lint
> npm run lint:php && npm run lint:css && npm run lint:js


> @woocommerce/block-library@8.7.0-dev lint:php
> composer run-script phpcs ./src && composer run-script phpcs ./tests/mocks/woo-test-helper

> phpcs --extensions=php -s -p './src'
............................................................  60 / 207 (29%)
............................................................ 120 / 207 (58%)
...............................W............................ 180 / 207 (87%)
...........................                                  207 / 207 (100%)



FILE: /home/helga/Sites/sandbox/wp-content/plugins/woocommerce-blocks/src/BlockTypes/HandpickedProducts.php
-----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------
 24 | WARNING | Detected high pagination limit, `posts_per_page` is set to `count( $ids )`
    |         | (WordPress.WP.PostsPerPage.posts_per_page_posts_per_page)
-----------------------------------------------------------------------------------------------------------------------------------------------------

Time: 12.35 secs; Memory: 30MB

Script phpcs --extensions=php -s -p handling the phpcs event returned with error code 1
```

I don't think that's a problem with any of my proposed code? I don't know what else to do but don't really have the capacity right now with a major international qualifier on Thursday.

**Comment by alexflorisca** [comment]
Ok it looks like an issue with not being able to resolve a path related to eslint, so I will merge this and if there are linting failures afterwards I will fix them. Thanks again for your contribution and good luck with your match on Thursday!

**Pull request merged**
