### PR TITLE
Tests for the Checkout data store

### PR DESCRIPTION
**Pull request by alexflorisca**
Added unit tests for the checkout data store reducer and selectors

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. `npm run test`

### CODE REVIEW

**Comment by tarhi-saad** [comment]
Hi, @alexflorisca! I believe this PR is still in progress! If so, please let me know via Slack when it's ready for a review! 🙌

**Review by nielslange — APPROVED** [review]
Works like charm when running the following command, to only test the unit test that you added:
```
npm run test -- assets/js/data/checkout/test/reducer.ts           
```

Screenshot 2022-09-22 at 17 03 33

I do see one failing unit test when running `npm run test` respectively the short version `npm t`. But the failing test (`Testing Payment Methods work correctly with saved cards turned on › resets saved payment method data after starting and closing an express payment method`) seems unrelated to this PR.

**Review by tarhi-saad — APPROVED** [review]
Thank you, @alexflorisca, for working on the unit tests! All tests are successful! I only noticed a couple of TS errors on lines 11, 65, and 266.

**Comment by alexflorisca** [comment]
Thanks @tarhi-saad, I fixed the ts errors and will merge it :)

**Pull request merged**
