### PR TITLE
Make Attribute Filter block compatible with PHP rendered Classic Template block

### LINKED ISSUE #6136: Make Filter Products by Attribute work with PHP templates
Currently, it's not possible to use the Filter Products by Attribute block with PHP templates. That's because that block is designed to only work with the All Products block.

This issue is about updating it, so it can work with the Shop catalog template.

## To reproduce

1. With a block theme, go to Appearance > Editor > Template > Product Catalog.
2. Add the Filter Products by Attribute block above the product grid.
3. Change the selected values in the filter block
4. Notice the products in the product grid don't update.

## Expected behavior

The products in the product grid should update based on the selected filters.

### PR DESCRIPTION
**Pull request by tjcafferkey**
Update the Filter Attribute block to work with the Classic Template block which is PHP rendered, but also still maintain compatibility with the All Products block.

Filter Products by Attribute block will only work with the PHP rendered Classic Template block if the filters are applied to the URL and the page is re-rendered. This behaviour happens with the Classic Themes such as Storefront.

Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6136

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
 
### Manual Testing

How to test the changes in this Pull Request:

1. With a block theme, go to Appearance > Editor > Template > Product Catalog.
2. Add the Filter Products by Attribute block above the product grid.
3. Check some of the attributes on the frontend
4. Notice the page reloads and the list of products updates accordingly.
5. Now add the "Active Filters" block and repeat steps 1-4 and view the active filters appear upon page reload. Please bare in mind the "Clear All" functionality will not work with the Active Filters block yet, this needs to be worked on separately.
6. Add a test page to your site with the `All Products` block, and the `Filter by Attribute` block and ensure no regressions have been introduced here.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above, or
* [ ] See steps below.

1.
2.
3.

### Changelog

> Allow adding the Filter Products by Attribute block to Product Catalog templates to filter products.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
Failing E2E tests appear unrelated.

**Review by Aljullu — COMMENTED** [review]
Overall this is looking good, but I found a couple of issues while testing:

First, I don't seem to be able to remove the last attribute filter, is that expected?

Kooha-04-07-2022-10-41-31
_(it's not obvious from the GIF, but I'm pressing the checkbox and nothing happens :sweat_smile: )_

The second one happens when I set the _Display Style_ to _Dropdown_ in the editor. The block crashes after I select one filter:

Kooha-04-07-2022-10-43-37

Can you reproduce them?

**Comment by tjcafferkey** [comment]
>I don't seem to be able to remove the last attribute filter, is that expected?

@Aljullu that's definitely not expected 😅 . I have fixed the crashing component just working on removal of filter now.

**Comment by gigitux** [comment]
I updated this PR with the fix for removing the filter. I noticed other three bugs:
- when the user is on page 2 (so the base url was `/shop/page/{number_page}`) and applied a filter, the generated URL was `shop/page/2/?filter_color=gray&query_type_color=and` and WordPress returned a 404 error.
- The system always queried for AND, never for OR.
- The request to the endpoint returned attributes for the hidden product too. The archive product shows only the product visible, so I updated the request.

This task was pretty trickier, I hope that I didn't introduce new bugs :D

**Review by Aljullu — COMMENTED** [review]
I'm facing a strange issue when I add two Attribute Filter blocks in the page and one has _Query Type: AND_ and the other one _Query Type: OR_, the page enters an infinite reloading loop. Can you reproduce as well?

**Comment by gigitux** [comment]
> I'm facing a strange issue when I add two Attribute Filter blocks in the page and one has Query Type: AND and the other one Query Type: OR, the page enters an infinite reloading loop. Can you reproduce as well?

Yes, thanks for catching this! I'm working on a fix!

**Comment by gigitux** [comment]
Fixed with [0bdf8a7](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6204/commits/0bdf8a7eae6d79dbee4c030d60eb3cc8c06f1496)

**Review by albarin — APPROVED** [review]

**Pull request merged**
