### PR TITLE
Add new `Product collections: featured collections` pattern

### LINKED ISSUE #9106: Create `Product collections: featured collections` pattern
Featured Collections

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33624 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by albarin**
This PR implements the `Product collections: featured collections` pattern.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9106

#### Design
Centered Search

#### User-Facing Testing

1. Create a new page or post
2. Make sure the `Product collections: featured collections` pattern appears under the WooCommerce category dropdown.
3. Insert in and make sure it shows as expected on the design.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by kmanijak — APPROVED** [review]
LGTM 🚀

**Review by kmanijak — CHANGES_REQUESTED** [review]
I actually spotted one thing last minute when I clicked approval! 😅 

There's no button as on the designs:

Design | Screenshot
--- | ---
image | image

**Comment by albarin** [comment]
> I actually spotted one thing last minute when I clicked approval! 😅
> 
> There's no button as on the designs

Ouch, I just pushed the change, not sure how I missed that 🙈

**Review by kmanijak — COMMENTED** [review]
When using a light-colored style like Sherbet, the button's text is unreadable:

image

When using dark-colored style like Pitch, the headings are unreadable:

image

I'm not sure if that's up to the merchant to adjust if necessary or should work out of the box. I assume you may have more context. 🤔 

Otherwise, it looks good!

**Comment by albarin** [comment]
Thanks, @kmanijak, I've added colors to the title and button, we agreed on adding more opinionated styles. But it still does not work too well with the Sherbet theme :(

**Review by roykho — APPROVED** [review]
LGTM! I don't think we can successfully accommodate every theme styles out there. For now this looked fine on several themes I've tested. The only thing worth mentioning is the image of the Beats headphones. Recently we changed an image of a Nike shoes to something else as we err on the side of caution not to include branded images. Other than that I am approving it.

**Review by kmanijak — APPROVED** [review]
>  I've added colors to the title and button, we agreed on adding more opinionated styles. But it still does not work too well with the Sherbet theme :(

It's alright, I understand the context now!

Approving! 🚀

**Pull request merged**
