### PR TITLE
Register new footer patterns

### LINKED ISSUE #7284: Register footer patterns
Create and register the [footer patterns](https://woofse.wordpress.com/2022/08/24/headers-and-footers-i4/) under the WooCommerce category.
This is the list with all the required footer patterns: https://github.com/woocommerce/woocommerce-blocks/discussions?discussions_q=label%3A%22%E2%96%AB%EF%B8%8F+pattern%3A+footers%22

### PR DESCRIPTION
**Pull request by imanish003**
This PR registers [6 new footer patterns](https://github.com/woocommerce/woocommerce-blocks/discussions?discussions_q=label%3A%22%E2%96%AB%EF%B8%8F+pattern%3A+footers%22):
- [Simple Dark](https://github.com/woocommerce/woocommerce-blocks/discussions/6933)
- [Simple Light](https://github.com/woocommerce/woocommerce-blocks/discussions/6932)
- [Large Dark](https://github.com/woocommerce/woocommerce-blocks/discussions/6935)
- [Large Light](https://github.com/woocommerce/woocommerce-blocks/discussions/6934)
- [Two menus Light](https://github.com/woocommerce/woocommerce-blocks/discussions/6936)
- [Two menus Dark](https://github.com/woocommerce/woocommerce-blocks/discussions/6937)

Fixes #7284 

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. In a new page or a template, go to the patterns tab and make sure all 6 patterns appear under the WooCommerce category dropdown.
2. Insert each one of the footer patterns, save and make sure they all look as expected on the GH discussions.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [X] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add simple, large & two menus footer patterns

### CODE REVIEW

**Comment by albarin** [comment]
Hey @imanish003 , the only issue I found is with the `Large menu`, it shows cut-off for me.
Screenshot 2022-10-05 at 15 10 59

Are you able to reproduce?  🤔

**Comment by imanish003** [comment]
> Hey @imanish003 , the only issue I found is with the `Large menu`, it shows cut-off for me. Screenshot 2022-10-05 at 15 10 59
> 
> Are you able to reproduce? 🤔

@albarin Yes, I can reproduce it. Thanks for pointing this out 🙏 

Looks like setting `Align` equal to `Full width` is causing the issue, as shown in the image below:
image

IMO we should set it to `wide width` instead because setting it to `full width` will not look great on large screens, as shown in the screenshot below
image

Here is how setting it to wide width will look like on large screens
image

What do you think? 🙂

**Comment by albarin** [comment]
> What do you think? 🙂

Look better now, thanks for working on it! 
@vivialice what do you think about this?

**Comment by imanish003** [comment]
@albarin FYI just pushed a fix. Can you please have a look? 🙌🏻

**Review by albarin — APPROVED** [review]
Looking good! 👍

**Pull request merged**
