### PR TITLE
[Product Query] Fix filter block data counter 

### LINKED ISSUE #7245: [Product Query] When a specific variation is used (e.g. on-sale variation), the filter blocks have to render data that matches the variation
When a specific variation is used (e.g. on-sale variation), the filter blocks have to render data that matches the variation.

For example, when `on-sale variation` is used, the `Filter Products by Price` block should render as max price `$55.00`. 
The same for the `Filter Products by Attributes`. The counter number near the attribute is related to all the products.

image
image

So we have to take care of the kind of variation (e.g.:on sale, most sold products), but also of the pagination settings. For example, the merchant can show only the first 6 products but also show the first 12 products or all the products of a specific variation.

### PR DESCRIPTION
**Pull request by gigitux**
This PR is blocked by #7251 #7186.

If you want to see only the code related to this PR, please check the commit b8bf17efb32caf70c484e45d2a1e90a90c1bec90

This PR is an attempt to allow the filter blocks to render the right data when a variation is used. 
For example when on the page there is the On Sale Products variation:
- the Filter Products by Price block has to render as the max price: $55.00.
- the Filter Products by Stock block has to render as a counter for "in-stock product" 7 and hasn't to render the option "out of stock". 

### Technical details

The backend does a query to the database to retrieve all the product ids reading the attributes used by the specific variation. The function is:`get_products_ids_by_attributes`.

### Technical issue

With this implementation, we can't support different Product Query blocks on the same page. Also, not sure how it works with hydration :(

Fixes #7245

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
| image| image|

The data in the first image are wrong because:
- the most expensive on-sale product costs $55.00.
- there isn't an on-sale product out of stock.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add a Product Query and enable ´Show only products on sale´.
2. Add the Filter Products by Price block and add the Filter Products by stock block.
3. Save and on the frontend be sure that the max price is $55.00 and there isn't the option "out of stock".

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### Changelog

> N/A

### CODE REVIEW

**Review by sunyatasattva — CHANGES_REQUESTED** [review]
I left a comment in the commit you linked. Otherwise, code looks good, but I didn't test functionality yet.

**Comment by sunyatasattva** [comment]
@gigitux Please let me know when the feedback on this is also addressed.

**Comment by gigitux** [comment]
> @gigitux Please let me know when the feedback on this is also addressed.

I moved the comment for disabling phpcs rules on top [c4a46c3](https://github.com/woocommerce/woocommerce-blocks/pull/7257/commits/c4a46c304e4b9494afc6d29c45dc93f272ae5fd5). Also I change the name of the parameters [e95122d](https://github.com/woocommerce/woocommerce-blocks/pull/7257/commits/e95122d19765a17a988d3bd509fa103b0867c2a8)

I still have some doubts about refactoring the entire function. Let me know what you think! 🙏

**Review by sunyatasattva — APPROVED** [review]
Thanks for addressing the feedback. I am ok with you leaving the function as is: I have my own opinion, but it boils down to personal preference at this point, I'm ok with this.

**Pull request merged**
