### PR TITLE
Make `Notice` component legible in dark themes

### LINKED ISSUE #8265: Store Notices and Catalog Sorting blocks don't work well in dark themes
## To reproduce

1. Install a theme with a dark background (ie: theme TT3 with Auberginie style or theme Zaino).
2. Go to Appearance > Editor and edit the Product Catalog template.
3. Add the Store Notices and Catalog Sorting blocks.
4. Notice they are illegible.

Editor | Frontend
--- | ---
imatge | imatge

## Expected behavior

We should make sure the texts are legible in dark themes.

### PR DESCRIPTION
**Pull request by albarin**
The Notice component text is not legible in dark themes since the background color is light and the text color is too. With this change, we are setting the color always to black for our blocks, so it's always legible.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8265#issuecomment-1400717080

### Screenshots

| Before | After |
| ------ | ----- |
|Screenshot 2023-01-24 at 10 06 22 | Screenshot 2023-01-24 at 10 06 08 |

#### User-Facing Testing

1. Install a theme with a dark background (ie: theme TT3 with Aubergine style or theme Zaino).
2. Go to Appearance > Editor and edit the Product Catalog template.
3. Add the `Store Notices` block.
4. Make sure the notice text is black and legible.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Adjust `Store Notices` text color in dark themes.

### CODE REVIEW

**Comment by albarin** [comment]
@Aljullu do you think this a good place to put styles affecting all blocks?

**Comment by albarin** [comment]
@Aljullu do you think this a good place to put styles affecting all blocks?

**Comment by Aljullu** [comment]
> @Aljullu do you think this a good place to put styles affecting all blocks?

@albarin maybe `/assets/css/editor.scss` might be a better one in this case? These notices are only displayed in the editor, right?

At the same time, I wonder if we should be more specific and only target notices inside our blocks. I don't think we have any generic class, but we could write the individual block class name:

```CSS
.wc-block-attribute-filter .components-notice__content,
.wc-block-store-notices .components-notice__content {
	...
}
```
Or maybe, even better, adding these styles directly in the block's `editor.scss`, ie: `/assets/js/blocks/attribute-filter/editor.scss`.

What do you think?

**Comment by albarin** [comment]
@Aljullu 
> @albarin maybe `/assets/css/editor.scss` might be a better one in this case? These notices are only displayed in the editor, right?

True.
 
> At the same time, I wonder if we should be more specific and only target notices inside our blocks. I don't think we have any generic class, but we could write the individual block class name:
> 
> ```css
> .wc-block-attribute-filter .components-notice__content,
> .wc-block-store-notices .components-notice__content {
> 	...
> }
> ```

I thought about that, but since I couldn't find that generic class for our blocks I didn't do it.

> Or maybe, even better, adding these styles directly in the block's `editor.scss`, ie: `/assets/js/blocks/attribute-filter/editor.scss`.
> 
> What do you think?

I think that a good option, the only thing I see with it and with the prev one is that it is not future-proof. We'll have the same problem every time we use again the Notice component, but maybe this is not that important, it's not something that we use very very frequently. 🤔

**Comment by Aljullu** [comment]
> I think that a good option, the only thing I see with it and with the prev one is that it is not future-proof. We'll have the same problem every time we use again the Notice component, but maybe this is not that important, it's not something that we use very very frequently. 🤔 

These are my concerns as well, but agree with you that we don't use notices in blocks very frequently, so IMO it should be ok to have this CSS snippet in each block that uses notices in the editor.

**Comment by albarin** [comment]
@Aljullu I've reviewed one by one all the `Notices` and turns out most of them are shown on the settings sidebar (not affected by the theme), so I've only added the style for the ones showing on the editor side.

**Review by Aljullu — COMMENTED** [review]
For all files which are new, you will need to add `import './editor.scss'` in the `edit.tsx` file.

Something like this:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/attribute-filter/edit.tsx#L37

Otherwise, it doesn't seem to work for me.

**Comment by albarin** [comment]
> For all files which are new, you will need to add `import './editor.scss'` in the `edit.tsx` file.
> 
> Something like this:
> 
> https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/attribute-filter/edit.tsx#L37
> 
> Otherwise, it doesn't seem to work for me.

Weird, I don't understand why it was working for me, I've added them, and removed one file that I realised was not necessary.

**Review by Aljullu — APPROVED** [review]
I only tested the Filter by Attribute and the Store Notcies blocks, but both of them work well. :ship:

**Pull request merged**
