### PR TITLE
 Fix the local pickup price in the shipping type selector and pickup options

### LINKED ISSUE #8514: Local Pickup: price is incorrect in the shipping type selector
## Describe the bug

I have local pickup enabled and all of my methods are free, however I see "From $200.00"  in the local pickup UI.

## To reproduce

1. Add some local pickup locations for free
2. Add some regular shipping methods, but NOT a free one, assign costs to them.
3. Add an item to your cart and go to the Checkout block.
4. View the shipping selector, see the "From" price for Local Pickup has the lowest _regular_ shipping price, not the free local pickup price.

## Expected behavior

The from price should reflect the lowest price in the local pickup options.

### PR DESCRIPTION
**Pull request by tarunvijwani**
If the local pickup is free and the shipping rate has a cost, the local pickup was displaying the shipping rate price. 

Also, we were concatenating the tax and price in the local pickup instead of adding them. 

With this PR, we're fixing the local pickup price in the shipping type selector and fixing the pickup price in the pickup options. 

Fixes #8514

### Screenshots

| Before | After |
| ------ | ----- |
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to WooCommerce -> Settings -> Tax (you might need to check _Enable tax rates and calculations_ before).
2. Under Prices entered with tax, select Yes, I will enter prices inclusive of tax
3. Under Display prices in the shop and Price display suffix, select Including tax
4. Save changes
5. Go to WooCommerce -> Shipping -> Local pickup
6. Add price for local pickup. You may keep it not taxable.. 
7. Add some regular shipping methods, but NOT a free one, assign costs to them.
8. Add an item to your cart and go to the Checkout block.
9. Confirm shipping and local pickup price is correct. 
10. Confirm correct price is getting displayed in the pickup options. 

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix the local pickup price in the shipping type selector and pickup options.

### CODE REVIEW

**Review by opr — CHANGES_REQUESTED** [review]
Looks and works great, thanks Tarun. Do you think we could add some unit tests to this?

**Comment by tarunvijwani** [comment]
> Looks and works great, thanks Tarun. Do you think we could add some unit tests to this?

Yes, that's a great suggestion. Thank you! I'm converting the PR to a draft to add unit test cases.

**Comment by tarunvijwani** [comment]
We plan to add the unit test cases in a different ticket.

**Review by tarhi-saad — APPROVED** [review]
Thank you for the fixes, @tarunvijwani! Everything works as expected. Let's 🚢

**Comment by tarunvijwani** [comment]
Created the ticket to add unit test case: #8762

**Review by Aljullu — APPROVED** [review]
I didn't review the code as I'm not very familiar with it. But wanted to mention that I tested it and it's working well on my end.

**Review by kmanijak — APPROVED** [review]
Didn't check the code, but tested as well - works good! 👍

**Pull request merged**
