### PR TITLE
Fix - "Order received" page does not display the payment method information.

### LINKED ISSUE #8448: "Order received" page does not display the payment method information when an order is completed via the Checkout Block
## **🐞 Description-**

1. **When an order is completed through the Checkout Block, the "Order received" page fails to display the payment method information. This issue does not occur when orders are completed via the shortcode-based checkout page.**

| **With Block-Based checkout**                                                                                  | **With Shortcode-Based checkout**                                                                              |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| image | image |

2.  🐞  **Payment Method details also missing on Order Listing Page in WP dashboard.** 

image

## To reproduce

1. Install the WooCommerce Block plugin on a WordPress site.
4. Create a product and add it to the site's shopping cart.
5. Proceed to checkout using the "Checkout" Block, which can be added to a page using the "WooCommerce" block category.
6. Complete the checkout process and confirm the order.
7. On the "Order received" page, observe that the payment method information is missing.

To confirm that the issue does not occur when using the shortcode-based checkout page, follow these additional steps:

1. Create a product and add it to the site's shopping cart.
2. Add the shortcode [woocommerce_checkout] to a page and publish it.
3. Proceed to checkout using the newly created shortcode-based checkout page.
4. Complete the checkout process and confirm the order.
5. On the "Order received" page, observe that the payment method information is properly displayed.

## Expected behavior

Payment Method information should appear for the customer on Order/Thank you Page.

## Environment

<Details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woolocal.local
Site address (URL): https://woolocal.local
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.6.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5


### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###


WooCommerce Blocks: by Automattic – 9.6.0
WooCommerce Bookings Stable: by WooCommerce – 1.15.75
WooCommerce Stripe Gateway: by WooCommerce – 7.0.2
WooCommerce Product Vendors: by WooCommerce – 2.1.70
WooCommerce: by Automattic – 7.4.0



### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔




### Status report information ###

Generated at: 2023-02-16 14:05:07 +05:30
`

```

</Details>

### PR DESCRIPTION
**Pull request by iamdharmesh**
This PR contains a minor change to fix #8448. Currently, when we place an order using the checkout block, the payment method title information not getting saved to the order and it results in payment method information is not showing on Order received page and backed order list page as described in the reported issue.

This was happening due to we are passing the payment method ID in `set_payment_method()` in the `update_order_from_request` function so, Payment method title is not getting updated for orders. This PR updates it to pass the payment method object to update the payment method title to order.

Fixes #8448 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|Screenshot 2023-04-19 at 11 06 06 AM | Screenshot 2023-04-19 at 11 05 00 AM |
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Checkout to this PR branch.
2. Create a product and add it to the site's shopping cart.
3. Proceed to checkout using the "Checkout" Block
4. Complete the checkout process and confirm the order.
5. Verify that payment method information is there on the "Order received" page.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix - "Order received" page does not display the payment method information.

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Thank you very much for working on this, @iamdharmesh! 🙌

While the fix works as expected, I'd like to get a second review from @mikejolley, who has deeper knowledge about the Store API. What surprises me in this particular case, is the history of the line you changed: 

**This PR**
https://github.com/woocommerce/woocommerce-blocks/blob/5565747ea7cb4813d124ebd1c70673fbc0e6bf07/src/StoreApi/Routes/V1/Checkout.php#L476

**Jan 5, 2022**
https://github.com/woocommerce/woocommerce-blocks/blob/b8de0ab7317e62bf32b59b6eea9430e89bea5c12/src/StoreApi/Routes/Checkout.php#L418

**Oct 26, 2021**
https://github.com/woocommerce/woocommerce-blocks/blob/ed517bbbd9541e85b8a95d0cbb8e5d6abc5ceb06/src/StoreApi/Routes/Checkout.php#L465

**Sep 28, 2021**
https://github.com/woocommerce/woocommerce-blocks/blob/90e513b893fce394a83640a01471c96045eac983/src/StoreApi/Routes/Checkout.php#L464

**Dec 2, 2020**
https://github.com/woocommerce/woocommerce-blocks/blob/accd1bbf402e043b9fc322f118ab614ba7437c92/src/StoreApi/Routes/Checkout.php#L414

@mikejolley Would you mind taking a look at this case?

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.2 
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.6.0
* PHP: 8.0.22
* Web Server: Nginx
* Browser: Chrome - Version 111.0.5563.64 
* OS: macOS Monterey V 12.3.1


</Details>

**Steps to Test-** 

Steps to test this PR:

1. Install the WooCommerce Block plugin on a WordPress site.
2. Create a product and add it to the site's shopping cart.
3. Proceed to checkout using the "Checkout" Block, which can be added to a page using the "WooCommerce" block category.
4. Complete the checkout process and confirm the order.
5. On the "Order received" page, observe that the payment method information is available.
6. Also check payment method on New Order Email, Order Listing page in wp-admin

**Test Results -** 

This pull request has been tested and found to be functional in resolving the aforementioned issue. Payment method is now appearing consistently across all relevant areas, including the Order Confirmation Thank You Page, Order Listing page in wp-admin, and Email sent to the customer upon successful payment. All relevant test cases have passed successfully.



**Functional Demo /  Screencast -**



**Before Fix-**

https://user-images.githubusercontent.com/6384299/233024555-2ad62f9a-87dd-4ccd-93ae-626339b6008b.mp4


**After Fix-**


https://user-images.githubusercontent.com/6384299/233026135-a885b06a-8116-4d52-ac8f-aeed8a1ddf36.mp4


---

**Negative Test -**  To ensure new change doesn't break already working functionality. 



https://user-images.githubusercontent.com/6384299/233027573-c481f78c-a637-4080-b9f4-ff817a11738c.mp4


---
**QA Status-** Pass ✅

**Comment by mikejolley** [comment]
@nielslange @iamdharmesh Looking back at the last major change in https://github.com/woocommerce/woocommerce-blocks/pull/5440, both functions were changed so that `get_request_payment_method_id` uses `get_request_payment_method` internally, so flipping these again is fine and should work with the core function which I'm pasting below for reference:

 ```php
	/**
	 * Set the payment method.
	 *
	 * @param string $payment_method Supports WC_Payment_Gateway for bw compatibility with < 3.0.
	 * @throws WC_Data_Exception Throws exception when invalid data is found.
	 */
	public function set_payment_method( $payment_method = '' ) {
		if ( is_object( $payment_method ) ) {
			$this->set_payment_method( $payment_method->id );
			$this->set_payment_method_title( $payment_method->get_title() );
		} elseif ( '' === $payment_method ) {
			$this->set_prop( 'payment_method', '' );
			$this->set_prop( 'payment_method_title', '' );
		} else {
			$this->set_prop( 'payment_method', $payment_method );
		}
	}
```

However, while this does state that the method is for bw compatibility and not deprecated, the type defined by the docblock suggests that we should be passing a string.

The other concern is that there may be an edge case issue where there is no payment method. This would result is us passing `null` to the above `set_payment_method` function. This is unhandled and could result in breakage.

I think there are 2 options to resolve this.

1. Handle the potential `null` value coming from `get_request_payment_method` inline, and if null, pass an empty string. This would fix the issue but could result in IDE warnings due to the unexpected `object` type rather than `string` as documented.

2. Leave this line as is and instead add a second call to `$this->order->set_payment_method_title()`. There we can pass the title instead. We could introduce a `get_request_payment_method_title` helper method in our `Checkout` class to obtain this and handle `null` (return empty string if null).

How does this sound?

**Comment by iamdharmesh** [comment]
Thanks for the detailed explanation @mikejolley, I have updated PR as per 2nd option. Could you please help to review it once? 

Thanks

**Review by mikejolley — APPROVED** [review]
Thanks for making those changes. This fixes the original issues and any potential edge cases. 👍🏻

**Comment by mikejolley** [comment]
e2e tests passing. The failing tests are relating to forks/permission issues, so ignoring. Merging this now 👍🏻

**Pull request merged**
