### PR TITLE
Add screenshots on E2E test failures

### PR DESCRIPTION
**Pull request by opr**
This PR will add a step to the E2E test workflow that will upload a test report and screenshots of test failures if any E2E tests do not pass.

The following changes were made to achieve this:
- Add `jest-circus` test runner - this is required to cause jest/puppeteer to emit events during test runs, we need events so we can perform actions when certain events happen, specifically we need to listen for the `test_fn_failure` event and take a screenshot when it happens as this indicates a test failure.
- Add a test environment for the E2E tests to run in, this is added in `tests/e2e/config/environment.js` it's necessary so we can add the event listeners described above.
- Add a new action to both E2E test runs that will upload an artifact on failure. The artifact can then be downloaded and viewed from the actions page, e.g. https://github.com/woocommerce/woocommerce-gutenberg-products-block/actions/runs/1308522664 - scroll to the bottom and you'll be able to download an artifact.

### Screenshots

image

image

image

### Testing
1. Push a commit to this PR that will cause the E2E tests to fail - for example what I did in c57f2c5ab1d7b60d8824d854c1cb9a8281a71c4b - don't forget to revert it!
2. When the tests fail, go to the run and download the artifact, verify it contains the correct information and a screenshot of the failure.

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Hello @opr 👋 After pushing a breaking change to this PR, I see that the tests are failing, but I do not see an artifact being uploaded via https://github.com/woocommerce/woocommerce-gutenberg-products-block/actions/runs/1319392048:

Screenshot 2021-10-08 at 14 53 57

Am I doing some wrong while testing?

**Review by nielslange — APPROVED** [review]
Thanks to you support in p1633681189366400-slack-C8X6Q7XQU, I was able to successfully test this PR!

LGTM! 🚢

**Comment by dinhtungdu** [comment]
@opr I'm not sure if this is a known issue, but I'm getting this errors with failed tests:

```
[jest-html-reporters]: Param attach error, not a buffer or string, pic  - undefined log failed.
```

No screenshot was attached to the report.

**Comment by opr** [comment]
> @opr I'm not sure if this is a known issue, but I'm getting this errors with failed tests:
> 
> ```
> [jest-html-reporters]: Param attach error, not a buffer or string, pic  - undefined log failed.
> ```
> 
> No screenshot was attached to the report.

Hey could you please link to one of the failing runs?

**Comment by dinhtungdu** [comment]
@opr here it is: https://github.com/woocommerce/woocommerce-gutenberg-products-block/runs/5284094339?check_suite_focus=true#step:11:1190

**Pull request merged**
