### PR TITLE
Refactor Featured Category and Featured Product blocks

### PR DESCRIPTION
**Pull request by sunyatasattva**
**Featured Category** and **Featured Product** blocks shared about 90% of their implementation code, both in JS and in CSS. This meant that every time we worked with them, we needed to duplicate code, copy + paste, and keep things in sync.

On top of that, the main `block.js` file was an unwieldy ~700 LOC, and included many functionalities within the main closure of the component, making it very hard to reason about.

This PR aims to fix those issues:

1. It creates a new directory called: `featured-items` which includes both blocks. All the shared code lives at the top level of that directory. This is so that moving to a monorepo approach will be easier, and all the code is nicely scoped within the “package boundaries”.
2. Individual blocks still have their own directories, with their `block.json` and all other relevant configuration.
3. All the functionalities have been refactored out into their own files, accepting configuration when relevant, but mostly de-duplicating all the code.
4. Styles have also been refactored using mixins and extends and they mostly live in one place.

This should also make reasoning with TypeScript a lot easier once we get to the migration.

Ideally, no functionality has changed after this PR.

References #6237, #6238

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Only regression testing is needed for this PR. The changes introduced in this PR should be compared with a version without those changes and verified that no behavior has changed.

1. Add the **Featured Product** block to a page
2. Compare its functionality with the same block before these changes. Non-exhaustive list:
     - When added, it shows a full-width selection dropdown to choose the product
     - After choosing the product and clicking "Done", a loading spinner appears and the product is loaded
     - All the info are displayed correctly (default image, title, description, price, call to action)
     - The block toolbar shows the same tools (duotone, alignment, cropping/replacing, editing)
     - The block sidebar shows the same options and they all work correctly (colors, content, media settings, etc.); note that the “border” does not currently work.
     - The block appears resizable and resizing works the same way.
3. Verify the same for the **Featured Category** block

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by albarin — CHANGES_REQUESTED** [review]
Hey, fantastic effort in this refactor! 💯 

I've been testing both blocks and the only thing I found it's not working is the overlay.
It is applied on the edit page but not rendered on the frontend.

**Comment by sunyatasattva** [comment]
Thank you a lot! It was hard to disentangle all that code! I'll wait for your other PR to merge so I can also integrate those changes and fix the issue you've found.

**Comment by sunyatasattva** [comment]
Hey @albarin! I have addressed your feedback and also merged your changes back. The cool thing about this refactor, is that now we get the fixed/repeated background for free also for the Featured Category block!

…well, at least in the editor. I didn't implement your changes for the frontend php, so it'd be cool if you could do that in another PR once this is merged. Even cooler would be if we could refactor the blocks in a similar way on the PHP side too, so that all the duplicated code is abstracted in maybe a `FeaturedItem.php` class from which the blocks would extend, or something like that.

In any case, please since you have implemented fixed/repeated background, do an extra test on that making sure I didn't change any functionality from how you had conceived it. 🙏

**Comment by albarin** [comment]
> Hey @albarin! I have addressed your feedback and also merged your changes back. The cool thing about this refactor, is that now we get the fixed/repeated background for free also for the Featured Category block!

That's great! 💪 

> …well, at least in the editor. I didn't implement your changes for the frontend php, so it'd be cool if you could do that in another PR once this is merged. Even cooler would be if we could refactor the blocks in a similar way on the PHP side too, so that all the duplicated code is abstracted in maybe a FeaturedItem.php class from which the blocks would extend, or something like that.

Agree, I will do that!

> In any case, please since you have implemented fixed/repeated background, do an extra test on that making sure I didn't change any functionality from how you had conceived it. 🙏

Tested again, and all looks good to me now! 🔝 🚀

**Review by albarin — APPROVED** [review]

**Pull request merged**
