### PR TITLE
Move cart widget tests to playwright and ensure classic/block theme configs are executed correctly

### PR DESCRIPTION
**Pull request by opr**
This PR is based on https://github.com/woocommerce/woocommerce-blocks/pull/10663 to include the changes to the updated folder structure and newly migrated tests.

## What

This PR removes the "in the widget editor" test from the puppeteer environment and reimplements it in playwright. It also:
- Adds a `closeModalByName` util which will take a modal name and close it if it's visible.
- Ensures the correct theme is set up when running the classic/block theme tests
- Ensures the configuration files for each environment run correctly.

**It also adds a new configuration to the e2e test environment**

This is required because there are tests that rely on a specific type of theme (classic theme vs. block theme) and these cannot run in parallel because certain features are missing depending on what type of theme you're using.

Therefore, I created a new configuration for playwright which runs these classic-theme tests, added a new configuration to the GitHub action for playwright, and added new scripts in `package.json` which allow these classic theme tests to be run in isolation.

## Why

This enables us to remove one of the puppeteer test files as it would be fully migrated!

It also changes the configuration files because this is necessary to ensure the environment setup runs correctly. Without this change, running tests against the classic theme may not use the correct theme.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Ensure all e2e tests pass, playwright and puppeteer.
2. Locally, run `npm run test:e2e -- tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts` then go to `localhost:8889` and verify it's using storefront.
3. Then run `npm run test:e2e -- tests/e2e/tests/cart/cart-block.merchant.block_theme.spec.ts` and go to `localhost:8889` and verify it's using twentytwentythree

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

n/a

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Skipping

### CODE REVIEW

**Comment by wavvves** [comment]
Hey @opr I'm having trouble testing this, the test failed when running all playwright tests:
`1) [blockTheme] › cart/cart-block.merchant.block_theme.spec.ts:36:7 › Merchant → Cart › in page editor › renders without crashing and can only be inserted once `

And trying to run it individually:
```
> @woocommerce/block-library@11.0.0-dev test:e2e
> sh ./bin/check-env.sh && npx playwright test --config=tests/e2e/playwright.config.ts "tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts"

Customer state file deleted successfully.
Logged-in as customer successfully.
Error: No tests found
```

I have a fresh env up, after first fail also tried the env:restart command. I'm now restarting PW job on the pipeline just for curiosity sake..

**Comment by opr** [comment]
Hi, @wavvves what command are you using to run it locally?

**Comment by wavvves** [comment]
> Hi, @wavvves what command are you using to run it locally?

`npm run test:e2e -- tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts`

The other one runs fine

**Comment by opr** [comment]
> > Hi, @wavvves what command are you using to run it locally?
> 
> `npm run test:e2e -- tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts`
> 
> The other one runs fine

Ok sorry my testing instructions weren't updated.

Try `npm run test:e2e:classic-theme -- tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts`

**Comment by wavvves** [comment]
> > > Hi, @wavvves what command are you using to run it locally?
> > 
> > 
> > `npm run test:e2e -- tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts`
> > The other one runs fine
> 
> Ok sorry my testing instructions weren't updated.
> 
> Try `npm run test:e2e:classic-theme -- tests/e2e/tests/cart/cart-block.merchant.classic_theme.spec.ts`

Oh thanks, it now works 👍🏼 

I still get that failed test though when I run all E2E. And also two fail now. Clean branch, fresh deps, freshly built, clean env. Do I just don't get along with PW or isn't it that far off from previous flaky tests?

Can you run the PW tests to compare?

**Comment by opr** [comment]
@wavvves I just rebased, let's see if they work now.

**Comment by wavvves** [comment]
> @wavvves I just rebased, let's see if they work now.

No luck :/

```
1) [blockTheme] › cart/cart-block.merchant.block_theme.spec.ts:36:7 › Merchant → Cart › in page editor › renders without crashing and can only be inserted once 

    Test timeout of 90000ms exceeded.

    Error: page.click: Target closed
    =========================== logs ===========================
    waiting for locator('.edit-post-header [aria-label="Add block"],.edit-site-header [aria-label="Add block"],.edit-post-header [aria-label="Toggle block inserter"],.edit-site-header [aria-label="Toggle block inserter"],.edit-widgets-header [aria-label="Add block"],.edit-widgets-header [aria-label="Toggle block inserter"],.edit-site-header-edit-mode__inserter-toggle')
      locator resolved to <button id=":re:" type="button" data-command="" data-act…>…</button>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="components-modal__screen-overlay">…</div> intercepts pointer events
    retrying click action, attempt #1
    (...)
```

**Comment by opr** [comment]
@wavvves Not sure why you're getting that, tests are passing in CI

**Comment by wavvves** [comment]
> @wavvves Not sure why you're getting that, tests are passing in CI

Do they pass locally for you? Should this be disregarded for review since it works in the CI?

**Comment by opr** [comment]
> Do they pass locally for you? Should this be disregarded for review since it works in the CI?

Yup, just checked, all passing!

**Review by wavvves — APPROVED** [review]

**Pull request merged**
