### PR TITLE
Order Received FSE template

### PR DESCRIPTION
**Pull request by wavvves**
This PR is part of the Technical Spike to create a block theme template for the Order Received Route.
The goal is to introduce the template with a single “classic order confirmation block” that simply renders the entirety of the existing PHP template. The editor view would simply be a placeholder, and this provides full compatibility with existing extensions and add the logic to render the suitable template depending on the theme type:

- Classic themes: render the current Order Received route
- Block themes: render the new block theme template

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

image

| Before | After |
| ------ | ----- |
|        |       |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Install and enable a blocks enabled theme (eg Twenty Twenty Three)
2. Go to Appearance -> Editor
3. Verify that the "Order Received" template shows on the list, is editable, and displays saved changes after placing an order (eg: removing the page header)

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [X] WooCommerce Core
* [X] Feature plugin
* [ ] Experimental

### Changelog

>  Introduce a FSE template with a single “classic order confirmation block” that simply renders the entirety of the existing PHP template

### CODE REVIEW

**Review by albarin — APPROVED** [review]
Looking good, great job 👏

**Comment by ralucaStan** [comment]
Let's not merge this work yet, the plan is to merge at the same time with the Cart and Checkout templates

**Comment by thealexandrelara** [comment]
WooCommerce Blocks 10.1.0 will be released soon. I'm bumping this PR to the next milestone

**Comment by wavvves** [comment]
Replaced by https://github.com/woocommerce/woocommerce-blocks/pull/9301

**Pull request merged**
