### PR TITLE
Featured Products: Fresh & Tasty pattern > Enhance mobile view and optimize images

### LINKED ISSUE #10519: Featured Products: Fresh & Tasty pattern > Update the wrapping on mobile
Address design feedback and update the wrapping on mobile view for the Fresh & Tasty pattern

Ref. https://github.com/woocommerce/woocommerce-blocks/issues/10458

### PR DESCRIPTION
**Pull request by nefeline**
Fixes #10519

Update the **Featured Products: Fresh & Tasty** pattern with the following changes:

- Ensure the texts are stacked on mobile
- Update the styling of images so they have a uniform aspect ratio on mobile
- Resize images
- Change font weight for the product titles

### Screenshots

| Before | After |
| ------ | ----- |
|  Screenshot 2023-08-09 at 18 11 40 | Screenshot 2023-08-09 at 18 11 57 |

#### User Facing Testing

1. Create a new post
2. Insert the **Featured Products: Fresh & Tasty** pattern
3. Make sure the pattern is properly displayed in the editor without any problems
4. Save the post and head over to the front-end
5. Make sure the pattern is correctly displayed and the mobile view matches the screenshot provided on the description of this PR.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Featured Products: Fresh & Tasty pattern: Enhance mobile view and optimize images.

### CODE REVIEW

**Review by albarin — CHANGES_REQUESTED** [review]
Hey @nefeline, I'm getting this error when inserting the pattern
Screenshot 2023-08-10 at 10 07 19
I think it's related to `style="aspect-ratio:2/3;object-fit:cover"` on the images, are you getting it?

**Comment by nefeline** [comment]
> I'm getting this error when inserting the pattern

@albarin this is odd! I'm not able to reproduce this at all:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/fba10565-1ce7-4fab-8dc8-6404a2fd651b

I did a few extra tests here with WP 6.2.2, WP 6.3, and the GB plugin enabled/disabled, but no dice =/

Do you mind sharing the WP version & the plugins you have enabled locally?

**Comment by albarin** [comment]
> Do you mind sharing the WP version & the plugins you have enabled locally?

I just tried enabling/disabling GB. With WordPress 6.2.2 and GB disabled, I get the error. Once I enable GB it works fine.

**Comment by nefeline** [comment]
> I just tried enabling/disabling GB. With WordPress 6.2.2 and GB disabled, I get the error. Once I enable GB it works fine.

Thanks for sharing more details! I was able to reproduce with this setup. Updated https://github.com/woocommerce/woocommerce-blocks/pull/10521/commits/4355b12e1436485d0be072a5a4f1ab4cfd0b6d3f 

I wonder if we should consider updating our [version support policy ](https://developer.woocommerce.com/2021/07/27/announcing-a-change-to-the-woocommerce-blocks-version-support-policy/) from L0 to L1? Traditionally we have been developing and testing with the latest version of WordPress (and the new major upcoming version), but given the significant recent changes between versions 6.2.2 and 6.3, I think we should start being a bit more defensive.

**Comment by albarin** [comment]
> I wonder if we should consider updating our [version support policy ](https://developer.woocommerce.com/2021/07/27/announcing-a-change-to-the-woocommerce-blocks-version-support-policy/) from L0 to L1? Traditionally we have been developing and testing with the latest version of WordPress (and the new major upcoming version), but given the significant recent changes between versions 6.2.2 and 6.3, I think we should start being a bit more defensive.

Maybe, it make sense to me, I guess that should be a wider team discussion, I saw you already asked on the channel 👌

**Review by albarin — APPROVED** [review]
Good job!

**Pull request merged**
