### PR TITLE
Style Book: Fix Mini Cart Contents Preview

### PR DESCRIPTION
**Pull request by gigitux**
This PR fixes the Mini Cart Contents preview in Style Book. Style Book creates an iframe and injects inside it the block. Unfortunately, the `vh` unit doesn't work well with the iframe. Furthermore, the default height (100vh) would be too big for the Style Book view.

### Screenshots

| Before | After |
| ------ | ----- |
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. With WordPress 6.2 (or a previous version with GB installed) and a block theme like [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) enabled.
2. Go to Appearance > Editor and edit a template.
3. In the toolbar, select Styles (black and white circle) and then, Open Style Book (eye icon).
4. Go to the WooCommerce tab.
5. Be sure that the Mini Cart Contents preview looks as the image above.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Style Book: Fix Mini Cart Contents Preview

### CODE REVIEW

**Review by thealexandrelara — COMMENTED** [review]
I'm testing using WordPress 6.1.1, WooCommerce 7.2.2 and Gutenberg 14.8.4. For some reason, it is being displayed to me with a blank space between the cart items and the subtotal. Do you think it could be related to the WP/plugins version that I'm using?

Here is how it is being displayed to me:

Screen Capture on 2023-01-27 at 17-39-21

**Comment by gigitux** [comment]
Thanks for the review! 
I'm using the trunk version of GB. Could you try with the latest version of GB? (15.0.1)

**Comment by thealexandrelara** [comment]
> Thanks for the review! I'm using the trunk version of GB. Could you try with the latest version of GB? (15.0.1)

Ohh thank you, I just updated to version 15.0.1 and tried in Incognito window and now everything seems right:
image

Quick question: The Remove Item button in the second item is truncated, is that the expected behavior?

**Comment by gigitux** [comment]
> > Thanks for the review! I'm using the trunk version of GB. Could you try with the latest version of GB? (15.0.1)
> 
> Ohh thank you, I just updated to version 15.0.1 and tried in Incognito window and now everything seems right: image
> 
> Quick question: The Remove Item button in the second item is truncated, is that the expected behavior?

Mmm, don't you see the scrollbar?

**Comment by thealexandrelara** [comment]
> > Quick question: The Remove Item button in the second item is truncated, is that the expected behavior?
> 
> Mmm, don't you see the scrollbar?

I can't see any scrollbar for the block itself, just the Style Book's scrollbar that allows me to scroll up/down the page

**Comment by gigitux** [comment]
> > > Quick question: The Remove Item button in the second item is truncated, is that the expected behavior?
> > 
> > 
> > Mmm, don't you see the scrollbar?
> 
> I can't see any scrollbar for the block itself, just the Style Book's scrollbar that allows me to scroll up/down the page

I see the scrollbar :/ 

image


Did you try to start the build from scratch?

**Comment by thealexandrelara** [comment]
> Did you try to start the build from scratch?

Yes, I build it from scratch. I just tried with Safari and the cart item is not truncated; however, if I use Chrome, the second cart item is truncated. Maybe it's something on my side, so I think we need someone else to check this 😅

**Comment by gigitux** [comment]
Hey, @thealexandrelara, I tried with a small monitor and I replicated the issue. I tried to use the scrollbar, but it isn't easy and could impact the front end too. Instead, I increased the high of the container. `770` px should be the height to see the entire Mini Cart Contents preview.

Let me know if works, if yes I will update the image in the description!

**Comment by thealexandrelara** [comment]
> Hey, @thealexandrelara, I tried with a small monitor and I replicated the issue. I tried to use the scrollbar, but it isn't easy and could impact the front end too. Instead, I increased the high of the container. `770` px should be the height to see the entire Mini Cart Contents preview.
> 
> Let me know if works, if yes I will update the image in the description!

Unfortunately the issue is still occurring to me. I spent some time testing it, and here is what I figured out. When I'm using Google Chrome, I still see that ample blank space (like in the gif I shared here). However, inspecting the iframe Element, I realized that some styles are being applied, including a height property 'height: 1911px;'.
image

This height property on the iframe element is causing the issue to me. When I 'unset' it, the block gets the height you set using `useBlockProps.`

With that in mind, if we could get the iframe element and unset the height property, we could solve the problem. So I added this code to the Edit component, and the issue is gone:
```
useEffect( () => {
  const iframeWithMiniCartContentsBlock = Array.from< HTMLIFrameElement >(
	  document.querySelectorAll( '.edit-site-visual-editor iframe' )
  ).find( ( iframe ) =>
	  Boolean(
		  iframe.contentDocument?.querySelector(
			  '.wp-block-woocommerce-mini-cart-contents'
		  )
	  )
  );
  if ( iframeWithMiniCartContentsBlock ) {
	  iframeWithMiniCartContentsBlock.style.height = 'unset';
  }
} );
```
Explaining this code:
`Array.from...`: Here, I select all the iframe elements that we have on the page;
`find( ( iframe ) => { ... }`: I filter that array and find only the one with the Mini Cart Contents block inside
`iframeWithMiniCartContentsBlock.style.height`: Finally, if I find the corresponding iframe, I unset the height on it so it doesn't overwrite the height style that you set with `useBlockProps`

It's important to say that this code is just an initial version that I was testing, to prevent performance issues, we can improve this code by adding a dependency array to the `useEffect` so it prevents some re-renders of this component. If you know a better way to unset that height property from the iframe without having to do this workaround of selecting all the iframes and filtering them, it would be a much better version so I hope it helps

**Comment by gigitux** [comment]
I'm going to close this PR. With https://github.com/WordPress/gutenberg/pull/47461, the blocks that are not visible in the inserter, Style Book doesn't render them.

Mini Cart Contents has the inserter option set to false.

**Pull request closed without merging**
