### PR TITLE
Add stories for Button component #5250

### LINKED ISSUE #5250: Revise storybook entry for `Button` component
As part of the [Storybook resurrection](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5248) project, we intend to revise our currently implemented components to add full control and, where applicable, a few useful stories.

In particular, for the `Button` component:

- [ ] Implement controls for all props

### Possible stories

- [ ] Disallow add to cart
- [ ] Adding to cart state
- [ ] Added to cart state

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR adds 3 stories for the Button component:
- Default
- Disabled
- With Spinner

It also adds Storybook controls to change dynamically the props of the Button component

@sunyatasattva in the original issue (#5250 ), you have suggested the following names for the stories: Disallow add to cart, Adding to cart state, Added to cart state.

We have decided to keep the names a bit more generic: Default, Disabled, With Spinner as the Button component is used in multiple contexts. What do you think?

Fixes #5250 

### Screenshots

Screenshot_02_02_2022__15_40

### Manual Testing
How to test the changes in this Pull Request:

1. Run `npm run storybook`
2. Explore the [Button stories](http://localhost:6006/?path=/story/woocommerce-blocks-base-components-button--default). You should see one default story, and two additional stories with the appropriate controls.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).

- [x] Same as above

Co-authored-by: gigitux <gigitux@gmail.com>

### CODE REVIEW

**Comment by sunyatasattva** [comment]
@danieldudzic Thanks for taking this issue on! Those in the issue description were not suggestions for names of the stories, rather for their content. So, no worries.

But since you wanted my opinion, I'd probably rename `With Spinner` to `Loading`: IMHO it's more terse as to what it is and it's more consistent with the naming of `Disabled` too.

**Comment by gigitux** [comment]
@sunyatasattva Thanks for the feedback! You are right! 👍

**Review by gigitux — APPROVED** [review]
I'm approving this pull request. Thanks to @sunyatasattva for the feedback. We should just replace `WithSpinner` with `Loading`. 
Can you change it?

BTW, great job! 👏

**Comment by danieldudzic** [comment]
> I'm approving this pull request. Thanks to @sunyatasattva for the feedback. We should just replace `WithSpinner` with `Loading`. Can you change it?

Done!

**Pull request merged**
