### PR TITLE
[Store Customization MVP] Add fallbacks to all the pattern titles, descriptions and buttons

### PR DESCRIPTION
**Pull request by albarin**
## What

This PR adds fallbacks to all the pattern titles, descriptions and buttons.

Part of https://github.com/woocommerce/woocommerce-blocks/issues/11166

## Why

To avoid a PHP warning that could be triggered if certain parts of the content for the pattern don't exist on the AI-generated content within the 'wc_blocks_patterns_content' option yet.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new page or post.
2. Insert all the patterns in the `dictionary.json` file.
3. Make sure they work as expected both on the editor side and on the front end.
4. Check your PHP error log and confirm you don't see any errors related to any pattern.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add a fallback to avoid the PHP warnings that could be triggered if the content saved within the "wc_blocks_patterns_content" option does not match the updated patterns dictionary.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
There was no PHP errors in my error log, however I noticed some issues with a few patterns. Some may be a result of this PR, others may not be:

<table>
<tr>
 <td>Slug
 <td>Image
<td>Description
<tr>
 <td> woocommerce-blocks/discount-banner
 <td> 
<td> White space to the right of the image
<tr>
 <td> woocommerce-blocks/product-collections-featured-collection
 <td> 
<td> Spacing & height issue on the far right product
<tr>
 <td> woocommerce-blocks/featured-products-2-cols
 <td> 
<td> Pagination is still present here, should that be the case?
<tr>
 <td> woocommerce-blocks/product-hero-2-col-2-row
 <td> 
<td> Missing images
</table>

**Comment by albarin** [comment]
@tjcafferkey 
Regarding the `woocommerce-blocks/discount-banner`, I think it was done with a `Column` block as a wrapper because it's the only way we can choose a fixed with (400px in this case), I've tried to do it with a `Group` I cannot seem to set a width.
So, we either keep it as is, or wrap it in a `Group` and it would look like the second one 👇 (unless there's another option that I'm not aware right now)
Screenshot 2023-10-12 at 16 34 10

Regarding `woocommerce-blocks/product-collections-featured-collection`. There's some bug there happening only in the editor, something related to which `Stack` is selected. Since it's not happening in the FE and it's not one of the patterns used on the 3 homepages for the MVP, do you think we can create a separate task and fix it later?

About the `woocommerce-blocks/product-hero-2-col-2-row`, I think it's a mistake using the `Media & Text` block, I always get a block error in the editor when trying to add an image in the pattern code. I'm not sure if this pattern makes a lot of sense now, we have already 2 other patterns which look pretty similar: the `Hero Product Chessboard` and the `Alternating Image and Text`. Is also not used for the MVP templates, should we make a decision later?

I've removed the pagination in ` woocommerce-blocks/featured-products-2-cols` 👌

**Comment by tjcafferkey** [comment]
`woocommerce-blocks/discount-banner` - Lets follow up on that. Unrelated to this PR so shouldn't block it.

`woocommerce-blocks/product-collections-featured-collection` Again, lets follow up on that since its unrelated to this PR so shouldn't block it. Also since its editor side and not in the CYS MVP I don't consider it _major_.

`woocommerce-blocks/product-hero-2-col-2-row` - Since this pattern is essentially broken can we temporarily remove/disable it in a separate PR and create an issue to follow up?

`woocommerce-blocks/featured-products-2-cols` - Thanks for fixing!

**Review by tjcafferkey — APPROVED** [review]

**Review by nefeline — APPROVED** [review]
Thank you so much for working on this @albarin 🙏; this fallback is an important measure to safeguard us against any errors if the relevant scheduled action fails to update the pattern content right after a plugin update.

**Pull request merged**
