### PR TITLE
Replace react imports with wordpress/element

### LINKED ISSUE #6732: Mention that we prefer importing from `@wordpress/element` instead of `react`
In our repo we want to try to avoid importing directly from `react` as a policy. Instead, developers should use `@wordpress/element`. I was informed of this by @Aljullu on [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/6551), but I hadn't noticed myself, as our repo is a bit inconsistent (92 instances of importing from `react` vs 154 of importing from `@wordpress/element`).

However, the philosophy behind this is very solid: we want an abstraction layer so we don't have to rely on a specific underlying implementation. As such, me and @Aljullu agree that this preference should be indicated somewhere in the repo docs, and—I should add—we should perhaps migrate all the current `react` imports to `@wordpress/element`.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #6732.

This PR:
* Replaces imports from `react` with imports from `@wordpress/element` except for type imports.
* Add an eslint rule that will flag new add imports as suggested [here](https://github.com/woocommerce/woocommerce-blocks/issues/6732#issuecomment-1234448469).

#### User Facing Testing

1. Run `npm run lint:js` and verify there are no errors (there are some warnings, but they are unrelated).
2. Run several scripts and verify they still work (`npm run start`, `npm run storybook` and `npm run build`).
3. Do some smoking testing with the browser console open and verify there are no error logs related to the changes in this PR: try adding blocks in the editor, viewing them in the frontend, interacting with some of the options...

* [x] Do not include in the Testing Notes

### CODE REVIEW

**Review by nefeline — APPROVED** [review]
Massive work here; well done 🎉 ! I left a couple of questions, but pre-approving.

> Run npm run lint:js and verify there are no errors (there are some warnings, but they are unrelated).

Can you confirm what the expected errors are? Are these the warnings that are a-ok?

Screenshot 2023-02-28 at 19 18 40

> Run several scripts and verify they still work (npm run start, npm run storybook and npm run build).

✅ Confirmed all these scripts are working as expected.

> Do some smoking testing with the browser console open and verify there are no error logs related to the changes in this PR: try adding blocks in the editor, viewing them in the frontend, interacting with some of the options...

✅  I didn't test all blocks, but a handful (filter blocks, a few atomic blocks, mini-cart, checkout), and everything works as expected. Should we be more detail-oriented here and review them all one by one, or are we a-ok with a superficial test?

**Comment by Aljullu** [comment]
Thanks for the review @nefeline!

> Can you confirm what the expected errors are? Are these the warnings that are a-ok?

I think we should still fix or investigate them, but since they are reproducible in `trunk` as well and are unrelated to the changes on this PR, I wanted to exclude them to avoid the diff growing too much. Do you agree?

Btw, I pushed a couple more fixes in 1068daed71527312e1b5e32ddb69f7fa8fecfed6, which were introduced these last days.

**Comment by nefeline** [comment]
> I think we should still fix or investigate them, but since they are reproducible in trunk as well and are unrelated to the changes on this PR, I wanted to exclude them to avoid the diff growing too much. Do you agree?

Agreed!

**Comment by nefeline** [comment]
> Btw, I pushed a couple more fixes in https://github.com/woocommerce/woocommerce-blocks/commit/1068daed71527312e1b5e32ddb69f7fa8fecfed6, which were introduced these last days.

👍 I'm taking another look here quickly to confirm things are a-ok after the latest commit.

**Comment by nefeline** [comment]
All good! 🙌  :shipit:

**Pull request merged**
