### PR TITLE
Store Customization > Create a new endpoint within Store API for updating patterns with AI-generated content

### LINKED ISSUE #10617: Store Customization > Implement Client for requests to the GPT API within WooCommerce
As part of the scope described on https://github.com/woocommerce/woocommerce-blocks/issues/10503 , we need to create a new client for handling the POST requests to the GPT API so it can return us the IDs of the verticals that are a match for a given store:

Screenshot 2023-08-16 at 11 56 25

There's a direct dependency between this API and Jetpack, so we will have to be careful with the assumptions we make and be defensive (e.g. always check for the existence of a given function/class before calling it).

### The Scope

- We need to create a new directory under `src/AI` & a new class called `Connection` (or any other preferred/suitable name).
- Within this class, we need to make a POST request to the GPT endpoint. It currently lives within WP.com.
- The "code is the documentation" for this API, so extra investigation is required to identify the shape and form of the body for this POST request.
- To authenticate, we will need to provide a JWT token. We can fetch this from another endpoint on the local site (with Jetpack installed). This will give us a token that lasts for 2 minutes.
- In this first moment, to expedite work, this util will live within WooCommerce Blocks. A separate issue will be created to move it to the core of WooCommerce so other teams/projects working with AI can use the same client for their requests.
- This issue can be considered complete as soon as we can successfully make a POST request to the GPT API. Adapting the prompt and the returned results to our needs and other fine-tuning will be made in separate issues.

Important and details are available on: pdnLyh-44f-p2#comment-2908

### LINKED ISSUE #10658: Store Customization > Create a new endpoint within Store API for updating patterns with AI-generated content
⚠️ This issue can be worked on as soon as https://github.com/woocommerce/woocommerce-blocks/issues/10623 is complete.

As soon as we have the entire flow as described on https://github.com/woocommerce/woocommerce-blocks/issues/10503 in place, we should create a new endpoint within Store API so patterns can have their content generated/managed by AI during the initial store onboarding phase in a synchronous manner (e.g. remove the loading screen and show the pattern assembler only after all content is in place).

## The Scope

- Within Store API, create a new Route called `Patterns`
- We can name the endpoint as `/wc/store/v1/patterns` or any other preferred/more suitable name
- This endpoint can receive the business description as a param, but its optional (if not provided, the API should get whatever is stored within the [`'woo_ai_describe_store_description'`](https://github.com/woocommerce/woocommerce/blob/9418072a472b53bd4519086bc1958145600c42ae/plugins/woo-ai/includes/class-woo-ai-settings.php#L39) option.)
- This endpoint should return a 200 status code as soon as all images and content were successfully generated and assigned to each one of the patterns (in other words, as soon as we finish populating the `wc_blocks_patterns_content` option)

### PR DESCRIPTION
**Pull request by nefeline**
## What

Create a new endpoint within Store API for updating patterns with AI-managed images fetched from the Verticals API.

### `POST wp-json/wc/store/patterns`

- The endpoint is accessible exclusively to users with `manage_options` capabilities.
- The request is allowed only if the store owner granted permissions during the onboarding phase (only if `'woocommerce_blocks_allow_ai_connection'` is `true` ).
- The endpoint has an optional `'business_description'` parameter, which corresponds to a string with a brief description for the business: if not provided, the API will automatically fetch whatever is saved within the `'woo_ai_describe_store_description'` wp_option to generate the content that will be used to populate the patterns.

🎯 #10658

## Why

This is a requirement to ensure all of our patterns can have AI-managed images and, later on, AI-generated content.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new [JN install](https://jurassic.ninja/) with both Jetpack and Woocommerce installed and activated.
3. Install and activate WooCommerce Blocks from this zip file:  [woocommerce-gutenberg-products-block.zip](https://github.com/woocommerce/woocommerce-blocks/files/12598602/woocommerce-gutenberg-products-block.zip)

5. In your wp-admin, you should see the following section for Jetpack:

Screenshot 2023-09-11 at 18 55 38

6. Click on "Set up Jetpack" and make sure the connection is successful:

Screenshot 2023-09-11 at 18 58 30

7. Using [Postman](https://www.postman.com/) or any other equivalent app, make a POST request to the following endpoint: `wp-json/wc/store/patterns` (e.g. `https://outside-dwelling.jurassic.ninja/wp-json/wc/store/patterns`). Since you are not authenticated, you should get the following error:

Screenshot 2023-09-13 at 16 25 45

8. Now, we need to make sure the request works for admin users: you can do so by adding your credentials via Postman directly or, alternatively:

- From your admin screen, click on Tools > Plugin editor: 

Screenshot 2023-09-11 at 18 34 23

- Select the WooCommerce Blocks plugin and add the following within your woocommerce-blocks/woocommerce-gutenberg-products-block.php file:

```php
function connect_to_endpoint() {
	update_option( 'woocommerce_blocks_allow_ai_connection', true );

	$request = new WP_REST_Request( 'POST', '/wc/store/patterns' );

	$request->set_param( 'business_description', 'selling art' );

	$response = rest_do_request( $request )->get_data();

	error_log( print_r( $response, true ) );
}

add_action( 'admin_init', 'connect_to_endpoint' );
```
- Now access your JN install via SSH (you can copy the command for access over here:)

Screenshot 2023-09-11 at 18 38 44

- Head over to your wp-content directory and tail the debug.log file. Example:

```
cd /srv/users/user964902c9/apps/{insert-your-jurassic-ninja-username-here}/public/wp-content
tail -f debug.log
```

- Now go back to your browser and refresh the page in the main admin page e.g. `https://your-site.jurassic.ninja/wp-admin`

- Go back to your terminal and confirm that you can see the following response:

Screenshot 2023-09-13 at 16 43 52

* [] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

N/A

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
This tested well for me and nothing in the code stands out to me as a problem. 

🚀

**Review by thealexandrelara — APPROVED** [review]
I just tested and confirm that this is working as expected. Great job!

Considering the testing instructions, I think the "Should be tested by the development team exclusively" checkbox should be checked since it requires to change the plugin's code.

A possible improvement for the testing instructions could be made in this part:
CleanShot 2023-09-14 at 11 52 41@2x

The user in the path is different for each JN installation, and it is possible to retrieve it from the "SSH User" on the Dashboard.

**Comment by nefeline** [comment]
> The user in the path is different for each JN installation, and it is possible to retrieve it from the "SSH User" on the Dashboard.

Thanks for the suggestion! That was meant to be just an example, but I am going ahead and updating the description to be more explanatory.

**Comment by nefeline** [comment]
@albarin FYI: I temporarily removed the unit tests for the PatternsImages and the VerticalSelector classes here [dc567dc](https://github.com/woocommerce/woocommerce-blocks/pull/10881/commits/dc567dc6b33bf3d280bc3122ecf860ec3f343dd7) as some extra work is now required to mock the Jetpack connection methods to fetch the site ID and the JWT token, in addition to some changes made in the methods. I'm opening an issue for us to circle back and reintroduce them later on, since right now we are on a tight schedule.

**Pull request merged**
