### PR TITLE
Implement `@wordpress/scripts` analyze script

### LINKED ISSUE #5028: Implement `@wordpress/scripts` analyze script.
In [this pr](https://github.com/WordPress/gutenberg/pull/21827) a bundle analyzer script was added to `@wordpress/scripts` to expose an easy way to analyze the weight of all packages within built bundles. While Woo Blocks already has a built-in script taking advantage of `source-map-explorer`, I think it'd be advantageous to switch to the `@wordpress/scripts` implementation to reduce the dependencies listed in our `package.json` as well as consolidate another script feature to our usage of wp-scripts.

### PR DESCRIPTION
**Pull request by mikejolley**
Replaces `source-map-explorer` and the `npm run explore` command with the `@wordpress/scripts` equivilent. This can be ran with `npm run analyze-bundles` generating output like this:

Screenshot 2022-01-18 at 13 33 29

[This was based on the work in Gutenberg here.](https://github.com/WordPress/gutenberg/pull/21827)

Fixes #5028

### Testing

How to test the changes in this Pull Request:

1. Run `npm install`
2. Run `npm run analyze-bundles`
3. Confirm the map is shown once build has completed.
4. Confirm no major build size increases (there will be a comment on the PR). This is because I modified the webpack config.

### CODE REVIEW

**Review by opr — APPROVED** [review]
Cool! Changes to webpack look fine and the analyzer runs well thanks Mike! Can you commit a new package-lock to solve the conflicts? I think this one wasn't generated with node v16 because I got a load of `npm WARN old lockfile` warnings when testing this.

**Comment by mikejolley** [comment]
e2e fails are unrelated.

**Comment by dinhtungdu** [comment]
@mikejolley with this PR, I got the following error when I tried to build the assets. Both my current workspace and fresh clone have the same issue. Checking out the former commit (9d4ab23), I could build the plugin as normal. Do you have the same issue? I'm using a M1 Mac Mini, not sure if it plays any role here.

image

**Comment by mikejolley** [comment]
@dinhtungdu thanks for heads up, unit tests wound't have caught the dev build. It was a deleted line - fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/75796010c54865a01313800d9f83ee08b1f39d97

**Pull request merged**
