### PR TITLE
Store Customization > Add placeholder images for the Alternating Image and Text pattern

### LINKED ISSUE #10478: Alternating Image and Text Pattern > add sample images as placeholders
Address design feedback and update the Alternating Image and Text pattern to add placeholder images.

Ref. https://github.com/woocommerce/woocommerce-blocks/issues/10458

### PR DESCRIPTION
**Pull request by nefeline**
Add placeholder images and update the text styles for the Alternating Image and Text pattern.

Fixes #10478

### Screenshots

| Before | After |
| ------ | ----- |
|  Screenshot 2023-08-04 at 15 57 46 |  Screenshot 2023-08-04 at 16 02 36 |

#### User Facing Testing

1. Create a new post.
2. Insert the **Alternating Image and Text** pattern.
3. Save the post and ensure everything is working as expected both in the editor and on the frontend. The designs should match the "After" screenshot on this PR.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add placeholder images and update text styles for the Alternating Image and Text pattern.

### CODE REVIEW

**Review by danieldudzic — CHANGES_REQUESTED** [review]
Hey!

The pattern works well!

Just a few minor suggestions:

1. You're using the same "`all-items-are-100-hand-made-using-the-potter-s-wheel-or-traditional-techniques-created-with-love-and-care-in-australia`" id for two different `<h3>` headings. Maybe these could be unique?

2. The column widths add up to more than 100% in both rows (52% + 50% = 102%).

3. You can cut down on the size of these images by running them through a service like TinyPNG.

I was able to reduce them to something like 150kb. There is of course the question of quality, but since this is just a pattern placeholder, I wouldn't worry too much, especially if we can provide much smaller files.
hand-made-pots
crafting-pots

**Comment by nefeline** [comment]
Thanks for the thorough review @danieldudzic ! All feedback was addressed

> You're using the same "all-items-are-100-hand-made-using-the-potter-s-wheel-or-traditional-techniques-created-with-love-and-care-in-australia" id for two different `<h3>` headings. Maybe these could be unique?

Nice catch! This is pre-existing and not required at all, so they were removed.

> You can cut down on the size of these images

Done! Sidenote: we won't be relying on these images for much longer (with the exception of local WP installs running without an internet connection) with the upcoming replacement with Verticals https://github.com/woocommerce/woocommerce-blocks/issues/10503

cc: @jarekmorawski if from your design perspective there's a preference for preserving the original quality as provided on Figma instead, please let me know.

**Comment by jarekmorawski** [comment]
> if from your design perspective there's a preference for preserving the original quality as provided on Figma instead, please let me know.

Nope! I'm fine with reducing the file size. 👍

**Comment by nefeline** [comment]
> Nope! I'm fine with reducing the file size. 👍

Awesome, thanks for confirming! 🙌

**Review by albarin — APPROVED** [review]

**Pull request merged**
