### PR TITLE
Product Gallery: Add a better default Dialog template part

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR tries to improve upon the default Dialog template.

## What

This PR aims to address some of the concerns of woocommerce/woocommerce#42217.

- This PR **does not** answer the question of how should Thumbnails be displayed (especially when there's a lot of them).
- This PR **does not** answer the question of how should the Next/Previous buttons be displayed in the Dialog.

## Why

This PR changes how the Large Image behaves (and gets re-sized) in the Dialog in relation to the Thumbnails.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. With a block theme, open `Appearance > Editor`.
2. Open `Template Parts > Product Gallery`.
3. If you had one customized earlier, reset it to load the new default template.
4. Change the `Row` alignment to `Top` and save (this won't be needed when woocommerce/woocommerce-blocks#11104 is fixed):
Product_Gallery_‹_Template_Part_‹_Editor_‹_newproductgallery_—_WordPress_i_Messenger

5. Open a product page on the frontend **with multiple product images** and select the Large Image.
6. Make sure the Dialog opens and resizes the Large Image correctly (without overflowing the Dialog).

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|V-Neck_T-Shirt_–_newproductgallery|V-Neck_T-Shirt_–_newproductgallery|

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Gallery: Update the default dialog template part.

### CODE REVIEW

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this issue! I noticed that there is a style issue on the editor side on small screens:

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/3955e356-2ac8-43cb-85c8-d9bf034f0dec

I am not sure about this, but it seems that this PR introduces some regression on the front side:

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/b4ca33ac-dd6b-4cf5-b452-593487722157

**Comment by danieldudzic** [comment]
> Thanks for working on this issue! I noticed that there is a style issue on the editor side on small screens:
> Screen.Capture.Oct.10.mov
> 
> I am not sure about this, but it seems that this PR introduces some regression on the front side:
> Screen.Capture.Oct.10.mp4

@gigitux Could you please elaborate further on what you mean by the style issue and the regression?

Please also note from the description of the PR:

> This PR does not fix the issue of the Pager overflowing the Dialog. We probably should enable Margin control for it and add the fix via that method.

**Comment by gigitux** [comment]
Sorry for not being clear, I was convinced that the videos were self-explanatory. 

On the editor side, the arrows disappear on "large window" and appear when the window is smaller. I think that this should be addressed.

On the frontend side, during the zoom effect, it seems that the image moves. I think that this is a regression introduced by this PR. (I'm not able to replicate it on trunk)

**Comment by danieldudzic** [comment]
Thank you for clarifying, @gigitux!

> On the editor side, the arrows disappear on "large window" and appear when the window is smaller. I think that this should be addressed.

Well, that's kind of to be expected. We can reduce the height of the Large Image in the editor, but then the placeholder will not extend to the full width of the container.

wcIIWFfCPE

> On the frontend side, during the zoom effect, it seems that the image moves. I think that this is a regression introduced by this PR. (I'm not able to replicate it on trunk)

Do we want/need zoom in the Dialog? That behavior is to be expected if the image isn't wide enough to fill out the entire width. I'm not sure how we can "fix" this. Do you have any suggestions?

**Comment by gigitux** [comment]
> Thank you for clarifying, @gigitux!
> 
> > On the editor side, the arrows disappear on "large window" and appear when the window is smaller. I think that this should be addressed.
> 
> Well, that's kind of to be expected. We can reduce the height of the Large Image in the editor, but then the placeholder will not extend to the full width of the container.
> 
> wcIIWFfCPE [ wcIIWFfCPE ](https://user-images.githubusercontent.com/905781/274420786-1a9e4ff5-7318-43f1-a130-39cdf21389ee.gif) [ ](https://user-images.githubusercontent.com/905781/274420786-1a9e4ff5-7318-43f1-a130-39cdf21389ee.gif)
> 

Aaah ok! I didn't realize that there was a scrollbar. Could it sense to make the image smaller?

> > On the frontend side, during the zoom effect, it seems that the image moves. I think that this is a regression introduced by this PR. (I'm not able to replicate it on trunk)
> 
> Do we want/need zoom in the Dialog? That behavior is to be expected if the image isn't wide enough to fill out the entire width. I'm not sure how we can "fix" this. Do you have any suggestions?

Since that we are using the same block in the dialog, we should support all the functionalities in any context. The only thing that we can do, is provide a default state that doesn't have the zoom effect enabled.

The changes that I did in https://github.com/woocommerce/woocommerce-blocks/pull/11113 could help you.

**Comment by danieldudzic** [comment]
> Aaah ok! I didn't realize that there was a scrollbar. Could it sense to make the image smaller?

Would it be beneficial if it would fit in the viewport: yes. The question is how? It's set to Full-Width because that's how it's supposed to display in the front end. I don't know what a potential solution could be here.

> Since that we are using the same block in the dialog, we should support all the functionalities in any context. The only thing that we can do, is provide a default state that doesn't have the zoom effect enabled.

I agree in principle (even though, for example, `Full-screen when clicked` doesn't do anything in the Dialog).

It will be very tricky to "fix", as the way it behaves now is technically correct. The problem is that the image isn't wide enough, so when Zoomed it's a wonky zoom.

I'll have an additional look, next week.

**Comment by danieldudzic** [comment]
> It will be very tricky to "fix", as the way it behaves now is technically correct. The problem is that the image isn't wide enough, so when Zoomed it's a wonky zoom.
> 
> I'll have an additional look, next week.

I was, unfortunately, unable to find a solution to this.

For this not to be a blocker, I'd suggest disabling Zoom in the context of the Dialog altogether.

cc: @gigitux thoughts?

**Comment by gigitux** [comment]
> For this not to be a blocker, I'd suggest disabling Zoom in the context of the Dialog altogether.

Did you try to pull `trunk`? Did we fix it with woocommerce/woocommerce-blocks#11113?

**Comment by danieldudzic** [comment]
This PR is no longer relevant.

**Pull request closed without merging**
