### PR TITLE
`Filter by Attribute` block design updates

### LINKED ISSUE #6843: `Filter by Attributes` block: update the front-end and block panel according to the new design
The goal is to update the `Filter by Attributes` block with the new [proposed design](https://woofse.wordpress.com/2022/08/10/filter-blocks-adjustments-i2/): ([Figma](https://www.figma.com/file/6ZhHLQ7ucHUYgWHr3nusNB/%F0%9F%94%8E-Filter-Blocks-%26-Patterns?node-id=374%3A7448))

category-_-ui-update

### PR DESCRIPTION
**Pull request by albarin**
Update the `Filter by Attribute` block UI to match the new designs.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/6843

### Screenshots

| Before | After |
| ------ | ----- |
| Screenshot 2022-08-19 at 11 36 19 | Screenshot 2022-08-19 at 11 35 10 |
|  Screenshot 2022-08-19 at 11 36 41|   Screenshot 2022-08-19 at 11 37 15 |
| Screenshot 2022-08-19 at 11 38 01 | Screenshot 2022-08-19 at 11 37 28 |
#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [x] E2E tests

#### User Facing Testing

1. Add the `Filter by Attribute` block to a page.
2. Check that it looks like the new design in the editor and the front-end.
3. Check that the `Reset` button appears when a checkbox is checked.
4. Edit the page and change the Display Style to dropdown.
5. Check that it looks like the new design in the editor and the front-end (it won't look exactly like the design, check [this conversation](p1660817888642199-slack-C02SGH7JBGS) for more context)

### WooCommerce Visibility

* [x] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### Changelog

> Update the design of the Filter Products by Attribute block.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
Hey @albarin just a few things Ive noticed:

* If you use this filter block in a block template (e.g. shop) then clicking "Reset" does not refresh the page as it should do. You will probably need to call the `onSubmit` for this to happen.
* If you use this filter block in conjunction with the All Products block, clicking reset does not refresh the results. Im guessing if you fix the above point, this will also be fixed.
* Also on the block template page (e.g. shop) the alignment is off. Please see the below screenshot.

Screenshot 2022-08-19 at 14 37 55

**Comment by vivialice** [comment]
Hey Alba! This is looking really great 🤩 I have made a few notes below: 

For both, can we disable the `Apply` button by lightening the colour before a change has been made? For example, when you `reset` the filter list, it can be unclear that the user needs to save the changes and I think the visual feedback would help here. 

**Dropdown:**
I think it's fine we aren't able to put the link and button within the overlay. Likewise with the badge, using what we have is okay. 

I noticed the dropdown arrow is missing - are we able to add that in? 

After hitting `reset`, we don't need to open the dropdown, just clear the chips. When the user deletes a chip directly, it is okay to keep the overlay open. 

Are we able to match the chip styles in `Active Filters`?

**List:** 
Can we reduce the vertical spacing between list items? It feels a bit too big at the moment. 

I will do another review of these tomorrow, but that's what stuck out to me so far!

**Review by dinhtungdu — COMMENTED** [review]
@albarin This is looking great! The block tested well on my end. However, I found a scenario where the behavior of the Reset button can be improved, please follow these steps to reproduce:
1. Add the attribute filter block to the shop page.
2. Enable the filter button.
3. On the front end, select an attribute.
4. Click on the Reset button, and see the page reloads.

The page doesn't reload when I do the same for Stock and Price filter blocks. So I'm wondering if we can do the same for the attribute filter block. I think we shouldn't reload the page when clicking the Reset button if the filter isn't applied.

**Comment by vivialice** [comment]
I took another look on my test site and I have a couple of other thoughts: 

- Are we able to reduce the button sizes? These should be a smaller style. Currently they are matching other CTAs on the site and lack heriarchy.

Screenshot 2022-08-22 at 11 39 28

- Not sure if this in a separate issue, but can we remove `filter by` on the label headings? 

- I noticed the Heading sizes appear differently in the editor vs on the front end. I'm using TT2 theme. Not sure why this would be the case? 

**Editor:** 
Screenshot 2022-08-22 at 11 59 54

**FE:** 
Screenshot 2022-08-22 at 12 00 15

- This might still be in progress so apologies if it is, but the loading state includes the border and text and should only be a shape like the others.

Screenshot 2022-08-22 at 12 40 21

**Comment by albarin** [comment]
> The page doesn't reload when I do the same for Stock and Price filter blocks. So I'm wondering if we can do the same for the attribute filter block. I think we shouldn't reload the page when clicking the Reset button if the filter isn't applied.

Good catch! I just pushed a fix :)

**Comment by albarin** [comment]
> I noticed the dropdown arrow is missing - are we able to add that in?

Fixed, thanks to @tjcafferkey 🙌 

> After hitting reset, we don't need to open the dropdown, just clear the chips. When the user deletes a chip directly, it is okay to keep the overlay open.

We are checking if we can do that, but since that's the behaviour of the underlying `FormTokenField` component, we might not be able to do it.

>  Can we reduce the vertical spacing between list items? It feels a bit too big at the moment.

Done.

> For both, can we disable the Apply button by lightening the colour before a change has been made? For example, when you reset the filter list, it can be unclear that the user needs to save the changes and I think the visual feedback would help here.

Fixed! 

> Are we able to reduce the button sizes? These should be a smaller style. Currently they are matching other CTAs on the site and lack heriarchy.

I'll do that change on a separate PR since it's not `filter by attributes` specific, but it's affecting all filters.

>  Not sure if this in a separate issue, but can we remove `filter by` on the label headings?

Since we already have this issue to completely remove the headings https://github.com/woocommerce/woocommerce-blocks/issues/6845, do you think it's okey to keep them for now?
 
> I noticed the Heading sizes appear differently in the editor vs on the front end. I'm using TT2 theme. Not sure why this would be the case?

Fixed :)

> This might still be in progress so apologies if it is, but the loading state includes the border and text and should only be a shape like the others.

This will be tackled when we work on this other issue.

Thanks a lot for the review @vivialice, please have another look and let us know what you think! ☺️

**Comment by tjcafferkey** [comment]
>We are checking if we can do that, but since that's the behaviour of the underlying FormTokenField component, we might not be able to do it.

When we click “Reset” and clear the suggestions, it runs [this function](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/form-token-field/index.tsx#L530) which opens the dropdown again [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/form-token-field/index.tsx#L536-L539) because we have `__experimentalExpandOnFocus` set to `true`. But we _need_ that value set to `true` so I don't see another way at the moment, but I'm going to continue investigating.

Also currently when we click “Reset” and open the dropdown. It's quite tricky to get it to close again which results in an experience that isn't ideal.

**Update**: The only way I could find to fix this problem was to force the `<FormTokenField />` component to remount by re-generating a unique ID which I had given the component on reset. Please find the change here https://github.com/woocommerce/woocommerce-blocks/pull/6920/commits/f6d6f9958f702dadcfd1901b7720bb46c15ccb7c

**Review by dinhtungdu — COMMENTED** [review]
@albarin testing the latest commit, I found a small index issue with the price filter:

image

---

Relating to the filter button, I found the block is harder to use when the dropdown and filter button are enabled. When selecting the attribute, the dropdown covers the filter button so users need to click out of the block to hide the dropdown and see the filter button. It think it's the reason why we put the filter button inline with the dropdown formerly.

**Comment by albarin** [comment]
> @albarin testing the latest commit, I found a small index issue with the price filter:

Good catch, just pushed a fix 👌 

> Relating to the filter button, I found the block is harder to use when the dropdown and filter button are enabled. When selecting the attribute, the dropdown covers the filter button so users need to click out of the block to hide the dropdown and see the filter button. It think it's the reason why we put the filter button inline with the dropdown formerly.

I see what you mean, I moved it to the bottom instead of having it inline because now we have the `reset` button that only shows when something has changed, so it felt weird having the dropdown, then a space for the `reset` button and next the `apply` button. There's probably a better solution, I think @vivialice can help us here to decide what to do? 🙏

**Comment by dinhtungdu** [comment]
> I see what you mean, I moved it to the bottom instead of having it inline because now we have the `reset` button that only shows when something has changed, so it felt weird having the dropdown, then a space for the `reset` button and next the `apply` button. There's probably a better solution, I think @vivialice can help us here to decide what to do? 🙏

I think Vivient also thought about that, that's why she put the apply filter button inside the dropdown. I like the reset and submit buttons being in a dedicated row, it's easier to style them and the block. But with the limitation of the `<FormTokenField/>`, we need to find a workaround for this case.

**Comment by vivialice** [comment]
Thanks guys! I just had a review and it's looking great. 

> Since we already have this issue to completely remove the headings https://github.com/woocommerce/woocommerce-blocks/issues/6845, do you think it's okey to keep them for now?

Hmm maybe. Do we have an ETA for this issue? How difficult of a change is it? 

> This will be tackled when we work on this other issue.

👍  

> I think Vivient also thought about that, that's why she put the apply filter button inside the dropdown. I like the reset and submit buttons being in a dedicated row, it's easier to style them and the block. But with the limitation of the <FormTokenField/>, we need to find a workaround for this case.

Yes that is why I originally placed the button and links in the overlay. Keep me posted if you are able to find a solution for this.

**Comment by albarin** [comment]
> Yes that is why I originally placed the button and links in the overlay. Keep me posted if you are able to find a solution for this.

What about something like this @vivialice 👇 
Screenshot 2022-08-23 at 13 36 34

**Comment by albarin** [comment]
> Hmm maybe. Do we have an ETA for this issue? How difficult of a change is it?

@tjcafferkey or @dinhtungdu do you have any news regarding the issue to remove the headings https://github.com/woocommerce/woocommerce-blocks/issues/6845 ? 🤔

**Comment by vivialice** [comment]
> What about something like this @vivialice 👇

It's a good attempt but it's too inconsistent from the other blocks, so I don't think we should do this.

**Comment by tjcafferkey** [comment]
>@tjcafferkey or @dinhtungdu do you have any news regarding the issue to remove the headings https://github.com/woocommerce/woocommerce-blocks/issues/6845 ? 🤔

We're currently exploring a few approaches [here](https://github.com/woocommerce/woocommerce-blocks/pull/6907/). Im not sure on the ETA but it feels we may be close to an approach we can start to implement with a HOC.

It would also be good if @vivialice can take a look at the video in the PR too and post thoughts on it there.

**Comment by albarin** [comment]
@tjcafferkey @dinhtungdu @vivialice I think the only thing missing here is to decide what to do with the Reset/Apply buttons when the `dropdown` is enabled. Does anyone have a better idea?
Should we merge this as is and tackle it in a separate PR?

**Comment by tjcafferkey** [comment]
>Should we merge this as is and tackle it in a separate PR?

I think we can tackle this separately and it shouldn't block this PR, but happy to go with the majority vote on this.

**Review by Aljullu — COMMENTED** [review]
@albarin I was playing around with this PR and I noticed a `z-index` issue when two dropdowns overlap, can you reproduce as well?

imatge

And one question about the design: when only a single item can be selected, could we remove the pill border around? It feels a bit strange.

imatge

**Comment by vivialice** [comment]
> And one question about the design: when only a single item can be selected, could we remove the pill border around? It feels a bit strange.

That pill shouldn't be full width, what is happening here?

**Comment by albarin** [comment]
> > And one question about the design: when only a single item can be selected, could we remove the pill border around? It feels a bit strange.
> 
> That pill shouldn't be full width, what is happening here?

Totally missed testing the behavior for single item! It's fixed now :)

> @albarin I was playing around with this PR and I noticed a z-index issue when two dropdowns overlap, can you reproduce as well?

Can someone give me a hand with this z-index? I've been trying but haven't managed to fix it so far 😞 

Thanks for the review and the patience @Aljullu @vivialice, could you give another try to the single selection issue?

**Comment by tjcafferkey** [comment]
>Can someone give me a hand with this z-index?

on it 😄

**Review by tjcafferkey — APPROVED** [review]
It looks like the remaining issues raised by @vivialice and @Aljullu have been fixed. The only outstanding issue is the `z-index` one spotted by Albert, however we've decided to merge this PR and tackle this final issue independently. Good job on this PR @albarin !

**Pull request merged**
