### PR TITLE
Update from deprecated registerStore to register for data stores

### LINKED ISSUE #7032: Use `register` instead of `registerStore` from wpData
## Describe the bug

wpData have updated the `registerStore` function to `register`, and marked `registerStore` as deprecated. We should make sure we use the new function throughout our codebase

### PR DESCRIPTION
**Pull request by alexflorisca**
This updates the way data stores are registered to the wp.data global registry. The `registerStore` function has been deprecated in favour of `createReduxStore` and `register`. 

Fixes #7032 

#### User Facing Testing

1. Open up the Checkout Block page on the front end
2. Open up the redux dev tools
3.  Make sure the following stores are present:

- `wc/store/cart`
- `wc/store/collections`
- `wc/store/checkout`
- `wc/store/payment`
- `wc/store/query-state`
- `wc/store/validation`
- `wc/store/schema`

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by tarhi-saad — APPROVED** [review]
Thank you, @alexflorisca, for updating all the stores! They are available on the front-end, and the code looks good! So, let's 🚢 it 🙌

**Comment by alexflorisca** [comment]
Converting this back to draft as there's a problem we discovered with the `subscribe` function actually subscribes to any change from any store, not just the cart store. So this might not work. Waiting to hear back from gutenber folks here: p1666869842896719-slack-C45SNKV4Z

**Comment by alexflorisca** [comment]
This [PR](https://github.com/WordPress/gutenberg/pull/45513) in Gutenberg will solve the problem with not being able to subscribe to a single store. However this won't be merged into WP Core for a while so we will need to delay using subscribe in this way.

I think the best way to move forward with this PR is to remove the changes to the cart store, and keep the rest as none of the other stores use the `subscribe` method

**Review by tarhi-saad — APPROVED** [review]
Thank you, @tarunvijwani, for resetting the changes on the cart store. I added a comment to explain the reason behind keeping the deprecated "registerStore"

**Pull request merged**
