### PR TITLE
Use backslashes to fix webpack build on windows

### LINKED ISSUE #6797: Windows development issue - `SassError: This file is already being loaded.`
## Describe the bug
When running `npm run build` on Windows 10 or 11, it shows ` SassError: This file is already being loaded.` and the project cannot build. I suspect this is caused by Windows directory separators not being tested correctly.

This was also reported here (https://github.com/woocommerce/woocommerce-blocks/issues/6029#issuecomment-1067905345) but the user who found the issue didn't make the follow up ticket.

There is another issue where building sass files from the `node_modules` directory doesn't work and that is also caused by the  directory separators.

## To reproduce

1. Load Windows 10 or 11.
2. Clone the repo, ensure you're using node v16 and run `npm install`
3. Next run `npm run build`
4. See error.

## Expected behavior

Project should build regardless of platform.

### LINKED ISSUE #7440: Cannot build on windows
## Describe the bug

Cannot build on Windows

## To reproduce

1. Run `npm run start`

## Expected behavior

Successfull build

### WordPress (please complete the following information):

-   WordPress version: 6.0.1

### Desktop (please complete the following information):

-   OS: Windows

## Additional context

```    ERROR in ./assets/css/abstracts/_mixins.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This file is already being loaded.
      ╷
    1 │ @use "sass:math";@use "sass:string";@use "sass:color";@use "sass:map";@import "_colors"; @import "_variables"; @import "_breakpoints"; @import "_mixins"; $fontSizes: (
      │
                               ^^^^^^^^^
      ╵
      assets\css\abstracts\_mixins.scss 1:144  root stylesheet
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\webpack\lib\NormalModule.js:316:20
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass-loader\dist\index.js:62:7
        at Function.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:99807:16)
        at render_closure1.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:85345:12)
        at _RootZone.runBinary$3$3 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:29712:18)
        at _FutureListener.handleError$1 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28226:21)
        at _Future__propagateToListeners_handleError.call$0 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28533:49)
        at Object._Future__propagateToListeners (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3936:77)
        at _Future._completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28379:9)
        at _AsyncAwaitCompleter.completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28024:12)
        at Object._asyncRethrow (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3712:17)
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:19922:20
        at _wrapJsFunctionForAsync_closure.$protected (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28043:12)
        at _awaitOnObject_closure0.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28037:25)
        at _RootZone.runBinary$3$3 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:29712:18)
        at _FutureListener.handleError$1 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28226:21)
        at _Future__propagateToListeners_handleError.call$0 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28533:49)
        at Object._Future__propagateToListeners (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3936:77)
        at _Future._completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28379:9)
        at _AsyncAwaitCompleter.completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28024:12)
        at Object._asyncRethrow (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3712:17)
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:15400:20
        at _wrapJsFunctionForAsync_closure.$protected (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28043:12)
        at _awaitOnObject_closure0.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28037:25)
        at _RootZone.runBinary$3$3 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:29712:18)
        at _FutureListener.handleError$1 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28226:21)
        at _Future__propagateToListeners_handleError.call$0 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28533:49)
        at Object._Future__propagateToListeners (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3936:77)
        at _Future._completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28379:9)
        at _AsyncAwaitCompleter.completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28024:12)
        at Object._asyncRethrow (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3712:17)```

### PR DESCRIPTION
**Pull request by opr**
This PR will modify the webpack config to test for Windows directory separators too in case someone is developing on a Windows machine.

In #6797 I reported that certain Sass files were not loading and it is because the test did not check for Windows directory separators (which use a backslash  instead of a forward slash).

Fixes #6797
Might fix #7440 (investigation required)

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### Manual testing
1. Get a Windows 10 or 11 machine
2. Run `npm run build` and ensure no errors show up.
3. Smoke test the blocks and ensure styles are working properly.
4. Do the same on Mac or Linux and check step block and styles are working correctly.

#### User Facing Testing

None required.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Developers: Fixed an issue where the project would not build on Windows machines.

### CODE REVIEW

**Comment by wavvves** [comment]
@opr this has merging conflicts with trunk that might involve some refactoring to the work done 😢

**Comment by senadir** [comment]
I'm removing the `needs_review` until we have a rebased/updated solution for this, is this fine?

**Comment by opr** [comment]
> I'm removing the `needs_review` until we have a rebased/updated solution for this, is this fine?

Yes, I am going to work on it this cooldown, so I'll add it back when I fix it.

**Comment by senadir** [comment]
I added on hold so this isn't shown on the PR reminder.

**Comment by opr** [comment]
@senadir  and @wavvves  this is now ready for review. I tested on my Windows machine and the project builds!

@Tropicalista would you like to test this as well? Please also make sure you're using node v16.6.0 or greater (that's what I tested with)

**Comment by wavvves** [comment]
> @senadir  and @wavvves  this is now ready for review. I tested on my Windows machine and the project builds!
> 
> 
> 
> @Tropicalista would you like to test this as well? Please also make sure you're using node v16.6.0 or greater (that's what I tested with)

Shouldn't it be compatible with the node version from .nvmrc?

**Comment by Tropicalista** [comment]
I can confirm it builds on Windows 11 and node `v16.16.0`.

**Comment by opr** [comment]
> Shouldn't it be compatible with the node version from .nvmrc?

Yes it should, but I had a really hard time getting nvm to work on Windows, something I recall a lot of people having issues with. I mentioned node 16.6.0 because that's what I tested with.

**Review by senadir — APPROVED** [review]
I didn't test in windows but this PR doesn't break anything in Mac and 2 of you said it fixes windows so let's merge.

**Pull request merged**
