### PR TITLE
Align text sizing in filter blocks: chips, checkboxes, buttons, dropdown

### LINKED ISSUE #7119: Filter Block Buttons appearing differently in the editor vs the front end
The button styles for the theme aren't translating over to the front end for some reason. In this example from the pre-set styles in the TT2 theme, buttons are shown with a border radius in the editor but aren't showing in the front end. 

Screenshot 2022-09-09 at 14 07 04

Screenshot 2022-09-09 at 13 51 09

### LINKED ISSUE #7126: Text sizing for Filter Blocks
Let's clean up the text sizing across all the blocks as they aren't looking consistent or following heirarchy. 

Some notes with screenshots:
Screenshot 2022-09-12 at 16 44 31

Summary: 
- Currently we have what looks like 5 or 6 text sizes, at most we should have maybe two. Not including the header/label text size. 
- To me, the ideal target size is the size used in the filter by price input. Can we update: all list, chips, dropdown, reset/clear links, button text to this

Reference: 
This mockup with the empty state is the visual balance we want. Majority of the type slightly smaller in proportion to other text on the site (body, header text).

### LINKED ISSUE #42591: Filter Block Buttons appearing differently in the editor vs the front end
The button styles for the theme aren't translating over to the front end for some reason. In this example from the pre-set styles in the TT2 theme, buttons are shown with a border radius in the editor but aren't showing in the front end. 

Screenshot 2022-09-09 at 14 07 04

Screenshot 2022-09-09 at 13 51 09

### PR DESCRIPTION
**Pull request by kmanijak**
Font sizes (Twenty Twenty-Two):

Applied mixin: `font-size(small)`

| Element | Editor - was | Editor - is | Frontend - was | Frontend - is |
| ------ | ----- | ------ |----- | ------ |
|  Active filters - list                 |  18px     |  **15.75px**  |   18px  | **15.75px**   |
|  Active filters - chips                |  18px     |  **15.75px**  |   18px  | **15.75px**   |
|  Active filters - 'Clear All'          |  15.75px  |  **15.75px**  | 15.75px | **15.75px**   |
|  Filter by price - editable            |  14px     |  **15.75px**  | 13.3px  | **15.75px**   |
|  Filter by price - text                |  18px     |  **15.75px**  | 18px    | **15.75px**   |
|  Filter by attribute - list            |  18px     |  **15.75px**  | 18px    | **15.75px**   |
|  Filter by attribute - dropdown - chips|  13px     |  -            | 13px    | **15.75px**   |
|  Filter by attribute - placeholder     |  13px     |  **15.75px**  | 13px    | **15.75px**   |
|  Filter by rating/stock                |  18px     |  **15.75px**  | 18px    | **15.75px**   |
|  Others - 'Reset'                      |  -        |  -  | 13.3px |  **15.75px**  |
|  Others - 'Apply'                      |  15.75px  |  **15.75px**  | 16px    | **15.75px**   |

Standardised font-size using `font-size(small)` mixin (no zoom in browser):
| Theme | `font-size(smaller)`<br />not used in PR, for comparison only | `font-size(small)`<br />used in PR |
|----- | ------ | --- |
| Twenty Twenty-Two | 13.5px | **15.75px** |
| Twenty Twenty-Three | 12px - 13.5px | **14px** - **15.75** |

Other fixes:
- 'Apply' button for Filter by Attribute had different padding in Editor (there's [an issue for that](https://github.com/woocommerce/woocommerce/issues/42591))

Fixes woocommerce/woocommerce-blocks#7126 
Partially fixes woocommerce/woocommerce#42591 ("Apply" button size, but doesn't fix the problem of square vs rounded buttons)

#### (Twenty Twenty-Two)
| Case | Before | After |
| ------ | ----- |----- |
|  Editor   |   TT2-editor-before  |   TT2-editor  |
|  Frontend   |   TT2-fe-before  |    TT2-frontend  |

#### (Twenty Twenty-Three)
| Case | Before | After |
| ------ | ----- |----- |
|  Editor   |   TT3-editore-before   |   TT3-editor   |
|  Frontend   |   TT3-frontend-before  |   TT3-fe  |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Enter Site Editor
2. Insert WooCommerce Product Filters pattern
3. Check the font-sizes in both, **Editor and the Frontend**, of the following elements in following combinations
  - Active filters: list and chips
  - Active filters: "Clear All" button
  - Filter by Price: editable and text
  - Filter by Attribute: list and dropdown (check placeholder, dropdown options and chips)
  - Filter by Rating
  - Filter by Stock
  - For each of the above enable "Apply" button - check it too
4. On the frontend:
  - Check "Apply" button
  - Provide any change to filters without applying - check "Reset" button

**Expected:** All of the above have the same font-size: 
- Twenty Twenty-Two: 15.75px
- Twenty Twenty-Three: 14 - 15.75px (depends on the screen width, narrower the screen, smaller the font)

Note: headings are not expected to change!

Check at least briefly other blocks of a WooCommerce that could be influenced by the changes (there may be something I might've missed).

### WooCommerce Visibility

* [ ] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### Changelog

> Align the font-sizes in filters

### CODE REVIEW

**Comment by vivialice** [comment]
This is looking really good @kmanijak !

**Comment by kmanijak** [comment]
@dinhtungdu, @vivialice, please take a look at this font-sizes alignment. 🙏 

There are also two open questions:
- isn't 12.04px font-size on Twenty Twenty-Three theme too small?
- maybe we should seek a generic solution to avoid fractional font-sizes? Even if the answer is yes I think unification of font sizes is still a good middle step.

**Comment by Aljullu** [comment]
Sorry for chiming in here, but wanted to give my two cents. :upside_down_face: 

> isn't 12.04px font-size on Twenty Twenty-Three theme too small?

I have the same concern. I was testing this PR in Storefront and widget controls are the smallest texts in the page, even smaller than the _Category:_ label in the footer and the _Posted on_ text above the title.
imatge

Wondering if we could go with `font-size(small)` instead of `smaller`.

Btw, @kmanijak, I noticed that the Filter by Attributes dropdown text is slightly bigger (13px) than the other controls (12px), is that indended?

> maybe we should seek a generic solution to avoid fractional font-sizes? Even if the answer is yes I think unification of font sizes is still a good middle step.

I'm curious, are there any cons of using a fractional font-size?

**Review by dinhtungdu — COMMENTED** [review]
Great work @kmanijak, I followed the testing instructions and both TT3 and TT2 were tested well.

About your questions

> isn't 12.04px font-size on Twenty Twenty-Three theme too small?

I agree with @Aljullu that this is too small. 

> maybe we should seek a generic solution to avoid fractional font-sizes? Even if the answer is yes I think unification of font sizes is still a good middle step.

Browsers actually don't have issues with subpixel rendering. The web has been using fractional `em` for years, which will lead to fractional `px`. So I also don't think we need to avoid fractional font-size.
Btw, I found a good article testing fractional px font size [here](https://freiesfeld.de/programming/2020/06/18/css-and-fractional-font-size/).

**Comment by kmanijak** [comment]
Thanks for a review and your comments! 🙌 

---

### Too small font size

@dinhtungdu ,
> I agree with @Aljullu that this is too small.

@Aljullu ,
> Wondering if we could go with font-size(small) instead of smaller.

Let me try `font-size(small)` out, I'll provide a screenshots and we can agree on final size.
Unless we'd like to adjust the font size contextually depends on the theme. There's multiple places styles are wrapped in theme class (e.g `.theme-twentytwentyone { ... }`. But I'm not sure if that doesn't add unnecessary complexity. Happy to hear your opinion.

> I noticed that the Filter by Attributes dropdown text is slightly bigger (13px) than the other controls (12px), is that indended?

It's not, I'll take care of this, thanks for catching it!

---

### Fractional font-size

> I'm curious, are there any cons of using a fractional font-size?

> Browsers actually don't have issues with subpixel rendering. 

I had in mind the differences in how scaling is performed by different browsers, but that's rather really minor caveat.

> Btw, I found a good article testing fractional px font size [here](https://freiesfeld.de/programming/2020/06/18/css-and-fractional-font-size/).

Great one! Thanks for providing this!

**Comment by kmanijak** [comment]
### Too small font size

I agree the `font-size(small)` is more readable for both themes. One important thing to mention, that I didn't notice earlier, is the default font-size for TT3 theme is dynamic, based on the variable:

`--wp--preset--font-size--medium: clamp(1rem, 1rem + ((1vw - 0.48rem) * 0.24), 1.125rem);`

As you can see it's based on a screen-width, and this is the value taken to calculate the final font-size using `em` from `font-size` mixin.

Hence, the font-sizes for filters are as following:

| Theme | font-size(smaller) | font-size(small) |
|----- | ------ | --- |
| Twenty Twenty-Two | 13.5px | **15.75px** |
| Twenty Twenty-Three | 12px - 13.5px | **14px** - **15.75** |

For TT3 the font sizes are dynamic, but are aligned between Editor and a Frontend.

The PR description has been updated to the newest values.

### Newest changes summary:

- Use `font-size(small)` instead of `font-size(smaller)`
- Placeholder in Filter by Attributes dropdown font-size is adjusted
- Updated PR description with newest values and screenshots.

@dinhtungdu, I'd be grateful if you could take a look again 🙏 
@Aljullu, feel free to do the same if you wish 🙏

**Review by Aljullu — APPROVED** [review]
LGTM. Just a couple of comments:

* I noticed that in the Filter by Attribute block, the dropdown placeholder still has the inherited font size instead of the small one. Can you reproduce as well?

imatge

* I think we should convert [this value](https://github.com/woocommerce/woocommerce-blocks/blob/9ff8dba0cf91c0750b65408fd9ed7295d7d508af/packages/checkout/components/checkbox-control/style.scss#L20) to em  (the [em mixin](https://github.com/woocommerce/woocommerce-blocks/blob/9ff8dba0cf91c0750b65408fd9ed7295d7d508af/assets/css/abstracts/_mixins.scss#L181-L184) should help with this: `em( $gap )`). It doesn't make a huge difference, but I feel it better adapts to the theme font size.

16px | 1em
--- | ---
imatge | imatge


Besides that, everything else looks good to me, so pre-approving.

**Comment by kmanijak** [comment]
Thanks @Aljullu for a second round of review!

> I noticed that in the Filter by Attribute block, the dropdown placeholder still has the inherited font size instead of the small one. Can you reproduce as well?

Interesting 🤔 I couldn't reproduce it. In TT2 I see 15.75px which is expected size. One thing that comes to my mind is that I applied the styles to the placeholder pseudo-element directly ([see the commit](https://github.com/woocommerce/woocommerce-blocks/pull/7707/commits/a5f58543ef92f793fd9aa687dd59bacfe364e465)). In the dev tools the size for the `input` element itself would show bigger (18px in TT2) than for the placeholder (15.75px in TT2), whose styles are not displayed by default (at least in Chrome). [Here's a description how to enable that in Chrome in case you'd be interested](https://stackoverflow.com/questions/26852922/inspect-webkit-input-placeholder-with-developer-tools/26853319#26853319).

But anyway - that made me realise I didn't apply the font-size for input text in a dropdown. So [the this commit ](https://github.com/woocommerce/woocommerce-blocks/pull/7707/commits/f0d0522059a84a1905a19c6c58dfbed41ad1e4eb) covers both:
- input text
- placeholder
 
https://user-images.githubusercontent.com/20098064/204560406-113a233c-da84-4528-bbaa-e45cd12b1dff.mov

> I think we should convert [this value](https://github.com/woocommerce/woocommerce-blocks/blob/9ff8dba0cf91c0750b65408fd9ed7295d7d508af/packages/checkout/components/checkbox-control/style.scss#L20) to em (the [em mixin](https://github.com/woocommerce/woocommerce-blocks/blob/9ff8dba0cf91c0750b65408fd9ed7295d7d508af/assets/css/abstracts/_mixins.scss#L181-L184) should help with this: em( $gap )). It doesn't make a huge difference, but I feel it better adapts to the theme font size.

I agree! It looks much better especially on narrower screens, good one! Change applied [in this commit](https://github.com/woocommerce/woocommerce-blocks/pull/7707/commits/cf398a94870345ca8bb2854ac556269aa1013555).

**Pull request merged**
