### PR TITLE
Newest Products: fix Stock Status filter

### LINKED ISSUE #9389: Newest Products block becomes empty when changing settings
### Steps to reproduce
1. Create new post
2. Add Newest Products block
3. Change settings (open and change Filter by Stock controls)

### Expected
Blocks works normally

### Actual
Block becomes empty with the annotation "Block rendered as empty"

### Notes
- That may be related to the specific setup (ref: peapX7-2k4-p2#comment-2817)
- The easiest path MAY be to replace it with Products block instead of fixing the current one

### PR DESCRIPTION
**Pull request by kmanijak**
When testing Newest Products block against WordPress 6.3 I found a problem, the Stock Status filter in Inspector Controls doesn't work and crashes the block.

This is due to the initial state of `stockStatus` was `undefined`, while it's expected to be an array and also, by default all of the stock statuses should be enabled.

This PR adds the necessary initial state for Newest Products to work correctly.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9389

### Screenshots

Result after clicking "Filter by stock status":

| Before | After |
| ------ | ----- |
|   image     |   image    |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to Editor
2. Add Newest Products block
3. Focus on block
4. Try to open "Filter by stock status" and change the switches
5. Expected: Block doesn't crash and reacts to changes
6. Save and check that block renders on the frontend

* [ ] Do not include in the Testing Notes 

Additional tests - do not include below testing steps in the release testing notes!

1. Checkout to `trunk`
2. Add custom stock statuses. You can do so by using a plugin that manipulates Stock Statuses or by adding a following script to your `functions.php`:

```
// Add custom stock status to products in WooCommerce
function filter_woocommerce_product_stock_status_options( $status ) {
    // Add new statuses
    $status['pre_order'] = __( 'Pre order', 'woocommerce' );
    return $status;
}
add_filter( 'woocommerce_product_stock_status_options', 'filter_woocommerce_product_stock_status_options', 10, 1 );
```

3. Add one of your newest products to the custom "Pre Order" stock status
4. Go to Editor
5. Add Newest Products block
6. Save
7. Checkout to this branch (`fix/wordpress-6-3-newest-products`)
8. Go to edited post/template
9. Make sure Newest Products displays the same set of products

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Newest Products: Fix the stock status filter that would crash the block when opened

### CODE REVIEW

**Review by Aljullu — APPROVED** [review]
Good catch with this @kmanijak! Something I wonder is whether we should use the statuses set in `stockStatusOptions`, which honors statuses added by extensions. It looks like the editor controls read from that setting:

https://github.com/woocommerce/woocommerce-blocks/blob/9ec54b4561bf1b43e6cc303078646055c84cf578/assets/js/editor-components/product-stock-control/index.tsx#L17-L18

However, considering we are planning to replace this block with the Product Collection some time soon, I don't think that's a blocker, so leaving the decision up to you.

**Comment by kmanijak** [comment]
> Something I wonder is whether we should use the statuses set in stockStatusOptions, which honors statuses added by extensions. It looks like the editor controls read from that setting:

Good point @Aljullu ! 🤔 I double-checked and all the statuses will be displayed in the list based on the logic you mentioned. It's only about what statuses should be enabled by default, which I think is fair behavior.

image

**Review by Aljullu — COMMENTED** [review]
> I double-checked and all the statuses will be displayed in the list based on the logic you mentioned. It's only about what statuses should be enabled by default, which I think is fair behavior.

The issue I see is that if you had a product with the 'Custom stock status', in `trunk` it would be displayed in a _Newest Products_ block without custom attributes, while in this branch it would not.

Steps to reproduce:
1. In `trunk`, add a couple of products to the stock status you have created (ie I added _Beanie with Logo_ and _Tshirt with Logo_).
2. Add the Newest Products block to a post or page. Notice _Beanie with Logo_ and _Tshirt with Logo_ are there.
3. Now, check out this branch.
4. Notice _Beanie with Logo_ and _Tshirt with Logo_ are no longer displayed in the block you added in step 2.

`trunk` | This branch
--- | ---
imatge | imatge

I think we should avoid causing a change in which products are displayed by default. That's why I suggested adding _all_ status options to the default attribute. An alternative approach could consist on updating `<ProductStockControl />` so it doesn't break when `value` is `undefined`. This way we don't need to change the default attribute of the block.

**Comment by kmanijak** [comment]
> The issue I see is that if you had a product with the 'Custom stock status', in trunk it would be displayed in a Newest Products block without custom attributes, while in this branch it would not.

> I think we should avoid causing a change in which products are displayed by default. That's why I suggested adding all status options to the default attribute. An alternative approach could consist on updating <ProductStockControl /> so it doesn't break when value is undefined. This way we don't need to change the default attribute of the block.

Great catch and an equally great suggestion! Thank you @Aljullu!

I changed the approach and also added additional testing steps to cover this case. Do you mind checking it again?

**Comment by thealexandrelara** [comment]
I'm bumping the milestone for this PR to 10.8.0.

**Review by Aljullu — APPROVED** [review]
LGTM, thanks for the updates, @kmanijak!

For the testing steps, I think only this code snippet is needed, no? :thinking: 

```PHP
// Add custom stock status to products in WooCommerce
function filter_woocommerce_product_stock_status_options( $status ) {
    // Add new statuses
    $status['pre_order'] = __( 'Pre order', 'woocommerce' );
    return $status;
}
add_filter( 'woocommerce_product_stock_status_options', 'filter_woocommerce_product_stock_status_options', 10, 1 );
```

**Pull request merged**
