### PR TITLE
Single Product block: Add wide and full-width alignments support

### LINKED ISSUE #8900: Single Product Block: Add support to wide and full-width alignments
Since the work on the Single Product Block is almost done, we can start mapping some enhancements that we want to do. One of these enhancements is to add support to wide and full-width alignments to the block

The idea is to have controls that allows the merchants to modify the alignment property providing the opportunity to select between wide and full-width alignments.

### PR DESCRIPTION
**Pull request by thealexandrelara**
The idea is to have controls that allows the merchants to modify the alignment property providing the opportunity to select between wide and full-width alignments.

Fixes #8900

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
| image | image  |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

## Site Editor

1. Log in to your WordPress dashboard;
2. Go to Appearance > Themes, and select a block theme (for example: Twenty-twenty three);
3. Go to Appearance > Site Editor;
4. Click the Edit button;
5. Click on the "+" icon to add a new block and search for "Group" block in the search bar;
6. Click on the "Group" block to add it to your page or post;
7. Select a layout and click the "+" icon to add a new block and search for "Single Product" block in the search bar;
8. Select the Single Product block, check that the align option is being shown and change the Align to Wide;
9. Select a product on the Product Selector and click on the Save button;
10. Check that the product is displayed wide on the frontend;
11. Go back to the Editor, select the Single Product block and change the Align to Full Width;
12. Check that the product is displayed as full width on the frontend;

## Post or Page

1. Log in to your WordPress dashboard;
2. Go to Pages (or Posts) > Add New;
3. Click on the "+" icon to add a new block and search for "Single Product" block in the search bar;
4. Click on the "Single Product" block to add it to your page or post;
5. Select the Single Product block, check that the align option is being shown and change the Align to Wide;
6. Select a product on the Product Selector and click on the Save button;
7. Check that the product is displayed wide on the frontend;
8. Go back to the Editor, select the Single Product block and change the Align to Full Width;
9. Check that the product is displayed as full width on the frontend;

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### Changelog

> Add wide and full width alignments support to Single Product Block

### CODE REVIEW

**Review by nefeline — CHANGES_REQUESTED** [review]
Hi there!

Thanks for working on this. Here are the test results:

> Click on the "+" icon to add a new block and search for "Group" block in the search bar;
> Click on the "Group" block to add it to your page or post;
> Select a layout and click the "+" icon to add a new block and search for "Single Product" block in the search bar;
> Select the Single Product block, check that the align option is being shown and change the Align to Wide;

✅ Confirmed the align options are displayed:

Screenshot 2023-04-11 at 14 06 06

> Check that the product is displayed wide on the frontend;
> Go back to the Editor, select the Single Product block and change the Align to Full Width;
> Check that the product is displayed as full width on the frontend;

❌ When an alignment option is selected for this block, no changes are observed on the FE:

https://user-images.githubusercontent.com/15730971/231238260-944bf3f9-dd84-44db-b27d-4df945c260cc.mov

**Comment by thealexandrelara** [comment]
> ❌ When an alignment option is selected for this block, no changes are observed on the FE:

Thank you @nefeline for pointing this out, I just pushed a new commit that fix that issue. I think the correct classes were not being applied since the class attribute was hardcoded, but now it is dynamic

**Comment by nefeline** [comment]
Thanks for the update 🙌 !

Things are now working as expected when adding the Single Product block within a Group block on a template or template part, but when adding this same combination of blocks in a post or page, it still doesn't work. Basically, I'm still seeing the same behavior as demonstrated on:

https://user-images.githubusercontent.com/15730971/231238260-944bf3f9-dd84-44db-b27d-4df945c260cc.mov

**Comment by thealexandrelara** [comment]
> Thanks for the update 🙌 !
> 
> Things are now working as expected when adding the Single Product block within a Group block on a template or template part, but when adding this same combination of blocks in a post or page, it still doesn't work. Basically, I'm still seeing the same behavior as demonstrated on:
 
Ohh nice catch! I was investigating this issue, and what is happening is that the Group block, when used inside a Post or Page, also has support for Wide and Full Width alignments; by default, the alignment is set to None (650px). However, when we add the Single Product inside, it will respect the outer block width, so even if we change it to Wide or Full Width, the block will be restricted to a max width of 650px.

I just updated the testing instructions because, inside a Post or Page, adding a Group block to wrap the Single Product block is unnecessary, so we don't need to have that step when inside these. Because the latter will have support for the alignments without needing to be wrapped in a Group block. Thank you for the detailed review, as always 🙌

**Review by nefeline — APPROVED** [review]
> Ohh nice catch! I was investigating this issue, and what is happening is that the Group block, when used inside a Post or Page, also has support for Wide and Full Width alignments; by default, the alignment is set to None (650px). However, when we add the Single Product inside, it will respect the outer block width, so even if we change it to Wide or Full Width, the block will be restricted to a max width of 650px.

> I just updated the testing instructions because, inside a Post or Page, adding a Group block to wrap the Single Product block is unnecessary, so we don't need to have that step when inside these. Because the latter will have support for the alignments without needing to be wrapped in a Group block. Thank you for the detailed review, as always 🙌

Thanks for investigating this, great job! 🎉 

I can confirm everything works as expected :shipit:

**Comment by thealexandrelara** [comment]
WooCommerce Blocks 10.1.0 will be released soon. I'm bumping this PR to the next milestone

**Pull request merged**
