### PR TITLE
Improve Hero Product Chessboard pattern

### LINKED ISSUE #11404: [CYS Woo Express] Hero product chessboard
Pattern: `Hero product chessboard`.

First section:
- Review spacing between heading and subheading.
- Review spacing between subheading and cta.

Second section:
- Review spacing between title and body.
- Review spacing between single modules.

image

---

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1406-127650&mode=design&t=ZBW0Ds0G26mxIowu-4)

image

### PR DESCRIPTION
**Pull request by gigitux**
## What

Fixes #11404. This PR improves:
- spacing
- text size

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Add a new post.
2. Add the `Hero Product Chessbord` pattern.
3. Save the page.
4. Visit the saved page
5. Ensure that the pattern looks like in the images below.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

### Mockup

| Desktop |Mobile |
| ------ | ----- |
|image|image|

### Implementation

| Desktop | Mobile |
|--------|--------|
|locale local|'Locale Galaxy Fold| 

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by albarin** [comment]
@gigitux In general we want the patterns to be wireframe, meaning they should have any font or color settings hardcoded, so they work well in all themes. In this case, I think we should not set the `"fontSize": "large"` in the headings, we discussed this for other patterns a few days ago, sorry you weren't in the loop yet.

Also, could we add some more spacing between the title and the text in the bottom left square of the pattern? The titles seem too close to the content compared to the designs.

**Comment by gigitux** [comment]
> @gigitux In general we want the patterns to be wireframe, meaning they should have any font or color settings hardcoded, so they work well in all themes. In this case, I think we should not set the `"fontSize": "large"` in the headings, we discussed this for other patterns a few days ago, sorry you weren't in the loop yet.
> 
> Also, could we add some more spacing between the title and the text in the bottom left square of the pattern? The titles seem too close to the content compared to the designs.
 
Thanks for the feedback! I removed the hardcoded font size for all blocks. Also, I added more spacing!

This is the final result:

| Desktop | Mobile |
|--------|--------|
|locale local (1)|locale local_724-2_(Galaxy Fold)|

**Review by albarin — APPROVED** [review]
Code looks good to me, @verofasulo could you review as well? 🙏

**Comment by verofasulo** [comment]
>  @verofasulo could you review as well?

Thanks for tagging me, @albarin 🙏

I can't see the visual issues described above addressed, to be honest. 😅 Are you able to access the Figma file and have a deeper look at the specs?  

If you enable the dev mode, it's easier 😊 

image

**Comment by gigitux** [comment]
> I can't see the visual issues described above addressed, to be honest. 😅 Are you able to access the Figma file and have a deeper look at the specs?

Are you referring to the space between the two columns, right? Sorry, I should be more specific on why I didn't implement it. I didn't because the same spacing would be applied on the mobile view.

**Comment by verofasulo** [comment]
> Are you referring to the space between the two columns, right?

Not specifically 🙂 many things are still not in good shape, but I'm not sure if there's a specific reason behind it.

Here's a pic with the proper spacing in more detail:

image

Also, it looks like all the font sizes are off and barely readable. Could we please check all the font sizes in this pattern? The body seems like 12px, which is not accessible. What style did we apply?

**Comment by gigitux** [comment]
> Could we please check all the font sizes in this pattern? The body seems like 12px, which is not accessible. What style did we apply?



We don't apply any custom font size (as specs for all the patterns).

I addressed some feedback about the spacing:

## Desktop

image


## Mobile

locale local_852-2_(iPhone XR) png``` -  ```Locale iPhone XR (2)

**Comment by verofasulo** [comment]
> We don't apply any custom font size

I'm aware of it — We apply text styles tho. Is this correct? 

From Jarek's design, I can see the text style applied is [Tsubaki] Body small - 16px. 
There are three body styles: L (18 px), S (16 px), and XS (14 px).

Despite the fact that text styles can differ between themes, it's unlikely that the regular body text in TT3 is set to 12px. This is what I'd like to be double-checked — I have the feeling that there are inconsistencies in lots of patterns and the result is a visual appearance far away from the original design with accessibility issues.

**Comment by verofasulo** [comment]
cc @jarekmorawski

**Comment by jarekmorawski** [comment]
That's correct. When I worked on the designs, I extracted the font styles from the theme's code. It's quite possible, however, that some blocks have hardcoded values that do not adhere to the text styles (or that the version of the theme I tested was outdated or experimental).

All in all, I'd stick to the global styles defined in the theme. If Tsubaki uses 12 px for body, I'd stick to it and contribute a change upstream to improve the theme's overall appearance, legibility, and accessibility. But first, I'd double check other patterns to see what's the baseline font style we use elsewhere, then apply the same style here.

**Comment by gigitux** [comment]
> unlikely that the regular body text in TT3 is set to 12px.

The font-size is 18px (the default TT3 font size):

image

**Comment by jarekmorawski** [comment]
I'd use the default front-size if it exists as a style in TT3. In general, body=default.

**Comment by gigitux** [comment]
> I'd use the default front-size if it exists as a style in TT3. In general, body=default.

[I'm using the default font size](https://github.com/WordPress/twentytwentythree/blob/11440a5b38bae6882fc2c00b703d4bb95420a0f5/DESIGN-SPEC.md?plain=1#L18): 
image

**Comment by verofasulo** [comment]
> [I'm using the default font size](https://github.com/WordPress/twentytwentythree/blob/11440a5b38bae6882fc2c00b703d4bb95420a0f5/DESIGN-SPEC.md?plain=1#L18):

Okay, thanks for checking, @gigitux! We tested it yesterday with Ghidorah, and the font size was 12px. Happy we changed it 😊

**Comment by gigitux** [comment]
> > [I'm using the default font size](https://github.com/WordPress/twentytwentythree/blob/11440a5b38bae6882fc2c00b703d4bb95420a0f5/DESIGN-SPEC.md?plain=1#L18):
> 
> Okay, thanks for checking, @gigitux! We tested it yesterday with Ghidorah, and the font size was 12px. Happy we changed it 😊

Yes! I removed the custom font size in this PR 👍 

Can I merge this PR?

**Comment by verofasulo** [comment]
> Yes! I removed the custom font size in this PR

Awesome! Have you checked the headings too? They seem to be off.  

- H2 for the main heading. 
- H4 for the others in the second row. 

They look all the same now. Thanks!

**Comment by gigitux** [comment]
> > Yes! I removed the custom font size in this PR
> 
> Awesome! Have you checked the headings too? They seem to be off.
> 
> * H2 for the main heading.
> * H4 for the others in the second row.
> 
> They look all the same now. Thanks!

It is H3 with bold enabled for the main heading.
H4 with bold enabled for others in the second row.

In this screenshot, I updated the H2 and removed the bold.

image


If you think that this screenshot is better, I will update the pattern!

**Comment by verofasulo** [comment]
> It is H3 with bold enabled for the main heading.
H4 with bold enabled for others in the second row.
In this screenshot, I updated the H2 and removed the bold.

@gigitux, I'm not sure why they're all H3 now 😅

As mentioned above, the first heading is H2:

Screenshot 2023-10-27 at 16 48 15

 while the others are H4:

image

**Comment by gigitux** [comment]
> I'm not sure why they're all H3 now 😅

Sorry for not being clear. Only the first header was H3, and the rest were H4. I updated the PR and now, the first header is H2.

@albarin, can you take a look?

**Review by albarin — APPROVED** [review]
👌

**Pull request merged**
