### PR TITLE
Cross-Sells block: Replace <AddToCartButton /> with <ProductButton />

### LINKED ISSUE #8858: Cross-Sells Products block: Replace Add to Cart block with Product Button block
In woocommerce/woocommerce#44503, @kmanijak suggested removing the Add to Cart block as that block is experimental, hasn't been touched for 3 years and as there's a newer block. Currently, the Cross-Sells Block is still using the Add to Cart block. This issue aims to replace the Add to Cart block with the Product Button block within the Cross-Sells Products block.

### PR DESCRIPTION
**Pull request by nielslange**
Fixes woocommerce/woocommerce-blocks#8858

In woocommerce/woocommerce#44503, @kmanijak suggested removing the Add to Cart block as that block is experimental, hasn't been touched for 3 years and as there's a newer block. Currently, the Cross-Sells Block is still using the Add to Cart block. This issue aims to replace <AddToCartButton /> with <ProductButton /> within the Cross-Sells Products block. 

### Screenshots

<table>
<tr>
<td>Before:
<br><br>

Screen Shot 2023-03-31 at 13 43 12
</td>
<td>After:
<br><br>

Screen Shot 2023-03-31 at 13 41 45
</td>
</tr>
</table>

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests
  
> **Note**
> The affected E2E test can individually be triggered using the following command:
> ```sh
> npm run test:e2e -- tests/e2e/specs/shopper/cart-checkout/cart.test.js
> ```

#### User Facing Testing

1. Install and activate the [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) theme.
2. Create a test page with the Cart block.
3. Ensure that you have four products:
  - 2 x Simple Product
  - 1 x Grouped Product
  - 1 x Variable Product
4. Open one of the Simple Products and define the other Simple Product, the Grouped Product and the Variable Product as Cross-sells products:
Screen Shot 2023-03-31 at 13 31 51

5. Go to the frontend.
6. Add the Simple Product from step 3. to the cart.
7. Open the test page from step 1.
8. Verify that the Cross-sell products, as defined in step 4., are visible in the cart.
9. Verify that the buttons `Select options`, `View products` and `Add to cart` are visible.
10. Verify that the buttons from the previous step show the same styles as the `Proceed to Checkout` button.
11. Verify that clicking the `Select options` button opens the corresponding product page.
12.  Verify that clicking the `View products` button opens the corresponding product page.
13. Verify that clicking the `Add to cart` button adds that Cross-sell product to the cart.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Update: Replace <AddToCartButton /> with <ProductButton /> within the Cross-Sells Products block.

### CODE REVIEW

**Comment by mikejolley** [comment]
Will you also be removing the block thats not in use, or is this used elsewhere?

**Comment by nielslange** [comment]
> Will you also be removing the block thats not in use, or is this used elsewhere?

To remove the "Add to Cart" block, @kmanijak created woocommerce/woocommerce#44503. I'd keep this separate from this PR, as it requires in-depth testing.

I also noticed that all E2E tests are failing currently. I briefly looked into this, but haven't had time to see what's causing this. What I noticed was that [all E2E tests of the featured branch](https://github.com/woocommerce/woocommerce-blocks/actions/runs/4571956868) are also failing.

**Review by mikejolley — APPROVED** [review]
Change looks good to me but we should make sure it's not this causing e2e breakage. I noticed some visual bugs on trunk so it might be unrelated.

**Comment by nielslange** [comment]
> Change looks good to me but we should make sure it's not this causing e2e breakage. I noticed some visual bugs on trunk so it might be unrelated.

Thanks for your review, @mikejolley. It appears that the failing E2E tests were related to woocommerce/woocommerce-blocks#8928. I just ran the failing E2E tests again, and all tests are passing now:

Screen Shot 2023-04-04 at 11 07 16

**Pull request merged**
