### PR TITLE
Button: Update deprecated props

### LINKED ISSUE #11855: Replace deprecated button props `isPrimary`, `isSecondary`, `isTertiary` and `isLink`
With Gutenberg 14.2.0, the button props`isPrimary`, `isSecondary`, `isTertiary` and `isLink` have been deprecated in favour of `variant`. See https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md#1420-2021-07-21 and  https://github.com/WordPress/gutenberg/pull/31713. 

Currently, we're still using all four deprecated button props:
- [`isPrimary`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks%20isPrimary&type=code) → should be replaced with `variant="primary"`
- [`isSecondary`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks+isSecondary&type=code) → should be replaced with `variant="secondary"`
- [`isTertiary`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks+isTertiary&type=code) → should be replaced with `variant="tertiary"`
- [`isLink`](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-blocks+isLink+language%3ATSX&type=code) → should be replaced with `variant="link"`

Reference:
- https://developer.wordpress.org/block-editor/reference-guides/components/button/#variant-primary-secondary-tertiary-link

### PR DESCRIPTION
**Pull request by arsanyjoseph**
## What

Fixes #11855

## Why

This PR updates the deprecated `isPrimary`, `isSecondary`, `isTertiary` and `isLink` props to the `variant` prop.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new page
2. Add test blocks from the file: [testblocks](HTTP://cloudup.com/cTsFpZodJye)
3. Make sure that all the updated buttons work/appear correctly.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

PR description updated by @danieldudzic

### CODE REVIEW

**Comment by arsanyjoseph** [comment]
@nielslange 
Not sure how to fill in the report

**Comment by nielslange** [comment]
> Not sure how to fill in the report

Thanks for asking and, especially, thanks for your contribution, @arsanyjoseph! 🙌

As for filling in the PR, allow me to briefly walk you thought the sections and give you examples.

- **What**: Here you mention the corresponding issue, in this case #11855. You can also mention what you adjusted, but mentioning the issue is the most important part.
- **Why**: This section explains why this PR is needed. In this particular case because the button props `isPrimary`, `isSecondary`, `isTertiary` and `isLink` re deprecated, meaning they will stop working in the future.
- **Testing Instructions**: This is another crucial section, as this helps the person, that is reviewing the PR, to understand what to look for. Your articular PR affects the styling of the buttons. Therefore, it would be helpful to point out the various sections/buttons, that are affected by your change so that a reviewer can verify that the PR works as expected and did not break existing styles.
- **Screenshots or screencast**: This section is usually used to show the before and after screenshots or a screencast. In your case, both before and after screenshots should look identical, as you replaced deprecated functionality with a newer one.
- **WooCommerce Visibility**: You PR will land in _WooCommerce Core_ so you can select this checkbox. Some changes are "guarded" behind the featured or experimental gate. On https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md?plain=1 you can learn more about that. For now, don't worry too much about this, though. `N/A` is used for changes that are not visible such as changing in the tooling, e.g. #8013.
- **Checklist**: Don't worry too much about this section, either. It helps the development team to ensure that nothing falls though the cracks. 
- **Changelog**: This section is used to highlight the change in the changelog when shipping a new release that contains the change. You can find an example in https://developer.woo.com/2023/11/23/woocommerce-blocks-10-6-0-release-notes-2/. Everything that's mentioned in `Changelog » Enhancements` and `Changelog » Bug Fixes` is coming from that changelog section. It's great if you can add a speaking changelog message, but don't worry too much if you don't know how to phrase your changes properly.

I hope this helps. If you have any further questions, feel free to ask anytime!

**Comment by danieldudzic** [comment]
@arsanyjoseph, do you need any further assistance? Were @nielslange's suggestions helpful?

**Comment by danieldudzic** [comment]
As we are migrating to the WooCommerce monorepo this weekend I'm taking over this PR so that we can get it merged before the migration.

**Review by danieldudzic — APPROVED** [review]
I have now updated the PR description and tested it. Buttons are working fine with the updated props.

**Comment by danieldudzic** [comment]
All tests have passed on the copy of this PR here: https://github.com/woocommerce/woocommerce-blocks/pull/12099

I'm merging.

**Pull request merged**
