### PR TITLE
Fix an Endless loop when using handpicked-products

### LINKED ISSUE #6416: Endless loop when using `handpicked-products`
## Describe the bug

When the current product is in the list of `handpicked-products`, it results in an endless loop, causing out of memory issues.

There is no indication of what caused the error; all users see is a white screen of death.

The screenshot below, is from my local environment, where "luckily", after 256 nested loops, it crashed.

Thanks @andrew-ajrwebdesign, for reporting this, and sorry for the trouble!

## To reproduce

Steps to reproduce the behavior: (replicated on my local environment)

1. Enable Gutenberg for products
```php
function ps_activate_gutenberg( $can_edit, $post_type ) {
	if ( 'product' === $post_type ) {
		$can_edit = true;
	}
	return $can_edit;
}
add_filter( 'use_block_editor_for_post_type', 'ps_activate_gutenberg', 10, 2 );
```
2. Assuming you have products created, edit a product with ID `17` and add the following code. Note that `17` is in the array of `"products":[17,38,31,34]`

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column">
<!-- wp:woocommerce/handpicked-products {"columns":4,"editMode":false,"contentVisibility":{"image":true,"title":true,"price":true,"rating":true,"button":true},"products":[17,38,31,34]} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```
3. Press update, and you'll be greeted with an error `Updating failed` - If you reload the wp-admin edit product page, you'll get a fatal error (or white screen of death)
4. Visit the product page, you'll get a fatal error (or white screen of death)
5. On some hosts, it causes out of memory issues.

```
Fatal error: Uncaught Error: Maximum function nesting level of '256' reached. aborting 
in /Users/panos/Locasites/app/public/testsite/wp-includes/class-wp-object-cache.php on line 493
```

Another easier way, is to add the block normally, and select the product you're currently editing

image

In order to "fix" the errors, users would have to disable Gutenberg for product blocks, edit the product (switch to code), remove the conflicting ID, save and then enable block support once again.

OR

Do the exact same change on a database level. 

## Expected behavior

It shouldn't crash. If the current product ID, is in the list of products, then it should be ignored and move on with the rest.

On top of that, the current product, shouldn't be available in the `search for products to display`

## Screenshots

Edit product “Test 10” ‹ WordPress 2022-05-16 12-20-42 png 2022-05-16 12-51-32

## Solution

It can be tackled on PHP level, and when looping the products, if `global $post_id` is the same as the current ID of the loop, then `continue`.

In the future, when the block is refactored, we can use the `Query Loop` and limit the products displayed in the `Search for products to display` field

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   WooCommerce version: 6.5.1
-   WooCommerce Blocks version: 7.6.0

### PR DESCRIPTION
**Pull request by PanosSynetos**
Fixes #6416

As described in the issue, there is an endless loop if the `handpicked-products` block is used in a product, and the user has selected the same product ID as the one currently viewing.

The `hack` is to remove the `$post->ID` from the list of selected product IDs, just on the PHP side.

This works and partially solves the issue
- Viewing the product/block on the frontend ✅
- Viewing the block on the backend ✅
- Editing the block on the backend (results in an infinite loop/fatal error) ❌

And it makes sense, as when editing the product, there is a call to the StoreAPI, `global $post` is not available, and it keeps on causing the endless loop.

https://user-images.githubusercontent.com/2484390/170231319-75ac7021-9a6c-4d64-a9eb-a7a003144c99.mp4

It needs more work on the JS side of things. 

- maybe passing the current post ID as props so we can filter it out
- when selecting products, exclude the current product from the list of products
- don't save the current product ID in the block's attributes

The above are just rough ideas, but as @Aljullu mentioned, this block will be refactored to use the Query Loop block.

Until then, my solution is temporary, to avoid infinite loop fatal errors.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1.
2.
3.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by Aljullu** [comment]
Thanks for opening this PR, @PanosSynetos! As I was reviewing it, I was wondering if the same check you added to Handpicked Products could be used when making the product query, so that benefits all other blocks. So I took the liberty to open a new PR: #6471. Feel free to take a look!

**Comment by PanosSynetos** [comment]
Awesome @Aljullu - Awesome stuff :) I like the way you think!

I see that you have missed the `parent_post_id` check. Was there a reason?
When diving through the code with xdebug, it was passing from `set_block_query_args` for all the revisions, again and again, and kept on causing infinite loops.

@danieldudzic that was the reason why, even if you were removing the post_id from the array, it kept on failing. ;)

@Aljullu I guess your PR covers this PR, right? So we'll not merge this one?

**Comment by danieldudzic** [comment]
> @danieldudzic that was the reason why, even if you were removing the post_id from the array, it kept on failing. ;)

That's it, good catch!

My code was quite similar to your PR, but yeah I was missing the _set_block_query_args for all the revisions_ part :)

Good job.

**Comment by Aljullu** [comment]
> I see that you have missed the `parent_post_id` check. Was there a reason?
> When diving through the code with xdebug, it was passing from `set_block_query_args` for all the revisions, again and again, and kept on causing infinite loops.

Do you have some steps to reproduce it? I'm not sure to understand what the issue is here.

> @Aljullu I guess your PR covers this PR, right? So we'll not merge this one?

Yes, the intention is that #6471 should replace this PR.

**Comment by PanosSynetos** [comment]
> > I see that you have missed the parent_post_id check. Was there a reason?
When diving through the code with xdebug, it was passing from set_block_query_args for all the revisions, again and again, and kept on causing infinite loops.

> Do you have some steps to reproduce it? I'm not sure to understand what the issue is here.

Hey @Aljullu - At the point where I did the fix, the execution was passing again and again, even for revisions - hence the check for the parent id.

Where you do the filtering, doesn't seem to be affected by revisions, so we're good.

**Comment by Aljullu** [comment]
@PanosSynetos given that #6471 was merged, do you think we can close this PR?

**Comment by PanosSynetos** [comment]
Hey @Aljullu , sure I'll go ahead and close it

**Pull request closed without merging**
