### PR TITLE
Store API Cart Docs Update

### LINKED ISSUE #7878: Feedback on ./src/StoreApi/docs/cart.md
Under "Select Shipping Rate", it looks like the "package_id" -> "required" is set to "string" rather than a boolean "yes" or "no" value, and the description is set to "yes". I'm guessing the intention was to set the "type" to integer | string which moved everything over a column.

Screen Shot 2022-12-07 at 1 41 23 PM

### PR DESCRIPTION
**Pull request by mikejolley**
Small docs fix - there was a mistake in the cart data types table.

Closes #7878

### CODE REVIEW

**Review by tarunvijwani — APPROVED** [review]

**Comment by dinhtungdu** [comment]
@mikejolley FYI, this PR introduces new MD errors for `src/StoreApi/docs/cart.md`: https://github.com/woocommerce/woocommerce-blocks/actions/runs/3686970590/jobs/6239949821

**Comment by mikejolley** [comment]
@dinhtungdu, there must be a discrepancy between our linting rules and editor config because VSCode formats this automatically. Ill check its not my environment.

**Comment by mikejolley** [comment]
@dinhtungdu https://github.com/woocommerce/woocommerce-blocks/pull/7968

**Comment by dinhtungdu** [comment]
@mikejolley You're correct. Look like most of us will use Prettier as the MD formatted, while `wp-scripts` uses `markdownlint` to format MD files. We should fix that issue to make Prettier and markdownlint using the same format.

By the way, we check the MD file using precommit hook, didn't it catch those lint issues for you?

**Comment by mikejolley** [comment]
@dinhtungdu no, nothing was shown. Do I need to do anything special to make that work?

**Comment by dinhtungdu** [comment]
@mikejolley if a staged MD file contains errors, we should get this message when committing:

```sh
% git commit        
husky > pre-commit (node v16.17.0)
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ package.json — 1 file
    ↓ *.scss — no files [SKIPPED]
    ↓ *.{js,ts,tsx} — no files [SKIPPED]
    ↓ *.php — no files [SKIPPED]
    ❯ *.md — 1 file
      ✖ npm run lint:md:docs [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ npm run lint:md:docs:
/Users/tung/Sites/wc/app/public/wp-content/plugins/woocommerce-blocks/src/StoreApi/docs/cart.md:6:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
/Users/tung/Sites/wc/app/public/wp-content/plugins/woocommerce-blocks/src/StoreApi/docs/cart.md:7:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]

> @woocommerce/block-library@9.2.0-dev lint:md:docs
> wp-scripts lint-md-docs

husky > pre-commit hook failed (add --no-verify to bypass)
```


> Do I need to do anything special to make that work?

Everything should be installed and configured by installing node modules. Can you try a fresh clone? Look like it is the quickest way, I can't find mentions about regenerating git hooks on [the Husky docs](https://typicode.github.io/husky/#/).

**Pull request merged**
