### PR TITLE
Update patterns with the new images

### LINKED ISSUE #11780: Update Patterns with the new images
We have to update the patterns with the new images by following the designs provided by @verofasulo.

### PR DESCRIPTION
**Pull request by gigitux**
## What

Fixes #11780 

## Why

This PR improves the default state of some patterns.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Add a new post.
2. Add all the patterns in the section below and ensure they match the screenshot.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

#### Featured Category Cover Image
image

#### Hero Product Split

image

#### Just Arrived full hero 

image

#### Featured Category Triple 

image

#### Hero product 3 Split
image

#### Hero Product Chessboard

 locale local

#### Banner

image

#### Featured Category Focus
image

#### Alterning image and text 
image

 
#### Testimonials single
image

#### Social Media

image

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Review by albarin — COMMENTED** [review]
Hey @gigitux, overall looks good, I'm just leaving here some questions/suggestions, sorry if some of them are design decisions I've missed 🙏 

- `Banner`: I'm seeing some hard-coded blue colors, is this expected? I see in your screenshots the color is white.
Screenshot 2023-11-16 at 14 13 05

- `Alternating image and text`: this is not related to this PR (it's actually a mistake I did 😬) but while testing I noticed that in the `dictionary.json` the `{image.1}` placeholder is on the pattern text, not in the AI prompt (check [here](https://github.com/woocommerce/woocommerce-blocks/blob/ba6bd9e409bc0daff5b74124f73fd4d62540bf44/src/Patterns/dictionary.json#L522)). Would you mind fixing it? Otherwise I can do it in another PR.

- `Featured Category Focus`: it also has a hard-coded color, is it expected?

Thanks! 🙌

**Comment by albarin** [comment]
@gigitux Also, I see a few of the new images are over `2mb` of size, could we try optimizing them a bit? We did that when added the pattern placeholder images and managed to reduce the size significantly.

**Comment by albarin** [comment]
@gigitux I found an issue with a few patterns, I'm getting the `Attempt block recovery` error message in the editor for:
- `Testimonals single`
- `Banner`
- `Featured Category Focus`

To reproduce: insert the patterns, save and refresh the editor.

Screenshot 2023-11-16 at 14 25 42
Screenshot 2023-11-16 at 14 25 47
Screenshot 2023-11-16 at 14 26 18
ory Focus`





Also, probably unrelated to this PR, I'm seeing the images on `Social: Follow us on social media` don't maintain the aspect ratio square on the frontend (they do in the editor):
Screenshot 2023-11-16 at 14 32 08

**Comment by gigitux** [comment]
> Hey @gigitux, overall looks good, I'm just leaving here some questions/suggestions, sorry if some of them are design decisions I've missed 🙏
> 
> * `Banner`: I'm seeing some hard-coded blue colors, is this expected? I see in your screenshots the color is white.
> 
> Screenshot 2023-11-16 at 14 13 05
> * `Alternating image and text`: this is not related to this PR (it's actually a mistake I did 😬) but while testing I noticed that in the `dictionary.json` the `{image.1}` placeholder is on the pattern text, not in the AI prompt (check [here](https://github.com/woocommerce/woocommerce-blocks/blob/ba6bd9e409bc0daff5b74124f73fd4d62540bf44/src/Patterns/dictionary.json#L522)). Would you mind fixing it? Otherwise I can do it in another PR.
> * `Featured Category Focus`: it also has a hard-coded color, is it expected?
> 
> Thanks! 🙌

Thanks for the review!

I fixed the banner pattern with [81b3183](https://github.com/woocommerce/woocommerce-blocks/pull/11782/commits/81b3183b2e563916d5250dac27bec8c8fbaf84a7).

I updated the dictionary.json with [c130ee4](https://github.com/woocommerce/woocommerce-blocks/pull/11782/commits/c130ee4b3fff1fa8e86e1f7f1030221fad56b28e).

I noticed that only an image was 2.1 MB and I optimizated it with [0d7a317](https://github.com/woocommerce/woocommerce-blocks/pull/11782/commits/0d7a3175189016c2048b063ee44c8a14f03a1b02).

> Featured Category Focus: it also has a hard-coded color, is it expected?

Good point! I asked it to @verofasulo! Let's wait for feedback!

**Comment by gigitux** [comment]
> `Social: Follow us on social media`

Good catch! I was able to replicate the issue with `Testimonals Single` and `Banner` patterns. I fixed them with [09e7c05](https://github.com/woocommerce/woocommerce-blocks/pull/11782/commits/09e7c05694c3f0baf724aaf47ab0f50403849fd2).

**Review by albarin — APPROVED** [review]

**Comment by gigitux** [comment]
> Featured Category Focus: it also has a hard-coded color, is it expected?

After a chat with @verofasulo, I updated the Featured Category Focus:

image

@albarin I will wait for your final review before merging this PR!

**Review by albarin — APPROVED** [review]
Nice job! Thanks for addressing all the comments! 🙌

**Pull request merged**
