### PR TITLE
Product button: Fix 'In cart' button localization.

### LINKED ISSUE #7494: The "In cart" text is not translatable within the All Products Block
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The "x in cart" text is not translating within the All product Block within WooCommerce core.

Screen Shot on 2022-10-25 at 13:32:38

This was reported on the WooCommerce Forums.

https://wordpress.org/support/topic/woocommerce-all-products-block-will-not-display-chinese/

Screen Shot 2022-10-25 at 13 37 58

### Expected behavior

The "x in cart" text which displays on the Add To Cart button after adding a product to the cart from the All Products Block should be translatable using Loco Translate or similar.

### Actual behavior

There is the text for `%d in cart` within the WooCommerce core language files. Changing that however does not affect the product Add To Cart buttons of the All Products Block.

Screen Shot on 2022-10-25 at 13:37:12

### Steps to reproduce

1. Add an instance of the All Products Block to the page.
2. Use a plugin like Loco Translate to translate the text of `%d in cart` within the WooCommerce core plugin language files
3. Visit the All Products Block page and add a product to the cart.
4. See the issue.

### WordPress Environment

The latest version of WordPress + WooCommerce core.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by danieldudzic**
Fixes the issue with the "x in cart" text not translating within the **All products** block.

Fixes #7494.

Co-authored-by: Niels Lange <info@nielslange.de>

### Screenshots

| Before | After |
| ------ | ----- |
| Produkty_–_ratings-2|Produkty_–_ratings|

### Testing
1. Add an instance of the **All Products** Block to the page.
2. Use a plugin like Loco Translate to translate the text of `%d in cart` within the WooCommerce core plugin language files.
3. Visit the All Products Block page and add a product to the cart.
4. Verify the string is being translated.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing
Same as the above.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Product button: Fix 'In cart' button localization.

### CODE REVIEW

**Comment by sunyatasattva** [comment]
Tagging @gigitux here. The change to return `null` from `register_block_type_assets` function was made by him in [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/6948). I assume the reason is connected with compatibility with the Product Query block.

It seems this change could cause a cycle of back-and-forth reversions, so maybe @gigitux can clarify why that change was required and how can we restore l12n without undoing support for Product Query.

**Comment by gigitux** [comment]
Thanks @sunyatasattva, for tagging me! 

I made that change because when this block is used in the PQ, we generate the markup on the server side, so it isn't necessary to load JS assets.

But if we break custom translations, we have to find another solution. We are using this approach for all atomic blocks :/

**Comment by sunyatasattva** [comment]
Well, many atomic blocks don't use translations, right? Like Product Image. But we need to be aware of those which do. Do you suggest to merge this PR and create an issue on the Product Query epic to figure out an alternative solution?

I think it's more important to fix the breaking translations now and merge this, as our work on the PQ is not public yet. What do you think?

**Comment by gigitux** [comment]
@sunyatasattva It makes sense. We can investigate this issue in the following weeks 👍 

I will open an issue about this!

**Review by sunyatasattva — APPROVED** [review]

**Pull request merged**
