### PR TITLE
Fix: remove IntersectionObserver shim

### LINKED ISSUE #3035: Remove IntersectionObserver shim when we drop IE11 support.
Remove IntersectionObserver shim when we drop IE11 support.

---
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b2e3d05ec6e9d371d3c8f2068cb86216133b669d/assets/js/base/utils/get-intersection-observer.js#L13-L24
---
###### :rocket: This issue was generated by the [automations bot](https://github.com/woocommerce/automations) based on a `todo` comment in b2e3d05ec6e9d371d3c8f2068cb86216133b669d when #3004 was merged. cc @Aljullu

### PR DESCRIPTION
**Pull request by dinhtungdu**
As WordPress 5.8 dropped support for IE11, so does WooCommerce, this PR removes the shim for `IntersectionObserver`. This PR also converts the source file to typescript.

Fixes #3035 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)
- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Check out this PR.
2. Run `npm run dev`.
3. Test the Cart block, see no error in console.

### Changelog

> Remove IntersectionObserver shim in favor of dropping IE11 support.

### CODE REVIEW

**Comment by dinhtungdu** [comment]
I'm wondering should we remove the function entirely because of the shim removal? We only use it in `usePositionRelativeToViewport`, and the `@woocommerce/base-utils` is an internal package of this repo.

**Comment by tjcafferkey** [comment]
>I'm wondering should we remove the function entirely because of the shim removal? We only use it in usePositionRelativeToViewport, and the @woocommerce/base-utils is an internal package of this repo.

I think so. Lets encourage the usage of the native Web API now that we support it and seeing as though it is only used in one place it should be a fairly simple removal.

**Comment by dinhtungdu** [comment]
@tjcafferkey I removed the helper, please give this PR another look!

**Review by tjcafferkey — APPROVED** [review]
Sorry for the delay on this re-review. LGTM 🚀

**Pull request merged**
