### PR TITLE
Rename js/components to js/editor-components

### LINKED ISSUE #2954: Consider renaming /assets/js/components/ to /assets/js/editor-components/
All components inside `/assets/js/components/` are exclusively used inside the editor, but the folder naming is a bit conflicting, especially with folders like `/assets/js/base/components/`, we should consider renaming it to something more relevant to the editor.

### PR DESCRIPTION
**Pull request by haszari**
Fixes #2954

This PR renames our editor components (aka `block-components`) so it's clear they are for use in the editor. 

Changes:

- source folder rename  `js/components` => `js/editor-components`
- alias rename `@woocommerce/block-components` => `@woocommerce/editor-components`
- fixed up mentions in docs
- fixed jest config and relative paths in jest tests
- fixed reference in typescript config

### How to test the changes in this Pull Request:

1. Rebuild everything.
2. Smoke test all the blocks - there's a lot of impact here!
3. (Thanks in advance for mega testing.)

Since there's a lot of impact here, feel free to start a checklist of blocks or components to test, so we can tag-team it.

Also test storybook - confirm all relevant stories are working correctly.

### Changelog

> Dev: Renamed `@woocommerce/block-components` alias `@woocommerce/editor-components`.

### CODE REVIEW

**Comment by haszari** [comment]
Huge appreciation to our e2e (thank you @senadir!) & other tests/checks, great to have that protection when doing a big refactor!

**Review by Aljullu — COMMENTED** [review]
I tested all blocks listed in the [.org description](https://wordpress.org/plugins/woo-gutenberg-products-block/) and did some extra smoke testing with the Single Product block, and everything seemed to be fine. :ok_hand: 

Only thing: we should update the [editor components path in webpack-configs.js](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/bin/webpack-configs.js#L420).

**Comment by haszari** [comment]
> Only thing: we should update the editor components path in webpack-configs.js.

Good spotting! I did not know about that 🙂 

I'm not clear on how/what this would break. Would it break the built stylesheets, so `editor-component` styles would be bundled in `style.css` and enqueued on front end? Feel free to add info about this to PR description for posterity / clarity (and testing instructions if useful). 

Now fixed d82f6fd7ecebe49b5361b7e0865aa961c38987c0, and also note I rebased the PR to latest `main`.

Ready for another review @Aljullu ! If it passes review, feel free to go ahead and merge for me – I don't want this huge changeset going stale... 🧅

**Comment by Aljullu** [comment]
> I'm not clear on how/what this would break. Would it break the built stylesheets, so `editor-component` styles would be bundled in `style.css` and enqueued on front end? Feel free to add info about this to PR description for posterity / clarity (and testing instructions if useful). 

Actually it didn't break anything, but some styles from editor components leaked into `style.css`. `style.css` is always loaded, so everything worked as usual, but that meant we were loading some editor styles in the store frontend.

For reference, I noticed that because `github-actions` showed a file size increase for `style.css`:

> imatge

I don't think there is a need to add testing instructions for this since everything was working as usual.

**Review by Aljullu — APPROVED** [review]
Working great! :ok_hand:

**Pull request merged**
