### PR TITLE
Upgrade TypeScript to 5.3.2

### PR DESCRIPTION
**Pull request by samueljseay**
## What

* Upgrade TypeScript to version 5.3.2

## Why

Our current version of TypeScript is very old and already lead to some unusual bugs for me while trying to use certain language features.

Here is an example of a TS playground that fails in 4.7.4 but works perfectly in newer versions: https://www.typescriptlang.org/play?target=99&isolatedModules=true&ts=4.7.4#code/MYewdgzgLgBNICcCmMC8MAUBKNA+TA3tAIZRIBcMR5A5MXFAgJZgDmNAvh1gFA+iRYBBqRQc0DREmwBuPkgAeAB0SwoATyUoAYiBASNWkADMRZOT0MoAgmHAAVTUgA8MezHzoCPAJABtGAAFGBYYAGskdRM3GABdSnsA4Ni5DgtFFQQ1JxhdEAB9CVsHJ2craJIyXDkrXKYAGzIEAGUoUSK7MEctV3LTSpRq+WVVGFrA5mAkbQam1vb0GcakFrbzIA

I think it's pretty obvious we should keep these dependencies up to date, this will also align with Woo core who are on TS 5+.

## Testing Instructions

As long as all the CI checks pass I think we're ok since right now we don't actually fail on TS errors. I have decided not to try and fix any particular issues with upgrading here, because we can always fix them as we encounter them in our work. 

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast
n/a
## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by gigitux** [comment]
Hey @samueljseay,
Thanks for opening this issue! Super agree that we have to upgrade the TS version! My only concern is that with this issue, we are introducing new TS errors:

> This PR introduces new TS errors on 31 files:

Looking at these errors, it seems that some libraries create new TS errors (maybe they are incompatible with the new version of TS). Before merging this PR, should we try to update all the devDependecies?

**Comment by samueljseay** [comment]
@gigitux yep fair enough, let me take a look and see if its not too much work to get the dependencies updated.

**Comment by samueljseay** [comment]
@gigitux the errors are dependencies of dependencies so I really felt its low value to deal with that. We could force resolution of newer versions but probably our `@wordpress` dependencies are just a bit out of date now.

I have opted to use `skipLibCheck` for now instead I think its a more pragmatic approach since we still are in a state where we have don't have error free TS this feels like an OK compromise to me. Wdyt?

I will have a look at the 8 remaining errors in our codebase though, since its not many, maybe there are some here that are low effort to fix in this PR.

**Comment by gigitux** [comment]
> I have opted to use skipLibCheck for now instead I think its a more pragmatic approach since we still are in a state where we have don't have error free TS this feels like an OK compromise to me. Wdyt?

LGTM!

**Review by gigitux — APPROVED** [review]
Thanks for updating TS and its configuration! 🚢

**Pull request merged**
