### PR TITLE
Fix: Add support to apply filters via URL for All Products block

### LINKED ISSUE #6441: Add support to apply filters via URL when it is used the `All Products` block and a `Product Filter` block
## Is your feature request related to a problem? Please describe.
At this stage when the user uses a `Product Filter` block and the `All Products` block, it is not possible to apply a filter via URL as on the PHP template.

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #6441

With this PR, when filtering for the All Products block:

- The URL is updated on filter state changes.
- Only the URL is updated, no page reload occurs.
- Initial filters are set from the URL like PHP templates.

This PR also:
- simplifies the logic that set the initial filters from the URL and makes the filter blocks more stable.
- fixes the issue with the Filter Products by Stock Status when filtering the All Products block on the homepage (see [screenshot](https://user-images.githubusercontent.com/5423135/176631335-607f075e-22bc-4f9f-bd7f-5901fd823508.png)).

#### To reviewers:

- Should we disable the new behavior by default and let developers enable it by a filter or setting?
- The codebase of filter blocks are similar and I think we should refactor and extract the common logic to share between them during the cooldown periods.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

https://user-images.githubusercontent.com/5423135/176621151-db1644d8-3e86-4615-b8fe-eba095dcfb34.mov

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

For each filter block, ensure:
- No regression when used with PHP templates.
- The URL is updated when checking or unchecking filters.
- For filter blocks using the filter button, the URL is updated after clicking the filter button.
- With the updated URL, all selected filters are set correctly after reloading the page. Filter blocks with or without the filter button should work the same.
- Removing the filter from the Active Filters block should update the URL and the corresponding filter block.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add filter URL support to filter blocks when filtering for All Products block.

### CODE REVIEW

**Comment by dinhtungdu** [comment]
Requesting additional reviews because this is a quite big PR.

**Review by albarin — APPROVED** [review]
Nice work! Works 👌

**Comment by dinhtungdu** [comment]
> Nice work! Works 👌

@albarin Thanks for your review and testing! Do you think we should let stores enable/disable the URL updating function when filtering the All Products Block?

**Comment by albarin** [comment]
@albarin Thanks for your review and testing! Do you think we should let stores enable/disable the URL updating function when filtering the All Products Block?
Not sure if doing that would provide much value, I might be missing something, do you think by enabling this by default we could bother some users? maybe break something? 🤔

**Comment by dinhtungdu** [comment]
> Not sure if doing that would provide much value, I might be missing something, do you think by enabling this by default we could bother some users? maybe break something?

@albarin You're right! I also don't think it will bother users. Because if users add filter blocks to pages, they already want to filter products.

**Review by Aljullu — COMMENTED** [review]
Nice to see this improvement! Everything seems to be working fine except the back/forward button in the All Products block with filters:

https://user-images.githubusercontent.com/3616980/177539966-1842ad83-81da-4f49-bf07-c0623ba52078.mp4

In the screencast above, you will notice that I have to press twice for the query URL to be cleared, and even when doing so, the filter is not cleared. Is that something that would be easy to fix?

> The codebase of filter blocks are similar and I think we should refactor and extract the common logic to share between them during the cooldown periods.

Good idea! Could you create an issue for this?

**Comment by dinhtungdu** [comment]
@Aljullu In 0c2e198, I use `replaceState` instead of `pushState` to avoid creating new history entries.

Clearing/updating the filter on history changes is possible but we need to create a router for that purpose. By the way, using `pushState` will create a new entry on every change to the query state. So I think the optima direction here is using the `replaceState` method. What do you think?

**Comment by dinhtungdu** [comment]
> Good idea! Could you create an issue for this?

Looking closer at filter blocks, the logic of common actions is quite different for each filter block. In 2a94b77, I extract the logic that updates the URL or reloads the page. At the moment, it's the only logic that is worth extracting IMO. So I don't think we need to create an issue anymore.

**Review by Aljullu — APPROVED** [review]
> Clearing/updating the filter on history changes is possible but we need to create a router for that purpose. By the way, using `pushState` will create a new entry on every change to the query state. So I think the optima direction here is using the `replaceState` method. What do you think?

Makes sense and it's testing alright. :+1: 

> Looking closer at filter blocks, the logic of common actions is quite different for each filter block. In 2a94b77, I extract the logic that updates the URL or reloads the page. At the moment, it's the only logic that is worth extracting IMO. So I don't think we need to create an issue anymore.

Sounds good.

**Comment by Marc-pi** [comment]
@Aljullu / @dinhtungdu 

`we should let stores enable/disable the URL updating function when filtering the All Products Block?`
please don't, changing url per query is **a very very bad practice** in term of SEO. You generate duplicate content.
Please use hashbang instead (#!), but the better is to not use query strings in url at all

`Should we disable the new behavior by default and let developers enable it by a filter or setting?`
yes, but again please please avoid pushing query string vars in url (get)

**Comment by dinhtungdu** [comment]
@Marc-pi Thanks for your comments! I agree that we should ensure the plugin optimized for SEO. I have some questions related to your comments and love to hear your options:

> please don't, changing url per query is a very very bad practice in term of SEO. You generate duplicate content.
Please use hashbang instead (#!), but the better is to not use query strings in url at all

WC has been applying filters through URL for a long time with filter widgets. I'm wondering how stores are dealing with the filter URL.

From my research, we can use the canonical tag to avoid duplicated content issue according to [this page](https://developers.google.com/search/docs/advanced/guidelines/duplicate-content). What do you think?

> A better solution is to allow search engines to crawl these URLs, but mark them as duplicates by using the rel="canonical" link element or 301 redirects.

 _(Thanks @Aljullu for the reference!)_

The URL doesn't exist in DOM, the URL is changed by JS when users interact with the filter blocks. So we don't provide them to search engines. Do search engines still be able to index those URLs?

**Comment by Marc-pi** [comment]
@dinhtungdu / @Aljullu 

"WC has been applying filters through URL for a long time with filter widgets." 
yep, that's why SEO are looking for some dedicated plugins that manage this better. 

Level 1 - There dirty method is to add noindex on the page each time an attribute / filter is checked
Level 2 - The right method is indeed the canonical tag as explained in Google Dev Doc.
Level 3 - The expert method is to open facets when needed (to decide to index some long tail queries) but it harder to manager because we need for that to also personalize meta description & title tag, and add noindex to others. 

Please note also that we need to take care about the filter anchors. Please do not use a pure a:ref value but encapsulate it in a button with onclick event / location href value, for instance, so crawlers do not follow the url.

From my knowledge Filtereverything can manage the level 3, but there should exists for sure some other plugins
Step 3 could be left to dedicated plugins i think, or later PR. Please avoid also nofollow value.

see https://filtereverything.pro/resources/seo-rules/
and https://yithemes.com/themes/plugins/yith-woocommerce-ajax-product-filter

**Pull request merged**
