### PR TITLE
Make loading placeholder colors match the current font color

### LINKED ISSUE #7526: Loading placeholder colors of filter blocks and All Products block should depend on currentColor
## Describe the bug

When loading the filter blocks and the All Products block, a loading placeholder is shown. However, it looks a bit off because it doesn't honor the font color.

## To reproduce

1. Change the font color of your theme (via Appearance > Site Editor > Styles) to something that is not black or white (ie: yellow).
2. Add all filter blocks and the All Products block to a post or page.
2. Visit the page in the frontend.
3. Notice the loading placeholder look off because they don't honor the font color.

## Expected behavior

Ideally we should use `currentColor` to style these placeholders.

## Screenshots

imatge

### PR DESCRIPTION
**Pull request by thealexandrelara**
Currently, the loading placeholder effect has a default gray color. However, since users can modify their themes with the Site Editor and choose a different set of colors for their websites, it would be interesting to make those placeholders match the color palette.

*Changes*
The idea was to modify the `placeholder` mixin to replace the transparent font color with the current color and also modify the background-color and the linear-gradient to match the current font color. Furthermore, transparency was added to the middle color of the linear-gradient so we can keep the loading animation close to what it currently is.

Fixes #7526 

### Screenshots

| Before | After |
| ------ | ----- |
|   2022-11-10 loading placeholder color before   |    2022-11-10 loading placeholder color after   |

#### User Facing Testing

1. Change the font color of your theme (via Appearance > Site Editor > Styles) to something that is not black or white (ie: yellow);
2. Add all filter blocks (Filter by Price, Filter By Attribute, etc) and the All Products block to a post or page;
3. Visit the page that you added the blocks;
4. Make sure that the colors for the loading placeholder matches the current font color.

### Changelog

> Make loading placeholder colors match the current font color for the theme

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this, @thealexandrelara!

I have a couple of comments:

1. The filter titles don't seem to follow the current color. I think it's because of [this line](https://github.com/woocommerce/woocommerce-blocks/blob/e044fe6e65a82555b59dd685e1d52edac6e1dfbf/assets/js/base/components/filter-placeholder/style.scss#L12). I guess it can be removed? :thinking: 
imatge

2. I do think we should play around with the opacity. Otherwise, placeholders look very dark in light themes with a dark font. You can see how the placeholders looks in Storefront in `trunk` and this branch:

| `trunk` | This branch |
| --- | --- |
| imatge | imatge |

**Comment by thealexandrelara** [comment]
Thank you for your review and suggestions. About what you said:

> I have a couple of comments:
> 
> 1. The filter titles don't seem to follow the current color. I think it's because of [this line]

I did what you suggested and removed that line and the background-color as well, so now the title placeholder is following the placeholder mixin.

> 2. I do think we should play around with the opacity. Otherwise, placeholders look very dark in light themes with a dark font. You can see how the placeholders looks in Storefront in `trunk` and this branch:

I just changed the opacity to `0.3` (30%) so now the color is closer to the image you shared. I was trying to make it dynamically set the opacity depending on the `currentColor` lightness, but unfortunately this is not possible because [the `currentColor` is computed at runtime be the browser](https://github.com/sass/sass/issues/2907#issuecomment-696228428) and SASS does not have access to it.

**Review by Aljullu — APPROVED** [review]
Thanks for updating this PR and working on this, @thealexandrelara. It looks great!

Personally, I would reduce the placeholder opacity still a bit more, from 0.3 to something like 0.15. Otherwise in some themes the placeholders are still a bit too dark IMO (ie: Twenty Twenty Three with white background and black text).

But besides that, LGTM, so pre-approving.

**Comment by thealexandrelara** [comment]
> Thanks for updating this PR and working on this, @thealexandrelara. It looks great!
> 
> Personally, I would reduce the placeholder opacity still a bit more, from 0.3 to something like 0.15. Otherwise in some themes the placeholders are still a bit too dark IMO (ie: Twenty Twenty Three with white background and black text).
> 
> But besides that, LGTM, so pre-approving.

Awesome, thank you for your suggestion, I just changed the opacity from 0.3 to 0.15 :D

**Pull request merged**
