### PR TITLE
Fix correct branding color

### LINKED ISSUE #4878: Correct WooCommerce branding color
## Describe the bug

Some block icons are still using the old WooCommerce color code `#96588a` instead of the new one `#7f54b3`. This is in violation of the [WooCommerce Brand and Logo Guidelines](https://woocommerce.com/brand-and-logo-guidelines/).

## To reproduce

1. Create a test page.
2. Open the block inserter.
3. Scroll to the section WooCommerce.
4. See the icons using the wrong color.

## Expected behavior

The icons must use the correct color as defined in the [WooCommerce Brand and Logo Guidelines](https://woocommerce.com/brand-and-logo-guidelines/).

## Screenshots

Screenshot 2021-09-30 at 22 07 11

## Environment

* Core version: 5.8.1
* Gutenberg version (if installed): n/a
* WooCommerce version: 5.8.0-dev
* WooCommerce Blocks version: 6.1.0-dev

## Related issues

- https://github.com/woocommerce/woocommerce/issues/30829
- https://github.com/woocommerce/woocommerce/pull/30586

### PR DESCRIPTION
**Pull request by corgoss**
Fixes #4878  

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [x] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)
- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.

### Screenshots

<table>
<tr>
<td>Before:
<br><br>

#4878-before
</td>
<td>After:
<br><br>

#4878-after
</td>
</tr>
</table>

### Manual Testing

How to test the changes in this Pull Request:

1. Create a test page.
2. Toggle the block inserter.
3. Scroll down to the WooCommerce blocks.
4. See the old WooCommerce color.
5. Check out this PR.
6. Refresh the page.
7. See the new WooCommerce color.

### CODE REVIEW

**Review by nielslange — CHANGES_REQUESTED** [review]
Thanks for your contribution, @hafhaf10! 🙌 I just noticed that the color codes still use uppercase. Based on https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/#properties, the color codes should use lowercase. This is partially my fault, as I haven't mentioned this explicitly in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4878. Could you change the color codes from uppercase to lowercase so that the colors are in sync with the official WordPress CSS Coding Standards?

**Comment by corgoss** [comment]
> Thanks for your contribution, @hafhaf10! 🙌 I just noticed that the color codes still use uppercase. Based on https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/#properties, the color codes should use lowercase. This is partially my fault, as I haven't mentioned this explicitly in #4878. Could you change the color codes from uppercase to lowercase so that the colors are in sync with the official WordPress CSS Coding Standards?

Yes of course.

**Review by nielslange — CHANGES_REQUESTED** [review]
Almost perfect. We're getting there. 😀 I quickly checked the entire codebase for `#96588a` and found two more apperances:

- https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/569c1b149bd2167892073aaa8cb96b0684ee765e/assets/js/atomic/blocks/product-elements/shared/config.tsx#L22
- https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/569c1b149bd2167892073aaa8cb96b0684ee765e/assets/js/icons/library/woo.js#L17

It would be great if you could adjust these two sections as well. I'd say, we're then good to merge this PR. 😉

**Comment by corgoss** [comment]
> Almost perfect. We're getting there. 😀 I quickly checked the entire codebase for `#96588a` and found two more apperances:
> 
> * https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/569c1b149bd2167892073aaa8cb96b0684ee765e/assets/js/atomic/blocks/product-elements/shared/config.tsx#L22
> * https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/569c1b149bd2167892073aaa8cb96b0684ee765e/assets/js/icons/library/woo.js#L17
> 
> It would be great if you could adjust these two sections as well. I'd say, we're then good to merge this PR. 😉

Done 😀

**Review by nielslange — DISMISSED** [review]
~Thanks for your contribution, @hafhaf10. The changes look great and should be included in the next release.~

**Comment by nielslange** [comment]
@hafhaf10 I just see that your last commit contains the outdated file `/assets/js/atomic/blocks/product-elements/shared/config.js`. This file had been replaced with `/assets/js/atomic/blocks/product-elements/shared/config.tsx` last week. It's also the file in mentioned in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4911#pullrequestreview-775513314. Could you fetch the latest version of this plugin and integrate your change from `/assets/js/atomic/blocks/product-elements/shared/config.js` into `/assets/js/atomic/blocks/product-elements/shared/config.tsx`?

I tried merging you PR, but I'm unable of doing so as long as the merge conflict hasn't been resolved. As your changes are located in your fork, I'm unable to merge the changes there. This should be the last change, before being able to ship your change with the next release.

**Comment by corgoss** [comment]
> @hafhaf10 I just see that your last commit contains the outdated file `/assets/js/atomic/blocks/product-elements/shared/config.js`. This file had been replaced with `/assets/js/atomic/blocks/product-elements/shared/config.tsx` last week. It's also the file in mentioned in [#4911 (review)](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4911#pullrequestreview-775513314). Could you fetch the latest version of this plugin and integrate your change from `/assets/js/atomic/blocks/product-elements/shared/config.js` into `/assets/js/atomic/blocks/product-elements/shared/config.tsx`?
> 
> I tried merging you PR, but I'm unable of doing so as long as the merge conflict hasn't been resolved. As your changes are located in your fork, I'm unable to merge the changes there. This should be the last change, before being able to ship your change with the next release.

should be mergable now

**Review by nielslange — APPROVED** [review]
Looks great! Thanks a lot for your contribution, @hafhaf10!

**Pull request merged**
