### PR TITLE
Fix broken shipping Calculator

### LINKED ISSUE #3697: Investigate size increase in @woocommerce/blocks-checkout
While working on moving components to `@woocommerce/blocks-checkout` package, its size increased to 50kb, and there was a total of 9kb increased between all files, this didn't make sense because if anything, the total size should decrease because we removed duplicated components between cart and checkout.

This PR introduced the size change https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3671

We should investigate if this increase is legit and if there's anything we can do to reduce it.

### LINKED ISSUE #3758: Move ShippingRatesControl, TotalsShipping, and ShippingRa...
Move ShippingRatesControl, TotalsShipping, and ShippingRateSelector to our base components folder. they&#x27;re too coupled with our base implementation to be exported and we should only export Package.

---
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/80e5b6595316e93864420e66b2292aad2eadf4d2/packages/checkout/shipping/shipping-rates-control/shipping-rates-control.js#L28-L41
---
###### :rocket: This issue was generated by the [automations bot](https://github.com/woocommerce/automations) based on a `todo` comment in 80e5b6595316e93864420e66b2292aad2eadf4d2 when #3687 was merged. cc @mikejolley

### PR DESCRIPTION
**Pull request by nerrad**
Closes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3697
Closes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3758

In testing the 4.4.0 release (#3773 ), it was discovered the Shipping Calculator was broken. After some debugging I discovered that the Shipping context provider (and `useShippingAddress` hook) was being built into two different scopes. One for the checkout block built file, and one for the `wc-blocks-checkout` (aliased to `@woocommerce/blocks-checkout`) file. This meant that when the `ShippingCalculator` was pulled into the `wc-blocks-checkout` file, it was referencing a different context provider than what was wrapping the actual checkout block.

A quick solution for this was to implement the work outlined in #3758 which is what I did in this PR, but I'm not sure if this will have the side-effect of breaking the Subscriptions integration work. If yes, then we'll have to have a conversation about what approach we'll take for a fix for the 4.4.0 release and if we do this pull for a temp fix giving us some room to do a more robust refactor to address the issues (might need to pull out the contexts into their own built file shared by others).

There's definitely some relation here to what is outlined in #3723 as well.

## To Test

- [x] Verify that anything shipping related works as expected with the cart and the checkout block flows (make sure you test with built production file) and there are no errors in the console that impact user experience.

Might not be blocking if this fails so 4.4.0 can be shipped, but definitely needs addressed immediately after in that case.
- [x] Verify anything needed by Subscriptions integration is not affected.

**Note:** I have not done exhaustive tests other than verifying this appears to fix the shipping calculator issue in the cart. However, I did see this error in the console which suggests this might break the Subscriptions integration:

Image 2021-02-02 at 3 22 02 PM

### CODE REVIEW

**Comment by nerrad** [comment]
You can actually get a peek into the effects of the original bug by looking at the bundle size differences. `build/blocks-checkout` decreased by 33.2kb whereas the build/cart-frontend, build/cart, build/checkout-frontend, and build/checkout files only increased a total of 20.02kb. So the extra `~13kb` that was in `build/blocks-checkout` was all the duplicate context and dependencies pulled in from `base/context` and elsewhere.

**Comment by senadir** [comment]
This is breaking some of our integration, mainly the recurring totals section.

**Comment by senadir** [comment]
Subscription issues are fixed by 3985-gh-woocommerce/woocommerce-subscriptions and are non-blocking for this.

**Review by budzanowski — APPROVED** [review]
The code looks good.
Did some quick testing and found some issues with Subscriptions integration, but they should be fixed with 3985-gh-woocommerce/woocommerce-subscriptions, so thi does not impact this PR,

**Review by mikejolley — APPROVED** [review]

**Pull request merged**
