### PR TITLE
Local Pickup: merge country and state into same field in location modal

### LINKED ISSUE #8025: Local Pickup: in location modal, merge country and state into same field.
In Local pickup modal, we have country coming after state, and state being disabled because there's no default country.

WooCommerce core has a merged state + country field that we can rebuild using React.

### PR DESCRIPTION
**Pull request by tarhi-saad**
This PR merges the `Country` and `State` fields into the same field in the local pickup modal in `WooCommerce -> Settings -> Shipping -> Local pickup -> Pickup locations -> Add pickup location`

Some countries have missing states in WooCommerce. If they are selected, we display a `State` text field to add it manually.

Fixes #8025

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|     image   |    image   |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. `Enable local pickup` in `WooCommerce -> Settings -> Shipping -> Local pickup -> General`.
2. Under `Pickup locations`, click on `Add pickup location`. The `Pickup location` modal should open
3. Choose a country with a state. Ensure it's displayed in one field
4. Fill in the other fields of the modal form, click on `done`, then save changes
5. Go to your store, add a product to the cart, then go to the Checkout Block page
6. Under the `Shipping method` section, select `Local Pickup`
7. Ensure the correct country and state you previously selected are correctly showing under `Pickup options`
8. Go back to the local pickup settings from step 1. Follow the same steps from 2 to 7, but in step 3, choose a country without a state (e.g., Cameroon) and ensure that the `State` text field is displayed. Fill in the form and continue with the rest of the instructions.

image

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Local Pickup: merge country and state into same field in location modal

### CODE REVIEW

**Review by mikejolley — CHANGES_REQUESTED** [review]
Code looks pretty solid - I have some feedback however and some issues that need resolving.

1. If you're already using the pickup locations (in my case I had a location for United States), the new select does not pickup that value. In my case it defaulted to Afganistan.

2. When you select a country/state the summary text uses the codes:

Screenshot 2023-02-17 at 13 45 21

Do you think it's possible to show the full names?

3. When you select a country without states the text field appears below the country. Perhaps it might be better above/before the country select.

Thats all!

**Review by opr — COMMENTED** [review]
Same feedback as Mike. Code looks good but the country/state does not update on existing locations.

**Comment by tarhi-saad** [comment]
Thank you, @opr and @mikejolley, for the review! I made the following updates:

- [Show the state text field above the country select](https://github.com/woocommerce/woocommerce-blocks/pull/8408/commits/13ccdaf2ca3f30a585f94db8e1f9d4d8e9afb7c2)
- [Display a user-friendly country and state in admin](https://github.com/woocommerce/woocommerce-blocks/pull/8408/commits/df9d0afa8ca036ab0c9fd7bfd3982de107623156)
- And some refactoring

I couldn't reproduce the bug you both mentioned! I thought maybe it was a backward compatibility issue, but I added a local pickup address while on the trunk branch, then switched to this branch, and the `Country/state` select input did pick up the correct values. Are there any steps I can follow to reproduce this bug?

**Comment by mikejolley** [comment]
> I couldn't reproduce the bug you both mentioned! I thought maybe it was a backward compatibility issue, but I added a local pickup address while on the trunk branch, then switched to this branch, and the Country/state select input did pick up the correct values. Are there any steps I can follow to reproduce this bug?

Did you populate the pickup location with a country without a state you can select, one you must type? E.g. choose _United Kingdom_ and enter _Cambs_ as the state/country.

**Comment by tarhi-saad** [comment]
Hello, @mikejolley! 👋 As a follow-up to my last message via Slack: p1678344985194959/1678291671.432779-slack-C8X6Q7XQU, I implemented a fix for the following bug:

### Bug

1. In the Local pickup admin page, add a new address and select a country that has states (e.g., US). But do not select a state
2. Save your changes. Then checkout to this branch.
3. Click on "Edit" under the new address you've added previously. You'll notice that the country defaults to "Afghanistan"

### Fix

I mentioned here some potential fixes: p1678344985194959/1678291671.432779-slack-C8X6Q7XQU. I choose eventually to default to the same country (e.g. `US`) and the first of its states on the list (e.g., `US — Alabama`)! Please let me know what you think of this solution!

**Review by mikejolley — APPROVED** [review]
🚢

**Pull request merged**
