### PR TITLE
Product Button: Remove the hardcoded width and padding

### LINKED ISSUE #11436: 4-Column Product Row pattern: Button overflow
## Describe the bug

When testing TT4 and WP 6.4 I have discovered the **Add to Cart Button** blocks are overflowing on narrower screen-sizes:

4-Column_Product_Row_–_Eyed_Coyote

## To reproduce

1. Add the `4-Column Product Row` pattern to a post or a page.
2. Go to the front end and try re-sizing the viewport.
3. Note the button overflow.

## Additional context

I have noticed this issue is also happening for WP 6.3 and the Twenty Twenty-Three theme.

### PR DESCRIPTION
**Pull request by danieldudzic**
## What

This PR removes the hardcoded button width and padding (to inherit the padding from the theme styling).

Fixes #11436

## Why

Currently, the width of the buttons is hardcoded to `150px`. My assumption is that this was introduced to prevent the following effect of "jumping width" because of the spinner:
279669403-8c05f08c-6101-44f8-b715-7cbe171b7910

The hardcoded width is less than ideal as it leads to issues like #11436.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Add the `4-Column Product Row` pattern to a post or a page.
2. Go to the front end and try re-sizing the viewport.
3. Make sure the buttons are not overflowing.
4. Try adding products to the cart. Make sure there's no odd visual behavior.
5. Go to the `Shop` page and make sure the buttons look and behave correctly.
6. Try testing with regular, wide and full width.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|4-Column_Product_Row_–_newproductgallery|4-Column_Product_Row_–_newproductgallery|

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Button: Improve the width and padding.

### CODE REVIEW

**Comment by danieldudzic** [comment]
@jarekmorawski I'd appreciate your input regarding the proposed solution in this PR to the button width problem.

**Comment by jarekmorawski** [comment]
Looks good to me! Nice work, @danieldudzic. 👏

> The downside of this solution is that when there's not a lot of available width the buttons get quite high as their text wraps:

It's a good compromise and the difference is night and day when it comes to overall order and harmony.

**Review by Aljullu — COMMENTED** [review]
Confirming it solves the problem, I really like that we are trying to make this kind of visual improvements. :clap:  Code-wise the PR looks good to me. The only concern I have is that now it's quite easy for words to break into two lines (screenshots from TT3):



(See how the word _products_ in the second button is broken even though there is enough horizontal space for it)

After thinking about this, I think there are two approaches that we could investigate:

1. It looks like these buttons have `word-break: break-word`. I'm not sure why is that, but maybe it's safe to remove it? I did a quick test and IMO it looks better:



2. Given that with this PR we are adding margin to the `:before` and `:after`, I wonder if it would make sense to remove the default horizontal padding from the button. I mean, specifically setting it to 0 so the theme padding doesn't add on top of the `:before` and `:after` margins. Do you think that would work? (If we go that route, I'm not sure if it would be better to do it via global styles or directly in CSS)

Before | After
--- | ---
imatge | imatge

**Comment by danieldudzic** [comment]
@Aljullu thanks for testing!

1. Getting rid of the `word-break: break-word` will result in the following overflow issues: 
4-Column_Product_Row_–_newproductgallery

2. If we remove the padding, the spinner will not have sufficient padding and will look bad:

Shop_–_newproductgallery

**Comment by Aljullu** [comment]
Thanks for checking and good catch with those issues, @danieldudzic!

> 2. If we remove the padding, the spinner will not have sufficient padding and will look bad:

A quick fix could be to move the spinner a little bit to the left. I think that way it might look "aligned" without needing to have double horizontal padding.

---

However, the more I think about this, the more I think we shouldn't work-around the "jumping width" issue. The reason I'm mentioning that is because:

1. Adding margin to `:left` and `:right` might feel confusing for users. Ie, in the editor they might set a specific horizontal padding for the button but then, in the frontend there is this `:left` and `:right` margins which are added on top of that padding. I see how this can be confusing, specially as there is no way to remove it.
2. Having margin for `:left` and `:right` means we have less space for the button text, which is what causes words to break into two lines.

So my proposal would be to remove the hard-coded 150px width as you did, but not try to fix the "jumping width" issue (because of the issues mentioned above).

I know that's not ideal. So in the future, we could consider changing this spinner effect (which causes the "jumping width" issue) for something else: either simply disabling the button while "adding to cart" or doing something like the _Proceed to Checkout_ button of the Cart block, which allows keeping the button the same size:

[Enregistrament de pantalla des de 2023-11-03 10-39-32.webm](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/27d2d2a7-88d7-4ddd-9540-989a093c95d0)

Of course, that would need design input and it's out of the scope of this PR. But I feel that would be the more future-proof solution, as the current _Add to Cart_ spinner will always either cause the "jumping width" issue or need some extra padding which might be confusing with global styles. What do you think?

**Comment by danieldudzic** [comment]
@Aljullu 

> A quick fix could be to move the spinner a little bit to the left. I think that way it might look "aligned" without needing to have double horizontal padding.

This would also require some smart adjusting of padding/margins so that the width of the button doesn't jump. Potentially should be possible.

> So my proposal would be to remove the hard-coded 150px width as you did, but not try to fix the "jumping width" issue (because of the issues mentioned above).

I normally would agree with you, but here we have a situation where the button currently doesn't jump because of the static width. So that change will alter the existing behavior and the buttons will start jumping.

> So in the future, we could consider changing this spinner effect

Yes, I believe a design exploration into this would be useful. I like the spinner replacing the text altogether.

--------

I think the proposed margin solution in this PR could be an interim fix to the overflow issue. But I don't feel strongly one way or another :)

**Comment by mikejolley** [comment]
Moving to 11.6.0

**Comment by Aljullu** [comment]
@danieldudzic 

> I normally would agree with you, but here we have a situation where the button currently doesn't jump because of the static width. So that change will alter the existing behavior and the buttons will start jumping.

Yeah... I see what you mean, but at the same time, any CSS change that we make will alter the existing behavior. In `trunk`, the _Add to Cart_ button has a fixed width of 150px while in this PR it doesn't, so that's already an alteration of the existing behavior. In my opinion, it's definitely worth it, given that the hard-coded width has several issues, as you mentioned in #11436.

However, given that we need to alter the existing behavior no matter what, I think we should move towards the solution that we feel will be more future-proof and cause less issues with existing themes. I'm advocating for removing the hard-coded width while not adding margin to `:before` and `:after` for some reasons:

1. It doesn't add a horizontal padding that users can't remove. I think it's confusing for merchants to edit the horizontal padding of the button to find out that there are some invisible elements (`::before` and `::after`) which are adding padding without any way to control that. If a store wanted to show a "Learn more" button next to the "Add to Cart" button, there would be no easy way to make them have the same horizontal padding if the "Add to Cart" button has `::before` and `::after` margins while the "Learn more" button doesn't.
2. Not setting a margin to `::before` and `::after` elements allows us to change the animation of the _Add to cart_ interaction without breaking existing buttons in the future. In other words, if we add a margin to the `::before` and `::after` pseudoelements and, in the future, we want to move to an animation like the one from the _Proceed to Checkout_ buttons [I mentioned above](https://github.com/woocommerce/woocommerce-blocks/pull/11537#issuecomment-1792137118), what would we do with the `::before` and `::after` margins? Keeping them (even though they won't be needed anymore) or removing them (with the risk of breaking existing stores which might have set the button padding to 0)?
3. I also think that adding margin to the `::before` and `::after` pseudoelements might be dangerous. They have been there for a long time, and we can't know how different themes use them. For example, I think this PR breaks the buttons on Storefront because [SF hides the `::after` element](https://github.com/woocommerce/storefront/blob/bdc770d3abc954c2ce3a7731dfa4852fe09aebfc/assets/css/base/_base.scss#L914-L916): (might be worth verifying, I might have done something wrong)
imatge

Let me know what you think! Also, happy to jump in a sync-combo if you prefer. :slightly_smiling_face:  I acknowledge my proposal is not perfect, but I consider the _pros_ of not adding margins to `::before` and `::after` to outweigh the regression in the "jumping width" issue that would be introduced. We could also ask for some design direction if needed.

**Comment by danieldudzic** [comment]
@Aljullu All valid points. Thank you for championing a better Add to Cart button experience 🙏 I'm happy to follow your proposed direction on this. Even with the drawbacks, the "jumping-width" button solution seems to be a bit more robust.

**Review by Aljullu — APPROVED** [review]
I tested on TT1, TT2, TT3, TT4 and Storefront and it looks great on all of them! Thanks for the update, @danieldudzic! :ship:

**Pull request merged**
