### PR TITLE
Mini Cart Block: The color of the badge reflects the global style

### LINKED ISSUE #4965: Add global styles to all WC Blocks
We would like to add [global styles](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) to all WC Blocks.

Below, there is a list of which styles we would like each block to have enabled:

* [x] Featured Category/Featured Product: font size, text color, gradient and duotone (for the overlay), padding, border (color, width, radius). (@gigitux) #5542 #5555 
* [x] Product Categories List: font size, line height, text color, link color. (@gigitux #5133 )
* [ ] ~Product Search: text color, background color (including gradients), border (color and radius -- it should behave as the Search block from Gutenberg), width.~ (on hold, we might rewrite this block soon)
* [x] Active Filters: text color. (@gigitux #5465) 
* [x] Attribute Filter: text color, border (color and radius -- it should be applied to the fields). (@gigitux #5557)
* [x] Price filter: text color, border (color and radius -- it should be applied to the fields). (@gigitux #5559) 
* [x] ~Reviews (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4323): font size, text color.~
* [x] Mini Cart (button): text color (it should also change the icon color). (@gigitux  #5477) 

**Product element blocks**

* [x] Product title: font size, line height, font family, font weight, text transform, text color, background color (including gradients), margin (~#5009~) (@gigitux #5515 )
* [x] Add to cart button: text color, background color (including gradients), padding, border (color and radius) and width
* [x] Category List: font size, text color @gigitux #5516 
* [x] Image: font size, border (radius) @gigitux  #5562
* [x] ~Price: font size, text color~ (on hold: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4965#issuecomment-1005871877)
* [x] Rating: text color (it should change the color of stars) (@gigitux #5521)
* [x] Sale badge: font size, text color, background color (including gradients), padding, color, radius (@gigitux)  #5565
* [x] Stock indicator: font size, text color (@gigitux) #5525
* [x] Summary: font size, text color (@gigitux) #5524
* [x] Tag list: font size, text color, link color (@gigitux) #5528

Some of them are experimental, so you might need Gutenberg installed to get them working.
  
One challenge of this issue is that we might need to update the blocks to use [`apiVersion: 2`](https://make.wordpress.org/core/2020/11/18/block-api-version-2/).

### PR DESCRIPTION
**Pull request by gigitux**
With this PR, the color of the badge of Mini Cart Block will reflect the global style.

This PR also disables the ability to customize the background because it shouldn't be possible.

Fixes #4965 

### Screenshots

image
*before this PR* 

image
*with this PR*

### Manual Testing

How to test the changes in this PR:

Check out this branch:

1. Install and enable `Gutenberg` plugin.
2. Install and enable `TT1 Blocks` theme.
3. Add the `Mini Cart Block`.
4. Verify you can change ONLY the text color.
5. Save.
6. Go on the page and check if there are changes.
7. Reset to default.
8. Go to Dashboard and select Appearance > Editor (beta).
9. Click on the Global styles icon .
10. Verify the `Mini Cart Block` is shown and you can tweak its styles.
11. Save 
12. Go on the page created earlier and check if all styles are applied correctly.
10. Edit the previous post/page again.
11. Change again text color.
12. Save.
13. Check if these styles have priority over the styles from the Site editor.

### CODE REVIEW

**Review by sunyatasattva — APPROVED** [review]
LGTM!

**Comment by dinhtungdu** [comment]
@gigitux @Aljullu with this PR, the Mini Cart button doesn't work well for dark themes. The background setting was added to set the background color of the button as well as the badge. We used `__experimentalSelector` to make global style work with it, and it worked at the time the PR was merged, please see #5100 for more details.

image

**Comment by Aljullu** [comment]
> @gigitux @Aljullu with this PR, the Mini Cart button doesn't work well for dark themes.

Sorry I'm very late on this. :slightly_smiling_face:  I'm right assuming this was fixed in #5539 or is there anything that needs to be done? @gigitux @dinhtungdu

**Comment by gigitux** [comment]
> I'm right assuming this was fixed in #5539 

Yes, it is fixed in #5539

**Pull request merged**
