### PR TITLE
fix:  Markup is visible in checkout error notices 

### LINKED ISSUE #6628: Markup is visible in checkout error notices when the error is caused by a PHP syntax error.
When a server-side error occurs during checkout, the error shown contains unrendered HTML/Markup.

To reproduce:
1. Add items to the cart and go to the Checkout block.
2. Open https://github.com/woocommerce/woocommerce-blocks/blob/029b379138906872dec3ed920fcb23d24404a3f2/src/StoreApi/Schemas/V1/CheckoutSchema.php#L26-L25 in your editor, introduce a syntax error.
3. Try to check out.
4. See the error with unrendered HTML.
image

### PR DESCRIPTION
**Pull request by wavvves**
This PR fixes the displaying of unrendered HTML within our checkout notices.

Fixes #6628

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

Before:

image

After:

image

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add items to the cart and go to the Checkout block.
2. Open https://github.com/woocommerce/woocommerce-blocks/blob/029b379138906872dec3ed920fcb23d24404a3f2/src/StoreApi/Schemas/V1/CheckoutSchema.php#L26-L25 in your editor, introduce a syntax error.
3. Try to check out.
4. See the notice with rendered HTML. Special note to the link displaying properly.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Enabled HTML rendering within notices for checkout.

### CODE REVIEW

**Comment by wavvves** [comment]
Hi @opr, do you mind giving me a hand here? I had a [look online](https://github.com/WordPress/gutenberg/issues/6292) about using [@wordpress/element](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-element/) to properly render HTML inside notices, but I'm still seeing `[object Object]`. Am I missing any step?

**Comment by opr** [comment]
> Hi @opr, do you mind giving me a hand here? I had a [look online](https://github.com/WordPress/gutenberg/issues/6292) about using [@wordpress/element](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-element/) to properly render HTML inside notices, but I'm still seeing `[object Object]`. Am I missing any step?

What exactly are you doing to get this? Can you share some code? What is inside the object?

**Comment by wavvves** [comment]
> What exactly are you doing to get this? Can you share some code? What is inside the object?
[
This is the change](https://github.com/woocommerce/woocommerce-blocks/pull/6800/commits/d058f20787fd06ceefff44cb17f58c5407595320) I did, and I was taking [this](https://github.com/WordPress/gutenberg/issues/6292#issuecomment-382851504) as a clue for fixing this. 

This is what the object contains (print because copying the object is just too plain):

image

**Comment by wavvves** [comment]
I don't know if something changed in the meantime, but those links I referred might be outdated. Looking at `createErrorNotice()` definition we see it's just a wrapper for `createNotice()`. Also by method signature, `string` is the only param type truly acceptable. Not sure how we can go further with this without changing external stuff 🤔

```
/**
 * Returns an action object used in signalling that an error notice is to be
 * created. Refer to `createNotice` for options documentation.
 *
 * @see createNotice
 *
 * @param {string} content   Notice message.
 * @param {Object} [options] Optional notice options.
 *
 * @return {Object} Action object.
 */
export function createErrorNotice( content, options ) {
	return createNotice( 'error', content, options );
}
```

**Comment by opr** [comment]
`createNotice` is an action on the `core/notices` data store. Maybe we could check how the `StoreNoticesContainer` component reads and displays those notices. We might be able to render HTML by changing something there?

**Comment by wavvves** [comment]
> `createNotice` is an action on the `core/notices` data store. Maybe we could check how the `StoreNoticesContainer` component reads and displays those notices. We might be able to render HTML by changing something there?

Without changing `Notice`? Plus it reuses it for `spokenMessage` attr 🤔

These are the props being passed for `Notice`. And it explicitly uses `createElement(Text, ..., content)`
```
{
    "id": "checkout",
    "status": "error",
    "content": "<p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/support/article/faq-troubleshooting/\">Learn more about troubleshooting WordPress.</a></p>",
    "spokenMessage": "<p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/support/article/faq-troubleshooting/\">Learn more about troubleshooting WordPress.</a></p>",
    "isDismissible": true,
    "actions": [],
    "type": "default",
    "icon": null,
    "explicitDismiss": false
}
```

**Comment by wavvves** [comment]
@opr have a look now, please. As I was about to reach Gutenberg for help I noticed the undocumented ` __unstableHTML` option, and setting that to `true` did what we wanted. You can have a look at the source for `createNotice()` [here](https://github.com/WordPress/gutenberg/blob/77b940d669217fc917d246df44dd087cf6345b08/packages/notices/src/store/actions.js) (the other methods are wrappers for that). 🤞🏼

**Review by opr — COMMENTED** [review]
Thanks @wavvves it's working for me now, the link works.

I see the second paragraph in this notice has some `bottom-margin` which makes the notice look weird. I'm not sure how we can solve that for every use case, we can remove the margin on the last `p` element, but what if another notice has a different element with margin on.

Moreover, I'm not really confident we should be using `__unstableHTML` solve this. That API is unstable and could change without notice, do you feel OK with using it?

**Comment by wavvves** [comment]
> I see the second paragraph in this notice has some `bottom-margin` which makes the notice look weird. I'm not sure how we can solve that for every use case, we can remove the margin on the last `p` element, but what if another notice has a different element with margin on.

Since the notices wrapper has padding set, I would say we should remove margin-top for the `*:first-child`, and margin-bottom on the `*:last-child` (notice the wrapping div container).  When the content is plain text this won't have any effect. Even if it did it would probably be ok, we only need to ensure we won't mess with the action button.

image

What do you think?

> Moreover, I'm not really confident we should be using `__unstableHTML` to solve this. That API is unstable and could change without notice, do you feel OK with using it?

It's not using it that bothers me, but the fact that it exists 😅.
Since we are using a fixed version for it (`"@wordpress/notices": "3.12.0"`) and this is for 4xx/5xx where errors are predictable we should be relatively safe using this.
If someone could modify the server response to hijack a checkout page, then not using this won't prevent that.

**Comment by opr** [comment]
> Since the notices wrapper has padding set, I would say we should remove margin-top for the `*:first-child`, and margin-bottom on the `*:last-child` (notice the wrapping div container). When the content is plain text this won't have any effect. Even if it did it would probably be ok, we only need to ensure we won't mess with the action button.

Yes, I think this is fine! Please would you implement it?

> Since we are using a fixed version for it ("@wordpress/notices": "3.12.0") and this is for 4xx/5xx where errors are predictable we should be relatively safe using this.

OK, thank you, I think your solution is fine then 😄

**Review by alexflorisca — APPROVED** [review]
Looks good, nice one @wavvves , 🚢  it

**Comment by wavvves** [comment]
> Looks good, nice one @wavvves , 🚢 it

Thanks @alexflorisca 😎
I think there's still a failing test caused by this (maybe just needs to be updated)

**Review by tarunvijwani — APPROVED** [review]
> Thanks @alexflorisca 😎 I think there's still a failing test caused by this (maybe just needs to be updated)

May I know which test is failing for you? It is working for me. 

image

**Comment by alexflorisca** [comment]
> I think there's still a failing test caused by this (maybe just needs to be updated)

The unit tests all pass in CI so I think we're good there. The e2e tests I assume are down to flakiness but that might be a bad habit I got into!

**Comment by wavvves** [comment]
> May I know which test is failing for you? It is working for me.

@tarunvijwani @alexflorisca  It's [this one](https://github.com/woocommerce/woocommerce-blocks/actions/runs/3086515886/jobs/4990937681) that seems related to this. The Gutenberg ones are the flaky stuff, and there seems to be another (expecting **/checkout** and got **/checkout-block**) that I would put down my money got introduced because it slipped under the radar due to the flaky ones, right?

**Comment by wavvves** [comment]
> > May I know which test is failing for you? It is working for me.
> 
> ~~@tarunvijwani @alexflorisca It's [this one](https://github.com/woocommerce/woocommerce-blocks/actions/runs/3086515886/jobs/4990937681) that seems related to this.~~ The Gutenberg ones are the flaky stuff, and there seems to be another (expecting **/checkout** and got **/checkout-block**) that I would put down my money got introduced because it slipped under the radar due to the flaky ones, right?

Forget about that, I thought it was a notice, so unrelated. Still, the non-Gutenberg failing tests seem fixable. (that one expecting "Your cart is empty!" whereas the text seems to be "Your cart is currently empty!". I'll try a quick fix for that on this branch.)

PS- It seems to have fixed that particular test. I think I'm merging this now and will leave any additional E2E investigation to the proper issue. I merging this :)

**Comment by sunyatasattva** [comment]
Excluding from testing notes as discussed here: p1664204890072169-slack-C02UBB1EPEF

**Pull request merged**
