### PR TITLE
Add permission_callback filter for the Store API

### LINKED ISSUE #7409: Disable Checkout Route if Guest Checkout is disabled
An attempt to change the permission_callback for a route (e.g. Checkout GET) was not successful. Overriding the regiser_rest_route() method with the override flag does not give the desired result - some properties for the third argument obtained from the Checkout object are not public.
Extending and redefining classes in order to extend the Checkout class is also not possible (that is, it is possible, but quite a lot of classes that use StoreApi will have to be rewritten) - without this, it is impossible to easily extend the RoutesController class - action in StoreApi:: init() uses an anonymous function callback that is passed directly.

In Woocommerce, I extended a couple of classes without any problems: with the remove_action('init', (\WooCommerce::instance(), 'load_rest_api')) function and then adding a new action with the extended Automattic\WooCommerce\RestApi\Server class, in which I overridden the method for controllers by adding new extended ones.

I did not have time to thoroughly study all the classes and the hierarchy, but I would like to be able to allow - in my case it is necessary that only registered users have the ability to make a /checkot request.
Thanks in advance!

### PR DESCRIPTION
**Pull request by mikejolley**
This PR makes it possible to disable API endpoints using a permission filter. For example:

```
add_filter(
     'woocommerce_store_api_permission_callback',
          function( $permission, $namespace, $path ) {
               if ( $path === '/checkout' ) {
                    return false;
               }
               return $permission;
          },
          10,
          3
);
```

The hook gets context of the request path and API namespace, and you simply return a boolean. It defaults to `true` (all endpoints are public).

Due to the nature of the filter, this would be use at your own risk, because you would be preventing access to checkout or other important endpoints. But its there if needed.

Fixes #7409

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Implement the above example code somewhere, for example the main plugin file.
2. Make a request to the checkout endpoint.
3. You should be locked out with a permission error.
4. Other endpoints should continue to function e.g. cart

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Introduce `woocommerce_store_api_permission_callback` filter for the store API.

### CODE REVIEW

**Comment by senadir** [comment]
This feels like a very down level API to disable something as important as Checkout, I don't see a way for a third consumer to detect and see if Checkout is disabled here, a "security" plugin can disable Checkout endpoint and now Checkout block or WooPay are unaware that you can't post to Checkout until you actually attempt to.

**Comment by mikejolley** [comment]
@senadir yup thats true. There are already plugins doing this as we've had some support requests from people disabling REST and wondering why checkout is broken. 

Whats the alternative? This is the only way to remove or change specific endpoint permissions—everything else is locked down.

**Review by opr — APPROVED** [review]
From a code and functionality point of view this is working well, I just see the generic Checkout Error with the crossed out shopping cart.

image

I am not sure if there's a better solution for this, if this is the only way of changing endpoint permissions.

Could we somehow advertise which endpoints are available, either by having a generic "info" endpoint, or adding metadata onto existing requests? Neither of these seem that good of an idea either though.

**Comment by mikejolley** [comment]
There is an index endpoint but I'm not sure if it factors in permissions. It may already do so. Ill mark this blocked until I check. If anyone else has an alternative solution or reason to reject the request from the developer who requested it, please chime in. @woocommerce/rubik

**Comment by opr** [comment]
Removing 10.0.0 milestone and ready to merge label. Not including this in 10.0.0 release!

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-blocks/issues/7409#issuecomment-1541852975

**Pull request closed without merging**
