### PR TITLE
Prevent Express Checkout block from being cut off

### LINKED ISSUE #6885: Checkout Block cutting off its content
## To reproduce

- Create a new page
- Insert the checkout block

Notice the limits of the checkout block will cut off its content. 

## Expected behavior

No content should be outside of the checkout block limits.

### WordPress:

-   Core version: 6.0.1
-   WooCommerce version: 6.7.0
-   WooCommerce Blocks version: 8.2.1
-   Site language: english

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: MacOS
-   Version: Version 104.0.5112.79 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #6885 

### Notes

When activating Express Checkout as a payment option, the Express Checkout block is cut off when selecting the Checkout block in the editor. This PR aims to solve this problem.

### Screenshots

<table>
<tr>
<td valign="top">Before:
<br><br>

Screenshot 2022-09-14 at 14 17 38

</td>
<td valign="top">After:
<br><br>

Screenshot 2022-09-14 at 14 13 35
</td>
</tr>
</table>

#### User Facing Testing

1. Install the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) plugin.
2. Go to `/wp-admin/admin.php?page=wc-settings&tab=checkout` and activate the payment method `Stripe` so that the Express Payment block becomes visible.
3. Create a page and add the Checkout block to it.
4. Select the Checkout block and verify that the Express Payment block is no longer cut off.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Ensure that the Express Payment block is not cut off when selecting the Checkout block in the editor.

### CODE REVIEW

**Review by tarunvijwani — CHANGES_REQUESTED** [review]
Thank you for working on this, @nielslange! It works great! 👍 
I see we have some overlapping/cutting on the step number as well. I think we can fix both of these by adding some padding under `.block-editor-block-list__layout` in `assets/js/blocks/checkout/styles/editor.scss` file:

image

| Before | After |
|---|---|
|image|image|

**Comment by nielslange** [comment]
> I see we have some overlapping/cutting on the step number as well. I think we can fix both of these by adding some padding under `.block-editor-block-list__layout` in `assets/js/blocks/checkout/styles/editor.scss` file:

Thanks for your review, @tarunvijwani, and suggesting the change. I just applied it, but went with `padding-left: 5px;` instead of with `padding: 5px;`. Below, you can find screenshots that show the Express Checkout block and the step numbers before this PR and how they both look now:

<table>
<tr>
<td>Before:
<br><br>

Screenshot 2022-09-19 at 18 16 14
</td>
<td>After:
<br><br>

Screenshot 2022-09-19 at 18 15 46
</td>
</tr>
</table>

**Review by tarunvijwani — APPROVED** [review]
Thank you, @nielslange! The reason why I wanted to add padding everywhere as it will fix it from all sides. It is looking good now. However, on the other sides, we still have some overlapping screenshots:

image

image

It is not visible though, it won't impact any user experience, and we have this on the Cart block as well. Approving the changes, let's 🚢  it. 👍

**Comment by nielslange** [comment]
> The reason why I wanted to add padding everywhere as it will fix it from all the sides. It is looking good now. However, at the other sides, we still have some overlapping, screenshots:

I would not call these overlaps, @tarunvijwani. By default, Gutenberg shows the border in synch with the edges of a block:

<table>
<tr>
<td>

Screenshot 2022-09-20 at 17 35 16
</td>
<td>

Screenshot 2022-09-20 at 17 35 44
</td>
</tr>
</table>

In comparison, the Express Payments block and the Step Numbers both overlapped, meaning they were crossing the border of the block. That said, thanks for reviewing this PR and for explaining what you had in mind by "overlapping" elements.

**Comment by tarunvijwani** [comment]
Gotcha! Thank you, @nielslange, for sharing the details! 🙂

**Pull request merged**
