### PR TITLE
Remove Featured Category Cover Image pattern

### PR DESCRIPTION
**Pull request by Aljullu**
As discussed in https://github.com/woocommerce/woocommerce-blocks/pull/10239, instead of updating the pattern, we are going to remove it. So this PR takes care of it. :slightly_smiling_face: 

@albarin @roykho do you think we should look into merging this PR right away or better wait until https://github.com/woocommerce/woocommerce/issues/42316 is merged?

#### User Facing Testing

1. In the post editor or the site editor, open the inserter and search for the Featured Category Cover Image pattern.
2. Verify it doesn't exist.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Remove Featured Category Cover Image pattern in favor of the Feature Category block.

### CODE REVIEW

**Comment by albarin** [comment]
@Aljullu @roykho 
Do we really need https://github.com/woocommerce/woocommerce/issues/42316 if we are removing the pattern?
That issue was to be able to achieve the design with the text in the top left.

**Comment by Aljullu** [comment]
> Do we really need https://github.com/woocommerce/woocommerce/issues/42316 if we are removing the pattern?

I'm not sure. I still think it's a nice addition to the Featured Product/Category blocks, but it doesn't block the pattern projects anymore.

**Review by roykho — CHANGES_REQUESTED** [review]
We should probably delete the pattern image as well to save filesize.

**Comment by Aljullu** [comment]
> We should probably delete the pattern image as well to save filesize.

Oh, right. Good point. Done in 85861ca60a49d90a809699352801d193f32ba110.

**Review by roykho — APPROVED** [review]
LGTM!

**Pull request merged**
