### PR TITLE
Optimise Check Markdown links GitHub Action

### LINKED ISSUE #9626: Optimise `Check Markdown links` GitHub Action
In #9625, I mentioned the following:

> While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files. In addition, I noticed that the GitHub Action, to check for broken links in Markdown files, runs independent if the PR touches Markdown files or not.

This issue aims to apply the following changes to the `Check Markdown links` GitHub Action:

- Remove `max-depth: 3`to detect broken links in all Markdown files
- Remove `use-verbose-mode: ‘no’`, as `no` is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)
- Exclude Markdown files in `./docs/internal-developers/testing/releases/`

### PR DESCRIPTION
**Pull request by hritikchaudhary**
Fixes #9626 

### Changes in the PR:
- Removed max-depth: 3to detect broken links in all Markdown files
- Removed use-verbose-mode: ‘no’, as no is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by tarunvijwani — COMMENTED** [review]
Thank you for working on it!

>Changes in the PR:
Removed max-depth: 3to detect broken links in all Markdown files
Removed use-verbose-mode: ‘no’, as no is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)
Excluded Markdown files in ./docs/internal-developers/testing/releases/


I could see the changes for  `use-verbose-mode` and `max-depth`. However, I couldn't find the changes for `Excluded Markdown files in ./docs/internal-developers/testing/releases/`. 
Please correct me if I am mistaken.

**Comment by hritikchaudhary** [comment]
>

**Comment by hritikchaudhary** [comment]
> Thank you for working on it!
> 
> > Changes in the PR:
> > Removed max-depth: 3to detect broken links in all Markdown files
> > Removed use-verbose-mode: ‘no’, as no is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)
> > Excluded Markdown files in ./docs/internal-developers/testing/releases/
> 
> I could see the changes for `use-verbose-mode` and `max-depth`. However, I couldn't find the changes for `Excluded Markdown files in ./docs/internal-developers/testing/releases/`. Please correct me if I am mistaken.

Hi @tarunvijwani, I don't think we'll be able to exclude ./docs/internal-developers/testing/releases/ md files as excluding files feature is still seems to be in development https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/38
We'll have to check if a workaround is available

**Comment by tarunvijwani** [comment]
@hritikchaudhary Just wondering if it's possible to use an `exclude` or `ignorePatterns` property in the check-doc-links-config.json file? By using this property, can we specify the exclusions?

```

{
  "exclude": [
    "./docs/internal-developers/testing/releases/**/*"
  ]
}


```

or 

```

"ignorePatterns": [
		{
			"pattern": "^./docs/internal-developers/testing/releases/"
		}
	]

```

Love to hear your thoughts about it. 

Also, it would be great if you could try adding the testing steps to this PR. It could involve forking the repo and unforking the repo. You can find similar instructions here: https://github.com/woocommerce/automations/pull/52

**Comment by hritikchaudhary** [comment]
Hi @tarunvijwani Apologies for late reply..
I went through the documentation of https://github.com/gaurav-nelson/github-action-markdown-link-check and https://github.com/tcort/markdown-link-check#config-file-format 
it says: `ignorePatterns: An array of objects holding regular expressions which a link is checked against and skipped for checking in case of a match.` 
So it is to the the link against that pattern and not which file to scan.. and there is no such property as `exclude` that is supported by config.json file following are the supported properties:
image

**Review by tarunvijwani — COMMENTED** [review]
I have created a separate [ticket](https://github.com/woocommerce/woocommerce-blocks/issues/10161) to tackle `Exclude Markdown files in ./docs/internal-developers/testing/releases/` issue. 

The changes look good to me. However, I see linters are failing for this PR. Not sure why? I tried re-running the checks but it didn't help.  

Adding @nielslange as an additional reviewer to confirm.

**Review by nielslange — CHANGES_REQUESTED** [review]
> Adding @nielslange as an additional reviewer to confirm.

Thanks for your ping, @tarunvijwani.

---

Thanks for working on this, @hritikchaudhary. I created the interim PR #10180 to run the CI pipeline for this PR. Due to the changes, I noticed that the running time for checking the links in *.md files went from 2 min up to 15 min. During a pairing session with @tarhi-saad we came up with the following potential solutions:

- Looking for a library apart from [`gaurav-nelson/github-action-markdown-link-check`](https://github.com/gaurav-nelson/github-action-markdown-link-check).
- Move the `release` folder to the root directory of the repo.
- Use `matrix` to specify which folders to test.
- Fork [`gaurav-nelson/github-action-markdown-link-check`](https://github.com/gaurav-nelson/github-action-markdown-link-check) to implement the exclude option.

Each option has its benefits and drawbacks. Given that [`gaurav-nelson/github-action-markdown-link-check`](https://github.com/gaurav-nelson/github-action-markdown-link-check) is using [`tcort/markdown-link-check`](https://github.com/tcort/markdown-link-check) under the hood, we were looking closer into this option and came up with the following terminal command:
```sh
find ./docs -path ./docs/internal-developers/testing/releases -prune -o -name "*.md" -print0 | xargs -0 -n1 markdown-link-check
```
This command recursively checks the links in all *.md files that are located inside the `./docs` folder, except the folder `./docs/internal-developers/testing/releases`. Running this command locally took approx. 2 min to check all links, while ignoring the files within the `release` folder.

Could you adjust the PR accordingly to utilise [`tcort/markdown-link-check`](https://github.com/tcort/markdown-link-check) instead of [`gaurav-nelson/github-action-markdown-link-check`](https://github.com/gaurav-nelson/github-action-markdown-link-check)?

**Comment by hritikchaudhary** [comment]
Sure, I'll look into it

**Comment by nielslange** [comment]
> Sure, I'll look into it

Thanks a lot, @hritikchaudhary.

**Comment by hritikchaudhary** [comment]
Hi @nielslange Apologies for delay... was busy with some work past weeks couldn't contribute..
I was looking into it and I can see that [`tcort/markdown-link-check`](https://github.com/tcort/markdown-link-check) is not a github action and to run the the terminal command:
> find ./docs -path ./docs/internal-developers/testing/releases -prune -o -name "*.md" -print0 | xargs -0 -n1 markdown-link-check

don't we have to install the `tcort/markdown-link-check` in the `woocommerce-block` repo?


PS: I also like the following option:
>Fork [gaurav-nelson/github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check) to implement the exclude option.

**Comment by nielslange** [comment]
> Hi @nielslange Apologies for delay... was busy with some work past weeks couldn't contribute.. I was looking into it and I can see that [`tcort/markdown-link-check`](https://github.com/tcort/markdown-link-check) is not a github action and to run the the terminal command:
> 
> > find ./docs -path ./docs/internal-developers/testing/releases -prune -o -name "*.md" -print0 | xargs -0 -n1 markdown-link-check
> 
> don't we have to install the `tcort/markdown-link-check` in the `woocommerce-block` repo?

Thanks for reaching out, @hritikchaudhary. To run the terminal command, the npm package `tcort/markdown-link-check` indeed needs to be installed. 

> PS: I also like the following option:
> 
> > Fork [gaurav-nelson/github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check) to implement the exclude option.

The problem with forking `gaurav-nelson/github-action-markdown-link-check` is that we potentially have to maintain it. Given that `gaurav-nelson/github-action-markdown-link-check` is using `tcort/markdown-link-check` under the hood, we decided to use the second library directly.

Thanks again for reaching out and double-checking this. We appreciate this very much. 🙏

**Comment by hritikchaudhary** [comment]
Ok, Thanks for the clarification!

**Comment by hritikchaudhary** [comment]
I updated the workflow to use [`tcort/markdown-link-check`](https://github.com/tcort/markdown-link-check) and run 
```
find ./docs -path ./docs/internal-developers/testing/releases -prune -o -name "*.md" -print0 | xargs -0 -n1 markdown-link-check -c .github/workflows/check-doc-links-config.json
```
and updated above command to use existing config.json file `-c .github/workflows/check-doc-links-config.json`.
Currently the job will fail as there are 14 dead links. I've tested it after removing the deadlinks and the job succeeded.
Attaching log archives of the workflow run.
[logs_246803_before removing dead links.zip](https://github.com/woocommerce/woocommerce-blocks/files/12242972/logs_246803_before.removing.dead.links.zip)
[logs_246835 after removing dead links.zip](https://github.com/woocommerce/woocommerce-blocks/files/12242974/logs_246835.after.removing.dead.links.zip). The time taken by the job was also around 2 mins.

To get a successful run we need to fix the following links in #9627: 

1. FILE: [./docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md) - [✖] #experimental-plugin-flag
2. FILE: [./docs/internal-developers/block-client-apis/checkout/checkout-api.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-api.md) - [✖] ../../extensibility/checkout-flow-and-events.md
3. FILE: [./docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md) -   [✖] #onCheckoutValidation
4.  FILE: [./docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md) - [✖] https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/block-client-apis/checkout/checkout-api.md
5. FILE: [./docs/internal-developers/testing/cart-checkout/data-stores.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/cart-checkout/data-stores.md) - [✖] https://github.com/woocommerce/woocommerce-bookings
6. FILE: [./docs/third-party-developers/extensibility/data-store/payment.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/payment.md) - [✖] #getcurrentstatus
7. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #-woocommerce_add_to_cart_validation 
8. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #-woocommerce_shared_settings
9. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #woocommerce_shipping_-this--id-_is_available
10. FILE: [./docs/third-party-developers/extensibility/hooks/filters.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/filters.md) - [✖] #woocommerce_store_api_product_quantity_-value_type
11. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #woocommerce_blocks_-this--registry_identifier-_registration 
12. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #-woocommerce_check_cart_items
13. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #woocommerce_-product--get_type-_add_to_cart
14. FILE: [./docs/third-party-developers/extensibility/hooks/actions.md](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/hooks/actions.md) - [✖] #-hook

**Review by nielslange — CHANGES_REQUESTED** [review]
> To get a successful run we need to fix the following links in https://github.com/woocommerce/woocommerce-blocks/issues/9627

Thanks for working on this, @hritikchaudhary. To prevent that our tests start failing once we merge this PR, could you create a PR for #9627 based on this PR? That way, we can ensure that this PR will not lead to failing tests.

**Comment by hritikchaudhary** [comment]
Sure @nielslange, Can you please assign #9627 to me.

**Comment by nielslange** [comment]
> Can you please assign https://github.com/woocommerce/woocommerce-blocks/issues/9627 to me.

Absolutely. I just assigned the issue to you, @hritikchaudhary.

**Review by nielslange — COMMENTED** [review]
Hello @hritikchaudhary, I just reviewed https://github.com/woocommerce/woocommerce-blocks/pull/10537 and added some comments there.

**Pull request closed without merging**
