### PR TITLE
Update placeholder styles

### LINKED ISSUE #2408: Fix padding, alignment, and various UI inconsistencies in the block editor interfaces
There are various padding and alignment issues in block editor UI - these bugs are in the preview state of the blocks, as well as in the sidebar controls

Preview state:

Screen Shot 2020-05-05 at 1 52 01 PM

Sidebar:

Screen Shot 2020-05-05 at 1 54 01 PM

Additionally some preview states have a grey background, while others have a white background:

Screen Shot 2020-05-04 at 9 46 47 PM

Screen Shot 2020-05-04 at 9 44 56 PM

Gutenberg version: 8.0.0
WordPress Version: 5.4.1
WooCommerce Version: 4.1.0-rc.2

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #2408.

### Screenshots
_Before:_
imatge

_After:_
imatge

_(notice chip styles are broken, that's being tracked in: #2407)_

### How to test the changes in this Pull Request:

1. Activate the latest version of Gutenberg.
2. Add a _Products by Category_ and a _Featured Product_ block in a post.
3. Verify the placeholder background is white, buttons are aligned, there is a border around the list, etc.
3. Deactivate Gutenberg and verify styles still look good and nothing is broken.

### Changelog

> Updated the placeholder styles to match the core block styles.

### CODE REVIEW

**Comment by Aljullu** [comment]
> I'm running Gutenberg 7.9, the styles are not aligned in the middle

I'm unable to reproduce it with Gutenberg 8.0 neither `master`. :confused: Could you try if you can reproduce it with the latest version of Gutenberg from .org or `master`?

> the hover/focus background contrast is low (the background color changed, so I guess that was the reason).
> The focus border is still shifted as well.

Yeah, I noticed that as well and was planning to take a deeper look later. This seems to be an issue between WC Admin's `<SearchListControl />` and the last versions of `@wordpress/components`, so we should probably fill an issue in wc-admin's repo and work on it there.

**Comment by senadir** [comment]
I should have noted that I only tested in Chrome, after updating the issue was still there, I tested in Firefox and it seems to work fine.

**Comment by Aljullu** [comment]
> I should have noted that I only tested in Chrome, after updating the issue was still there, I tested in Firefox and it seems to work fine, so only chrome for now is buggy.

Ah, good catch, I should have tested Chrome as well. This also seems to be an issue with `SearchListControl` styles.

I opened an issue in WC Admin so we can track it: https://github.com/woocommerce/woocommerce-admin/issues/4349, but given that those changes will need to be done in the other repo, I think they shouldn't block this PR.

**Comment by nerrad** [comment]
@senadir in light of Albert's most recent comment, are you in agreement this pull is ready for merge?

**Comment by Aljullu** [comment]
> .woocommerce-search-list__list .woocommerce-search-list__item needs a height: auto. This prevents the button being too small which is why the text is off center.

Thanks for the tip! I really feel the fix belongs to WC Admin. That's why I created https://github.com/woocommerce/woocommerce-admin/issues/4349, but updating `@wordpress/components` there is a bit tricky (needs changes in several components), so it might make sense adding a work-around on our end for now. Done in ec48c1ca65519a468de26d8dca634d1cc8ae05e1.

**Pull request merged**
