### PR TITLE
Product Image Gallery: fix 404 error

### LINKED ISSUE #8436: Product Image Gallery 404 error
## Describe the bug

During the review of #8225, @nefeline noticed a 404 error about the Product Image Gallery.

## To reproduce

1. Go to Site Editor
2. Check the network and see that a 404 error about Product Image Gallery block is visible.

## Expected behavior

No 404 error.

## Screenshots

image

### PR DESCRIPTION
**Pull request by gigitux**
This PR fixes the 404 error. Since it is a server-side block, it isn't necessary to enqueue any asset.

Fixes #8436 

#### User Facing Testing

1. Go to Site Editor.
2. Check the network and see that any 404 error is visible.
3. Open the Single Product template.
4. Add the Product Image Gallery.
5. Be sure that it is visible on the front end.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by albarin — APPROVED** [review]
👌

**Comment by nerrad** [comment]
This looks like something that will repeat again. It's not intuitive to have to override the `register_block_type_assets` method for server-side-only registration of blocks. I wonder if this is something that should be inferred from a property of the blocktype class?

**Comment by gigitux** [comment]
> This looks like something that will repeat again. It's not intuitive to have to override the register_block_type_assets method for server-side-only registration of blocks. I wonder if this is something that should be inferred from a property of the blocktype class?

What do you think if I create an issue about this?

**Comment by nerrad** [comment]
Yea, let's at least get it documented. I don't think it's urgent, I'm just wary of this popping up again.

**Pull request merged**
