### PR TITLE
[Store Customization] Update the Centered Header Menu with Search Pattern

### LINKED ISSUE #11253: Store Customization > Update the Centered Header Menu with Search Pattern
We have received the following feedback from @verofasulo regarding the **Centered Header Menu with Search** Pattern ( reference: Mrk6SERPZ4KrFHSjM0a8TK-fi-6347_54034 ):

> This header needs to be polished—some minor tweaks:
>
> - “Search your store” is not centered. And it would be lovely to increase the spacing on the left, it’s very compressed against the edge.
> - The cart icon and the price are not centered.
>
> Menu:
>
> - we need to increase spacing between menu items—they are too close to each other. 

Screenshot of the menu:

Screenshot 2023-10-16 at 01 07 47

@verofasulo would you please provide the updated design for this header to ensure we can match your expectations? Apart from the cart icon and the price not being centered, all other requested changes involve spacing and it would be great to have precise values to work with.

Also, regarding your question:

> Why do we have a blog page? Let’s not add any blog page as default.

The following area of this pattern:

Screenshot 2023-10-16 at 01 17 24

Corresponds to the Navigation Block, so the content is dynamically changed depending on the user's default menu: this means this menu was created with this structure on WooExpress out-of-the-box. 

I suggest that if we make any changes, do them on the initial site setup for Woo Express and do not create a blog page at all.

According to this feedback we need to add a width to the site logo as well Mrk6SERPZ4KrFHSjM0a8TK-fi-6660_69538

## Scope

- Ensure the cart icon and the price are centered
- TBD (additional changes pending design to ensure we follow the expected spacings)

### LINKED ISSUE #11389: [CYS Woo Express] Centered header menu with search
Please review `Centered header menu with search`. 

How it currently looks like:

image

image

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-35758&mode=design&t=qkpAGsXW7rY6XBmF-4)

image

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-34330&mode=design&t=qkpAGsXW7rY6XBmF-4)

image

### PR DESCRIPTION
**Pull request by albarin**
## What

Fixes a few issues with the `Centered Header Menu with Search`:
- Fix margins in the separator and first row.
- Increase navigation items spacing.
- Fix hidden search, cart, and account in mobile.
- Update site logo width

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11253
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11389

## Why

To match the design requirements in https://github.com/woocommerce/woocommerce-blocks/issues/11253

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new page or post.
2. Insert the `Centered Header Menu with Search` pattern.
3. Check it looks like the screenshot below.
4. Check all the elements are visible on mobile.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Desktop |
|--------|
| Screenshot 2023-10-23 at 14 04 18 |

| Mobile |
|--------|
| Screenshot 2023-10-23 at 14 09 48 |

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Improve the `Centered Header Menu with Search` pattern.

### CODE REVIEW

**Comment by albarin** [comment]
@verofasulo Could you have a look before we merge? 🙏 (sorry the comments are a bit repetitive, most of the issues are the same as in the other PRs). 

Some considerations/limitations we found:
1. The space between the search input and the button is not exactly the same as the design, but we cannot modify it, it's a limitation of the block. Same with the size of the 🔎 icon and the position of the placeholder text.
2. The button color depends on the theme, in this case, green because it's TT3.

On mobile:
- I know it's very different, but In this case, the mobile view that is designed cannot be achieved. The search bar cannot be hidden because it is not part of the menu, it's on a different row, so there's no way to put it in the menu. The same happens with the menu itself, it's on a different row (with the separator in the middle) and cannot be moved to the first row on mobile.

Let me know what you want to this with this pattern.

**Comment by verofasulo** [comment]
Thank you, @albarin! 💜

Would it be possible to set the default logo size to 60x60, as in the design, please?

>  On mobile:

I know it's very different, but In this case, the mobile view that is designed cannot be achieved. The search bar cannot be hidden because it is not part of the menu, it's on a different row, so there's no way to put it in the menu. The same happens with the menu itself, it's on a different row (with the separator in the middle) and cannot be moved to the first row on mobile.

Hmm, thanks for bringing this up! 🙏 I think we need to find an alternative because the mobile view doesn't work at all 🥲 Is there no workaround to achieve something close to the design?

**Comment by verofasulo** [comment]
@albarin, Is it possible we keep the search bar, account, and cart on the same line?

image

**Comment by albarin** [comment]
> @albarin, Is it possible we keep the search bar, account, and cart on the same line?
> image

I don't think so :( because of the minimum width, the search bar has, on smaller screens, the 3 elements don't fit together.

**Comment by verofasulo** [comment]
> I don't think so :( because of the minimum width, the search bar has, on smaller screens, the 3 elements don't fit together.

Hmm, what if we remove the price on mobile? 

Screenshot 2023-10-27 at 17 34 59

**Comment by albarin** [comment]
> > I don't think so :( because of the minimum width, the search bar has, on smaller screens, the 3 elements don't fit together.
> 
> Hmm, what if we remove the price on mobile?
> Screenshot 2023-10-27 at 17 34 59

It's the same problem, it works fine until a certain screen size where it starts breaking into multiple lines:
Screenshot 2023-10-27 at 17 44 14
Screenshot 2023-10-27 at 17 44 21
Screenshot 2023-10-27 at 17 44 06

**Comment by verofasulo** [comment]
> It's the same problem, it works fine until a certain screen size where it starts breaking into multiple lines:

Oh, no. Thanks for trying it out, @albarin 💜

What about moving the search bar to the hamburger menu? And keep the logo, cart, and account on the same row.

**Comment by albarin** [comment]
> What about moving the search bar to the hamburger menu? And keep the logo, cart, and account on the same row.

If you remember, we talked about this last week with @gigitux, we cannot move the search bar into the menu, this was the conversation for more context p1698144470308039/1698132360.788219-slack-C053716F2H2 :(

**Comment by verofasulo** [comment]
Adding this issue here from the latest QA — Is this double line the expected result? I find it a bit weird.  

image

Regarding the issues on mobile — what about:

- Removing the search bar (we already have other options if the user is interested in this kind of functionality)
- Spacing between account and cart icon: 16px.

@albarin, does it work better this way? 🤔 Let me know if you have any other proposals, of course 🙂

**Comment by gigitux** [comment]
The desktop view looks excellent:

image


Can we improve the mobile view to avoid two rows? I did a similar thing with #11490

image

**Comment by verofasulo** [comment]
> Can we improve the mobile view to avoid two rows?

@gigitux yes, please 🙏

**Comment by albarin** [comment]
> Can we improve the mobile view to avoid two rows?

@gigitux @verofasulo I've switched to columns to improve the mobile view, but I had to remove the price from the mini-cart to avoid the thing you can see in the gray example below. Now it looks like the first one in the example, is it fine?
Screenshot 2023-10-31 at 12 16 12

**Comment by gigitux** [comment]
> > Can we improve the mobile view to avoid two rows?
> 
> @gigitux @verofasulo I've switched to columns to improve the mobile view, but I had to remove the price from the mini-cart to avoid the thing you can see in the gray example below. Now it looks like the first one in the example, is it fine? Screenshot 2023-10-31 at 12 16 12

I think that it makes sense. I will approve this PR, but before merging it, let's wait for @verofasulo feedback.

**Review by gigitux — APPROVED** [review]
LGTM

**Comment by verofasulo** [comment]
> I've switched to columns to improve the mobile view, but I had to remove the price from the mini-cart to avoid the thing you can see in the gray example below. Now it looks like the first one in the example, is it fine?

@albarin, it looks great! It's ready to go 🌟

**Pull request merged**
