### PR TITLE
Add schedule to renovate bot config

### PR DESCRIPTION
**Pull request by Aljullu**
This PR copies the [renovate schedule configuration](https://github.com/woocommerce/woocommerce-admin/blob/master/renovate.json#L7) from wc-admin, so renovate bot creates all PRs on Wednesday.

### How to test the changes in this Pull Request:

I guess there is no other way to test other than waiting for next Wednesday and verify renovate continues working.

### CODE REVIEW

**Comment by ryelle** [comment]
Do you think this is necessary for this repo? I feel like we're much more on top of the renovate PRs here than we were on wc-admin. The current "backlog" has more to do with the fact that the #590 & #582 need to be combined, I think.

**Comment by Aljullu** [comment]
> Do you think this is necessary for this repo?

@ryelle not sure about it. Whatever works better for you. I created this PR after getting three PRs of core-js ([1](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/573), [2](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/579), [3](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/587)) in three days and thought it could make sense. But I don't mind closing this PR if you think it's not worth it.

**Comment by ryelle** [comment]
>  I created this PR after getting three PRs of core-js (1, 2, 3) in three days and thought it could make sense. 

Personally I like getting the PRs as they're released, I usually get to them within a work-day -i think the core-js ones were just an outlier (since we hadn't updated to 3.0, it kept cycling us between the 2.x and 3.x releases).

**Comment by Aljullu** [comment]
Sounds good. :+1:  Closing this PR then.

**Comment by Aljullu** [comment]
After discussing it with @mikejolley we might give it another try.

**Pull request merged**
