### PR TITLE
Product Query: Add a better default pattern

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR adds a default Product Query pattern based on Figma designs.

### Screenshots

Figma design:
loop

| Before | After |
| ------ | ----- |
|All_Products_–_ratings|All_Products_–_ratings-3|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add a page with the **Product Query** block.
2. Ensure the default pattern matches the screenshot.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by danieldudzic** [comment]
The spacing between the **Price** and **Add to Cart** button can be improved. I'm not clear whether this should be addressed via CSS or via margin spacing settings.

**Review by Aljullu — APPROVED** [review]
LGTM

> The spacing between the **Price** and **Add to Cart** button can be improved. I'm not clear whether this should be addressed via CSS or via margin spacing settings.

I think we should try to mimic what GB core blocks are doing. I'm taking a look at the _Post title_ block to see how it adds its own margins.

**Review by Aljullu — APPROVED** [review]
Thanks for adding the border to the price, @danieldudzic! LGTM

**Comment by nerrad** [comment]
Was it noticed that the [PR introduced a couple TS errors](https://github.com/woocommerce/woocommerce-blocks/pull/7833#issuecomment-1335970108)? Did it get addressed separately?

**Comment by Aljullu** [comment]
I missed that, thanks for pointing it out, @nerrad! However, those two files hadn't been modified in this PR. It seems like a false positive, maybe caused by this PR not being up-to-date with `trunk`? @gigitux do you know what might have caused this?

**Comment by gigitux** [comment]
>  maybe caused by this PR not being up-to-date with trunk

Exactly! There is an issue on GitHub related to this wrong behavior https://github.com/woocommerce/woocommerce-blocks/issues/7673. I will work on it during the next cooldown!

**Pull request merged**
