### PR TITLE
Automatic migration path from Products to Product Collection - step 1 - automatic migration

### PR DESCRIPTION
**Pull request by kmanijak**
This is the first PR out of many that introduce automatic migration from Products to Product Collection blocks.

This PR adds subscription to `core/block-editor` changes and if there are Products (Beta) block on the page, it will replace all of them with Product Collection blocks preserving the layout, styles, inner blocks and query.

Part of https://github.com/woocommerce/woocommerce-blocks/issues/9703

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Below you can find a testing steps with multiple different scenarios. I didn't write detailed testing steps on how to change settings of Products (Beta) block to keep it clean. However, if you're not familiar with these settings I recorded a video showcasing each of them, so please use it as a reference point. Video is split and attached to each section respectively

1. Go to Editor and edit for example Product Catalog
2. Add Products (Beta) block with different settings/configurations/scenarios etc.:
    - **PRODUCTS SET**
    - [ ] inherits the query from the template
    - [ ] doesn't inherit the query from the template and has some filters applied (e.g. products on sale, handpicked products etc.). You can try multiple combinations that result in various set of product
    - https://github.com/woocommerce/woocommerce-blocks/assets/20098064/4198f1a0-2c2c-4979-a60a-44e78ff97be1

    - **LAYOUT**
    - [ ] has "grid" layout and custom number of "columns", for example, 5
    - [ ] has "list" layout and custom number of "items per page", for example, 6
    - [ ] check with Gutenberg version below 16 (the layout was controlled on Query Loop level)
    - [ ] check with Gutenberg version 16+ (the layout properties were moved from Query Loop to Post Template block) 
    - https://github.com/woocommerce/woocommerce-blocks/assets/20098064/4732ee2a-4a12-422f-808d-66b06560e5ed

    - **PRODUCT ELEMENTS**
    - [ ] change product template by adding additional elements and changing order (e.g. add Product Rating, Product SKU etc.) and change order of them
    - [ ] change "No Results" content
    - https://github.com/woocommerce/woocommerce-blocks/assets/20098064/10ed1d9a-5d48-4184-8f83-e9e7b64b6e84

    - **STYLING**
    - [ ] change styles on the "Product Template" level, for example color and background color
    - [ ] change styles of some Product Elements
    - https://github.com/woocommerce/woocommerce-blocks/assets/20098064/22e49fb6-0b4d-4748-945f-9254ec702c77

    - **POSITION IN BLOCK STRUCTURE**
    - [ ] nest Products (Beta) block inside other blocks (e.g. Group, Columns etc.)

    - **OTHERS**
    - [ ] Suggest your own combination or edge cases of settings that should be preserved during migration 

3. Save the above
4. Change the [REPLACE_PRODUCTS_WITH_PRODUCT_COLLECTION](https://github.com/woocommerce/woocommerce-blocks/blob/add/migration-path-from-products-step-1-migrate-automatically/assets/js/blocks/product-query/constants.ts#L16) variable to `true` - replacement will be enabled for the next entries to the editor
5. Refresh the Editor
6. Expected: All of the Products (Beta) blocks should be replaced with Product Collection block and preserve all of the configuration (Products Set, Layout, Product Elements, Styling, Position in blocks structure and Others)

https://github.com/woocommerce/woocommerce-blocks/assets/20098064/376b80e5-420b-4210-9a44-d10e9a6cfa22

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### CODE REVIEW

**Comment by imanish003** [comment]
Hello @kmanijak,

I want to extend my appreciation for your work on this PR. I've tested the functionality and it's performing as expected. Fantastic work! Additionally, I found the detailed test steps you provided extremely helpful during the review 🙌🏻

However, I'd like to discuss a particular point:

> has "list" layout

Currently, we don’t allow users to modify it. There is no toolbar in the Product Collection block to change the layout type. So I have a concern about maintaining this setting during the migration. If a user has a list layout, they won't have the ability to switch to a grid layout in the Product Collection block post-migration. A potential solution could be to always default to a grid layout when replacing the Products Beta block until we integrate this toolbar.

Moreover, considering that adding the toolbar doesn't seem to be a major task, we might want to consider implementing it prior to the beta release. 

**Sidenote:** I have reviewed the functionality of the PR, but I will need to review the code itself later.

**Comment by kmanijak** [comment]
> Currently, we don’t allow users to modify it. There is no toolbar in the Product Collection block to change the layout type
Great catch!

> So I have a concern about maintaining this setting during the migration. If a user has a list layout, they won't have the ability to switch to a grid layout in the Product Collection block post-migration. A potential solution could be to always default to a grid layout when replacing the Products Beta block until we integrate this toolbar.

Considering a merchant will have the ability to revert the migration we cannot default to the grid view as we would lose the information about the original layout. So I believe we'll have to add this functionality. But as you said:

> Moreover, considering that adding the toolbar doesn't seem to be a major task, we might want to consider implementing it prior to the beta release.

It's not so hard, so I'll add this! :)
EDIT: I created an issue: https://github.com/woocommerce/woocommerce-blocks/issues/10138

PS. I appreciate your kind words and the testing, thank you! 👍

**Comment by albarin** [comment]
Hey @kmanijak great work!
Everything scenario I tested preserved the Products Beta configuration when replacing, just want to mention a scenario where some styles were a bit different: changing the template background color in Beta looks different than in Collection, and the editor and frontend styles don't match:

| Product Beta | Product Collection | Front end |
|--------|--------|--------|
| Screenshot 2023-07-10 at 09 39 15|Screenshot 2023-07-10 at 09 39 53 |Screenshot 2023-07-10 at 09 39 26  |

Also, I saw a couple of commented `console` in `assets/js/blocks/product-query/inspector-controls.tsx` that we may want to remove.

**Comment by kmanijak** [comment]
Thanks for the review @albarin!

> Everything scenario I tested preserved the Products Beta configuration when replacing, just want to mention a scenario where some styles were a bit different: changing the template background color in Beta looks different than in Collection, and the editor and frontend styles don't match:

I noticed that, but I'd rather keep it a separate issue from the migration for two reasons:
1. I think it's rather a minor thing (please let me know I you think otherwise)
2. The differences come from Gutenberg directly and Products (Beta) case is reproducible with Query Loop block

Editor | Frontend
-- | --
image | image

Product Collection doesn't have all the styles of Query Loop hence the additional padding on the left (which I think actually looks better as it's symmetrical 😅 )

What do you think?

**Comment by albarin** [comment]
@kmanijak Agree, I think it's fine to have it as a separate issue 👍

**Comment by kmanijak** [comment]
> Considering a merchant will have the ability to revert the migration we cannot default to the grid view as we would lose the information about the original layout. So I believe we'll have to add this functionality. But as you said:

> Moreover, considering that adding the toolbar doesn't seem to be a major task, we might want to consider implementing it prior to the beta release.
> EDIT: I created an issue: https://github.com/woocommerce/woocommerce-blocks/issues/10138

This has been addressed in https://github.com/woocommerce/woocommerce-blocks/pull/10145

@imanish003 , @albarin is there anything else you'd like to change in this PR or it could be approved?

**Review by albarin — APPROVED** [review]

**Pull request merged**
