### PR TITLE
Categorise patterns

### PR DESCRIPTION
**Pull request by kmanijak**
## What

Structure the patterns by putting them into subfolders depicting the category.

Before - full folder content doesn't even fit the screen | After - categorised patterns
-- | --
image | image

## Why

With the increasing number of patterns, I think it became harder to navigate properly in the folder structure. Putting them into subcategories allows for easier navigation and better pattern handling.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Go to Editor
2. Make sure patterns can be added and all the images are displayed correctly. Try couple of them, for example:
  - Discount Banner with Image
  - Product Details Pattern
  - 3-Column Product Row
  - Testimonials 3 Columns

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
The change makes sense from a developer experience perspective to me. Lets just make sure there are no implications from a UX perspective.

**Comment by tjcafferkey** [comment]
@kmanijak just an FYI: I noticed you've moved the screenshots to the top of the PR. Their position in the template was intentional: https://github.com/woocommerce/woocommerce-blocks/pull/10549#discussion_r1294800625

**Comment by kmanijak** [comment]
> @kmanijak just an FYI: I noticed you've moved the screenshots to the top of the PR. Their position in the template was intentional: https://github.com/woocommerce/woocommerce-blocks/pull/10549#discussion_r1294800625

@tjcafferkey, I actually moved them on purpose. In this case, images are not related to the testing steps (and _should not_ be included in testing steps), but rather I used them to better describe "What" section. I hope it makes sense 🙌

**Comment by kmanijak** [comment]
Hmm.. There's an issue with the `GLOB_BRACE` flag used in:

```glob( $this->patterns_path . '/{,*/}*.php', GLOB_BRACE );```

From [PHP `glob` docs](https://www.php.net/manual/en/function.glob.php):

> Note: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux.

So it's not available on some systems including the one we run our Playwright tests so running the env is failing. Seems like it may happen on some servers as well so we need to avoid using `GLOB_BRACE` variable. I didn't find a quick alternative, so I'm parking this PR for now and switching to draft unless someone has some quick idea.

**Comment by thealexandrelara** [comment]
> Hmm.. There's an issue with the `GLOB_BRACE` flag used in:
> 
> `glob( $this->patterns_path . '/{,*/}*.php', GLOB_BRACE );`
> 
> From [PHP `glob` docs](https://www.php.net/manual/en/function.glob.php):
> 
> > Note: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux.
> 
> So it's not available on some systems including the one we run our Playwright tests so running the env is failing. Seems like it may happen on some servers as well so we need to avoid using `GLOB_BRACE` variable. I didn't find a quick alternative, so I'm parking this PR for now and switching to draft unless someone has some quick idea.

Hmm, I'm wondering... it seems that this line matches files in the root directory and in the first-level subdirectory only. If that's the case, maybe we can create our own function and use a foreach for each path that we want to match? Something like:


```
$paths_to_match = [
    $this->patterns_path . '/*.php',       // matches PHP files in root directory
    $this->patterns_path . '/*/*.php'      // matches PHP files in first-level subdirectories
];

$files = [];
foreach ( $paths_to_match as $path ) {
    $matches = glob( $path );
    if ( is_array( $matches ) ) {
        $files = array_merge( $files, $matches );
    }
}
```

**Comment by nefeline** [comment]
Thanks for your proposal for categorizing the patterns @kmanijak! My take on this is:

- The `register_block_patterns` method within [WooCommerce Blocks for registering patterns](https://github.com/woocommerce/woocommerce-blocks/blob/811c37e01350670b4435bdde33ccc21ef944bed2/src/BlockPatterns.php#L57) is heavily based on `_register_theme_block_patterns` from the core of WordPress: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L352
- `$files = glob( $dirpath . '*.php' );` is the way the core of WordPress selects patterns, so this creates a clear expectation (or limitation?) that patterns should all be under the same `patterns` directory.
- I would recommend reaching out to the GB team to propose and discuss such changes, as by implementing this exclusively within Woo Blocks, we will diverge from what the rest of the WordPress ecosystem does, and this might have consequences in the long term, depending on how the registration of the patterns evolves in the core.

In the bigger scope (not related to the changes proposed here), I think we should explore not relying on our own copy of the blocks registration method as this creates an overhead and a risk for our patterns to not be taking advantage on key features as they are released on the core of WordPress.

**Comment by tjcafferkey** [comment]
>In the bigger scope (not related to the changes proposed here), I think we should explore not relying on our own copy of the blocks registration method as this creates an overhead and a risk for our patterns to not be taking advantage on key features as they are released on the core of WordPress.

Yes, this. We should where appropriate flag areas directly to Core where we've had to apply our own implementation. This way they (or we) can address this directly upstream within GB as there's likely a very good use case for it being needed by the community.

A good example of where we have had to create our own implementation which has grown arms and legs into a complex beast can be seen in the form of the `BlockTemplatesController.php`.

Again, it's unrelated to this PR but just wanted to chime with my thoughts.

**Comment by kmanijak** [comment]
> $files = glob( $dirpath . '*.php' ); is the way the core of WordPress selects patterns, so this creates a clear expectation (or limitation?) that patterns should all be under the same patterns directory.

I don't consider it an expectation or limitation. I see it as _a way_ of storing/selecting patterns, but not necessarily the only one.

As you said:

> The register_block_patterns method within [WooCommerce Blocks for registering patterns](https://github.com/woocommerce/woocommerce-blocks/blob/811c37e01350670b4435bdde33ccc21ef944bed2/src/BlockPatterns.php#L57) is heavily based on _register_theme_block_patterns from the core of WordPress: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L352

but the actual common contract which we have to obey is the WP methods: `register_block_pattern` and `register_block_pattern_category`, not what surrounds them or how we store the patterns internally. I agree the whole `BlockPatterns.php` is strongly inspired by WordPress code but I don't agree it implies we cannot modify it. Especially since the change is small and easily reversible if necessary, while I believe it increases the DX significantly.

I agree we would have to follow the flat `patterns/` structure if we relied on the core mechanism of registering patterns by moving patterns to one of the following directories that core mechanism takes into account:
- [theme's directory](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L379): `$dirpath = $theme->get_stylesheet_directory() . '/patterns/';`
- [core block patterns](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L33C4-L33C93): `$pattern           = require __DIR__ . '/block-patterns/' . $core_block_pattern . '.php';`

but in our case, we rely on registering methods, so IMO whatever happens before registration (including selecting patterns) is WC Blocks implementation detail.

> In the bigger scope (not related to the changes proposed here), I think we should explore not relying on our own copy of the blocks registration method as this creates an overhead and a risk for our patterns to not be taking advantage on key features as they are released on the core of WordPress.

Agree with that but on the other hand, I cannot imagine a better way of exposing registration than the current `register_block_pattern` and `register_block_pattern_category` methods 😅 `BlockPatterns.php` actually just finds the patterns, does some validation, and registers the patterns using WP methods. I don't think this is a big overhead and I'm not sure it has to be abstracted.

What do you think? 😅

**Comment by nefeline** [comment]
@kmanijak I don't have much more to add, TBH.

@nerrad @danielwrobert would you share your thoughts here as well, please 🙏 ?

IMO, we should focus on relying on https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L352 again (and upstreaming any changes we consider critical) and not deviating from it even further.

**Comment by nerrad** [comment]
IMO `_register_theme_block_patterns` is targeted more towards automatically registering patterns from themes and is also hinted as a private method via the use of the underscore prefix. I agree with Karol here that it's more of a convenience mechanism for themes as a wrapper around the actual APIs. 

Our implementation is inspired by this approach but imo we are free to do whatever we want under the hood as long as we're wrapping the canonical methods for registering the pattern. 

For our purposes, this is more of an internal convenience tool to make it easier for developers in the Woo project to create patterns. It's not something really intended for external consumption by the larger Woo ecosystem to supply patterns (WP already has that mechanism).

On the other hand, I do agree with Patricia that this sort of convenience mechanism would also be valuable for plugins (providing a canonical way for plugins to expose patterns via a `patterns` directory) and it'd be a nice thing to contribute upstream. However, I  don't think it should block any enhancements we make in our own wrapper for now.

**Comment by nefeline** [comment]
> However, I don't think it should block any enhancements we make in our own wrapper for now.

Thanks for the feedback @nerrad  🙏 : I agree this doesn't have to be a blocker for any changes here (as I mentioned earlier over here: https://github.com/woocommerce/woocommerce-blocks/pull/10834#issuecomment-1709829956 ); this is part of a more extensive/macro discussion regarding patterns registration.

> Our implementation is inspired by this approach but imo we are free to do whatever we want under the hood as long as we're wrapping the canonical methods for registering the pattern.

I think this is valid just because the core of WordPress still doesn't have a wrapper specific for plugins; as soon as they do,  I would be more inclined to rely on that.

> I do agree with Patricia that this sort of convenience mechanism would also be valuable for plugins (providing a canonical way for plugins to expose patterns via a patterns directory) and it'd be a nice thing to contribute upstream.

👍 I'll open a PR next week proposing to add a new `_register_plugin_block_patterns` based on our implementation, let's see how it goes!

**Comment by danielwrobert** [comment]
Mostly seconding what @nerrad stated above.

I agree that the lack of a convenience mechanism in WP Core isn’t something that we should be blocked by in this scenario and that we do have freedom around how we store our patterns under the hood.

As @kmanijak pointed out:

> the actual common contract which we have to obey is the WP methods: `register_block_pattern` and `register_block_pattern_category`

That said, having more flexibility around this in Core is something that other plugin developers would benefit from. Anytime we can make an upstream contribution to improve things for the broader ecosystem, we should definitely try to do that! 

> I think this is valid just because the core of WordPress still doesn't have a wrapper specific for plugins; as soon as they do, I would be more inclined to rely on that.

💯

**Comment by kmanijak** [comment]
I was planning to resurrect that work but didn't want to conflict and clash with the heavy and frequent changes in patterns. PRs now drifted away from `trunk` with too many conflicts. I believe this work has value and should be done again.

I created an issue to address that: https://github.com/woocommerce/woocommerce/issues/42067.

**Pull request closed without merging**
