### PR TITLE
Fix _n usage to use plural and singular correctly

### PR DESCRIPTION
**Pull request by tarunvijwani**
The `_n()` function was used in a way that it should not be used. Also, we missed adding the `packageCount` prop in `LocalPickupSelect` component. 

 

This PR fixes the  _n usage to use the plural and singular and display the correct package count.  

Slack: p1678807173212629-slack-C7U3Y3VMY

### Changes in the PR:

- Added missing  `packageCount` prop  in `LocalPickupSelect` component. 
- Fixed the usage of _n usage to use plural and singular. 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Enable the [Multiple Packages for WooCommerce](https://wordpress.org/plugins/multiple-packages-for-woocommerce/) extension and set a price for local pickup.
2. Add multiple products to cart. 
3. Go to the checkout and confirm you have multiple shipping packages, and the price x qty is shown when choosing local pickup.

### Screenshots
image

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by tarhi-saad — CHANGES_REQUESTED** [review]
Hey, @tarunvijwani! Thank you for working on this PR! I added some comments:

- When I changed the language to `Nederlands`, the text `price x number of packages` wasn't translated. And by reverting the changes in this PR, I get the translation back.
- The testing instruction for package count should be included in the testing notes
- The PR title and changelog should include both changes

You can apply the two last suggestions or split this PR instead!

**Comment by nielslange** [comment]
> When I changed the language to Nederlands, the text price x number of packages wasn't translated. And by reverting the changes in this PR, I get the translation back.

@tarhi-saad The original translation part was
```php
_n(
    '<price/>',
    '<price/> x <packageCount/> packages',
    packageCount,
    'woo-gutenberg-products-block'
),
```
while the new translation part is
```php
_n(
    '<price/> x <packageCount/> package',
    '<price/> x <packageCount/> packages',
    packageCount,
    'woo-gutenberg-products-block'
),
```

The current translation file, is still looking to match `'<price/>',` instead of `'<price/> x <packageCount/> package',`. That's why you do not see the Dutch translation yet. You can verify my comment by replacing
```json
"<price\/>":["<price\/>","<price\/> x <packageCount\/> pakketten"]
```
with
```json
"<price\/> x <packageCount\/> package":["<price\/>","<price\/> x <packageCount\/> pakketten"]
```
within the the corresponding *.json files. 

_(Please note that in the example above, I only adjusted the original string. I have not adjusted the singular version of the translated string.)_

**Comment by tarunvijwani** [comment]
> * The testing instruction for package count should be included in the testing notes
> * The PR title and changelog should include both changes

@tarhi-saad The package count was introduced in the PR: https://github.com/woocommerce/woocommerce-blocks/pull/7484/
I just fixed the bug, we missed passing the package count prop when we changed it to [ExperimentalOrderLocalPickupPackages](https://github.com/woocommerce/woocommerce-blocks/commit/58cf23f1dbdb4a2ea53883704b980209c525fb07). 

I feel it should not be mentioned in the change logs. Let me know your thoughts. 🙂

**Comment by tarunvijwani** [comment]
@nielslange Thank you for the details, Niels! Does this mean it will automatically be fixed when we merge it to the core? Or do we need to change anything in our code to make it work?

**Comment by nielslange** [comment]
> @nielslange Thank you for the details, Niels! Does this mean it will automatically be fixed when we merge it to the core? Or do we need to change anything in our code to make it work?

@tarunvijwani It will automatically work, so we don't have to apply any further changes to our code. That said, it does require someone to translate the strings. But assuming that translations have been provided, it will work as expected.

**Review by tarhi-saad — APPROVED** [review]
Thank you, @nielslange, for the explanation! I tested replacing the text in the translation file, which showed the correct translation! 👍 

> @tarhi-saad The package count was introduced in the PR: https://github.com/woocommerce/woocommerce-blocks/pull/7484
I just fixed the bug, we missed passing the package count prop when we changed it to [ExperimentalOrderLocalPickupPackages](https://github.com/woocommerce/woocommerce-blocks/commit/58cf23f1dbdb4a2ea53883704b980209c525fb07).

> I feel it should not be mentioned in the change logs. Let me know your thoughts. 

I understand, @tarunvijwani! It wouldn't make sense to add a changelog for a bug that wasn't released yet! Let's 🚢 it!

**Pull request merged**
