### PR TITLE
Add recommended extensions for VSCode #5233

### LINKED ISSUE #5233: Recommending VSCode extensions to improve the developer experience
This can improve the "developer experience” for everyone that opens the project for the first time.

### PR DESCRIPTION
**Pull request by gigitux**
This PR helps the onboarding experience for a new user that wants to contribute to this repo.

The recommended extensions are:​
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
- [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) 
- [WordPress Snippets](https://marketplace.visualstudio.com/items?itemName=wordpresstoolbox.wordpress-toolbox)
- [WooCommerce - Snippets & autocomplete](https://marketplace.visualstudio.com/items?itemName=claudiosanches.woocommerce)
- [Jest Snippets](https://marketplace.visualstudio.com/items?itemName=andys8.jest-snippets)
- [GitLens — Git supercharged](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
- [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)
- [PHP DocBlocker](https://marketplace.visualstudio.com/items?itemName=neilbrayfield.php-docblocker)
- [PHP Sniffer & Beautifier](https://marketplace.visualstudio.com/items?itemName=ValeryanM.vscode-phpsab)
- [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

Fixes #5233 

### Testing

How to test the changes in this Pull Request:

Check out this branch

1. Open the project with VSCode. Be sure that you don't have already all the extensions listed above installed.
2. Check if VSCode shows on the bottom right a box for installing the recommended extensions.

### CODE REVIEW

**Review by dinhtungdu — COMMENTED** [review]
@gigitux We already have a section on recommended extensions [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/getting-started.md#developer-tools-visual-studio-code). Personally, I just use a few extensions listed above. It's not a good developer experience to me if I install recommended extensions then have to remove some of them manually. It's also hard to debug when there is something unexpected caused by one extension in many recommended extensions I've just installed.

On the other hand, in your PR, you remove `.vscode` from the ignore file. That folder may contain many other local/project-specific files. So I don't think we should whitelist it. I'm not sure about other people's workflow, but for WordPress themes/plugins development, I add the WordPress root dir to the workspace, not the plugin folder, so the recommendation here may not work in that case.

**Comment by gigitux** [comment]
@dinhtungdu Thanks for your feedback!

> We already have a section on recommended extensions here. Personally, I just use a few extensions listed above. It's not a good developer experience to me if I install recommended extensions then have to remove some of them manually. It's also hard to debug when there is something unexpected caused by one extension in many recommended extensions I've just installed.

Before installing the recommended extensions, you can review them and decide not to install them. It's just to speed up the onboarding for the newcomers. 

> It's also hard to debug when there is something unexpected caused by one extension in many recommended extensions I've just installed.

These extensions were chosen after getting some opinions from other folks in the team about what extensions they use. 

> On the other hand, in your PR, you remove .vscode from the ignore file.
Maybe, for now, it's just better to whitelist only `extensions.json`. I will update the PR 👍

**Review by dinhtungdu — COMMENTED** [review]
@gigitux The recommendation doesn't show for me. I have some but not all of the recommended extensions installed. When I check the extension tab, I see some extensions not in our list but appear in the Recommended section. Please check the screencast for more detail.

https://user-images.githubusercontent.com/5423135/144019132-6d7c15c2-e4ba-4cd7-865c-592c780bd40b.mov

**Comment by dinhtungdu** [comment]
Also, I'm not sure about the benefit of this PR in real use-cases, given that we're developing a WordPress plugin.

> I'm not sure about other people's workflow, but for WordPress themes/plugins development, I add the WordPress root dir to the workspace, not the plugin folder, so the recommendation here may not work in that case.

**Comment by gigitux** [comment]
> @gigitux The recommendation doesn't show for me. I have some but not all of the recommended extensions installed. When I check the extension tab, I see some extensions not in our list but appear in the Recommended section. Please check the screencast for more detail.
> 
>  Screen.Recording.2021-11-30.at.16.09.55.mov


Maybe it doesn't show you because you already closed the dialog in the past or for your VSCode configuration. Check the attached video to check what should happen when a user opens for the first time our project. Another way to check that everything is okay is to open the extension section and write in the search box `@recommended`.

image

> Also, I'm not sure about the benefit of this PR in real use-cases, given that we're developing a WordPress plugin.
The goal of this PR is to improve the experience of our team as well.
They are simply things that don't impact productivity/codebase but can be helpful.


https://user-images.githubusercontent.com/4463174/144027907-54346033-d6ef-4066-b476-2a83372fdb75.mp4

**Review by dinhtungdu — APPROVED** [review]
> They are simply things that don't impact productivity/codebase but can be helpful.

👍🏽

**Pull request merged**
