### PR TITLE
Fix Single Product Classic Template block not showing on the front-end

### LINKED ISSUE #11454: WP 6.4: Classic Template block for Single Product does not work on the front-end
## Describe the bug

Classic Template block doesn't render on the front-end of WordPress 6.4-based block themes.

## To reproduce

1. Enable WordPress 6.4.
2. Enable a block theme.
3. Go to Site Editor → Single Product template.
4. Remove the blockified template and add the “Classic Template” block.
5. Save and check the front-end.
6. Notice that the template is not rendered.

## Expected behavior

The template should render correctly using the “Classic Template” block.

## Additional context

p1698230999338099-slack-C02FL3X7KR6
p1698246828170079-slack-C029LRAU2

### PR DESCRIPTION
**Pull request by sunyatasattva**
## What

In WordPress 6.4, it appears that the global `have_posts` is `false` in the context of the full site editing single product template. This breaks the Classic Template block.

In this PR, we are creating a custom query using the available id instead of relying on the global query.

This might be a temporary workaround as we are waiting to see if that's an issue that core is willing to fix, as it might affect backwards-compatibility for other vendors.

Fixes #11454 

## Testing Instructions

1. Enable WordPress 6.4.
2. Enable a block theme.
3. Go to Site Editor → Single Product template.
4. Remove the blockified template and add the “Classic Template” block.
5. Save and check the front-end.
6. Check that the template is correctly rendered on the front-end.

(Note: styling might not be the best in TT4, but that'd be a separate issue).

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> WordPress 6.4: fixed a bug which would break sites using the Classic Template block for the Single Product template.

## Notes

This PR is a WIP as we wait the result of this conversation: p1698246828170079-slack-C029LRAU2

### CODE REVIEW

**Comment by sunyatasattva** [comment]
Can confirm this is solved in [6.4-rc.3](https://wordpress.org/news/2023/11/wordpress-6-4-release-candidate-3/) as expected.

**Comment by sunyatasattva** [comment]
Reopening this because of this incident: p1699405119976099-slack-C03Q87XT1QF

cc @dinhtungdu

**Review by dinhtungdu — APPROVED** [review]
Tested and can confirm this fix the single product issue with legacy template. The 

Failed Playwright E2E tests - Normal are not related as the same tests are failing on trunk: https://github.com/woocommerce/woocommerce-blocks/actions/runs/6790191926/job/18459058400

**Comment by kinskiandbourke** [comment]
Thanks for that fix, is it possible to get them to mainline this, as if we done use it, our sites break.
perhaps they could simply add 	rewind_posts(); // to line 88 of the ClassicTemplate.php located in the BlockTypes folder in Woocommerce

**Comment by dinhtungdu** [comment]
@randomburner Can you share with us the error applying this fix or steps to reproduce? Curious what might be the cause.
Edit: I assume that you tried this PR and the fix introduced in this PR broke your site. If it's not the case, then as Lucio mentioned below, we're releasing a new WooCommerce version including this fix.

**Comment by sunyatasattva** [comment]
> Thanks for that fix, is it possible to get them to mainline this, as if we done use it, our sites break. perhaps they could simply add rewind_posts(); // to line 88 of the ClassicTemplate.php located in the BlockTypes folder in Woocommerce

@randomburner if by mainline you mean ship the code within WooCommerce, it should be merged as a patch in various version of WooCommerce soon.

**Pull request merged**
