### PR TITLE
[Experimental] Checkout Block Stepped Address Forms

### PR DESCRIPTION
**Pull request by mikejolley**
This is an alternative UI [similar in function to the address modals](https://github.com/woocommerce/woocommerce-blocks/pull/8513), but with inline forms/buttons. This PR extends the condensed address UI found here: 

https://github.com/woocommerce/woocommerce-blocks/pull/8559

What this does is remove the need for pushing changes as the user types by including a button after each address form which reads _Save address and continue. This triggers validation and a server push, then hides the form once successful.

Like the modal PR, this allows validation to happen only when the user is done typing, and them updates the other checkout sections with the correct, up to date data.

Screenshot 2023-03-23 at 14 09 26

Modals block access to other form steps, but this cannot, so to avoid a user skipping the form this PR **hides the shipping methods when the shipping address is being edited**. If you attempt to place order before finishing your address forms, **you'll see a notice telling you to complete the address form**. This mitigates any errors that could occur by submitting the checkout with incomplete address data.

Screenshot 2023-03-23 at 14 09 58

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add something to the cart
2. Go to checkout
3. See the address forms, or if you're logged in, click the 'change' button above your address
4. Fill in the form, save and continue

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

TBD

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @mikejolley. While reviewing this PR, I noticed a few things:

1. This PR is based on the branch #8559 which introduced the dependency `usehooks-ts@2.9.1`. When running `npm ci`, I get the following warning:
```sh
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'usehooks-ts@2.9.1',
npm WARN EBADENGINE   required: { node: '>=16.15.0', npm: '>=8' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.3.1' }
npm WARN EBADENGINE }
```
In https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.nvmrc, we locked the Node version to `16.13.2`. I believe we should bump the Node version accordingly and run additional tests to ensure that everything remains working. Alternatively, we could use a lower version of `usehooks-ts`, which supports the Node version to `16.13.2`.

2. When testing city names with special characters, e.g. `'s-Hertogenbosch`, the special character gets encoded:
Screenshot 2023-03-27 at 15 26 45
I tested a few more names with special characters, e.g. Hagåtña, Nāʻālehu and Līhuʻe, and so far, I only noticed problems when the city names contain an apostrophe.

3. On https://github.com/woocommerce/woocommerce-blocks/pull/8839/files#annotation_9953157344, I see three failed checks. The first two are related to each other and caused by this comment:
https://github.com/woocommerce/woocommerce-blocks/blob/3ba03b176e948e69aa1d40fafb5d0567af1b0b87/assets/js/data/cart/index.ts#L16

Deleting or moving the comment below this part, should solve the error:
https://github.com/woocommerce/woocommerce-blocks/blob/3ba03b176e948e69aa1d40fafb5d0567af1b0b87/assets/js/data/cart/index.ts#L17-L21

The third check points out that `hasAddress` is defined, but never used. 

4. On https://github.com/woocommerce/woocommerce-blocks/actions/runs/4502498067/jobs/7924426758?pr=8839, three ESLint error(s) are listed. I believe these are the errors are a result of the failed checks I mentioned before. 

5. The JS Unit tests `getCartData › when apiFetch returns a valid response, receives the cart correctly` currently fails. I wonder if that's related to this PR.

6. On https://github.com/woocommerce/woocommerce-blocks/actions/runs/4502498112, I see a few E2E tests failing. I wonder if they are also related to this PR.

**Comment by mikejolley** [comment]
@nielslange thanks. This PR is in progress/experimental so I won't fix any of those issues unless it gets a green light from design. Some of the points need to be applied to condensed address too when that gets the go ahead.

**Comment by nielslange** [comment]
@mikejolley I understand that fixing all these things might exceed the scope of this PR. As for the first issue I mentioned, the Node version, I manually had to switch it to Node 16.15.0 to be able to install the required dependencies and to build the project. Isn't that something that should be considered?

**Comment by mikejolley** [comment]
@nielslange this PR should not be marked for review :p I've sent it to the design team in the form of a demo site. If we decide to run with it I'll address the node issue.

**Comment by nielslange** [comment]
@mikejolley In that case, ignore (partially) what I said. 😁

**Pull request closed without merging**
