### PR TITLE
Return 402 instead of 400 when checkout payment fails

### PR DESCRIPTION
**Pull request by alexflorisca**
I was investigating a bug and wondered if we should be setting a HTTP status of 400 whenever the payment fails during checkout. HTTP 400 means a bad request, so it doesn't seem appropriate here. The reason the StoreApi `/checkout` endpoint failed, is because the request to process the payment failed for some reason. 

This PR changes the status from 400 to 402 - Request Failed, to better show why the request failed.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> StoreApi `/checkout` endpoint now returns HTTP 402 instead of HTTP 400 when payment fails

### CODE REVIEW

**Comment by mikejolley** [comment]
Since 424 (The request failed due to the failure of a previous request) is relatively uncommon and specific to WebDav, perhaps instead, we should just implement `402`?

```
402 - Request Failed: The parameters were valid but the request failed.
```

The request params were given, but something was wrong (card error). More in-depth error reporting would need to be handled gateway side.

**Comment by alexflorisca** [comment]
Yep, fair enough, I think that's a good shout. Changed to 402

**Review by mikejolley — APPROVED** [review]

**Comment by wavvves** [comment]
>Yep, fair enough, I think that's a good shout. Changed to 402

@alexflorisca can I change the title and PR description to reflect `402` instead of `424`?

**Comment by alexflorisca** [comment]
Sure thing, I've done it. If you want to change anything else feel free

**Pull request merged**
