### PR TITLE
[Patterns]: Add new `Featured Products 2 columns` pattern

### LINKED ISSUE #8949: Create `Product collections: b&w` pattern
Black   White

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33511 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by albarin**
This PR implements the `Featured products: 2 columns` pattern.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8949

### Screenshots

| Before | After |
| ------ | ----- |
| Black   White | Screenshot 2023-04-19 at 13 21 06 |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Create a new page or post
2. Make sure the `Featured products 2 columns` pattern appears under the WooCommerce category dropdown.
3. Insert in and make sure it shows as expected on the design.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add new `Featured Products 2 columns` pattern

### CODE REVIEW

**Review by nefeline — COMMENTED** [review]
Awesome work! 🎉 

The only thing I noticed is that the Pattern doesn't have a preview, is that expected?

Screenshot 2023-04-21 at 08 16 30

**Comment by albarin** [comment]
> The only thing I noticed is that the Pattern doesn't have a preview, is that expected?

@nefeline I think so, if I'm not wrong, checking [this code](https://github.com/albarin/gutenberg/blob/fdc180a53110b48e98be3460bb8be1b65152ea1e/packages/block-editor/src/components/inserter/preview-panel.js#L23) it seems the previews are not available for patterns.

**Comment by nefeline** [comment]
> @nefeline I think so, if I'm not wrong, checking [this code](https://github.com/albarin/gutenberg/blob/fdc180a53110b48e98be3460bb8be1b65152ea1e/packages/block-editor/src/components/inserter/preview-panel.js#L23) it seems the previews are not available for patterns.

Ok, gotcha! Not something that we can solve on our end, but if previews are not available for Patterns, perhaps Gutenberg should not display it at all in such cases (or alternatively, add support for it), right? What are your thoughts?

**Review by nefeline — APPROVED** [review]
🚀

**Comment by albarin** [comment]
> Ok, gotcha! Not something that we can solve on our end, but if previews are not available for Patterns, perhaps Gutenberg should not display it at all in such cases (or alternatively, add support for it), right? What are your thoughts?

@nefeline Yeah, I'm not sure what's the logic behind that, also, I'm seeing 2 different types of previews 👇 the first one works fine but not the second:
Screenshot 2023-04-24 at 09 44 52
Screenshot 2023-04-24 at 09 45 08

**Pull request merged**
