### PR TITLE
try adding docker and e2e to travis

### PR DESCRIPTION
**Pull request by senadir**
This PR adds support for travis, since #1670 is not merged I can’t base this against it, it has the same code in #1670 + modifications to `.travis.yaml`.
All tests are passing expect phpunit 5.6, phpunit 7.1 is not to be trusted as well
image

### CODE REVIEW

**Comment by senadir** [comment]
End to End is working 🎉time to figure out why phpunit is not working
image

**Comment by jeffstieler** [comment]
@senadir - looks like `composer install` isn't running in the PHP 5.6 build:

https://travis-ci.com/woocommerce/woocommerce-gutenberg-products-block/jobs/282762237#L950

**Comment by nerrad** [comment]
@senadir this pull will likely be replaced by #1716 (I setup travis in 1716 too - not tested yet but should work - it removes the dependency on woocommerce installed from composer).

**Comment by nerrad** [comment]
#1716 fixes this

**Pull request closed without merging**
