### PR TITLE
Migrate toward a native Select and update WordPress Components to the latest version.

### PR DESCRIPTION
**Pull request by senadir**
This PR updates `@wordpress/components` to the latest version 9.5, it also replaces `CustomSelectControl` to a native solution:

Firefox:
image

Chrome:
image

The case for a native select is better accessibility, better autocomplete without hacks, and less external dependencies, `CustomSelectControl` was built for when you need a custom-styled option, the docs suggests that you should use a native select if that's not the case.

Fully migrating to 9.5 still needs some work (we need to handle dependencies not handled by WP 5.3 that are extracted anyway).

At best, we can discuss this PR regarding the select component, revert the wordpress-component upgrade, merge this and handle WordPress components in a separate PR.

### CODE REVIEW

**Comment by senadir** [comment]
> Size Change: +20.3 kB (1%)
Well, one thing we can conclude from updating is that it won't fix the bundle size issues, it increases them.

**Comment by senadir** [comment]
> An issue I'm facing is that when running npm i && npm start in this branch, the blocks stop working completely. 😕 Can you reproduce it as well? (It might be something weird in my environment)

yes, this is expected since I didn't yet resolve the dependency issue, one solution would be to install Gutenberg to test this.

> After using autocomplete, the arrow is not visible.

autocomplete seems to add a background, the arrow is using a background, I think we can migrate to a hardcoded svg like the checkbox.

> Also, if you look at Spain, you will notice it's slightly cut-off at the bottom.

I did notice it but couldn't fix it yet

**Comment by Aljullu** [comment]
@senadir one more question: could the `remove dashicon` commit be split in another PR or it's tied to this one? I see the bundle size wins are quite huge :tada: so it might make sense to review it separately so both changes don't block each other. But I'm not sure if that's possible, so asking. :slightly_smiling_face:

**Comment by senadir** [comment]
> @senadir one more question: could the remove dashicon commit be split in another PR 

yes I have it in another branch that I didn't push yet.

**Comment by nerrad** [comment]
> One of the reasons to use the CustomSelectControl was that we were planning to migrate to the ComboboxControl at some point because it would allow searching through the options (see #1752). Has this been discarded for now? If it has, I agree there is no need to use CustomSelectControl over a native select. I would like to know @nerrad's opinion on that.

It looks like the biggest performance gains at this point will be eliminating the dashicons import which could be done in a separate pull.

Since we're already close to release and we've ironed out a lot of the bugs related to `CustomSelectControl`, I'd prefer to keep that in place and focus our efforts on a `ComboboxControl` (#1752) replacement at some point (but not for the initial release of the blocks).

If there were larger gains from converting to native select then I'd be more supportive of making the change.

**Comment by senadir** [comment]
@nerrad @Aljullu I'd appreciate if we can give this PR another shot.

**Comment by nerrad** [comment]
@senadir there's various discussion in this pull already. Is there something we are doing right now that increases the importance of surfacing this? Have you considered the last comment I made in this PR, what feedback do you have regarding it?

**Comment by senadir** [comment]
Yes I did consider that comment and here's my take form it:

- We fixed dashicon but still see some bundlesize for things like downshift (which is used here and only here).
- We stopped working on this because we were close to releasing the blocks, we should be in a comfortable position now to iterate on it (in a cooldown period maybe).
- a combobox still causes the same performance issues without any obvious benefits (except typing, which I feel is a wrong use for that component).

Ultimately the goal is to have a lighter native component when a custom one doesn't offer much value.

**Comment by nerrad** [comment]
> We fixed dashicon but still see some bundlesize for things like downshift (which is used here and only here)

How much impact does downshift add on the size?

> a combobox still causes the same performance issues without any obvious benefits (except typing, which I feel is a wrong use for that component).

Help me understand better why it's the wrong use for the component.

I've added the cooldown label to this - I think it's worthwhile to at least see:

a. How using native selects impacts bundlesize.
b. What the support is for the styling on native selects across browsers.
c. Have a concrete list of what we gain and what we lose (and then decide whether that's an acceptable trade-off).

**Comment by nerrad** [comment]
@senadir is this still something you feel is worth investigating (see [my comment here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2281#issuecomment-734786575))?

**Pull request closed without merging**
