### PR TITLE
Add default style to link-button mixin

### LINKED ISSUE #7118: Links for all filter blocks (reset and clear all)
Can we ensure all links are displayed as underlined for consistency between the blocks and other areas of the site.

Screenshot 2022-09-09 at 14 05 44

Screenshot 2022-09-09 at 14 07 04

### PR DESCRIPTION
**Pull request by thealexandrelara**
It was identified that we currently have 3 different behaviors for links used in the application. In issue #1778, it was discussed a set of good practices that we should follow in order to obtain consistency between links.

Currently, the link-button mixin is already used by the 'Clear all' button in the Active Filters block, so the idea was to increment it with a common pattern (font size small, font-weight normal, underlined by default and not underlined when on hover) that can be reused by other components (for example FilterResetButton).

* Change link-button mixin to make it attend the expected default style for links
* Replace text-button with link-button mixin in FilterResetButton component

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots

| Before | After |
| ------ | ----- |
|   CleanShot 2022-10-07 at 16 02 20@2x   |   CleanShot 2022-10-07 at 16 04 34@2x  |

#### User Facing Testing
1. Create a regular page (Pages > Add New) and add the All Product block to it;
2. Add the Active Filters block;
3. Add the Filter By Attribute block;
4. Select an attribute from the Filter By Attribute block and apply it;
5. When the page reloads, check if the "Clear All" button (in the Active Filters block) and the "Reset" button (in Filter By Attribute block) have the following properties:
> Font size: 14px
> Font weight: normal
> Text decoration: underlined
6. Hover the mouse over the "Clear All" button and the "Reset" button and make sure the text decoration is changed to `none` (no underline) while the other properties remain the same:
> Font size: 14px
> Font weight: normal
> Text decoration: none

### Changelog

> Improve visual consistency between block links

### CODE REVIEW

**Review by tjcafferkey — APPROVED** [review]
Great PR write-up and testing instructions @thealexandrelara ! This PR LGTM! 🚢

**Comment by tjcafferkey** [comment]
@thealexandrelara I have also just added a few labels to this PR, and assigned you to it for good practice. Other than that, great job!

**Comment by tjcafferkey** [comment]
I can also see that the failing tests are related to the Mini Cart, these are being looked into separately so this PR is safe to be merged I think 😃

**Comment by Aljullu** [comment]
Nice improvement and congrats on your first PR, @thealexandrelara!

@thealexandrelara @tjcafferkey I have just one question (sorry if that was discussed somewhere else and I missed it), but is it expected that the font size changes are applied to all consumers of `link-button()`? Ie, I see it changes the size of the `change address` button in the Cart block:

Before | After
--- | ---
imatge | imatge

_(I know it's hard to see :sweat_smile: but `(change address)` is slightly smaller now)_

I wonder if `font-size` should be left out of this mixin. We might want to have buttons that are displayed as links from different sizes depending on the context.

**Comment by tjcafferkey** [comment]
Good catch here @Aljullu , you might be right. @thealexandrelara how do you feel about reopening this and using the SCSS extend functionality instead for a new mixin to get the desired outcome specifically for the filter links?

cc'ing @wavvves incase you need to revert for the release.

**Comment by thealexandrelara** [comment]
> Nice improvement and congrats on your first PR, @thealexandrelara!
> 
> @thealexandrelara @tjcafferkey I have just one question (sorry if that was discussed somewhere else and I missed it), but is it expected that the font size changes are applied to all consumers of `link-button()`? Ie, I see it changes the size of the `change address` button in the Cart block:
> 
> Before	After
> imatge	imatge
> _(I know it's hard to see 😅 but `(change address)` is slightly smaller now)_
> 
> I wonder if `font-size` should be left out of this mixin. We might want to have buttons that are displayed as links from different sizes depending on the context.

Nice catch @Aljullu, I didn't release it was being used in a scope other than filter blocks 😓 

> Good catch here @Aljullu , you might be right. @thealexandrelara how do you feel about reopening this and using the SCSS extend functionality instead for a new mixin to get the desired outcome specifically for the filter links?

That's alright I can reopen this one. Any suggestion about the new mixin name? Maybe `filter-link-button`?

**Comment by tjcafferkey** [comment]
>Any suggestion about the new mixin name? Maybe filter-link-button?

I think that makes sense. Might need to also coordinate with @wavvves to ensure this does go into the release but that shouldn't be a problem 😃

**Comment by wavvves** [comment]
@tjcafferkey I reopened and added it to the milestone, and I'll cherrypick it tomorrow along with the other task 👍🏼

**Comment by thealexandrelara** [comment]
@wavvves I just opened a new PR (#7357 ) to address this issue, the idea was to revert the changes made on this one and also make the link button styles consistency in filter blocks

**Pull request merged**
