### PR TITLE
Provide a way to switch to the blockified Single Product Template

### LINKED ISSUE #8208: Provide a way to easily switch to the blockified Single Product Template
We have to provide an easy way for the merchant to switch to the blockified Single Product Template. As it is suggested in https://github.com/woocommerce/woocommerce-blocks/issues/8066, we can use the button on the current `Classic Product` block:

image

### PR DESCRIPTION
**Pull request by albarin**
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8208

### Screenshots
| Before | After |
| ------ | ----- |
| Screenshot 2023-01-30 at 12 41 58 |<video src=https://user-images.githubusercontent.com/4463174/227149851-235b6685-0955-48e8-91d5-37f2ad7f9b87.mp4/>|

##### Prerequisites:
WordPress: >=6.1
Make sure `Single Product` template is cleared out to the default state. To achieve that:
1. Go to (`/wp-admin/site-editor.php?postType=wp_template`)
2. Click three dots next to the template and click `Clear customizations`

##### Steps
1. Enter the `Single Product` template.
2. Check that the placeholder description says "This block serves as a placeholder for your WooCommerce Single Product Block. We recommend upgrading to the Single Products block for more features to edit your products visually. Don't worry, you can always revert back.".
3. Click the `Upgrade to Blockified Single Product Template` button.
4. See new templates work in the Site Editor and on the front end.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Enable users to migrate to the blockified Single Product template.

Description updated by @gigitux

### CODE REVIEW

**Comment by albarin** [comment]
@kmanijak @gigitux Just adding you here in case you want to have a look, I think this is all I can do here until we have all the necessary blocks for the blockified single product.

**Comment by gigitux** [comment]
The PR is ready to be reviewed! @thealexandrelara @kmanijak

**Review by thealexandrelara — COMMENTED** [review]
I have some points that I'd like to discuss before approving:

1. I noticed that the Related Products block does not have the title for the section, and probably this is happening because a `wp-block-heading` block is missing before the Related Products block.
image



2. I also noticed that the Product Details and the Related Products blocks have a smaller width than the blocks above. The classic template for the Single Product block had a width of 1000px, so I'm wondering if we should set this width for the Group block that is wrapping all the blocks, what do you think?

**Comment by gigitux** [comment]
Could you let me know if you pulled the last changes on this repo? The things that you noticed should be already fixed 🤔  


https://user-images.githubusercontent.com/4463174/227149497-5d521137-72d6-4644-9edf-b344fee708b4.mp4

**Review by thealexandrelara — APPROVED** [review]
Thank you @gigitux, I think it might be related to a cache issue, now it is working perfectly. Approving this PR. Thank you all for working on this!

**Pull request merged**
