### PR TITLE
Include address fields in the AddressForm component

### LINKED ISSUE #1879: Dynamic Address Fields Data
Coming out of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1868 we realised some field labels are dynamic when retrieved from core based on options we won't be using in blocks. See https://github.com/woocommerce/woocommerce/blob/d3a33f8d0547b709b4c7d7753b209802e85c3f44/includes/class-wc-countries.php#L648

We have visibility and required as block level options.

Whilst this would create duplication from core, we should look at including default fields in blocks itself -- including country locales for different field labels and positioning. That would mean core options do not affect us negatively.

Another point to bare in mind, this would affect extensibility. But if we're happy to remove checkout field customisation in the v1 we can proceed.

### LINKED ISSUE #1888: Can't add Checkout block anymore
**To Reproduce**
1. Create a post and add a _Checkout_ block.
2. Notice an error appears in the console:
`TypeError: can't access property "includes", fieldLabel is undefined`

The line causing the error is:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/base/components/address-form/index.js#L84

That's because we expect to have a label in all fields but `DEFAULT_ADDRESS_FIELDS` might be undefined when creating the block.

We should either:

1. Always define `DEFAULT_ADDRESS_FIELDS` in the editor even when no _Checkout_ block is present. So when one is added it has the necessary values.

2. Fix #1879, which might automatically fix this issue as well.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR moves away from using core data for address fields, into the AddressForm component. This ensures labels are correct (based on optional/required status), and that the data is available at all times.

Fixes #1879
Fixes #1888

Extensibility is hindered, however, this is something we can iterate on in the future.

### How to test the changes in this Pull Request:

1. Go to checkout
2. Try changing countries 
3. Confirm fields change, labels update etc

### CODE REVIEW

**Comment by mikejolley** [comment]
@nerrad The county locales include labels for some fields. This is part of what we need to override, including updated strings and the "optional" label. 

There is parity, but "hidden" was spread across functions. There is a function to get county states in core. Some countries define an empty array for state - this indicates the field is hidden. I've simply merged both data sets into this one object. 

As for extensions, no I have not searched. I know checkout field editor uses the filters. For county locale data, this should be based on actual real world addresses. If an extension needs to change this, it could indicate our config is wrong and needs updating. E.g. if a country doesn't use a particular field, our config should reflect that.

**Comment by nerrad** [comment]
> This is part of what we need to override, including updated strings and the "optional" label.

Is that something that could be added via filter php side before providing the data over the wire?

> There is parity, but "hidden" was spread across functions. There is a function to get county states in core. Some countries define an empty array for state - this indicates the field is hidden. I've simply merged both data sets into this one object.

Ahh, so lack of `hidden` infers `hidden: false`?  That also sounds like something that could be duplicated js side (just have `hidden` default to false where it's used).

> If an extension needs to change this, it could indicate our config is wrong and needs updating. E.g. if a country doesn't use a particular field, our config should reflect that.

I'm more concerned about extensions _enhancing_ this data for usage in processing server side (i.e. adding country locale information).  I think there may be value in double-checking extensions aren't using this in a way we didn't anticipate before committing to it.

I'm still not convinced we need to go this route for country locales. Based on what I see so far it seems like we could just use the existing `woocommerce_get_country_locale` filter server side to modify the shape as needed and pass it through to js?

**Comment by nerrad** [comment]
🤔 speaking of which, could we use the `woocommerce_default_address_fields` filter to normalize the default address fields exposed by the server (and just return the fields removed by the 'hidden' option to that for our use)?

**Comment by mikejolley** [comment]
> Ahh, so lack of hidden infers hidden: false

@nerrad No, the data comes from other places. The locale data is in some places wrong or contradictory to state data. Reconciling this could be possible but it's extra processing. 

I'll search Monday for usage. I disagree with shaping what is in core because once we do that, we have to maintain compatibility with core filters. I'd prefer a clean break, js only.

**Comment by mikejolley** [comment]
> speaking of which, could we use the woocommerce_default_address_fields filter to normalize the default address fields exposed by the server (and just return the fields removed by the 'hidden' option to that for our use)?

Bare in mind that filter can significantly alter fields or even add custom fields. Dangerous :)

**Comment by nerrad** [comment]
> Bare in mind that filter can significantly alter fields or even add custom fields. Dangerous :)

Agreed! Any time one uses a filter, one enters the land of dragons 🔥.  I'm just wary of prematurely branching off into our own client side population of data that might hide potential problems we _will_ have to deal with eventually anyways (hence my questions 😄 ).  I should be clear, I'm not nixxaying the approach in this pull (yet), I'm just posing questions around concerns I see.  What I've got so far:

Pros of this approach:

- tighter control over what is used/implemented in the blocks for the first iteration without worrying about potential pollution of data from filter usage and/or changes in Woo core.  
- extensibility can be thought through a bit more deliberately (which may mean plugins/themes have to hook into the new forms in a different way other than via filters). 
- we keep a positive velocity towards finishing the blocks.

Cons of this approach:

- we potentially whitewash over things that we should _want_ to surface as potential issues so we can address them (caveat, this could be argued as a pro too - start with a clean slate).
- we're essentially duplicating what's already exposed from Core. What happens if any of the labels change for a country, or if a country changes so it now has states? Ongoing maintenance of this could be a problem.
- If there are problems with how core is doing things, we should probably identify that as something that maybe needs solved in core? I recognize this slows velocity if we bring this up for core. Maybe a middle ground would be to clearly articulate _why_ we're taking this approach for now, but also create an issue in WC core for fixing whatever needs fixed so we can revert this approach and go back to using core methods in a future iteration?

The above are some things I'm weighing as I consider this pull. Even knowing the dangers of using a filter, I'm still leaning so far towards using filters server side to get the data in the shape we want. I'll think on this over the weekend.

**Comment by mikejolley** [comment]
First off, this is where I mention data being contradictory. When a country has states listed like this:

https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php#L75

This causes core make the state field hidden and non-required. Some of this config is duplicated in the countries class...

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L817

...but as I went through there were a few mismatches. Using a single data source for field config, like in this PR, would be prefered. Otherwise some consolidation would be needed, and that would run on every process. Keeping an array on the JS side is more efficient.

Next, the filters we're essentially avoiding are:

- `woocommerce_default_address_fields` - The list of fields for checkout addresses
- `woocommerce_get_country_locale` - The config for specific fields depending on country code

Some others in the countries class are also avoided due to the nature of new checkout,  but not in this PR, but these would also affect any consolidation work:

- `woocommerce_country_locale_field_selectors` - Determines which field classes map to address fields. I think this is used for show/hide field logic which we don't need in react.
- `woocommerce_get_country_locale_default` - "Countries with no specific locale will use default."
- `woocommerce_get_country_locale_base` - Locale for the store base country.
- `'woocommerce_' . $type . 'fields'` - Dynamically adjusts the field config for either billing or shipping addresses.

Why does this affect consolidation? Because some of these filters affect the address fields depending on context. If we support some fields, we might need to support others--being selective is tricky.

**`woocommerce_default_address_fields` usage**

Across this org there are a few:

- [Conditional shipping](https://github.com/woocommerce/woocommerce-conditional-shipping-and-payments/blob/51a24ae1e2c28692273b3754697cf51b854d981a/includes/restrictions/class-wc-csp-restrict-shipping-methods.php#L55) uses it to add a class. That class won't affect the react checkout.
- [One page checkout](https://github.com/woocommerce/woocommerce-one-page-checkout/blob/58b8c66b8bedc0a36d7a712b92dbd56494107743/woocommerce-one-page-checkout.php) adds autofocus to the first field. If beneficial we could include this, shouldn't need to be extension specific...
- [PayPal Express](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/6683c964bfa9444e83ab2a26288cdab7e19d952b/includes/class-wc-gateway-ppec-checkout-handler.php#L40) Makes some fields non-required and hides fields. If the other filters, or conditionals, were to fail or not be accurate with the react checkout, this could pose a risk as fields could not be rendered.

Outside of the org there are some examples(https://github.com/search?q=woocommerce_default_address_fields&type=Code) mostly changing default things such as required, or adding extra field params such as max length. Very opinionated. Conflicts with some of the block settings we're putting in users hands.

**`woocommerce_get_country_locale` usage**

In our org, some gateways use this to apply required fields (similar to above hook): 
https://github.com/search?p=1&q=org%3Awoocommerce+woocommerce_get_country_locale&type=Code

Example: https://github.com/woocommerce/WC-Payment-Gateways/blob/27f824f2dfb478564304776d0f6bf71dd6980734/_separated/woocommerce-gateway-authorize-net-aim/woocommerce-gateway-authorize-net-aim.php#L267-L284

Since gateways won't be compatible with the new checkout by default, I think validation logic can be implemented in more appropriate places now. The filter as-is could cause conflicts.

Outside of the org (https://github.com/search?q=woocommerce_get_country_locale&type=Code) the first few pages of results are minor tweaks to countries, or adding new states. Personally, I think if a country locale is _wrong_ we should update the locale in core, not rely on extensions to do so. Not sure why this pattern has emerged. 

** Addressing @nerrad's list of cons:

> we potentially whitewash over things that we should want to surface as potential issues so we can address them (caveat, this could be argued as a pro too - start with a clean slate).

And if the solution to an issue is to....stop using filters? We're in trouble :)

> we're essentially duplicating what's already exposed from Core. What happens if any of the labels change for a country, or if a country changes so it now has states? Ongoing maintenance of this could be a problem.

Yes we are, _however_, I feel we're doing it in a more efficient way, so it's not a duplication as such. Maintenance of course could be a problem, but our end goal is to create the future core checkout. Presumably at some point this becomes default and the current core methods go away, leaving one set, our set, in place maintained by whomever.

> If there are problems with how core is doing things, we should probably identify that as something that maybe needs solved in core? 

Depends, see above. If we're working towards the replacement for core, why refactor whats there now? The consolidation point I made above won't go away easily.

**Pros of this PR**
- Clean slate - avoids the mess of filters which do similar things in the countries class
- Easier to gauge feedback and add new filters than it is to take them away once implemented
- Avoids mixing PHP filters with our implementation
- Avoids extensions such as Checkout FIeld Editor from affecting the React based checkout -- this is important because any such fields would not be functional, and we'll likely have preferred ways (?) in the future to extend things in a structured way. 
- > "tighter control over what is used/implemented in the blocks for the first iteration without worrying about potential pollution of data from filter usage and/or changes in Woo core."
- Some other filters in countries class affect fields; why would we support some filters and not others?
- Filters can affect the user-facing options we're adding to the block.

**Cons**
- Duplication
- Potential maintenance medium term 
- Short term extensibility

I still vote to go ahead with this. cc @nerrad @Aljullu

**Pull request merged**
