### PR TITLE
Filter Products by Attribute: Fix the page reload which happens when clicking the filter button on PHP templates

### LINKED ISSUE #6282: Filter Products by Attribute: filter button doesn't work with Active Filters for PHP templates
## Describe the bug

When the filter button is enabled, after choosing an attribute and clicking the filter button, the page reloads as expected. The chosen attribute is selected in the Filter Products by Attribute block but does not appear in the Active Filters block.

## To reproduce

1. On a block theme, go to Edit Site >  Product Catalog template.
2. Add Active Filters and Filter Products by Attribute block to the template.
3. Choose an attribute to filter, and make sure the filter button is toggled.
4. Go to the shop page.
5. Select an attribute from the block added in step 2.
6. Click the filter button. See the page reload as expected.
7. See the correct filtered results after page load.
8. Don't see the selected filter in the Active Filters block.

## Expected behavior

Filter Products by Attribute block should always work with Active Filters block.

## Screenshots

https://user-images.githubusercontent.com/5423135/163999383-1df29934-2e88-4796-8c8e-d6a90be0882d.mov

Note: From the screenshot above, there are additional unexpected behaviors:

Right after clicking the filter button, the selected filter appears in the Active Filters block. In the Filter Products by Attribute, unchecked attribute options disappear, and the product count in the selected attribute changes to `0`.

IMO, in the PHP template context, we should only update the filter URL. On slow server or network, this behavior can make customers confused.

### LINKED ISSUE #6283: Filter Products by Attribute: the page reload without clicking the filter button on PHP templates
## To reproduce

1. On a block theme, go to Edit Site >  Product Catalog template.
2. Add Active Filters and Filter Products by Attribute block to the template.
3. Choose an attribute to filter, and make sure the filter button is toggled.
4. Go to the shop page.
5. Select an attribute from the block added in step 2.
6. Click the filter button. See the page reload as expected.
7. See the correct filtered results after page load.
8. Uncheck the selected attribute, see the page reload right away. (It should only reload after filter button is clicked).

Another behavior but same issue:
1. On a block theme, go to Edit Site >  Product Catalog template.
2. Add Active Filters and Filter Products by Attribute block to the template.
3. Choose an attribute to filter, and make sure the filter button is toggled.
4. Go to the shop page.
5. Select an attribute from the block added in step 2.
6. Uncheck the selected attribute.
7. See the page reload.

## Expected behavior

When filter button is enabled, the page should only reload after the filter button is clicked.

## Screenshots

https://user-images.githubusercontent.com/5423135/164000950-5ae1b299-55f5-4edf-b979-5501777d1515.mov

### PR DESCRIPTION
**Pull request by tjcafferkey**
This PR fixes the page reload which is triggered immediately when you uncheck an attribute filter when the "Filter button" option is enabled.

Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6283
Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6282

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. On a block theme, go to Edit Site >  Product Catalog template.
2. Add Active Filters and Filter Products by Attribute block to the template.
3. Choose an attribute to filter, and make sure the filter button is toggled.
4. Go to the shop page.
5. Select an attribute, a reload should not happen until you click the filter button.
6. Once the filter has been applied. Uncheck it, a reload should not happen until you click the filter button.
7. Try this again with the filter button untoggled, although these reloads should now happen as soon as you check the attribute you're filtering by
8. Check there are no regressions on All Products block.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above, or
* [ ] See steps below.

1.
2.
3.

### Changelog

> Filter Products by Attribute: Fix the page reload which happens when clicking the filter button on Woo templates using the Classic Template block

### CODE REVIEW

**Review by dinhtungdu — COMMENTED** [review]
@tjcafferkey Thanks for the PR! I can confirm that the page doesn't reload anymore after selecting the attribute within the block with the filter button. But look like the issue with Active Filters is still there. In the screenshot below, only selected attributes from the `Filter by Color` block appear in the Active Filters block, Color filter doesn't have a filter button while the Size filter does:

image

**Comment by tjcafferkey** [comment]
@dinhtungdu good catch, I've just pushed a commit to fix that!

**Review by dinhtungdu — COMMENTED** [review]
@tjcafferkey with [97a684c](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6287/commits/97a684c36fd9fd955e7dd8fd26db974c19ebecd6), the first issue comes back, please check my screencast for more detail. I tested with the Filter button enabled.

https://user-images.githubusercontent.com/5423135/164443333-93ac88b1-7cc6-476d-bc1c-75bc57bb86a7.mov

**Review by dinhtungdu — COMMENTED** [review]
I got a weird behavior with the filter button enabled block:

1. Enable the filter button for Filter Products by Attribute block.
2. On the front end, select one or two attributes, and click the filter button.
3. See the page reload: the filtered product result is correct, and the selected attributes appear in the Active Filters block => which are expected behaviors.
4. The Filter Products by Attribute now only shows selected attributes, with product count set to `0`.
5. In my case, I have another Filter block by another attribute (filter button disabled), that block disappears after the page load.

https://user-images.githubusercontent.com/5423135/164503860-d5612d00-f480-4bdf-a2f7-ccf884e408cc.mov

**Review by dinhtungdu — APPROVED** [review]
Thanks so much for your updates! Finally, it's working now! :shipit:

**Pull request merged**
