### PR TITLE
fix individual product block legacy.

### LINKED ISSUE #226: Individual product block fails with no image
**Describe the bug**
If an 'Individual Product' block is added to a page, it produces an error when associated with a product that doesn't have an image.

**To Reproduce**

1. Goto the admin panel
2. add a new product *without* an image
3. add a new page, while in editor
4. add a product block
5. select 'individual products'
6. Search for product created in (2)

**Expected behavior**
the search will report an error

**Desktop (please complete the following information):**

* OS: mac el-capitan
* Browser: chrome
* Version: 71

### PR DESCRIPTION
**Pull request by rogovski**
prior to this commit, an 'individual product' block would produce
an error if associated with a product with no image.

Fixes #226 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### How to test the changes in this Pull Request:

see issue.

### CODE REVIEW

**Comment by rogovski** [comment]
hey @joshuatf, 

no I didn't mean to commit the package lock. I can resubmit the PR if needed. let me know. Thanks

**Comment by ryelle** [comment]
@rogovski Yes, can you resubmit this without the `package-lock.json` change? Thanks!

**Comment by rogovski** [comment]
@ryelle this should be good to go. let me know if there is any issue. thanks.

**Comment by ryelle** [comment]
@rogovski I'm still seeing the package-lock change here– maybe try closing this PR & opening a new one with just the `views/specific-select.jsx` fix?

**Pull request closed without merging**
