### PR TITLE
Add `FormStep` to Storybook

### PR DESCRIPTION
**Pull request by opr**
## What

Adds a storybook entry for the `FormStep` component we recently exported.

## Why

To showcase the component and provide a level of documentation.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Run `npm run storybook`
2. Open `localhost:6006` and check the `WooCommerce Blocks/@woocommerce-blocks-components/FormStep` component.
3. Try changing the controls and make sure it reflects in the canvas. (Note `stepHeadingContent` is a React Node so can't be changed in Storybook.)

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Skipping.

### CODE REVIEW

**Review by tarunvijwani — APPROVED** [review]
Thank you for adding this component to Storybook! It works as expected. 🎉

**Review by senadir — APPROVED** [review]
Works very well!

**Comment by opr** [comment]
@senadir and @tarunvijwani  thanks for reviewing - I have rebased this to work with Storybook 7. I renamed the title of the story so it goes into the `Checkout Components` category and I renamed the file. Please give it another check (you probably need to run `npm i` to get storybook 7 if you didn't since #11524 was merged

**Comment by mikejolley** [comment]
Moving to 11.6.0

**Review by senadir — APPROVED** [review]
Redid a review, it looks fine, a couple of notes:

- The form looks too narrow/in the middle
image

- Not sure if we should show this raw, babel, children code here
image

**Comment by opr** [comment]
@senadir thanks, removed the control for the chidren prop and made all components appear as `padded`  by changing the settings in `storybook/preview.js`.

**Review by tarunvijwani — APPROVED** [review]
Works great! 👍

**Pull request merged**
