### PR TITLE
Add an interim filter for cart item and expose prepare_money_response

### PR DESCRIPTION
**Pull request by senadir**
### Add interim hook
In order to add subscription data to our endpoints, we need to provide some sort of a hook place, we discussed the approach we're going to take in this issue https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3244, but in order to not limit myself and overengineer it beforehand, I went ahead and created this interim filter that will be deleted once I implement what's discussed in that issue.

### Turn prepare_money_response to public
This function is used to format any monetary value, but it's protected, so third party code can't use it.
It's part of `AbstractSchema` and is only relevant when returning money in REST.
I temporarily turned it to public and will create an issue to decide if we want to keep it public or move it to a utility class.

## Why two changes in a single PR

Ideally, I would split those into two PRs, but to facilitate testing https://github.com/woocommerce/woocommerce-subscriptions/pull/3839 and because they're not permanent changes, I decided to keep them in a single PR. They're both needed for that PR.

### CODE REVIEW

**Comment by senadir** [comment]
While this issue is linked to #3262, it should not close it. That issue should be closed by a PR in Subscriptions repo.

**Comment by senadir** [comment]
Added relevant tracking issue for `prepare_money_response`
https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3264

**Comment by nerrad** [comment]
> In order to add subscription data to our endpoints, we need to provide some sort of a hook place, we discussed the approach we're going to take in this issue #3244, but in order to not limit myself and overengineer it beforehand, I went ahead and created this interim filter that will be deleted once I implement what's discussed in that issue.

I appreciate this. However, I wonder if the same can be achieved by an early iteration of something like `__experimental_register_endpoint_data` (or some other better function name) or `register_rest_field` if it works (which I don't think it will because it looks like it's coupled to custom post types?) for enhancing our endpoints. I'm wary about doing what you're doing here (even with it explicitly being temporary) because we definitely know we won't be using filters long term. So let's iterate on an interface we _will_ use.

> I temporarily turned it to public and will create an issue to decide if we want to keep it public or move it to a utility class.

The problem with doing this is that it could land in a release as a public method which then restricts us from making it protected/private again. The other issue here is that there's no clear indication in _this pull alone_, why it's being made public. I understand that you are doing this because the object instance is being passed along through the temporary filter, but this to me is another indicator that we should be thinking a bit more carefully about the interface we want to build for registering different fields on the endpoints.

**Comment by senadir** [comment]
> The problem with doing this is that it could land in a release as a public method which then restricts us from making it protected/private again. The other issue here is that there's no clear indication in this pull alone, why it's being made public. I understand that you are doing this because the object instance is being passed along through the temporary filter, but this to me is another indicator that we should be thinking a bit more carefully about the interface we want to build for registering different fields on the endpoints.

My basis for doing this is that if it's not announced publicly, it's not public. I understand that this is not a bullet-proof method.
This change is not final, but an interim solution while we [decide what to do.](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3264)


What kind of change do you suggest for this PR? postpone the release of this method? or move it to an Utility class?

For the action, I do agree, I will handle it after our cooldown.

If both actions are to redo, I can close this PR and we can try again independently (register method in a PR and utility class in a PR).

**Comment by nerrad** [comment]
> My basis for doing this is that if it's not announced publicly, it's not public. I understand that this is not a bullet-proof method.
> This change is not final, but an interim solution while we decide what to do.

In the current climate of people looking for ways to extend things, it's unlikely it won't get noticed. I know it's intended to be interim but that's all the more reason to avoid making public _in this class_.  Think of it this way:

- the only reason it's being made public is so it can be exposed to filter callbacks.
- the filter is a temporary implementation that we've already agreed is something we should avoid here.

Also think we should explore how the API we implement for extending the endpoint could automatically handle formatting money data so consumers don't do that.

**Comment by senadir** [comment]
I'm going to close this PR and start over with a `__experimental_register_endpoint_data` prototype, this should be a globally available function @nerrad? something we never did in our plugin, so I don't know if this is the best approach.

**the question here is: should `__experimental_register_endpoint_data` be part of some class, or a regular function?**

For `prepare_money_response` I'm going to try and implement it as part of `__experimental_register_endpoint_data`

**Comment by nerrad** [comment]
I think a _similar_ (but not exact) model for registration might be the [`register_post_meta` function](https://developer.wordpress.org/reference/functions/register_post_meta/) in WordPress core.

I wonder if this should be part of some sort of `ExtendRestApi` service class that could be used by extensions?

**Comment by senadir** [comment]
> I wonder if this should be part of some sort of ExtendRestApi service class that could be used by extensions?

That would certainly solve the `prepare_money_response` but I'm not if it will complicate things more for developers.

I will start with that and see where it takes me.

**Pull request closed without merging**
