### PR TITLE
[Patterns]: Add new `Featured products: 5-item grid` pattern

### LINKED ISSUE #8950: Create `Product collections: 5-item grid` pattern
5-item grid

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1327_25779 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by albarin**
Add a new pattern showing 5 newest products with a title and `/shop` button.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8950

### Screenshots
Screenshot 2023-04-11 at 16 25 52

#### User-Facing Testing
1. Create a new page or post
2. Make sure the `WooCommerce Featured Products 5-item grid` pattern appears under the WooCommerce category dropdown.
3. Insert in and make sure it shows as expected on the design.

### WooCommerce Visibility
* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add the new `WooCommerce Featured Products 5-item grid` pattern.

### CODE REVIEW

**Comment by albarin** [comment]
@shaunandrews @jarekmorawski could you review the pattern? (sorry that I'm mentioning both, should I only mention @shaunandrews from now on? 🤔)
I have a couple of questions:
- We already have a very similar pattern called `WooCommerce Minimal 5-Column Products Row`, does it make sense to keep both? or should we maybe update the existing one to add the title and button?
- Which width should the block have? I've used `Wide width` for now.
Screenshot 2023-04-11 at 16 36 06

**Comment by thealexandrelara** [comment]
Hey @albarin, thank you for working on this! I tested and I can see that the pattern can be added to the page. I saw some differences from the design that I'd like to understand if it is expected or not before approving the PR

## Space between the title and the products
It looks like it has a bigger spacing between the title and the products on the design

| Design | Implementation |
| ------ | ----- |
| image | image | 

## Product badge style and margin
The product badge has a different style on the implementation, and the margin between then and the border of the product image is also smaller. Should also the text be different depending on the product? On the design, we have the text "Bestseller" and "New" for some of the products

| Design | Implementation |
| ------ | ----- |
| image | image | 

## Product price position
The product price is located at the end of the container on the design, but in the implementation, there is a spacing between the product price and the container.

| Design | Implementation |
| ------ | ----- |
| image | image | 

## Product Title text alignment
The text alignment for the Product Title on the design seems left-aligned. In the implementation, it is centered, which creates a spacing between the container and the Product Title:

| Design | Implementation |
| ------ | ----- |
| image | image |

**Comment by albarin** [comment]
Thanks @thealexandrelara for the review.
I've increased the spacing in the title. 
I've removed the spacing at the beginning of the product title and at the end of the product price.

Regarding the product `SALE` badge on the product image, it cannot be currently customized to achieve the style of the designs, should we work on implementing options to do it? What do you think @shaunandrews?

**Comment by thealexandrelara** [comment]
Thank you for addressing those! I can see that now the spacing are fixed. 

While testing it, I noticed that if the image is not square, the product information is misaligned:

image

I think that maybe this is occurring because we need to set the "imageSizing" attribute of the Product Image to be `thumbnail` (by default it is set to "single", which displays the image as full size)

Another thing that I noticed is that on the mobile view, the Product Price is being displayed in a new line:

image

> Regarding the product SALE badge on the product image, it cannot be currently customized to achieve the style of the designs, should we work on implementing options to do it? What do you think @shaunandrews?

Ohh I see, maybe we can open a separate issue to work on this if this is not necessary for this card

**Comment by albarin** [comment]
@thealexandrelara thanks, great review! Fixed both issues 🙌

**Review by thealexandrelara — APPROVED** [review]
Awesome, just tested and LGTM! Great job! 🚀

**Comment by shaunandrews** [comment]
CleanShot 2023-04-19 at 11 48 50@2x

I noticed that with the current layout we leave little room for the product title and price, leading to a lot of awkward wrapping. I think it might work better if we keep the title and price to their own lines:

CleanShot 2023-04-19 at 11 52 08@2x

--

CleanShot 2023-04-19 at 11 52 39@2x

I know there's talk above about not being able to customize the sale badge. But, I think we _can_ customize it, we just have to add it without using the Product Image block. If, instead, we use the Cover block we can place the Sale Badge within and then we can customize its styles.

CleanShot 2023-04-19 at 11 54 09@2x

--

CleanShot 2023-04-19 at 11 56 22@2x

I noticed the button is linked to /shop — is there some magic here, or just a hardcoded link? Can we (safely) make the assumption that a /shop page exists?

**Comment by albarin** [comment]
@shaunandrews
>I noticed that with the current layout we leave little room for the product title and price, leading to a lot of awkward wrapping. I think it might work better if we keep the title and price to their own lines:

Fixed!

>I know there's talk above about not being able to customize the sale badge. But, I think we can customize it, we just have to add it without using the Product Image block. If, instead, we use the Cover block we can place the Sale Badge within and then we can customize its styles.

You are totally right, done! 🙌 

> I noticed the button is linked to /shop — is there some magic here, or just a hardcoded link? Can we (safely) make the assumption that a /shop page exists?

That's the default URL, but I found a better way to always get the shop URL event when the user changes it, I pushed the change.

**Comment by thealexandrelara** [comment]
WooCommerce Blocks 10.1.0 will be released soon. I'm bumping this PR to the next milestone

**Comment by shaunandrews** [comment]
CleanShot 2023-04-24 at 12 40 29@2x

It'd be amazing if we could add PHP here, but unfortunately it doesn't work.

--

I think this is unrelated to the pattern, but worth asking: When I select the **Product Title** block, the blue outline and toolbar appear to include the Cover block. Can you reproduce, and if so, perhaps this is a bug in the **Product Title** block?

CleanShot 2023-04-24 at 12 41 05@2x

--

Can we make the Product Title bold, to help add some visual hierarchy?

CleanShot 2023-04-24 at 12 42 11@2x

**Comment by shaunandrews** [comment]
CleanShot 2023-04-24 at 12 46 53@2x

**Comment by shaunandrews** [comment]
I'm a moron and hit the wrong button. Sorry.

**Comment by shaunandrews** [comment]
Oooh, I bet that PHP doesn't work cause I just copy/pasted the pattern block markup — I didn't actually add the whole PHP file.

**Comment by albarin** [comment]
> CleanShot 2023-04-24 at 12 40 29@2x
> 
> It'd be amazing if we could add PHP here, but unfortunately it doesn't work.
>
Yeah, I don't think we can do that.

> I think this is unrelated to the pattern, but worth asking: When I select the **Product Title** block, the blue outline and toolbar appear to include the Cover block. Can you reproduce, and if so, perhaps this is a bug in the **Product Title** block?
> 
> CleanShot 2023-04-24 at 12 41 05@2x
> 
Hmm, I am not able to reproduce it, it only selects the title for me 👇 
Screenshot 2023-04-25 at 10 14 26


> --
> 
> Can we make the Product Title bold, to help add some visual hierarchy?
> 
> CleanShot 2023-04-24 at 12 42 11@2x

Done! 👍 
@shaunandrews

**Comment by shaunandrews** [comment]
Looks good to me 🚢

**Pull request merged**
