### PR TITLE
Single Product block: Redirect to the cart page after successful addition setting isn't respected

### LINKED ISSUE #10775: Single Product Block: Redirect to the cart page after successful addition setting isn't respected
## Describe the bug

The Single Product block does not respect the setting under WooCommerce > Settings > Products > General > Add to cart behaviour > Check - Redirect to the cart page after successful addition.

## To reproduce

1. Enable redirects to the cart page with the setting under WooCommerce > Settings > Products > General > Add to cart behaviour > Check - Redirect to the cart page after successful addition
2. Create a product and a page with an FSE theme.
3. Add the product to the page with the Single Product block.
4. View the page and click "Add to cart".
5. User is not redirected to the cart page.
6. View the cart.
7. See the product was successfully added.

## Expected behavior

For the redirect to the cart page setting to be respected.

This only affects the Single Product Block. The Single Product template works as expected.

## Screenshots

https://github.com/woocommerce/woocommerce-blocks/assets/56649567/30eadb80-b54c-4844-870e-e03aa7207a86

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): N/A
-   WooCommerce version: 8.0.2
-   WooCommerce Blocks version: 10.6.5
-   Site language: English (US)
-   Any other plugins installed:

**System Status Report**

<details>

```
### WordPress Environment ###

WordPress address (URL): https://psychological-dragon.jurassic.ninja
Site address (URL): https://psychological-dragon.jurassic.ninja
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Total Database Size: 5.30MB
Database Data Size: 3.60MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
order_shipment: 2
page: 11
post: 2
product: 1
revision: 4
shop_order: 3
wp_global_styles: 1
wp_navigation: 1
wp_template: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.30
Jetpack: by Automattic – 12.5
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.8.3
WooCommerce: by Automattic – 8.0.2

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/users/userc0ba1945/apps/userc0ba1945/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/users/userc0ba1945/apps/userc0ba1945/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/users/userc0ba1945/apps/userc0ba1945/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-30 17:26:58 +00:00
Options: ✔
Notes: 62
Onboarding: skipped

### Action Scheduler ###

Complete: 11
Oldest: 2023-08-29 17:28:26 +0000
Newest: 2023-08-29 19:58:07 +0000

Failed: 1
Oldest: 2023-08-29 17:36:51 +0000
Newest: 2023-08-29 17:36:51 +0000

Pending: 1
Oldest: 2023-08-30 17:28:26 +0000
Newest: 2023-08-30 17:28:26 +0000


### Status report information ###

Generated at: 2023-08-29 20:02:34 +00:00
```

</details>

### Desktop (please complete the following information):

-   OS: macOS Ventura - 13.4.1 (22F82)
-   Browser Firefox
-   Version 117.0b9 (64-bit)

### Smartphone (please complete the following information):

Untested

## Additional context

Found in 6742597-zen

### PR DESCRIPTION
**Pull request by thealexandrelara**
## What
The Single Product block does not respect the setting under WooCommerce > Settings > Products > General > Add to cart behaviour > Check - Redirect to the cart page after successful addition.

Fixes #10775 

## Why
This PR solves that by checking if the "Redirect to the cart page after successful addition" option was set in the WooCommerce Settings. If that is the case, then we allow the user to be redirected to the cart page after adding the product to the cart.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

#### Test 1: Redirect shopper to the cart page after successful addition when setting is enabled
1. Enable redirects to the cart page with the setting under WooCommerce > Settings > Products > General > Add to cart behaviour > Check - Redirect to the cart page after successful addition
2. Create a product and a page with an FSE theme.
3. Add the product to the page with the Single Product block.
4. View the page and click "Add to cart". Make sure the shopper is redirected to the Cart page and the product was correctly added to the cart

#### Test 2: Keep shopper at the same page when setting is disabled
1. Enable redirects to the cart page with the setting under WooCommerce > Settings > Products > General > Add to cart behaviour > Check - Redirect to the cart page after successful addition
2. Create a product and a page with an FSE theme.
3. Add the product to the page with the Single Product block.
4. View the page and click "Add to cart". Make sure the shopper is NOT redirected to the Cart page;
5. Visit the Cart page and make sure the product was correctly added to the cart.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Changelog

> Resolved an issue where the Single Product block did not respect the WooCommerce setting for redirecting to the cart page after successful addition.

### CODE REVIEW

**Comment by Marc-pi** [comment]
@thealexandrelara 
strange, i just tested this feature this afternoon, and it worked indeed !!!!
Are you sure it is a bug ? i run all the latest stable releases with Woo, WooBlocks, Gutenberg and WP 6.3.1

**Comment by thealexandrelara** [comment]
> @thealexandrelara strange, i just tested this feature this afternoon, and it worked indeed !!!! Are you sure it is a bug ? i run all the latest stable releases with Woo, WooBlocks, Gutenberg and WP 6.3.1

Hey @Marc-pi,
I just wanted to confirm with you if you tested adding the Single Product block to a page. 

I can consistently reproduce this issue, however, it only occurs when the "Add to Cart With Options" block is inside the "Single Product" block. 

This happens because the default behavior when clicking the "Add to Cart" button is to redirect to the product page. However, since the "Single Product" block can be added to any page, we prevent the redirection from occurring. Unfortunately, we hadn't anticipated the case in which the shopper should be redirected to the cart if the setting is enabled in WooCommerce Settings.

**Review by gigitux — APPROVED** [review]
Nice catch! LGTM!

**Comment by roykho** [comment]
Bumping PR to next release.

**Comment by roykho** [comment]
Changed to include in 11.3.0 release.

**Pull request merged**
