### PR TITLE
Add featured category cover image

### LINKED ISSUE #9046: Create `Featured category: cover image` pattern
Cover Image

The `Featured category` block does not allow to move the text & button to the top left corner, we can use the `Cover` block with a `Paragraph` and `Button` or maybe add more customization options to the `Featured category` block.

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33400 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by roykho**
Closes https://github.com/woocommerce/woocommerce-blocks/issues/9046

#### User Facing Testing

1. Create a page and use the block inserter->patterns->WooCommerce and to insert the Featured Category Cover Image.
2. Insert the pattern and update/save and check the frontend and ensure it is displaying close to the design from https://github.com/woocommerce/woocommerce-blocks/issues/9046

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add featured category cover image pattern

### CODE REVIEW

**Review by albarin — APPROVED** [review]

**Comment by roykho** [comment]
Thanks for the review @albarin - but after the patterns discussion we had yesterday p1682971804704159-slack-C02FL3X7KR6 I will redo this pattern with just core blocks so we can make it as close to design as possible.

**Comment by roykho** [comment]
@albarin - ok I've updated this pattern to use WP core blocks. Note the only thing different is the image where I couldn't find the one proposed in the original design. However this one also showcases the jeans so I think it should be ok.

**Comment by albarin** [comment]
> @albarin - ok I've updated this pattern to use WP core blocks. Note the only thing different is the image where I couldn't find the one proposed in the original design. However this one also showcases the jeans so I think it should be ok.

Thanks! Could you try to align the text to the top left corner? I'm seeing it at the center of the image:
Screenshot 2023-05-03 at 10 44 16

**Comment by roykho** [comment]
@albarin - hmmm interesting. On my end, I am seeing it at the top left corner as shown in my OP. I wonder what is causing the discrepancy.

**Comment by albarin** [comment]
> @albarin - hmmm interesting. On my end, I am seeing it at the top left corner as shown in my OP. I wonder what is causing the discrepancy.

Ahh, I see what's going on, it's the theme, using Tsubaki works fine, but I was testing with TT3. This happened to me when on other patterns when using padding in `em`, using `px` solves this.

**Comment by roykho** [comment]
Ok I've explicitly added the measurement type `em` to the pattern. I think this should resolve that issue. Can you please check with latest pull?

**Review by albarin — APPROVED** [review]

**Pull request merged**
