### PR TITLE
Update/featured items content alignments

### LINKED ISSUE #42316: Enhancement: Featured Category block
Currently the `Featured Category` block is limited in the content inside the "cover" block. It does not allow you to add custom text or change the text content position to say the top left or bottom right. We should add these features making the block more customizable. For this first issue, let's just tackle the content alignment.

WP core cover block:

Woo featured category block:

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce/issues/42316

This PR adds a new control `BlockAlignmentMatrixControl` into the block toolbar. It allows the user to have more control of the position of the content within the "cover" style block. This allows us to make our patterns more dynamic when the design calls for content to be positioned in a certain way.

#### User Facing Testing

1. Add a post and insert the `Featured Category` and `Featured Product` block.
2. For each of the block added in step 1, test that you can use the `Change content position` featured tool from the block toolbar. Click on each of the alignment positions and ensure they're working as expected.
3. Save the post and go to the frontend and ensure they're working as expected.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Adds a new control `BlockAlignmentMatrixControl` into the block toolbar for featured category and product block

### CODE REVIEW

**Comment by albarin** [comment]
Good work @roykho 👍 

I see one issue though, this could break already existing blocks, created before this change.
| Created before | After this change |
|--------|--------|
| Screenshot 2023-07-11 at 16 00 35 | Screenshot 2023-07-11 at 16 01 52| 

I think this could be a good candidate to create a [deprecated](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) version of the block, since its attributes change.

**Comment by roykho** [comment]
So I actually accounted for that "somewhat" as seen here https://github.com/woocommerce/woocommerce-blocks/pull/10156/files#diff-c0a86a69d6d954b1749f4aef3f7f1161413daa8464da187d46fde010b6036631R284. But since the HTML markup is drastically change it was hard to preserve everything. Since this is a server side render, do we have common practices to deprecate this?

**Comment by roykho** [comment]
@albarin also I think what you're seeing is just in editor right? In frontend, it is correct?

**Comment by roykho** [comment]
@albarin - I've pushed up a change to hopefully solve the issue of retaining alignment from previously added block in the editor. Please see if that works for you.

**Comment by albarin** [comment]
> @albarin also I think what you're seeing is just in editor right? In frontend, it is correct?
> @albarin - I've pushed up a change to hopefully solve the issue of retaining alignment from previously added block in the editor. Please see if that works for you.

There are some differences in the frontend as well.

I think what you're trying to do (trying to keep the old styles if present) is a good approach here.
It's close, but I can see still some differences.

| Editor before | Editor after |
|--------|--------|
| Screenshot 2023-07-11 at 16 48 46| Screenshot 2023-07-11 at 16 48 53|

| Frontend before | Frontend after |
|--------|--------|
| Screenshot 2023-07-11 at 16 48 57|Screenshot 2023-07-11 at 16 49 00|

**Comment by roykho** [comment]
@albarin - ok I pushed up a fix which should fix the small discrepancies in the editor and frontend.

**Comment by albarin** [comment]
> @albarin - ok I pushed up a fix which should fix the small discrepancies in the editor and frontend.

Looks better 🙌 
I found another discrepancy when changing the alignment on the buttons only:
| Before | After |
|--------|--------|
| CleanShot 2023-07-12 at 11 24 14@2x |CleanShot 2023-07-12 at 11 24 39@2x |

**Comment by roykho** [comment]
@albarin - right so that one is quite difficult to change because with the alignment matrix, there is a container around the content. Making the button align right or left will work only within the confine of the container. Maybe we need to fine a way to deprecate a server side render after all. What do you think?

**Comment by albarin** [comment]
> @albarin - right so that one is quite difficult to change because with the alignment matrix, there is a container around the content. Making the button align right or left will work only within the confine of the container. Maybe we need to fine a way to deprecate a server side render after all. What do you think?

Right, maybe, could we detect in the `FeaturedItem.php` if the `contentAlign` setting is present and render it the old way or use the new way if it's not? 🤔 Might be worth sharing the issue it with the rest on Slack to get more ideas.

**Comment by roykho** [comment]
Closing ahead of the monorepo merge and will recreate there.

**Pull request closed without merging**
