### PR TITLE
Specific Select improvements

### LINKED ISSUE #33: It shouldn't be possible to finish adding the block if no products are selected.
For example if you elect to display individual products but do not select any, then click done you see this; 

no products

I appreciate that's what you'd see on the frontend but nobody would ever want to use the product block this way. 

The "Done" button should be disabled (with `cursor: not-allowed;`) in this case with a tooltip which states "Please search for and select products to display first".

disabled

### LINKED ISSUE #49: Specific select: list reloads when adding/removing products
Sometimes when adding or removing products, the list of products that were selected refreshes, and for a split second, the pages jumps while the content is loading again.

### PR DESCRIPTION
**Pull request by claudiulodro**
- Closes #49 (Refactored the way that section is rendered to use caching)
- Closes #33 (Disabled "Done" button on product, attribute, and category select screens if nothing is selected)
- Fixes frontend specific product rendering (Was using `include` shortcode attribute when it should be using `ids`)
- Fixes bug where selecting some products then switching to category or attribute select mode would end up with product ids in the list of category/attribute ids.

### CODE REVIEW

**Comment by jameskoster** [comment]
> Disabled "Done" button on product, attribute, and category select screens if nothing is selected

This button should be disabled for all scopes, until products are selected.

**Comment by claudiulodro** [comment]
@jameskoster it is disabled for all the scopes where you have to make a selection. I can't disable it for e.g. "All" or  "Best rated" because there is nothing further to do once that scope has been selected.

**Comment by jameskoster** [comment]
I can click "Done" when no scope is selected at all, though.

**Comment by claudiulodro** [comment]
@jameskoster I've disabled the button when no scope is selected.

**Comment by jameskoster** [comment]
Tiny nitpick - let's say;

"Please select which products you'd like to display" 

In the tooltip. Then this is good to merge.

**Pull request merged**
