### PR TITLE
Hide the shipping address form from the Checkout when the "Force shipping to the customer billing address" is enabled

### LINKED ISSUE #7219: Checkout Block doesn't respect "Force shipping to the customer billing address" option.
It seems like your Checkout Block is not respecting Shipping settings where Shipping should be forced to the billing address - even with this option on the Block allows to provide alternative address and displays Shipping address as a main one. Can you clarify how this should be working?

### PR DESCRIPTION
**Pull request by tarunvijwani**
Hides the shipping address form from the Checkout when the `Force shipping to the customer billing address` is enabled.

Fixes woocommerce/woocommerce-blocks#7219

### Changes in the PR

- Added conditions to hide the shipping address form from the Checkout when the forced billing address is enabled. 
- Added the condition to update the billing address to the shipping address.
- Modified the condition to display the shipping methods.

### Screenshots

| Before | After |
| ------ | ----- |
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to `wp-admin/admin.php?page=wc-settings&tab=shipping&section=options` page.
2. Enable the `Force shipping to the customer billing address` option and save the changes.
3. Go Checkout block, and confirm shipping address form is not visible.
4. Change the billing address, confirm the shipping address in the order summary gets changed and shipping methods are updated. 

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Hide the shipping address form from the Checkout when the "Force shipping to the customer billing address" is enabled.

### CODE REVIEW

**Review by wavvves — APPROVED** [review]
Testing steps returned the expected behavior 🚢

**Review by tarhi-saad — APPROVED** [review]
Thank you, @tarunvijwani, for working on this PR! And thank you, @wavvves, for the review! I tested the PR as well, and it works as expected! I'll merge the PR since @tarunvijwani is AFK and this need to be ready for next week's release! 🙌

**Comment by tarhi-saad** [comment]
I checked the failed E2E and JS Lint tests, which seem unrelated to this PR. We can see the same JS lint error on previous commits. The failing E2E test is a flaky one. I've run it locally, and it passed successfully!

**Comment by ralucaStan** [comment]
@nielslange This might impact woocommerce/woocommerce#42623. Good to test this scenario as well.

**Pull request merged**
