### PR TITLE
Replace placeholder blockified templates with the right one

### PR DESCRIPTION
**Pull request by gigitux**
This PR replaces the placeholder blockified templates with the right one. This is necessary since we are working on enabling blockified template for the new stores.

1. Open the Site Editor.
2. Edit the Products by Attribute template.
3. Convert to the blockified template. 
4. Open the code editor.
5. Be sure that there isn't any difference with the `taxonomy-product_attribute.html` template except for the `<!-- wp:template-part -->`
6. Do the same for the `Products By Category` (file: `taxonomy-product_cat.html`) and `Products By Tag` (file: `taxonomy-product_tag.html`)

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by nefeline — COMMENTED** [review]
Hey @gigitux ! I have a few questions here:

- All of these templates are identical for the Products by Category, Products by Tag, and Products by attribute: the only difference is in the code level and is the `queryId`, why is that? 
- Shouldn't we display those as filtered out products, as mentioned on those templates description? In this shape and form, those templates don't differ much from the main Product Catalog (the only difference is really the additional "Term Description" text block).

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/4e6dd1be-16ef-44b0-b9f4-4b02ad6809f5

- I'm consistently getting the following error whenever I customize a template and restore it to its original state:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/13b80991-582a-481f-aeef-b13202fe9126

Is it a known issue?

**Comment by gigitux** [comment]
> * All of these templates are identical for the Products by Category, Products by Tag, and Products by attribute: the only difference is in the code level and is the `queryId`, why is that?

Good catch! The `queryId` isn't necessary. with [22a432c](https://github.com/woocommerce/woocommerce-blocks/pull/9579/commits/22a432c9f235f8ed34ff1e133c7653070061805a) I removed them. The `queryId` will be generated by the block at runtime https://github.com/WordPress/gutenberg/blob/e312f9c47dafc817a40a76f155ecce253bcb1675/packages/block-library/src/query/edit/query-content.js/#L72-L79

> Shouldn't we display those as filtered out products, as mentioned on those templates description? In this shape and form, those templates don't differ much from the main Product Catalog (the only difference is really the additional "Term Description" text block).

This is one of the limitations of extending the Query Loop block. We can't control the editor side if the block has the "Inherit query from template" enabled. I think that the new Products Collection block will fix this (cc @imanish003 @kmanijak )

> I'm consistently getting the following error whenever I customize a template and restore it to its original state:

It seems that you are using a development version of GB. Can you try without GB? In any case, it isn't related to this PR. Could you open an issue, please? 🙇

**Comment by nefeline** [comment]
> Good catch! The queryId isn't necessary. with [22a432c](https://github.com/woocommerce/woocommerce-blocks/pull/9579/commits/22a432c9f235f8ed34ff1e133c7653070061805a) I removed them. The queryId will be generated by the block at runtime https://github.com/WordPress/gutenberg/blob/e312f9c47dafc817a40a76f155ecce253bcb1675/packages/block-library/src/query/edit/query-content.js/#L72-L79

👍 

> This is one of the limitations of extending the Query Loop block. We can't control the editor side if the block has the "Inherit query from template" enabled. I think that the new Products Collection block will fix this

Gotcha, thanks for clarifying! Out of curiosity, do we have this documented somewhere? Maybe this was already discussed with @shaunandrews, but tagging here just in case (TL;DR: the Products by Attribute, Products By Category, and Products By Tag templates all display the same content and are almost identical to the Product Catalog) (cc @imanish003 @kmanijak )

> It seems that you are using a development version of GB. Can you try without GB? In any case, it isn't related to this PR. 

Is this a known limitation with the latest version of GB, then? I'm glad to open the issue, just wanted to double-check if you were aware of it and/or if we already had an issue opened to get us covered.

**Comment by gigitux** [comment]
> Is this a known limitation with the latest version of GB, then? I'm glad to open the issue, just wanted to double-check if you were aware of it and/or if we already had an issue opened to get us covered.

Not sure, I didn't have time to investigate. It could be depended by [this code](https://github.com/woocommerce/woocommerce-blocks/blob/4b27966dfaad0889956a25d98f8d13bb606722ba/assets/js/blocks/classic-template/index.tsx/#L340-L382).
We register/de-register the block based on the template. There could be something wrong with that logic.

**Comment by nefeline** [comment]
> Not sure, I didn't have time to investigate. It could be depended by [this code](https://github.com/woocommerce/woocommerce-blocks/blob/4b27966dfaad0889956a25d98f8d13bb606722ba/assets/js/blocks/classic-template/index.tsx/#L340-L382).
We register/de-register the block based on the template. There could be something wrong with that logic.

Gotcha, thanks! I did a few tests here, and as it turns out, this error occurs with and without having the GB plugin enabled. Opened https://github.com/woocommerce/woocommerce-blocks/issues/9637

**Comment by gigitux** [comment]
> > Not sure, I didn't have time to investigate. It could be depended by [this code](https://github.com/woocommerce/woocommerce-blocks/blob/4b27966dfaad0889956a25d98f8d13bb606722ba/assets/js/blocks/classic-template/index.tsx/#L340-L382).
> > We register/de-register the block based on the template. There could be something wrong with that logic.
> 
> Gotcha, thanks! I did a few tests here, and as it turns out, this error occurs with and without having the GB plugin enabled. Opened #9637

Thanks! Let me know if I can merge this PR 🙇

**Comment by nefeline** [comment]
> Thanks! Let me know if I can merge this PR 🙇

I re-ran all tests, and things in general are working as expected, although I'm noticing some differences between the template and the auto-generated code. For example, within the `taxonomy-product_tag.html` file, we have:

`<!-- wp:template-part {"slug":"header"} /-->`

`<!-- wp:template-part {"slug":"footer"} /-->`

And for the auto-generated code in the editor for the Products by Tag template we have:

`<!-- wp:template-part {"slug":"header","theme":"twentytwentythree","tagName":"header"} /-->`

`<!-- wp:template-part {"slug":"footer","theme":"twentytwentythree","tagName":"footer"} /-->`

Are we a-ok with those differences?

**Comment by gigitux** [comment]
> > Thanks! Let me know if I can merge this PR 🙇
> 
> I re-ran all tests, and things in general are working as expected, although I'm noticing some differences between the template and the auto-generated code. For example, within the `taxonomy-product_tag.html` file, we have:
> 
> `<!-- wp:template-part {"slug":"header"} /-->`
> 
> `<!-- wp:template-part {"slug":"footer"} /-->`
> 
> And for the auto-generated code in the editor for the Products by Tag template we have:
> 
> `<!-- wp:template-part {"slug":"header","theme":"twentytwentythree","tagName":"header"} /-->`
> 
> `<!-- wp:template-part {"slug":"footer","theme":"twentytwentythree","tagName":"footer"} /-->`
> 
> Are we a-ok with those differences?

Yeah, it is fine. This happens for all the templates that we have.

**Review by nefeline — APPROVED** [review]
> Yeah, it is fine. This happens for all the templates that we have.

Thanks for confirming! I'm approving, but I would also recommend updating the testing instructions for whoever is going to test this for the release, as right now, it states:

> Open the code editor.
> Be sure that there isn't any difference with the taxonomy-product_attribute.html template. 

And none of the templates are identical (theme content is injected in different areas, making them differ).

**Comment by kmanijak** [comment]
> Shouldn't we display those as filtered out products, as mentioned on those templates description? In this shape and form, those templates don't differ much from the main Product Catalog (the only difference is really the additional "Term Description" text block).

@nefeline
1. So the default look of those templates is the same (they are even handled by the same piece of code). However, the key point is that each of them can be customized separately.
2. In terms of filtering out products - that's interesting, however, what behavior would you expect in the editor? For example, do you think Products by Attribute should display products filtered by single attribue? If so, which one to choose while it's a generic template and only on the frontend the attribute (and respectively category/tag) is determined. I think displaying randomly chosen attribute/category/tag in the editor side may be confusing for the users.

> This is one of the limitations of extending the Query Loop block. We can't control the editor side if the block has the "Inherit query from template" enabled. I think that the new Products Collection block will fix this

Yes, "Inherit query from template" determines the query and we cannot control it. In terms of Product Collection it follows the same concept at the moment and I think that's expected - if the query is inherited, that's the setting we should respect, unless I'm misunderstanding this 🤔 

> Gotcha, thanks for clarifying! Out of curiosity, do we have this documented somewhere? Maybe this was already discussed with shaunandrews, but tagging here just in case (TL;DR: the Products by Attribute, Products By Category, and Products By Tag templates all display the same content and are almost identical to the Product Catalog) (cc imanish003 kmanijak )

I'm not aware of documentation - at the moment of blockifying the templates we recreated the structure of the classic template and Products by Attribute/Tag/Category had the same structure with the little differences to Product Catalog (like Term Description block).

Some of the limitations were gathered in pdnLyh-3rD-p2 (example: generic "Archive Title" rather than customized title, which is due to the fact of using a generic block from WC Core).

**Pull request merged**
