### PR TITLE
Convert to tsx and replace proptypes by ts definitions

### LINKED ISSUE #9526: Convert `editor-container-block.js` to `editor-container-block.tsx` and replace `propTypes` with TypeScript definitions
## Problem

[`assets/js/blocks/reviews/editor-container-block.js`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/reviews/editor-container-block.js) is a JS file and uses `propTypes` definitions.

## Expected outcome

1. Convert the file from `editor-container-block.js` to `editor-container-block.tsx`.
2. Replace `propTypes` with TypeScript definitions.

### PR DESCRIPTION
**Pull request by albarin**
Fixes woocommerce/woocommerce-blocks#9526

#### User Facing Testing

1. Create a new page or post.
2. Insert the `All Reviews`, `Reviews by product`, and `Reviews by category` blocks and save.
3. Smoke test them in the editor and in the front-end.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by roykho — DISMISSED** [review]
Smoke test seems good however I am seeing new TS errors generated as stated in the CI.

**Comment by albarin** [comment]
> Smoke test seems good however I am seeing new TS errors generated as stated in the CI.

Thanks for catching that! @roykho 
I've fixed all the previously introduced TS errors, but because of that, new errors are introduced in other **JS** files.
I'm not sure what to do with that since they are JS files 🤔

**Comment by roykho** [comment]
Can you please explain the reason to wrap `withReviews` with HOC? Also to get rid of the errors, perhaps also convert `with-reviews.js` to `tsx`?

Aside: I guess the initial GH action doesn't update even after you fix the TS errors? https://github.com/woocommerce/woocommerce-blocks/pull/10471#issuecomment-1665149311

**Comment by albarin** [comment]
> Can you please explain the reason to wrap `withReviews` with HOC? Also to get rid of the errors, perhaps also convert `with-reviews.js` to `tsx`?

I was getting this error:
Screenshot 2023-08-09 at 09 55 10
So I started to check other similar components with the `WrappedComponent` class to see if they had the same problem and realized they were using the `createHigherOrderComponent` function, which seems to be doing the same as [this](https://github.com/woocommerce/woocommerce-blocks/blob/d5f786e4721877c2e3c3fe2048808aecb51d95b5/assets/js/base/hocs/with-reviews.js#L212-L216) 
Screenshot 2023-08-09 at 09 59 45
and using it got rid of the error.

> Aside: I guess the initial GH action doesn't update even after you fix the TS errors? https://github.com/woocommerce/woocommerce-blocks/pull/10471#issuecomment-1665149311

I think the comment updates, those are not the same errors I had at the beginning I think.

**Review by Aljullu — COMMENTED** [review]
Code changes look good to me and it's testing well. Nice improvement!

Just a couple of comments:

1. I see this PR is marked as _Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9543_, however, `with-reviews.js` is still a JS file. Should we convert it to TS as @roykho mentioned? Or alternatively leave #9543 open.
2. I'm not 100% sure about using `createHigherOrderComponent()` in `with-reviews.js`. While it's true other HOCs in our codebase use it, they are HOCs only used on the editor side, while `with-reviews.js` is also loaded in the frontend. So we should try to add as few dependencies as possible. I tested and it's true that `wp-compose` is loaded anyway in the frontend when adding a Reviews block (I guess because it's a dependency of another dependency), but even in that case, I think that if we can avoid using it, it might be better. What do you think?

**Comment by albarin** [comment]
@Aljullu 
1. Yep, I'll change the `Fixes` in the PR
2. Tbh, I don't completely remember because it was months ago, but I think I only changed that because I entered a rabbit hole of TS errors, I don't completely get what is going on there 😅 I'll revert that. I don't know, maybe it's better to close this PR, seems too convoluted and I'm very out of context now.

**Comment by Aljullu** [comment]
> Tbh, I don't completely remember because it was months ago, but I think I only changed that because I entered a rabbit hole of TS errors, I don't completely get what is going on there 😅 I'll revert that. I don't know, maybe it's better to close this PR, seems too convoluted and I'm very out of context now.

That's up to you! :smile:  But besides the `wp-compose` dependency, all the other changes in this PR look good to me and would be great if they get merged. But definitely not something urgent.

**Comment by albarin** [comment]
@Aljullu Okay, I've reverted the `with-reviews` file and everything seems to work fine, could you please give it another go? 🙏

**Review by Aljullu — APPROVED** [review]
LGTM, thanks @albarin! :ship:

**Pull request merged**
