### PR TITLE
Use shared save function for all the product elements blocks

### PR DESCRIPTION
**Pull request by kmanijak**
This PR removes the not used save function for each product element block. Also, I updated the logic to support the Single Product Template

#### User Facing Testing

1. Open a post/page editor and add a Products Block.
2. Be sure that you don't see any error regarding the save function in the console.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

Description updated by @gigitux

### CODE REVIEW

**Comment by kmanijak** [comment]
@gigitux , shouldn't the `save` function be imported in each of the product elements and provided to blockConfig? Otherwise, it's simply not used or there's some mechanism that does that under the hood which I'm not aware of.

I'm happy to do so, but I'd like you to confirm first 👍

**Comment by gigitux** [comment]
> @gigitux , shouldn't the `save` function be imported in each of the product elements and provided to blockConfig? Otherwise, it's simply not used or there's some mechanism that does that under the hood which I'm not aware of.
> 
> I'm happy to do so, but I'd like you to confirm first 👍

All the product elements imported [the sharedConfig object](https://github.com/woocommerce/woocommerce-blocks/blob/070b8fc20176daf469547a4abbdca4af4a593d06/assets/js/atomic/blocks/product-elements/button/index.ts/#L21-L22). And this object uses the save function that I updated.

**Review by albarin — APPROVED** [review]

**Comment by kmanijak** [comment]
@gigitux, one more question to this one, did you leave other Save (on a couple of blocks) functions on purpose, and if so I'm curious why? For example `title` or `summary` blocks? Or can they be removed?

**Comment by gigitux** [comment]
Title and Summary blocks aren't used in the Products block and Single Product Template. (we use a variation from the core block).

I think that I forgot to remove the old save function from the `stock-indicator` block. I will create a PR for this!

**Comment by gigitux** [comment]
@kmanijak I created #8832

**Pull request merged**
