### PR TITLE
Update pattern with images and alignment

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce-blocks/pull/9269

This PR converts the work from above PR that was initially using the product category blocks into using WP core blocks.

#### User Facing Testing

1. Create a page and use the block inserter->patterns->WooCommerce and to insert the Featured Category Triple pattern.
2. Check that the preview shows up nicely and add the pattern to the page.
3. Update/save and check the frontend and ensure it is displaying nicely per design.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Update featured category triple pattern

### CODE REVIEW

**Comment by roykho** [comment]
Noting this should skip testing as this PR is just to fix unreleased changes from https://github.com/woocommerce/woocommerce-blocks/pull/9340

**Review by imanish003 — APPROVED** [review]
Great job! 🚀 Thank you for enhancing this pattern 🙌🏻
By the way, I noticed that the Sprint and Epic fields are empty. Was that done intentionally? 🙂

**Review by kmanijak — COMMENTED** [review]
I was about to merge the changes to include it in the release, but I spotted the indentations are removed from the `patterns/featured-category-triple.php` file. Is that the intended change?

**Comment by roykho** [comment]
@imanish003 - yes that is intentional because if you read my comment above, this is just a fix for an already existing addition to the pattern https://github.com/woocommerce/woocommerce-blocks/pull/9340 which has the sprints and epics. We don't want to have duplicate PRs in this context.

@kmanijak - yes that is also intentional because there may be several rounds of changes and it became very tedious to indent them every time we made a change. So I think we could do that later when everything is settled to all patterns at once.

**Pull request merged**
