### PR TITLE
Add explicit CSS styling to mini-cart block amount in inserter preview

### LINKED ISSUE #7750: Mini Cart block: preview only displays the icon, not the price
Price is missing in the Mini Cart block preview.

## To reproduce

1. Create a post or page and open the inserter.
2. Hover the Mini Cart icon.
3. Notice in the preview, the Mini Cart block is rendered, but the price is not visible.

imatge

## Expected behavior

We should display the block as similar as possible to the way it will render. In this case, displaying a price next to the icon.

imatge

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/7750

~~This PR adds a class name to `noninteractive` component block so future blocks can style elements easier with certain level of specificity.~~ Added CSS style targeting the preview for mini cart amount element so that it isn't hidden when shown in the inserter preview.

#### User Facing Testing

1. Create a new page.
2. Click on the `inserter` plus icon/button.
3. In the search bar, search for `mini cart`.
4. Hover your mouse over the `mini cart` block icon.
5. Ensure you see the cart dollar amount in the preview.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix Mini Cart block inserter preview not showing the cart amount.

### CODE REVIEW

**Review by kmanijak — COMMENTED** [review]
It tests well with the preview, but there's one thing I noticed in Editor.

The amount was hidden for the screens smaller than 768px ([PR](https://github.com/woocommerce/woocommerce-blocks/issues/4907)) and that was happening in Editor and FE. Your changes affect not only a preview but also the Editor view, so there's this inconsistency, that in Editor the amount is visible no matter the screen size.

Video without your changes:
https://user-images.githubusercontent.com/20098064/221597475-caf43ece-2c6e-4fb8-9b30-f5644eecfcc9.mov

One option that comes to my mind is to use `:not(.editor-styles-wrapper)` class to exclude the Editor view.
Or maybe it's possible to pass a custom class specifically for a preview ([here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/mini-cart/index.tsx#L47)). In such a case there would be no need to touch `noninteractive` element. But I'm not sure if that's gonna work that way though.

**Comment by roykho** [comment]
Yeah I've already previously tried `.editor-styles-wrapper` and `isPreview` attribute however it doesn't work because in the editor context both of those are true and not just in the preview container. I've also tried targeting `.block-editor-inserter__preview-container` class but for some reason that doesn't work as well.

So the only thing I can think of to get around this is use an image preview instead of rendering it. What do you think?

**Comment by kmanijak** [comment]
Apologies for the poor explanation earlier, what I meant was something like this: [draft PR](https://github.com/woocommerce/woocommerce-blocks/pull/8566). To be honest I didn't know it would work, so I tried that myself and it was easier to show with an example 😅 so basically pass the custom `className` only when in preview. In such a case you don't need to touch the Noninteractive, which I think is pretty invasive compared to the use case.

What do you think about such an approach? It influences a preview but leaves the Editor view untouched 🙌

**Comment by roykho** [comment]
I like that! I didn't even know you can add custom class names to just the preview section. Updated PR thanks!

**Review by kmanijak — APPROVED** [review]
Works great! 💪

**Pull request merged**
