### PR TITLE
Add theme-level global styles to Cart and Checkout block

### LINKED ISSUE #8710: Add theme-level global styles to Cart and Checkout block
We're enabling the theme-level global styles in Cart and Checkout blocks. 

This epic aims to ensure that both the Cart and the Checkout block fully support the theme-level and WCBlocks-level global styles in the editor and front end.

```[tasklist]
## Theme Level Styles » Cart
- [ ] #8976
- [ ] #8711
- [ ] #8712
- [ ] #8750
- [ ] #8751 
- [ ] #8713
- [ ] #8828
- [ ] #8571
- [ ] #8752
```

```[tasklist]
## Theme Level Styles » Checkout
- [ ] #8976
- [ ] #8811
- [ ] #8810
- [ ] #8807
- [ ] #8806
- [ ] #8808
- [ ] #8826
- [ ] #8571
- [ ] #8858
- [ ] #8752
```

```[tasklist]
## WC Block Level Styles » Cart
- [ ] #8829
- [ ] #8830
- [ ] #8831
- [ ] #8827
```

```[tasklist]
## WC Block Level Styles » Checkout
- [x] There are no tasks for `WC Block Level Styles » Checkout`.
```

### PR DESCRIPTION
**Pull request by tarunvijwani**
Fixes #8710

With this PR, we're enabling the theme-level global styles in Cart and Checkout blocks.

## Changes in the PR
- [Fix link padding in TT3.](https://github.com/woocommerce/woocommerce-blocks/pull/8908)
- [Cross-Sells block: Replace AddToCartButton  with ProductButton.](https://github.com/woocommerce/woocommerce-blocks/pull/8914)
- [Add GS support for headings typography in Checkout block.](https://github.com/woocommerce/woocommerce-blocks/pull/8918)
- [Ensure Checkout block supports the theme-level global styles for Typography » Buttons](https://github.com/woocommerce/woocommerce-blocks/pull/8892)
- [Remove classname from cart image to avoid conflicts.](https://github.com/woocommerce/woocommerce-blocks/pull/8898)
- [Use consistent and semantically correct HTML elements in the Cart and Checkout blocks. ](https://github.com/woocommerce/woocommerce-blocks/pull/9065)
- [Ensure Checkout block supports the theme-level global styles for Colors » Buttons](https://github.com/woocommerce/woocommerce-blocks/pull/8844)

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Install and activate a block theme, e.g. [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/).
2. Create a test page with the Checkout block.
3. Create a test page with the Cart block.
4. Go to `WP Admin` » `Apperance` » `Editor.`
5. Open the Styles sidebar.
6. Adjust all `Typography ` and `Color` settings. 
7. Go to the Checkout block page editor.
8. Confirm Global styles are applied successfully. 
9. Go to the Cart block page editor.
10. Confirm Global styles are applied successfully. 
11. Navigate to Cart and Checkout block page on the front-end. 
12. Confirm Global styles are applied successfully.

* [ ] Do not include in the Testing Notes 

## Screen recording:

https://user-images.githubusercontent.com/11503784/233148708-6bb9846b-4d47-457c-8c61-f8a0205809bf.mov

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add theme-level global styles to Cart and Checkout block

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
I didn't review the code, but after some smoke testing I noticed:

### Color

1. Cart and Checkout: buttons can be hovered and they lose their style. This happens both, in the editor and the frontend:

[Enregistrament de pantalla des de 2023-04-20 19-29-19.webm](https://user-images.githubusercontent.com/3616980/233443153-2056e1ac-3a7d-4c87-b668-5f00ad91911b.webm)

2. Cart & Checkout: link color seems to work in the editor, but not the frontend:

Editor | Frontend
--- | ---
imatge | imatge

3. Checkout: heading background is full-width in editor but smaller in the frontend:

Editor | Frontend
--- | ---
imatge | imatge

### Typography

4. Checkout: heading appearance (italics and bold) is not respected in the editor:

Editor | Frontend
--- | ---
imatge | imatge

5. Cart and Checkout: heading line-height is not respected.
6. Checkout: text appearance (italics and bold) is not respected in the editor:

Editor | Frontend
--- | ---
imatge | imatge

Besides that, everything else seemed to be working well. :ok_hand:

**Comment by nielslange** [comment]
Thanks for your review, @Aljullu! 🙌 @tarunvijwani asked me if I can take care of this PR given that he's on porter rotation. 

The following issues, which you reported, are related to the TT3 theme: 

- Cart and Checkout: buttons can be hovered and they lose their style. This happens both, in the editor and the frontend.
- Cart & Checkout: link color seems to work in the editor, but not the frontend.
- Cart and Checkout: heading line-height is not respected.

> **Note**
> If you're using a different theme, e.g. [Beaumont](https://andersnoren.se/teman/beaumont-wordpress-theme/) or [Tove](https://andersnoren.se/teman/tove-wordpress-theme/), these issued no longer appear.

The following issues have been fixed:

- Checkout: heading background is full-width in editor but smaller in the frontend.
- Checkout: heading appearance (italics and bold) is not respected in the editor.
- Checkout: text appearance (italics and bold) is not respected in the editor.

## Screenshot

Screen Shot 2023-04-21 at 15 36 43

In the screenshot, you might notice that the `Country/Region` field in the style editor (and also in the post editor), is shorter than the other fields. I thought that this PR might have caused it, but I'm seeing the same problem in `trunk`.

**Review by Aljullu — COMMENTED** [review]
Thanks for the update, @nielslange!

I did another round of testing and couldn't find anything besides what has already been mentioned.

> The following issues have been fixed:

Confirming this. :ok_hand:

**Review by mikejolley — APPROVED** [review]
Smoke tested and seems to be in order, however I spotted one visual issue that may require a follow up.

With headings on the checkout, if you increase font size you'll see some abnormalities:

Screenshot 2023-04-21 at 15 41 33

And in editor:

Screenshot 2023-04-21 at 15 41 55

Approving anyhow.

**Comment by tarunvijwani** [comment]
@mikejolley Thank you for reviewing the PR. I have created a new ticket to tackle this problem in the sprint: https://github.com/woocommerce/woocommerce-blocks/issues/9164.

**Comment by tarunvijwani** [comment]
Markdown and Playwright tests are getting failed. Asked for confirmation to merge the PR: p1682089388117269-slack-C02UBB1EPEF

**Pull request merged**
