### PR TITLE
Fix: Spilled icecream error with Filter Products by Attribute when no attribute was selected

### LINKED ISSUE #2441: Spilled icecream (js error) with Filter Products by Attribute when store has no attributes
### To reproduce
- Ensure your store has no product attributes set up.
- Add a `Filter Products by Attribute` block to a page or post, publish.
- View on front end - javascript error: `TypeError: Cannot read property 'id' of undefined`

We probably need some checks to render nothing / placeholder if the store has no attributes.

### PR DESCRIPTION
**Pull request by dinhtungdu**
This PR:
- Fixes the Spilled ice cream error on the front end when the site has no attribute or no attribute was selected for the block.
- Adds a warning in the editor when users didn't select any attribute.
- Adds a warning in the editor when the site doesn't have any attribute term assigned to products.
- Prevents flashing title on the front-end if the users didn't select attribute or the site doesn't have any term assigned.
- Fixes the preview error when previewing the block without selecting any attributed, see https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2441#issuecomment-927318176.

Fixes #2441

### Screenshots
New warning messages:

image

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Adding a new Filter by Attribute block.
2. Click `Save` button without selecting any attribute.
3. See the warning message.
4. Edit the block, select an attribute that isn't assigned to any product.
5. See the warning message.

### Changelog

> Fix: Render error of Filter by Attribute block when no attribute was selected.

### CODE REVIEW

**Review by tjcafferkey — APPROVED** [review]
This tests well for me and code changes look good. However there's a conflict that will need resolving now.

**Comment by dinhtungdu** [comment]
@tjcafferkey I'm sorry for the late reply! I fixed the merge conflict. Can you take another look at this?

**Comment by tjcafferkey** [comment]
@dinhtungdu LGTM 😄  thanks for solving the conflict.

**Comment by haszari** [comment]
Nice to see this get fixed, thanks team! 🙌

**Pull request merged**
