### PR TITLE
Fix/cart button focus hover states

### PR DESCRIPTION
**Pull request by tarhi-saad**
This PR is intended to fix this issue #5647. The cart and mini-cart buttons didn't have hover & focus styles.

Our WC Block Button component is based on [Gutenberg's button](https://wordpress.github.io/gutenberg/?path=/story/components-button--buttons). The package name is [@wordpress/components](https://www.npmjs.com/package/@wordpress/components). This package's latest version displays a correct hover & focus style on the button component, but we are using an old version. We faced some issues with the bundle size of the newer versions because they include some libraries we don't need.

So, the solution is to set our focus and hover style for now. 

The latest Gutenberg's Button component introduced the `variant` attribute for "text", "contained" and "outlined" buttons. And since we are using an older version of this component that doesn't have this attribute, and we are already using the "contained" and "outlined" buttons in our plugin, implementing it on our end seems to be a good idea.

### Screenshots

Default state (filled button)
:-------------------------:
image 

Hover state (filled button)
:-------------------------:
image

Focus state (filled button)
:-------------------------:
image

Default state (outlined button)
:-------------------------:
image

Hover state (outlined button)
:-------------------------:
image

Focus state (outlined button)
:-------------------------:
image

### TODOS

- [X] Introduce the `outlined button` and replace the mini-cart custom styles

### Manual Testing

1. Checkout the branch
2. Create test pages for cart, mini cart, and checkout blocks.
3. In each page check the hover and focus styles for the `View my cart`, `Got to checkout`, `Proceed to Checkout`, and `Place Order` buttons.
4. You can do the same test using the available default themes and the Strofront theme as well.
### Changelog

> Fixed hover and focus states for button components

### CODE REVIEW

**Comment by mikejolley** [comment]
@tarhi-saad Not sure if this is ready for review but if so, please convert from draft to PR and add the "Needs Review" label. Cheers!

**Comment by tarhi-saad** [comment]
> @tarhi-saad Not sure if this is ready for review but if so, please convert from draft to PR and add the "Needs Review" label. Cheers!

Hi @mikejolley, this PR is now ready for review!

**Review by mikejolley — COMMENTED** [review]
Hover states work like a charm, good job. I tested cart, checkout, mini-cart.

The only issue I spotted which might be nice to fix our side, the outlined buttons are ever so slightly taller due to the border:

Screenshot 2022-02-08 at 15 41 49

Can we maybe fix this with an inner shadow instead of a border, or some padding changes?

**Review by mikejolley — APPROVED** [review]
Thanks, looks good now.

**Pull request merged**
