### PR TITLE
Fixed Price Slider Issue

### LINKED ISSUE #7130: Slider of Price filter block should use currentColor instead of a hard-coded color
## Describe the bug

When the Price filter block is added on a dark background, the slider can't be seen.

## To reproduce

1. Add the Filter by Price and All Products blocks inside a Columns block into a post or page.
2. Change the background color of the Filter by Price column to a dark color. Change the text color to a light color.
3. Notice the price slider is no longer visible.

## Expected behavior

That's because we have some hard-coded styles in the slider. Ideally, we should default to [`currentColor`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword).

### PR DESCRIPTION
**Pull request by EmptySet-Exe**
Fixes #7130 

Located where the price slider was hard coded and replaced it.

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | 
| ------ |
price-slider-before

| After | 
| ------ |
price-slider-after

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Create a product
2. Insert WooCommerce Price Filter Block
3. Adjust slider as needed

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by gigitux** [comment]
Hi!
Thanks for opening the PR! Could you update the description and add the corresponding issue number: https://github.com/woocommerce/woocommerce-blocks/issues/7130?

Also, it seems that there is a problem with the CSS linter. Could you fix this? You can find more details [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/contributing/getting-started.md#linting).

**Comment by gigitux** [comment]
Hi @EmptySet-Exe, are you still working on this PR?

**Comment by EmptySet-Exe** [comment]
Yes, I still am working on this PR. Thank you for removing the `stale` label.

**Comment by Aljullu** [comment]
Hey @EmptySet-Exe, thanks for working on this! We would like to include this fix in a release we will do on Monday, in order to get prepared for WordPress 6.1 and the new theme Twenty Twenty Three. Do you think you will have time to update this PR before then? Otherwise, somebody from our team can help with that. Reviewing the code, the diff included in this PR should be +1/-1 line, because all other changes seem to be style related.

Thanks in advance!

**Comment by Aljullu** [comment]
Closing given that this has already been fixed in #7527, which includes some commits from this PR. Thanks for your help @EmptySet-Exe!

**Pull request closed without merging**
