### PR TITLE
Rename Active Product Filters block to Active Filters

### PR DESCRIPTION
**Pull request by Aljullu**
#### User Facing Testing

1. Create a post or page and open the block inserter.
2. Search for _active_.
3. Verify there is a block named _Active Filters_ (and there isn't one named _Active Product Filters_).

Screenshot showing the Active Filters block in the inserter

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Rename Active Product Filters block to Active Filters

### CODE REVIEW

**Comment by thealexandrelara** [comment]
Hey @Aljullu,I was testing here and I realized that we have a test file in`tests/e2e/specs/backend/__fixtures__/active-product-filters.fixture.json`, do you think we should rename it to `active-filters.fixture.json`? 

We also have a classname `wc-block-active-product-filters__placeholder` being used/referred to in the following files:
```
assets/js/blocks/active-filters/index.tsx
docs/internal-developers/testing/smoke-testing.md
patterns/filters.php
tests/e2e/specs/backend/__fixtures__/active-product-filters.fixture.json
```

Just confirming with you if we should also edit inside the code to keep consistency with the new block name, or this is not necessary?

**Comment by Aljullu** [comment]
Good catch, @thealexandrelara! This should have been fixed in the last two commits.

**Review by thealexandrelara — APPROVED** [review]
Great work! LGTM! ✅

**Comment by Aljullu** [comment]
Thanks for the reviews @thealexandrelara!

Merging because e2e tests failing seem to be unrelated and they are failing in `trunk` too.

**Pull request merged**
