### PR TITLE
Store Customization > Add default image to Just Arrived pattern

### LINKED ISSUE #11091: Store Customization > Add default image to the Just Arrived Full Hero pattern
Ensure the **Just Arrived Full Hero** pattern has a default image that matches the design on figma: Mrk6SERPZ4KrFHSjM0a8TK-fi-1406_128003

Screenshot 2023-10-02 at 17 43 09

### PR DESCRIPTION
**Pull request by tjcafferkey**
## What

Adds default image and height to the Just Arrived pattern. Note that we could not use the same image as displayed in the related issue due to licensing.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11091

## Why

All patterns need a default image which may (or may not) be replaced by AI, the pattern design also had a fixed height.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new post and add the pattern "Just Arrived Full Hero"
2. Check that it looks like the below screenshots on both desktop and mobile viewports both in the editor and on the frontend.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Desktop | Mobile |
| ------ | ----- |
| Screenshot 2023-10-04 at 14 21 14 | Screenshot 2023-10-04 at 14 21 28 |

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add default image and fixed height to the Just Arrived Full Hero pattern.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
@nefeline should we add a default URL to the "Shop now" button?

**Review by nefeline — APPROVED** [review]
LGTM! 🚀

**Comment by nefeline** [comment]
> should we add a default URL to the "Shop now" button?

Just saw the question after approving the PR, but yes, it makes sense!

**Comment by tjcafferkey** [comment]
Not sure if you would like to re-review this @nefeline but I've added the link to the button here https://github.com/woocommerce/woocommerce-blocks/pull/11130/commits/5263e167d701f89f0843bc6e3e0f8525b2ca4398

**Review by nefeline — APPROVED** [review]
I tested again and confirmed the shop button works as expected 🎉 !

**Pull request merged**
