### PR TITLE
Lockfile Maintenance

### PR DESCRIPTION
**Pull request by danielwrobert**
Irons out lockfile updates to keep a clean working tree on a new `npm install`.

### Testing

1. Re-install packages (`npm install`)
2. Confirm `package-lock.json` file does not have any changes after packages are installed.
3. Run environment (`npm run build` and `npm start`) to confirm everything is still working as expected.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by alexflorisca — APPROVED** [review]
Nice one, was just about to do this, looks like this fixes the linting action failures as well :)

**Review by alexflorisca — CHANGES_REQUESTED** [review]
I just notices the the Check Modified assets actions fails because of a missing package `rimraf`. Think we need to fix that before we merge this

**Comment by danielwrobert** [comment]
> I just notices the the Check Modified assets actions fails because of a missing package `rimraf`. Think we need to fix that before we merge this

@alexflorisca I re-ran all of the checks and it seems like they're all passing now. Perhaps that was a fluke? I've had this happen before with the Check Modified Assets test.

Rebasing now so I may have to iron out the tests/checks again before it's ready.

**Review by alexflorisca — APPROVED** [review]
Green means go!

**Comment by danielwrobert** [comment]
Thanks for the review @alexflorisca! 🍻

**Pull request merged**
