### PR TITLE
Add `Customer account` to patterns

### LINKED ISSUE #7654: Add the `My Account` block to the footer patterns

### LINKED ISSUE #7655: Add the `My Account` block to the header patterns

### PR DESCRIPTION
**Pull request by albarin**
This PR introduces the new `Customer account` block into the WooCommerce header and footer patterns.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/7654
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/7655

#### User-Facing Testing
1. Create a new page and add all the `WooCommerce Header` patterns in their two versions (light and dark).
2. Save the page and check the `Customer Account` block shows as expected on the designs: 
CdRRBQ50zJiDvnY3AbDiXd-fi-76%3A9726
4. Repeat for all the `WooCommerce Footer` patterns (light and dark).

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add "Customer Account" block to header and footer patterns.

### CODE REVIEW

**Review by thealexandrelara — APPROVED** [review]
Great work! LGTM!

**Comment by vivialice** [comment]
Hey! 👋  These are looking great so far. I just noticed some improvements on mobile we should try and make. 

For this pattern it might work better to show the icon only. 

_Before:_
Screenshot 2022-12-15 at 12 28 11
_After changing the setting:_ 
Screenshot 2022-12-15 at 12 36 47

The mini cart block is dropping on the iPhone SE screen size, perhaps we can tweak the items a bit to make it sit with the customer account block? 
Screenshot 2022-12-15 at 12 28 46

Another note on the icon sizing. Generally they are looking really good but I am noticing an imbalance with the mini cart block. Can we make the rounded one a bit bigger? We might want to add controls to manage the icon sizing like we do in the mini cart in the next iteration. 

Screenshot 2022-12-15 at 12 38 14

Screenshot 2022-12-15 at 12 38 26

**Comment by albarin** [comment]
Thanks for your feedback @vivialice! I addressed it, adjusted the size of the rounded icon, made them resize with the fontSize setting (like mini-cart does), and changed the displayStyle for the Header Essential.
Can you pull the changes and do another review? 🙏

**Comment by vivialice** [comment]
Thanks @albarin ! 

Just did a review and the resize option is working well. Bringing our conversation over from Slack, I was wondering if we could look into decoupling the size of the icon alongside the text. I understand the mini cart icon and price also works like this but it would improve the UX if we could have a separate control, as the user wouldn't realize they can edit the `icon-only` option with text sizing controls. 

And a quick note on this pattern: 
Screenshot 2022-12-19 at 11 20 56

I increased the padding to `32px` `top` and `bottom` which looks a bit better. 

I also tried playing with the layout controls, adding/removing `rows` but I can't get the icons to align to the right on mobile view. It's especially frustrating in this layout where there's visually plenty of space. 

Screenshot 2022-12-19 at 11 24 54

Is there anything we can try?

**Comment by albarin** [comment]
@vivialice I increased the padding to 32px and aligned the second row with the customer account and the mini-cart to the right. Let me know what you think!

**Pull request merged**
