### PR TITLE
Fixed newly detected broken links

### LINKED ISSUE #9626: Optimise `Check Markdown links` GitHub Action
In #9625, I mentioned the following:

> While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files. In addition, I noticed that the GitHub Action, to check for broken links in Markdown files, runs independent if the PR touches Markdown files or not.

This issue aims to apply the following changes to the `Check Markdown links` GitHub Action:

- Remove `max-depth: 3`to detect broken links in all Markdown files
- Remove `use-verbose-mode: ‘no’`, as `no` is the default value, see [configuration](https://github.com/gaurav-nelson/github-action-markdown-link-check/#configuration)
- Exclude Markdown files in `./docs/internal-developers/testing/releases/`

### LINKED ISSUE #9627: Fix newly detected broken links
In #9625, I mentioned the following:

> While creating https://github.com/woocommerce/woocommerce-blocks/pull/9622, I noticed that the GitHub Action to check links within Markdown files only goes 3 levels deep. As some of our Markdown files are located deeper than three levels, we would not detect broken links in these files. In addition, I noticed that the GitHub Action, to check for broken links in Markdown files, runs independent if the PR touches Markdown files or not.

This issue aims to fix all newly detected broken links, once #9626 has been merged.

### PR DESCRIPTION
**Pull request by hritikchaudhary**
Fixes #9626
Fixes #9627 

### Changes in the PR:
- This PR aims to fix all newly detected broken links
- This PR is based on the branch of #9633 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by nielslange — CHANGES_REQUESTED** [review]
Thanks for working on this, @hritikchaudhary. I noticed that you updated the following files:
- docs/third-party-developers/extensibility/hooks/actions.md
- docs/third-party-developers/extensibility/hooks/filters.md

You couldn't know that, but these files are automatically generated by the following files:
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/hook-docs/actions/index.js
- https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/hook-docs/filters/index.js

Instead of changing actions.md and filters.md directly, we should ensure that the files are generated with the correct links.

**Comment by hritikchaudhary** [comment]
Sure, I'll look into it, I was not aware about that.

**Comment by nielslange** [comment]
> Sure, I'll look into it, I was not aware about that.

Thanks for looking into this. I was certain that you weren't aware of that. That's why I mentioned it. 😀

**Comment by hritikchaudhary** [comment]
Hi @nielslange I fixed the underlying problem and generated docs using `npm run build:docs` to check. it is fixed and there are no dead links, but a lot of docs got generated should I push the docs as well or only the fixed js files?

**Comment by nielslange** [comment]
> Hi @nielslange I fixed the underlying problem and generated docs using `npm run build:docs` to check. it is fixed and there are no dead links, but a lot of docs got generated should I push the docs as well or only the fixed js files?

You can add both, the updated *.js files as well as the updated docs files, @hritikchaudhary.

**Comment by hritikchaudhary** [comment]
Done... there were some duplicated content in some docs due to missing opening `<!-- FEEDBACK -->` comment which caused `npm run build:docs` command to generate duplicated section, fixed that.

Please note this branch is based on optimise-check-dead-links-action branch from #9633 so merging this will also resolve that.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @hritikchaudhary. All the changes look good. As this PR touches files from various areas of this repo, I requested a second review from @kmanijak from the @woocommerce/woo-fse team.

While the description says _"This PR is based on the branch of #9633"_, the PR had been created against `trunk` instead of against #9633. Therefore, merging this PR will not only fix #9627 but also #9626.

**Review by kmanijak — APPROVED** [review]
I checked the PR and it looks good. I'm happy we have MD files linted in a unified way! 🙌

**Comment by nielslange** [comment]
Thanks for your review, @kmanijak, and thanks again for working on these issues, @hritikchaudhary! 👏

**Pull request merged**
