### PR TITLE
Fix Markdown table in payment-method-integration.md

### PR DESCRIPTION
**Pull request by szepeviktor**
### Description
Fix the incorrect formatting in the [Payment Method Integration for the Checkout Block](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md) - table is not rendering correctly in the [Props Fed to Payment Method Nodes](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#props-fed-to-payment-method-nodes) section

This PR contains whitespace changes only.

### Screenshots
| Before | After |
| ------ | ----- |
|    image   |.   image | 

### Testing steps
- Before: check the table on `trunk`: [before](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#props-fed-to-payment-method-nodes)
- After: check the table in this PR: [after](https://github.com/woocommerce/woocommerce-blocks/blob/7e39f49632742d1b88a9f390219433217b775158/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#props-fed-to-payment-method-nodes) 😍 

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by kmanijak** [comment]
Hi @szepeviktor! That's a great contribution, thank you so much that you took a time to prepare it! 🙏 

Usually, when preparing a PR, we use the standard template that shows up when opening the PR. We apply that to all the types of PRs, even the smallest ones. That allows us to have a better understanding of what PR contains and keep a better history of the changes. Having said that, I hope you don't mind, that I allowed myself to extend the description, so it follows the standard template. 🙌 

At the same time it's so great you spotted the issue with the table and took action to fix that, we're grateful you did that!

I'll make sure the branch is up-to-date and will do the final review when all the checks will pass.

**Comment by szepeviktor** [comment]
@kmanijak Yes, it was hard to fix the Markdown table. I ran out of energy for PR documentation.

**Comment by nefeline** [comment]
Hi @szepeviktor : thank you so much for your contribution! We are investigating why some of the required checks are failing for this PR. We will post an update here as soon as everything is a-ok.

**Comment by szepeviktor** [comment]
Thank you Patricia!

**Comment by szepeviktor** [comment]
Meanwhile it was fixed in https://github.com/woocommerce/woocommerce-blocks/commit/61370e6e3ab3d83d1d4ccd1bb774c2fe57c1c9d2

**Comment by nefeline** [comment]
Hi @szepeviktor ! Our sincere apologies: the reason why your work here took so long to be merged is because it sparked an important internal discussion regarding how to handle CI tests in forked repositories, considering some of them are failing by default due to authentication problems, as visible here. In the end, your contribution had an impact even more significant than updating the markdown on `payment-method-integration.md`: thanks again for your work!

Your commit here was cherry-picked, the conflicts solved and merged on #8258

**Pull request closed without merging**
