### PR TITLE
Remove experimental flag from Cross-Sells block

### LINKED ISSUE #6965: Remove experimental flag from Cross-Sells block
Currently, the Cross-Sells block is located behind an experimental flag to prevent that the block accidentally becomes visible when someone is using the featured plugin. Once the Cross-Sells block had been fully tested and is ready to be launched, the experimental flag needs to be removed. 

When removing the experimental flag, the following sections need to be updated:

https://github.com/woocommerce/woocommerce-blocks/blob/84950e6188c451d522a7ce614f77272362575d37/assets/js/blocks/cart/inner-blocks/cart-cross-sells-block/index.tsx#L13-L24

https://github.com/woocommerce/woocommerce-blocks/blob/84950e6188c451d522a7ce614f77272362575d37/assets/js/blocks/cart/inner-blocks/cart-items-block/edit.tsx#L26-L28

https://github.com/woocommerce/woocommerce-blocks/blob/ba24ab7674cb8a2f1136277c2cf2103792eae0e7/assets/js/blocks/cart/inner-blocks/register-components.ts#L64-L86

https://github.com/woocommerce/woocommerce-blocks/blob/ba24ab7674cb8a2f1136277c2cf2103792eae0e7/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md?plain=1#L59

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #6965

### Note

To prevent that the Cross-Sells block accidentally gets shipped with the WooCommerce Blocks plugin and gets merged into the WooCommerce core, the block had been placed behind an experimental flag. This PR aims to remove the experimental flag, so that the Cross-Sells block becomes available both when using the WooCommerce Blocks and the WooCommerce plugin.

### Testing

1. Run `npm run build`.
2. Replace the content of`blocks.ini` with the following config:
```
woocommerce_blocks_phase = 1
woocommerce_blocks_env = production
```
3. Create a test page and add the Cart block.
4. Verify that the Cross-Sells block is visible on the Cart block both in the editor and in the frontend.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by wavvves** [comment]
Hey Niels, I ran into a problem testing this, when trying to add the cart to a test page:

image

image

Adding the cart works when shifting to trunk and rebuilding stuff.

**Comment by nielslange** [comment]
> Hey Niels, I ran into a problem testing this, when trying to add the cart to a test page:
> 
> image
> 
> image
> 
> Adding the cart works when shifting to trunk and rebuilding stuff.

@wavvves Somehow, I deleted the `save` function with my initial commit. I can't explain how this happened, but I just re-added it, and you should now be able to see the Cart block, as expected.

**Review by wavvves — APPROVED** [review]
~~It's working now 🚢 it :)~~ good catch @tarhi-saad

**Review by tarhi-saad — APPROVED** [review]
Excellent job, @nielslange! 🙌 Let's 🚢 it!

**Pull request merged**
