### PR TITLE
[Patterns]: Add new `Header: Simple Row` pattern

### LINKED ISSUE #9036: Create `Header: Simple Row` pattern
Simple Row

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33046 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by albarin**
This PR implements the `Header: Simple Row` pattern.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9036

#### User-Facing Testing

1. Create a new page or post
2. Make sure the `WooCommerce Header Simple Row` pattern appears under the WooCommerce category dropdown.
3. Insert in and make sure it shows as expected on the design.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add the new `Header: Simple Row` pattern.

### CODE REVIEW

**Comment by albarin** [comment]
@shaunandrews for now I'm using the pattern name in the designs for the title, in this case, `WooCommerce Header Simple Row`, should we come up with a different title?

**Comment by imanish003** [comment]
Hi @albarin, 

Thank you for your work on this implementation so far! I have a few observations regarding the implementation in relation to the design:

- The site title appears to be smaller and not bold, as per the design specifications.
- The design includes links for "New Arrivals" and "Sale," but these sections are not present in the implementation.
- Additionally, there seems to be a discrepancy between the mobile design and the implementation.

Could you please confirm whether these deviations from the design were intended, or if they require further attention? Thank you for your efforts! 🙌🏻

**Comment by albarin** [comment]
Thanks @imanish003!

> The site title appears to be smaller and not bold, as per the design specifications.

Thanks, fixed.

> The design includes links for "New Arrivals" and "Sale," but these sections are not present in the implementation.

I think these are just items on the menu.

> Additionally, there seems to be a discrepancy between the mobile design and the implementation.

I think we cannot achieve this 👇 mobile version for this header Simple Row (Mobile)
this is the current behaviour header
what do you think @shaunandrews ?

**Comment by imanish003** [comment]
Hi @albarin, thank you for making the changes. 🙌🏻 Regarding my second and third points, I believe we'll need input from @shaunandrews before we can merge the PR. What are your thoughts? 🙂

**Comment by shaunandrews** [comment]
> "New Arrivals" and "Sale,"

As mentioned, these are just representations of a menu, not specific requirements for the pattern.

--

I'm asking around for some options for what we can do with regards to mobile; I don't think the current behavior is something we should ship — its way too awkward to have the menu in the middle like that...

A few options that come to mind:
- We could force it with some custom mobile-only CSS, but I'm not sure where this CSS would live, and it maybe conflict with other themes.
- Maybe we could build a custom block that does this? I'm not sure what that would entail or if its even possible.

**Pull request closed without merging**
