### PR TITLE
Product Collection: Add support for filtering products by featured status

### LINKED ISSUE #11358: Product Collection - Filters - Featured Products
### Background

Add a filter allowing to filter FEATURED products.

### Requirements

- Merchant can filter featured products.

### Designs

The same as On Sale but with:
- title: "Featured"
- label: "Show only featured products"

image

### PR DESCRIPTION
**Pull request by imanish003**
## What

This PR introduces a new filter that allows users to filter products by their featured status. Specifically, the following changes have been made:  
- Added a `featured` attribute to the `ProductCollectionQuery` type, enabling filtering by featured status.
- Implemented the `FeaturedProductsControl` to provide a toggle option in the inspector controls.
- Updated existing functions and queries in the `ProductCollection.php` to support featured products filtering.

Fixes #11358

## Why

These changes allow merchants to easily display only featured products in their product collections, enhancing flexibility.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

**Case 1: Normal**

1. Create a new post & add "Product Collection (Beta)" block to it.
2. In the inspector controls, select the three dots on the filters panel.

3. Confirm the visibility of the "Featured" filter.
4. Click "Featured" to add the Featured filter to the Inspector controls. Ensure it matches the screenshot provided:

5. Toggle the button to the ON position and confirm that only featured products are displayed in the Editor.
6. Publish the post and inspect the frontend, verifying that only featured products are visible.
7. Furthermore, confirm that toggling to the OFF position displays all products in both the Editor and frontend.

**Case 2: Resetting the value of the Featured filter**

1. Follow the steps in Case 1 to add the Featured filter to the Inspector controls.
2. Toggle it to the ON position to display only featured products in the Editor.
3. Verify the ability to reset the filter using both options shown in the screenshot below:

- Click on "Featured" row itself
- Click on "Reset all" button.

**Case 3: Ensuring older blocks aren't broken (To be tested by developers only)**

1. Switch to the trunk branch.
2. Create a new post and add "Product Collection (Beta)" block.
3. Save and publish the post.
4. Switch to the branch named `add/11358-product-collection-featured-products-filter`.
5. Verify that everything functions as expected in both the saved post's Editor and frontend.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Collection: Add support for filtering products by featured status

### CODE REVIEW

**Review by kmanijak — CHANGES_REQUESTED** [review]
It works really nice! Thanks for taking care of it!

I think the initial `featured` value should be added to the patterns as well. They will work fine without that but I think it's important to add them explicitly. What do you think?

**Comment by imanish003** [comment]
Hi @kmanijak 👋 

> I think the initial featured value should be added to the patterns as well. They will work fine without that but I think it's important to add them explicitly. What do you think?

TBH I'm somewhat neutral on the matter. It seems reasonable to rely on the internal default values for attributes when not explicitly defined. We need to ensure that all the existing patterns still work as expected if new attribute is not defined. However, I'm open to following your suggestion. Should I go ahead & update all the patterns? 🤝

**Review by kmanijak — APPROVED** [review]
> TBH I'm somewhat neutral on the matter. It seems reasonable to rely on the internal default values for attributes when not explicitly defined. We need to ensure that all the existing patterns still work as expected if new attribute is not defined. However, I'm open to following your suggestion. Should I go ahead & update all the patterns? 🤝

I don't have any other argument for that except for being explicit. Maybe that's not that important 🤔 I'm approving and leaving decision up to you 🙌

**Comment by imanish003** [comment]
@kmanijak 

> I don't have any other argument for that except for being explicit. Maybe that's not that important 🤔 I'm approving and leaving decision up to you 🙌

Got it, I will keep the patterns as they are unless we want to override the default behavior using an attribute. This would also apply to synced patterns created by users and third-party developers. 🙂

**Pull request merged**
