### PR TITLE
Single Product: Fix Product SKU not loading for different variations

### LINKED ISSUE #9989: Product SKU: Doesn't load the correct SKU when selecting a variation in a blockified Single Product template
## Describe the bug

In a blockified Single Product template the SKU doesn't load for the selected varation.

## To reproduce

1. Select **Appearance > Editor > Templates > Single Product**. Blockify the Single Product template.
2. Make sure you have a least one variation product, with variations having a unique SKU set. 
3. Go to the frontend view of the variation product, and see that selecting different variations doesn't cause the variation SKU to load correctly.

## Screenshots
9g2q1nejKx

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR fixes the switching of the variation's SKU when using the blockified Single Product template.

Fixes #9989 

### Screenshots

| Before | After |
| ------ | ----- |
|9g2q1nejKx|3LvebPhtER|

#### User Facing Testing

1. Select **Appearance > Editor > Templates > Single Product**. Blockify the Single Product template.
2. Make sure you have a least one variation product, with variations having the **SKU** set. 
3. Go to the frontend view of the variation product, and verify that selecting different variations causes the SKU to reflect the variation's SKU.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Single Product template: Fix variation SKU switching in the blockified template.

### CODE REVIEW

**Comment by roykho** [comment]
So I am unsure if this is for the classic single product template or the blockified single product template. Because in your screenshot, it shows the variation images changes when you change the variation. That function only works for me when using the classic single product template. Assuming that is what you're also using, then it seems the SKU already changes correctly in trunk?

**Comment by danieldudzic** [comment]
> So I am unsure if this is for the classic single product template or the blockified single product template. Because in your screenshot, it shows the variation images changes when you change the variation. That function only works for me when using the classic single product template. Assuming that is what you're also using, then it seems the SKU already changes correctly in trunk?

Right, I'm sorry, this applies to the blockified template.

I believe #9986 is also necessary for this to work.

**Review by gigitux — APPROVED** [review]
LGTM! Thanks for working on this fix! 🚢

**Review by roykho — APPROVED** [review]
LGTM!

**Review by thealexandrelara — APPROVED** [review]
Thank you for addressing it! LGTM! 🚀

**Pull request merged**
