### PR TITLE
onPaymentProcessing->onPaymentSetup

### LINKED ISSUE #10690: Payment documentation shouldn't suggest deprecated `onPaymentProcessing` and `shippingData` `billingData`
## Describe the bug

I am implementing an express payment method (digital wallet) where the shipping address needs to be set from the info returned by the wallet.

Setting `billingData` works but `shippingAddress` does not work. This causes the `woocommerce_rest_invalid_address` error and the only way to resolve this is to set the shipping address fields in the Block Checkout form.

May be related to issue woocommerce/woocommerce-blocks#8785

## To reproduce

Return shipping address  in the observer for`onPaymentProcessing()` in the following format:

```js
onPaymentProcessing( () => {
	//
	// some logic...
	//
	const response = {
		meta: {
			paymentMethodData: {
				key1: 'value1',
				key2: 'value2',
			}
		},
		billingData: {
			email: 'user@example.com',
			first_name: 'John',
			last_name: 'Doe',
			company: 'Billing, INC.',
			address_1: 'Billing Apt.',
			address_2: '',
			city: 'LA',
			state: 'CA',
			postcode: '90001',
			country: 'US',
			phone: '8888899999',
		},
		shippingAddress: {
			first_name: 'Emily',
			last_name: 'Dawson',
			company: 'Shipping, INC.',
			address_1: 'Shipping Apt.',
			address_2: '',
			city: 'LA',
			state: 'NY',
			postcode: '10001',
			country: 'US',
		},
	};
	return response;
} );
```

So far, I have also tried the older response shapes for shipping data:

```js
const response = {
	meta: {
		paymentMethodData: {}
	},
	billingData: {},
	shippingData: {},
};
```

**and**

```js
const response = {
	meta: {
		paymentMethodData: {}
	},
	billingData: {},
	shippingData: {
		address: {}
	},
};
```

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.0.2
-   WooCommerce Blocks version: 11.0.0-dev
-   Site language:
-   WooCommerce Square

### PR DESCRIPTION
**Pull request by mikejolley**
## What

Removes references to `onPaymentProcessing` and `billingData` in favour of `onPaymentSetup` and `billingAddress`.

Fixes #10690

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @mikejolley. 

I noticed two places, in the docs, where we're still referring to [`billingData`](https://github.com/woocommerce/woocommerce-blocks/blob/50223e5cfd7552d777b09cfa538986f846c7e4e6/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md?plain=1#L167C1-L168C1) resp. to [`shippingData`](https://github.com/woocommerce/woocommerce-blocks/blob/50223e5cfd7552d777b09cfa538986f846c7e4e6/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md?plain=1#L178). I wonder if we should change these entries as well, to ensure that external developers are using `billingAddress` and `shippingAddress` in the future.

**Comment by mikejolley** [comment]
I missed one @nielslange but the others you linked to are correct as-is. `Data` is still used in some places when not dealing solely with addresses.

**Review by nielslange — APPROVED** [review]
Thanks for addressing my earlier feedback and for explaining that `Data` is still used in some places. The PR looks good now. Let's ⛴️ this change, @mikejolley.

**Comment by mikejolley** [comment]
I will force merge this as it only touches docs. The other test fails are not related.

**Pull request merged**
