### PR TITLE
Fix: use correct type specifier for rating HTML

### PR DESCRIPTION
**Pull request by dinhtungdu**
We're using the `%f` in the `sprintf` of the `ratingHTML`, but we feed the `sprintf` with a string instead of float, which throws a TypeError. We need to use `%s` instead to keep the console happy.

Screen Shot 2022-11-07 at 13 20 35

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### Screenshot

<table>
<tr>
	<td> Before 
	<td> After
<tr>
	<td> image
	<td> image

</table>

#### User Facing Testing

1. Add the `Filter by Rating` block to a page.
2. Do not see the TypeError error above in the console log.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by nielslange — COMMENTED** [review]
Great work, @dinhtungdu! I wonder if we should also change
```tsx
const ratingText = sprintf(
    /* translators: %f is referring to the average rating value */
    __( 'Rated %f out of 5', 'woo-gutenberg-products-block' ),
    rating
);
```
to
```tsx
const ratingText = sprintf(
    /* translators: %d is referring to the average rating value */
    __( 'Rated %d out of 5', 'woo-gutenberg-products-block' ),
    rating
);
```
and
```tsx
const ratingHTML = {
    __html: sprintf(
        /* translators: %s is the rating value wrapped in HTML strong tags. */
        __( 'Rated %s out of 5', 'woo-gutenberg-products-block' ),
        sprintf( '<strong class="rating">%f</strong>', rating )
    ),
};
```
to
```tsx
const ratingHTML = {
    __html: sprintf(
        /* translators: %s is the rating value wrapped in HTML strong tags. */
        __( 'Rated %s out of 5', 'woo-gutenberg-products-block' ),
        sprintf( '<strong class="rating">%d</strong>', rating )
    ),
};
```

Thus, instead of using `%f`, which indicates a float, we could use `%d` to indicate integers.

**Comment by dinhtungdu** [comment]
> Thus, instead of using %f, which indicates a float, we could use %d to indicate integers.

@nielslange Thanks for the great catch! We only use the integer so I agree that it's better to use `%d` instead of `%f`.

But I'm looking at the Rating product element block, the star shares the same codebase (look like the code of `assets/js/base/components/product-rating/index.tsx` mimics `assets/js/atomic/blocks/product-elements/rating/block.tsx`). So I think we should refactor them to eliminate duplication. What I'm planning is:
- Merge this PR. 
- Create an issue to refactor the `assets/js/atomic/blocks/product-elements/rating/block.tsx` using the `Rating` component. (The type of rating needs to change from uninion type to number).

What do you think?

**Review by Aljullu — APPROVED** [review]
LGTM, good catch!

> - Create an issue to refactor the `assets/js/atomic/blocks/product-elements/rating/block.tsx` using the `Rating` component. (The type of rating needs to change from uninion type to number).

Is this related to #7174? cc @danieldudzic

**Comment by nielslange** [comment]
> But I'm looking at the Rating product element block, the star shares the same codebase (look like the code of `assets/js/base/components/product-rating/index.tsx` mimics `assets/js/atomic/blocks/product-elements/rating/block.tsx`). So I think we should refactor them to eliminate duplication. What I'm planning is:
> 
> * Merge this PR.
> * Create an issue to refactor the `assets/js/atomic/blocks/product-elements/rating/block.tsx` using the `Rating` component. (The type of rating needs to change from uninion type to number).
> 
> What do you think?

Sounds like a great approach, @dinhtungdu! 👍

**Comment by dinhtungdu** [comment]
> Is this related to https://github.com/woocommerce/woocommerce/issues/42582?

I'm pretty sure it is, thanks for pointing it out @Aljullu!

**Pull request merged**
