### PR TITLE
Enable several i18n ESLint rules from wpcalypso

### LINKED ISSUE #1678: Consider enabling some eslint-plugin-wpcalypso rules
In #1672 we fixed an issue where we were using three dots (`...`) instead of an ellipsis (`…`) in a user-facing string. It turns out, Calypso has a ESLint rule to catch this kind of mistakes: `wpcalypso/i18n-ellipsis`.

This issue is about enabling that rule and consider enabling some more from [`eslint-plugin-wpcalypso`](https://github.com/Automattic/wp-calypso/tree/master/packages/eslint-plugin-wpcalypso).

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1678.

In #1672 it was suggested to add an ESLint rule to prevent using three dots instead of ellipsis in translatable strings. This PR adds this ESLint rule and some others from `eslint-plugin-wpcalypso`.

Fortunately there was no need to make any code change because all our code already passes! :tada:  But these rules should prevent us from introducing future bugs.

### How to test the changes in this Pull Request:

1. Run `npm run lint:js`.
2. Verify there are no errors (there is a warning, but unrelated to this PR and it's fixed in #1468).

Docs for each rule can be found in https://github.com/Automattic/wp-calypso/tree/master/packages/eslint-plugin-wpcalypso#supported-rules.

### CODE REVIEW

**Comment by nerrad** [comment]
@Aljullu correct me if I'm wrong, but aren't these eslint rules specific to usage of the calypso `translate` function? We use `wp.i18n` functions so I don't think these linting rules will apply in this repository?

**Comment by senadir** [comment]
unrelated to this PR but since we're talking about eslint, I noticed we don’t have [a11y jsx plugin](https://www.npmjs.com/package/eslint-plugin-jsx-a11y), this could help us catch accessibility issues during dev, can we add it (in a separate PR)?

**Comment by Aljullu** [comment]
You're right, it looks like only `i18n-ellipsis` supports WordPress i18n functions:

https://github.com/Automattic/wp-calypso/blob/master/packages/eslint-plugin-wpcalypso/lib/rules/i18n-ellipsis.js#L65

While testing, some other wrong translation strings were outputting an error too, so I optimistically thought those rules supported WP functions. But it turns out the error was shown by [`@wordpress/valid-sprintf`](https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/docs/rules/valid-sprintf.md) instead `wpcalypso`'s rules. :man_facepalming: 

So I think probably the only rule we can reuse from that package is `i18n-ellipsis`. Updated the PR accordingly.

You can test it with:
* `git revert fdb9e1f88731b81c76bf3ebbc103a8fbd21dbc77` (reverts this PR: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1672)
* `npm run lint:js`

---

I wonder, however, if a better approach would be to try to upstream that rule to WordPress's ESLint rules package?

**Comment by nerrad** [comment]
> I wonder, however, if a better approach would be to try to upstream that rule to WordPress's ESLint rules package?

I'd prefer to see this upstream.  Since it'd be in a dev package we'd be able to pull it in on the next package update. So I recommend, make the change upstream in the gb repo, leave this pull open in case the upstream rule change isn't accepted, and then we can revisit this pull then?

**Comment by nerrad** [comment]
I'm going to move this to icebox pipeline for now. @Aljullu I'd be happy to discuss alternative pipelines if you think it'd be better elsewhere?

**Comment by Aljullu** [comment]
> I'm going to move this to icebox pipeline for now. @Aljullu I'd be happy to discuss alternative pipelines if you think it'd be better elsewhere?

Sounds good to me. If we want to try to upstream it, this task might be better suited for a cooldown or HACK project, maybe?

**Comment by Aljullu** [comment]
I'm going to close this PR because it didn't have action for several months and it has conflicts with `trunk`. We already have an open issue to track the addition of those ESLint rules (#1678), so there is no need to keep the PR open.

**Pull request closed without merging**
