### PR TITLE
Fix: Product Collection show products with correct stock statuses

### PR DESCRIPTION
**Pull request by dinhtungdu**
## What

This PR fixes the issue that Product Collection shows out of stock products event if that status isn't selected:

1. Set some product to be out of stock.
2. Add Product Collection block to a page.
3. Set the stock status filter to all options except `outofstock`.
4. Still see the out of stock products in the editor preview.
5. Save and see the same on the front end. Out of stock products still show up.

Fixes #

## Why

We're handling query related to stock status a little more complex than other:
- If the selected stock statuses contain all available statuses or no status was selected, we do nothing.
- If the selected stock statuses contain all available statuses **but not `outofstock`**, we add out of stock term to product visibility tax query.
- For the remaining cases, we use a meta query.

We do it for some reasons:
- Following WC Core.
- Performance: using tax queries is more performant than using meta queries.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Set some product to be out of stock.
2. Add Product Collection block to a page.
3. Set the stock status filter to all options except `outofstock`.
4. See the out of stock products **not show up** in the editor preview.
5. Save and see the same on the front end. Out of stock products don't show up.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Fix: Product Collection show products with correct stock statuses

### CODE REVIEW

**Review by imanish003 — COMMENTED** [review]
I tested the PR and found that it functions correctly on the post but not as expected in the Product Catalog template. To replicate the issue:

1. Add a product collection block to the Product Catalog template.
2. In settings, Check the following checkbox (as shown in screenshot). Despite this, out of stock items remain visible in the Editor, although they are correctly hidden on the Frontend.

image

I believe I've identified the cause of this issue. Here's my detailed assessment:

The problem seems to manifest exclusively in the Editor, and not in the Frontend. This discrepancy arises due to the use of the query_loop_block_query_vars filter in our frontend query construction, as seen [here](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/src/BlockTypes/ProductCollection.php#L75-L80). The invocation of this filter is conditional, as outlined [here](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/src/BlockTypes/ProductTemplate.php#L45-L51), and it only executes when the 'Inherit query from template' option is turned off. Consequently, our custom query logic is not applied.

In contrast, within the Editor, the rest_product_query filter, referenced [here](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/src/BlockTypes/ProductCollection.php#L90), does not depend on such conditions. It runs regardless of whether the 'inherit query from template' is active or not.

This issue went unnoticed previously because the 'inherit query from template' feature, when enabled, triggers a reset of attribute values to their defaults, as implemented [here](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/assets/js/blocks/product-collection/inspector-controls/inherit-query-control.tsx#L80-L83). Therefore, default values were used in our custom query, making the conditional execution of rest_product_query redundant.

As for a solution, I propose we introduce a condition within the rest_product_query filter that bypasses our custom query logic when 'Inherit query from template' is enabled. I had hoped to use the inherit attribute we set [here](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/assets/js/blocks/product-collection/inspector-controls/inherit-query-control.tsx#L80-L84) as a part of this condition, but it's currently not accessible in the arguments of the rest_product_query filter ($args, $request). More debugging is required to understand why.

Regarding the merge of this PR, it seems feasible since the frontend functionality is performing as expected. What do you think? CC: @kmanijak

**Review by kmanijak — APPROVED** [review]
Apologies for long wait, I must've missed the notification 🙌 

> I tested the PR and found that it functions correctly on the post but not as expected in the Product Catalog template. To replicate the issue:
> 
> Add a product collection block to the Product Catalog template.
> In settings, Check the following checkbox (as shown in screenshot). Despite this, out of stock items remain visible in the Editor, although they are correctly hidden on the Frontend.

I couldn't reproduce this problem. In both cases - with this option enabled and disabled - I could see the right outcome in Editor and frontend (

> Regarding the merge of this PR, it seems feasible since the frontend functionality is performing as expected. What do you think? CC: @kmanijak

I'd say we merge it - it's a nice improvement both ways! 🚀

**Comment by imanish003** [comment]
@kmanijak 

> I couldn't reproduce this problem. In both cases - with this option enabled and disabled - I could see the right outcome in Editor and frontend

I am still able to reproduce this issue. Here are the steps that I followed:

1. Insert a Product Collection block into the Product Catalog template.
    - Ensure the presence of some out-of-stock products. If possible, rename an out-of-stock product to "1st product" to show it as 1st product in grid.
2. Check the checkbox(Make sure it isn't checked when block was inserted in 1st step):
image

3. Refresh the Product Catalog template in the Editor.
    1. Observe that the "1st product" remains visible, contrary to expectations, since the "Hide out of stock items from the catalog" option was activated.


@dinhtungdu Are you able to reproduce this issue? 🙂

**Comment by dinhtungdu** [comment]
@imanish003 The Product Collection block only checks for the `Out of stock visibility` setting when being added to the editor, after that, it will take the stock settings from its inspector setting only. So if the Product Collection block stock status setting contains `Out of stock`, the block will show out of stock products regardless of the `Out of stock visibility` setting.

**Comment by imanish003** [comment]
@dinhtungdu 

Good catch! The [code here](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/assets/js/blocks/product-collection/constants.ts#L25-L34) is designed to determine the stock status based on the global setting for hiding out-of-stock items in Editor. This function is triggered under two specific conditions:

- When the block is added.
- When the user selects the “Reset all” option in the filter dropdown, as depicted in this image:




A potential solution might be to assess whether “Inherit query from template” is enabled. If it is, we could always set the “stock status” attribute to the value returned by [getDefaultStockStatuses](https://github.com/woocommerce/woocommerce-blocks/blob/4e51c1953e46122aa3ebf96d1360f75641631460/assets/js/blocks/product-collection/constants.ts#L30-L34).

**Comment by dinhtungdu** [comment]
@imanish003 I don't see it's a problem here. I think it's good to respect the **block** stock status settings after it's been added and we shouldn't take the global setting into account after that.

- For blocks that inherit query from template, we won't have any issue as we just use the global query.
- For blocks that uses their own queries, I don't think they need to follow global stock setting as they have their own settings.

**Comment by imanish003** [comment]
@dinhtungdu 

> • For blocks that inherit query from template, we won't have any issue as we just use the global query.
> 

Based on my understanding, this applies to the Frontend but not to the Editor. Consequently, the Frontend operates smoothly, aligning with expectations, but the Editor encounters issues in the scenario I described https://github.com/woocommerce/woocommerce-blocks/pull/11708#issuecomment-1815805963.

- Therefore, I propose we proceed with merging the PR, as the Frontend functionality is consistent with expectations in https://github.com/woocommerce/woocommerce-blocks/pull/11708#issuecomment-1815805963.
- As for addressing the Editor's issue, we can tackle it in a subsequent PR. In that PR, we should ensure the Editor uses the Global value whenever the "Inherit query from template" option is selected.

Does this approach seem logical?  🙂

**Comment by dinhtungdu** [comment]
> * As for addressing the Editor's issue, we can tackle it in a subsequent PR. In that PR, we should ensure the Editor uses the Global value whenever the "Inherit query from template" option is selected.

That sounds good to me! Thanks so much for your explanation!

**Comment by wavvves** [comment]
PHP Unit tests are failing, going to push this onto 11.7.0 milestone

**Comment by dinhtungdu** [comment]
Test is fixed. Merging.

**Pull request merged**
