### PR TITLE
Remove duplicate HTML element and added classnames for single product…

### LINKED ISSUE #10269: Single Product block additional CSS class appears in two different elements in the frontend
Adding an additional CSS class to the Single Product block causes unexpected effects: the class is added to two different HTML elements and, in one of them, it appears twice.

## To reproduce

1. Add the Single Product block to a post or page.
2. In the sidebar, open the _Advanced_ panel and add an additional CSS class (ie: `lorem-ipsum`).
3. Publish the post or page and visit it in the frontend.
4. With your browser devtools, search for the class you added in step 2. Notice it has been added to two different HTML elements and in one of them it's duplicate:

imatge

## Expected behavior

The additional CSS class should only be added to the outermost HTML element.

### PR DESCRIPTION
**Pull request by roykho**
… block

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10269

### Screenshots

| Before | After |
| ------ | ----- |
|        |      |

#### Dev Facing Testing

1. Add `Single Product Block` to a post/page.
2. Add a custom CSS classname in the Advanced section.
3. Go to the frontend and inspect the outer container of this block to ensure there are no duplicate CSS classname.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Remove duplicate HTML element and added classnames for single product block

### CODE REVIEW

**Comment by roykho** [comment]
cc @Aljullu - 👋 could definitely use your insights here as to the best practice deprecating server side.

**Comment by danieldudzic** [comment]
Not a deprecation method per se, but perhaps [`_doing_it_wrong`](https://developer.wordpress.org/reference/functions/_doing_it_wrong/) could be useful in this case to communicate changes.

**Comment by roykho** [comment]
@danieldudzic - thanks for the comment however I am not sure how that would help in this case. The issue is with people that already have this block on a page. When they load it up with this change, it would look fine on the editor side and also no `block validation error` as that has been handled, on the frontend however, would exhibit issues because the markup is different. More specifically the classname `woocommerce` is no longer present due to the changes.

Sure we could probably handle this with `if/else` but I feel this is not practical because what if we have more changes later in the future, then we would litter conditionals everywhere which pollutes the code. It would be great to have a standard practice like how we're able to deprecate in Gutenberg with `deprecated` file.

**Review by Aljullu — COMMENTED** [review]
> cc @Aljullu - :wave: could definitely use your insights here as to the best practice deprecating server side.

Good question. I was wondering if it would be possible to avoid having to do a deprecation altogether. Ie, removing the code that renders the custom class from `SingleProduct.php` (but keeping the `woocommerce` class):

```PHP
protected function render( $attributes, $content, $block ) {
	$html = sprintf(
		'<div class="woocommerce">
			%1$s
		</div>',
		$content
	);

	return $html;
}
```

This way we wouldn't need to do a deprecation of the block, no? :thinking:

**Comment by roykho** [comment]
Yes but then it wouldn't be semantic because you have an extra `div` wrapper that doesn't do anything.

**Review by Aljullu — COMMENTED** [review]
> Yes but then it wouldn't be semantic because you have an extra `div` wrapper that doesn't do anything.

In most cases I would agree, but in this specific case I think we need to take into consideration that this `<div>` is there only to fix styling with WC core stylesheets and (maybe) themes which rely on the `.woocommerce` class to be present. I expect that with time, as we keep blockifying things, we will be less dependent on the presence of the `.woocommerce` class and, hopefully, one day we will be able to remove it.

That's why I prefer adding that class from the PHP-side dynamically than having it in the saved markup of the block. Because if one day we want to remove the `.woocommerce` class, it will be easier. You're right that it adds an unnecessary extra div, but I don't think that's a big deal and IMO the extra flexibility we get from adding it in the PHP-side overpass the cons.

**Comment by roykho** [comment]
@Aljullu - thanks for the feedback and insights. I've pushed up the change if you don't mind taking a second look.

**Review by danieldudzic — APPROVED** [review]
I have tested and the custom class appears only once!

**Pull request merged**
