### PR TITLE
Product Collection: Use Interactivity API for pagination

### LINKED ISSUE #10328: Product Collection - Interactivity API
### Background

Interactivity API has been introduced to the Products (Beta) block which significantly improved performance of changing the pages on the frontend. (PR: https://github.com/woocommerce/woocommerce-blocks/pull/10200).

As Product Collection should bring better or at least the experience, we should introduce the changes from https://github.com/woocommerce/woocommerce-blocks/pull/10200 to Product Collection as well so there's no performance drop after migrating from Products (Beta) block to Product Collection.

### Goal

Reuse the directives introduced in https://github.com/woocommerce/woocommerce-blocks/pull/10200 in Product Collection providing the same performance boost to the block.

### PR DESCRIPTION
**Pull request by imanish003**
Similar to PR #10200, This PR uses Interactivity API for the Product Collection block.

**Changes:**

1. Two new filter hooks, `render_block_woocommerce/product-collection` and `render_block_core/query-pagination`, are introduced. They employ the methods `add_navigation_id_directive` and `add_navigation_link_directives` respectively.

   - The `add_navigation_id_directive` method marks the Product Collection block as an interactive region that can be updated during client-side navigation. It adds a `data-wc-navigation-id` attribute to the block content, based on the `queryId` attribute of the parsed block.

   - The `add_navigation_link_directives` method adds interactive links to all anchors within the Query Pagination block. These interactive links receive payloads, including a `prefetch` value (true for previous and next pagination links) and a `scroll` value (always true). The anchors for previous and next pagination also receive a key attribute (`pagination-previous` and `pagination-next` respectively).

2. **`render_callback` Modification**: In the `render_callback` method, the parsed block is stored in the `$parsed_block` property. 

Fixes #10328

#### Testing with single Product Collection block in post

1. Create a new post
2. Add product collection block to it
3. To enhance the visibility of pagination, adjust the 'Items per page' setting within the 'Product Collection' block to 3 using the toolbar setting, as depicted in the screenshot below:
image

4. Publish the post and navigate to the frontend.
5. Traverse through pages using pagination, confirming that only the HTML inside the 'Product Collection' block gets updated.
6. Navigate back and forth between various pages, again confirming that only the HTML within the 'Product Collection' block is updated.
7. Click on any link outside the 'Pagination' block.
8. Verify that the browser correctly navigates to the selected link.

Here is a quick demo:

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/5dc0acf6-c012-446e-b9f9-d788e2f87356

#### Test with 2 or more Product Collection blocks in post

Repeat above step with two or more Product Collection blocks in same post. This ensures that blocks are isolated from each other while changing the pages. 

* [X] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [X] Experimental

### Changelog

> Product Collection: Use Interactivity API for pagination

### CODE REVIEW

**Comment by imanish003** [comment]
@kmanijak, JFYI, this pull request is ready. I will mark it as ready for review once #10200 is merged because there is some discussion around scrolling on #10200, and it's possible that some changes might be needed in this pull request as well, depending on the outcome of the discussion 🤝

**Review by kmanijak — APPROVED** [review]
That's an amazing UX improvement! 👍

I checked single and multiple Product Collection blocks on:
- post
- Product Catalog template

All works great!

**Review by thealexandrelara — APPROVED** [review]
Ohh this is awesome, much better user experience without having to reload the entire page every time we click to visit the next page. 

✅ When navigating to a different page, it updates the URL with the clicked page
✅ When navigating to a different page, it changes only the content for the Product Collection block
✅ When navigating to a different page, the page is not fully reloaded
✅ When navigating to a product and return to the page with the Product Collection, the pagination is correctly updated and shows the correct products
✅ When multiple Product Collection blocks are added to the page and we navigate to a different page, it updates the URL with the clicked page for that specific Product Collection block
✅ When multiple Product Collection blocks are added to the page and we navigate to a different page, it changes only the content for that specific Product Collection block

**Comment by luisherranz** [comment]
This is a related PR in Gutenberg that introduces client-side pagination to the Query block:

- https://github.com/WordPress/gutenberg/pull/53812

It has examples of:

- Opt-in mechanism to activate the feature in the Editor
- Delayed loading indicator with a top bar progress
- Accessibility announcements when the navigation starts and finishes, and movement of focus to the new content

It hasn't been reviewed yet by design or accessibility experts, so it may still change.

**Pull request merged**
