### PR TITLE
Implement `Fixed image` and `Repeated image` media controls for the `Featured Product`

### PR DESCRIPTION
**Pull request by albarin**
This PR adds the `Fixed image` and `Repeated image` media controls for the `Featured Product` block.

Fixes part of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6235

### Testing

How to test the changes in this Pull Request:

1. Create a new page and add a `Featured Product`.
2. On the block settings go to `Media Settings` and toggle `Fixed image` and `Repeated image` and save.
3. Check the rendered product on the frontend is correct and matches the one on the edit page.
4. Edit the block again, repeat the steps above with different combinations on `Fixed image`, `Repeated image` and any other configuration.

### Changelog

> Add the `Fixed image` and `Repeated image` media controls to the Featured Product block

### CODE REVIEW

**Comment by sunyatasattva** [comment]
While testing I have encountered this weird behavior:

I have an image that's relatively smaller than its container. I change the background to “Fixed” and the focal point is reset to the center. However, the image gets thrown to the top left corner.

Clicking around the focal point picker, allows me to restore the image location.

https://user-images.githubusercontent.com/1847066/166964339-56137543-4e7b-47dd-8fb5-67cb43698d80.mov

Another issue:

1. Have a smaller image
2. Set the image to fixed
3. Set the image fit to “Cover”

I expect the image to be stretched so it covers the available container. However, it gets stretched much larger.

**Review by sunyatasattva — CHANGES_REQUESTED** [review]
Commented above regarding my testing results

**Comment by albarin** [comment]
Thanks for the review @sunyatasattva

> I have an image that's relatively smaller than its container. I change the background to “Fixed” and the focal point is reset to the center. However, the image gets thrown to the top left corner.
Clicking around the focal point picker, allows me to restore the image location.

I just pushed a commit that I think fixes this issue.

> I expect the image to be stretched so it covers the available container. However, it gets stretched much larger.

Now that you mention it kind of makes sense, I followed the same behavior that the `Cover` block has when selecting `Fixed image`, not sure what's the correct one. 🤔

**Review by sunyatasattva — COMMENTED** [review]
I was testing more on this, and I noticed that neither Fixed nor Repeated options work with `duoTone` filters. I have no idea if there is a way to make them work, honestly. But we should do some research on that and then perhaps follow up with someone to see what to do about it. We can either:

1. Not implement fixed/repeated options
2. Find a workaround that's not too performance intensive
3. Add a notice after the settings about duotone not working
4. Disabling duotone entirely from the toolbar when either of those options are active

> Now that you mention it kind of makes sense, I followed the same behavior that the Cover block has when selecting Fixed image, not sure what's the correct one. 🤔

Is there an easy way to try out stretching the image only until it covers the container? Otherwise, I'll leave the decision on this up to you. While testing several cases, this seemed really weird behavior for me, but I'm open to your opinion.

**Comment by albarin** [comment]
> I was testing more on this, and I noticed that neither Fixed nor Repeated options work with duoTone filters.

Good catch! I just pushed a couple of commits to fix it. I've tested all the cases I could think of and everything seems to be working as before the fix 🤞

> Is there an easy way to try out stretching the image only until it covers the container? Otherwise, I'll leave the decision on this up to you. While testing several cases, this seemed really weird behavior for me, but I'm open to your opinion.

I've been researching a bit about it and it seems there's an issue with `background-size: cover` and `background-attachment: fixed`, check: https://stackoverflow.com/questions/21786272/css-background-size-cover-background-attachment-fixed-clipping-background-im
I've tried some of the suggestions, but it does not seems to work quite like expected, I'm not very good at CSS though, maybe you'd have some better idea? 🤔

**Review by sunyatasattva — APPROVED** [review]
Duotone is fixed! Nice job! I'm approving, as I don't want to be an absolute pain on this issue, and everything works correctly.

However, the background issue is still bothering me a bit. Your link was an excellent find to explain what was happening.

I played around a bit, and I don't think it's worth adding JS to fix this issue as we can have a big impact on the performance of the page (we don't know how many of these blocks are people going to add in one page after all). What do you think?

While playing around I thought of a solution that _could be_ viable, if you want to experiment a bit.

So, the issue in a nutshell is that when you tell a background to be fixed, its context will be calculated with the entire viewport: so the `cover` instruction essentially means to cover the entire viewport and not the wrapper container.

So, one way around it, would be to _emulate_ the behavior of `cover` ourselves. So, instead of using `background-size: cover`, we calculate the dimensions of the container and hardcode that in the `background-size` (similarly to what we do with `background-position`).

Yes, this is a JS solution, but it's not a very expensive one, as we only need to do it as the user is editing the block, and then the front end should be able to render everything correctly via the PHP, causing no performance issues.

Oh, and last thing, again optional as I don't want to block this PR any longer: when choosing `Fixed background` option, the tag is transformed to a `div`, making the `alt` attribute useless. When I check `Repeated background` the `alt` option disappears from the sidebar, but it doesn't when I used the fixed one.


Both of these comments are optional, feel free to merge it if you are happy with the current state. None of it is a big deal.

**Comment by albarin** [comment]
@sunyatasattva I've hidden the alt textarea for Fixed background, good catch 👍 

I've been trying your idea for cover but couldn't make it fully work, so I think for now we can proceed with this PR as is now, I don't want to delay it even more. Thanks for the reviews!

**Comment by sunyatasattva** [comment]
Thank you for trying! I don't even know if it was a good idea. ¯\_(ツ)_/¯ I've already approved the PR so you can proceed with the merge as far as I'm concerned.

**Pull request merged**
