### PR TITLE
Product Gallery Block: Add zoom on hovering on the frontend - E2E tests

### PR DESCRIPTION
**Pull request by gigitux**
## What

This PR adds the E2E test for #9941.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Ensure that the E2E tests pass on the CI.

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by gigitux** [comment]
@imanish003, I assigned this to you, given the bot has designated you as a reviewer of #10791.

**Review by danieldudzic — APPROVED** [review]
The tests pass locally!

I would expect testing zoom would be much harder, but your method is so simple!

`await expect( styleOnHover.transform ).toBe( 'scale(1.3)' );`

For a moment, I was wondering if there's any way we can test the actual zoom on different areas of the image, but can't think of a way, plus I believe the above is perfectly sufficient.

**Comment by gigitux** [comment]
> For a moment, I was wondering if there's any way we can test the actual zoom on different areas of the image, but can't think of a way, plus I believe the above is perfectly sufficient.

Same. I thought about it, but I didn't find any good approach :(

**Review by thealexandrelara — APPROVED** [review]
Tests are looking great! 

I cannot see a different approach than the one you used to check if the transform was updated with the correct value, unless we used visual testing for that but this is a clever approach 🚀

**Pull request merged**
