### PR TITLE
Replace phpcs rule

### PR DESCRIPTION
**Pull request by roykho**
## What

This PR replaces the removed `WordPress.PHP.DisallowShortTernary` in favor of `Universal.Operators.DisallowShortTernary`.

Ref: https://github.com/WordPress/WordPress-Coding-Standards/blob/7722c0b8a6f4eb615be4ba8ebe22ed92a5fa87d7/CHANGELOG.md?plain=1#L231

## Why

Since the rule is removed, it is causing an error such as this in the VS Code editor 

## Note

I am not sure why we're trying to exclude the `src/*` [folder](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/phpcs.xml#L38) since this is the folder where the bulk of the PHP files lives. I would think this is exactly the place we should lint? Perhaps you know cc @nielslange 

~~Also this is blocked by WooCommerce Sniffs need to be first updated to version `1.0.0` so we can use WP coding standards version `^3.0.0`.~~

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Have PHPCS installed globally.
2. Install the WooCommerce Sniffs `composer global require woocommerce/woocommerce-sniffs --dev` (version 1.0.0)
3. Add the PHPCS extension to your VS Code.
4. Change the execution path of the PHPCS extension to point to your globally installed PHPCS (use `which phpcs` to find the path).
5. Set the PHPCS extension standard to `WooCommerce-Core` in the `settings.json` like `"phpcs.standard": "WooCommerce-Core"`.
6. Open up a PHP file outside of `/src/*` and try to add a shorthand ternary operation and ensure PHPCS catches that. You can use `$foobar = true ?: false;`.

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> N/A

### CODE REVIEW

**Comment by nielslange** [comment]
> I am not sure why we're trying to exclude the `src/*` [folder](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/phpcs.xml#L38) since this is the folder where the bulk of the PHP files lives. I would think this is exactly the place we should lint? Perhaps you know cc @nielslange

Thanks for reaching out, @roykho. I see that with https://github.com/woocommerce/woocommerce-blocks/pull/5911/files, we introduced the following rule:

```xml
<rule ref="WordPress.PHP.DisallowShortTernary.Found">
    <exclude-pattern>src/*</exclude-pattern>
    <exclude-pattern>tests/*</exclude-pattern>
</rule>
```

Unfortunately, I cannot find any further information in the corresponding PR of why this rule had been added.

@mikejolley as you authored that PR, do you recall why it had been added, and why the `/src` and `/test` folders are excluded from this rule?

**Review by albarin — APPROVED** [review]
Works great!

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @roykho.

Currently, the testing instructions state:
> 1. Have PHPCS installed globally.
> 2. Install the WooCommerce Sniffs `composer global require woocommerce/woocommerce-sniffs --dev`
> 3. [...]

In `/package.json` we do have this definition:
https://github.com/woocommerce/woocommerce-blocks/blob/4b5ba05a3a0404b50473649e56396abe6e71b5e2/package.json#L67

I wonder if it wouldn't be better to adjust the testing instructions accordingly to use that command. 🤔

**Comment by roykho** [comment]
> I wonder if it wouldn't be better to adjust the testing instructions accordingly to use that command. 🤔

Probably not in this case because running that command will lint everything which indeed will flag errors for unchanged files. That can make it seem something went wrong. We can however include a test like `composer run phpcs woocommerce-gutenberg-products-block.php` to test a specific file.

**Comment by roykho** [comment]
I've pushed up changes to bump `woocommerce-sniffs` to `1.0.0`.

**Comment by gigitux** [comment]
> I've pushed up changes to bump `woocommerce-sniffs` to `1.0.0`.

Good idea! With the current version of `woocommerce-sniffs`,  the lint command doesn't work with PHP 8.x. I created an issue #11834

**Review by danielwrobert — COMMENTED** [review]
I've run through the steps in the test plan and everything works as described. 🎉 

However, as we've been discussing in Slack, the **PHP Coding Standards / PHP coding standards (pull_request)** check is still failing at the **Run PHPCS on all changed files** step.

Is it possible that it's failing because the rule has been updated and that subsequent runs will pass after this PR is merged? 🤔

**Comment by roykho** [comment]
Yeah because of the rule change, it runs the rule against all files it seems. I confirmed this via this test PR https://github.com/woocommerce/woocommerce-blocks/pull/12071 which is a dup of this PR here. Though looking at that specific action, I am not sure where it states to do that.

**Comment by roykho** [comment]
Closing ahead of the monorepo merge and will recreate there.

**Pull request closed without merging**
