### PR TITLE
Remove RawHTML used for notice translations

### PR DESCRIPTION
**Pull request by Aljullu**
Blocked by: #888.

Coming from https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/884#discussion_r315385440. We need to remove calls to `<RawHTML>` that were used to interpolate HTML tags with translations.

### Screenshots
image

### How to test the changes in this Pull Request:

1. In _WooCommerce_ > _Settings_ > _Products_ > _General_ > _Product ratings_ uncheck _Enable star rating on reviews_.
2. In _Settings_ > _Discussion_ > _Avatar Display_ uncheck _Show Avatars_.
3. Create a post with a _Reviews by Product_ block and verify notices are displayed correctly.

### Discussion
~This PR makes translation strings quite ugly and difficult to localize: `Product rating is disabled in your` and `store settings` are separate strings.~

@joshuatf ~how does it sound rewritting those notices to something like `Product rating is disabled in your store settings. <Read more>` or `Product rating is disabled in your store settings. <Modify them>` so the link is not in the middle of the sentence?~

### CODE REVIEW

**Comment by mikejolley** [comment]
Not keen on splitting these translation strings @Aljullu. Feels like very bad practice.

Could we not keep RawHTML if we escaped the translations too? i.e. `escapeHtml( __( ...`? @nerrad 

We could write a helper for this also to mimic WP core `esc_html__`

**Comment by nerrad** [comment]
> Not keen on splitting these translation strings @Aljullu. Feels like very bad practice.

Ya I agree here, splitting is a no-no.

So in this case can go the `escapeHTML` route for the translation string or this looks like it'd be an opportunity for us to try out a potential solution for interpolate strings here: https://github.com/WordPress/gutenberg/pull/16374/files#diff-c1413661ef0ce6f764ce37db98af136aR181-R190

I really want to get some real-world usage of it to see how it works.  If you guys are okay with it, we could just extract the code from the file I linked to and use that export for our needs?

**Comment by Aljullu** [comment]
> So in this case can go the `escapeHTML`

You mean doing something like this? 01d8ffa04016b3eb46539abe5170fb22b08ea0a6

> I really want to get some real-world usage of it to see how it works. If you guys are okay with it, we could just extract the code from the file I linked to and use that export for our needs?

It sounds good to me experimenting with this here. My only concern is about maintaining code that might get merged upstream but we will not be able to consume for some versions yet.

Before having duplicate code between Gutenberg and our repo, and considering we seem to only have this issue here and in the code touched in #884, I would prefer exploring other options that would be easier to maintain.

**Comment by Aljullu** [comment]
> Looks good, I wonder if it'd be worthwhile adding some tests to this with test cases (script tags etc) verifying we get the results we want?

Makes sense. Do you think we should extract it to a utils function or a component so we can reuse it in other components if needed?

**Comment by nerrad** [comment]
> Makes sense. Do you think we should extract it to a utils function or a component so we can reuse it in other components if needed?

I'm not sure.  While I think this way of handling interpolation is fine, the WordPress core i18n position is that basic html (`a`, `strong`, `em`) _should_ be in the translation string to help provide context for what is happening.  But to do that means we definitely _would_ need an interpolation solution along the lines of what I submitted to as a pull to GB.  

All that to say, I'm on the fence with whether we should continue with this pattern (and codify it in a util) or if we should just push this fix you have here and create an issue to have more robust solution going forward.

**Pull request merged**
