### PR TITLE
Update `filter by attribute` skeleton design

### PR DESCRIPTION
**Pull request by albarin**
This PR updates the `Filter by attribute` loading state according to the new designs.

Related to https://github.com/woocommerce/woocommerce-blocks/issues/6846

| Block | Loading |
| ------ | ----- |
| Screenshot 2022-08-29 at 15 18 17| Screenshot 2022-09-02 at 15 50 16|

#### User Facing Testing

1. Enable TT2 theme. Create a new page with an `All Products` block and a `Filter by attribute` block. Save the page.
2. Open the page in the frontend and check that the `Filter by attribute` block shows like the screenshot above while loading.
3. Try different combinations of the block settings (dropdown, show apply button, etc) and make sure the loading state makes sense and there are no regressions.
4. Repeat steps 1-3 with the Storefront theme.

### WooCommerce Visibility

* [X] WooCommerce Core
* [X] Feature plugin
* [ ] Experimental

> Update the Filter by Attribute loading state design.

### CODE REVIEW

**Comment by albarin** [comment]
@vivialice could you try it as well and give some feedback 🙏

**Review by dinhtungdu — COMMENTED** [review]
@albarin, I noticed in the design, we have 3 placeholders for checkboxes but testing this PR, I can see only one. Can you update that part? Otherwise, this is LGTM!

Side note: At first, I think there is a placeholder for each checkbox, but it's not practical in reality as we have to query for the attributes first.

**Comment by vivialice** [comment]
Hey! 👋  

So from what I understand we can't use a placeholder representing each line in the list because we don't check how many we have before displaying the loader. I'm guessing doing so would add extra loading time? Also, is it possible for the loading block to take up the same amount of space so the layout doesn't "jump"? 

If we cannot know in advance how many loading placeholder items to display, in the case of this block, we could show two lines to represent a list of items. Also, unless I'm mistaken most attributes are variations available for a product and should have at miniumum two options.

**Review by dinhtungdu — COMMENTED** [review]
I can confirm the placeholder now has two lines. Thanks for the update!

I notice when the current query is changed by another filter block, the placeholder for the attribute filter block is shown up again. Is that expected? I don't see other filter blocks have the same behavior. To reproduce:
1. Add filter by attribute, filter by price, and filter by stock to a page with the All Products block.
2. Visit the page on the front end.
3. Wait until the page is finished loading.
4. Check a stock option of the filter by stock block.
5. See the filter by attribute shows the placeholder.
6. See the price filter doesn't show the placeholder.

**Comment by tjcafferkey** [comment]
@albarin I don't think this is a blocker, but one thing that stood out to me is the spacing/margin around the title when its rendered vs when the placeholders there. If its an easy fix it might make it feel more smoother when replacing the placeholder with the title.

Screenshot 2022-09-06 at 11 32 44
Screenshot 2022-09-06 at 11 32 49

**Review by tjcafferkey — APPROVED** [review]
I have left a comment RE placeholder title margins, but other than that this LGTM!

**Pull request merged**
