### PR TITLE
Release: 2.7.0

### PR DESCRIPTION
**Pull request by Aljullu**
This is the release pull request for 2.7.0 of the WooCommerce Blocks plugin.

## Communication

This release introduces:

> Improvements and fixes to the Cart and Checkout blocks including better theme compatibility and a fix to an issue that was blocking users from placing an order after fixing an invalid cart number previously introduced.
> 
> This release also includes style improvements to product grid blocks and some styling fixes specifically targeting the Twenty Twenty theme.
> 
> Under the hood, there has been development related to the Single Product block and we introduced a feature gating system. Those two items should be transparent for the users so they are excluded from the changelog and the release post.

You can read the [full changelog](https://github.com/woocommerce/woocommerce-gutenberg-products-block/compare/release/2.7?expand=1#diff-eb6b6c90251ab33cee784713c451e6d8L121).

### Prepared Updates

The following documentation, blog posts, and changelog updates are prepared for the release:

**Release announcement:**

* "_[WooCommerce Blocks 2.7 release notes](https://woocommerce.wordpress.com/2020/06/09/woocommerce-blocks-2-7-release-notes/)_"

**Developer Notes** - The following issues require developer notes in the release post:

* #2428: a line is included in the release post which links to the [docs in the theming section](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/theming/product-grid-270.md).

**Relevant developer documentation:**

* We started a [Cart and Checkout Blocks theming](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/theming/cart-and-checkout.md) page in the docs. Currently it only includes documentation on how to style the 'item quantity badge', but the plan is to expand it in future releases.

* [x] The release includes a changelog entry in the readme.txt? [Click here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/compare/release/2.7?expand=1#diff-eb6b6c90251ab33cee784713c451e6d8L121).

## Quality

* [ ] Changes in this release are covered by Automated Tests.
    * Most changes included in this release are either behing a feature flag or are style fixes which are restricted to CSS or small markup refactors, so they are not covered by tests.

* This release has been tested on the following platforms:
    * [x] mobile
    * [x] desktop

* [ ] This release affects public facing REST APIs.
    * It doesn't.

* [ ] This release impacts **other extensions** or **backward compatibility**.
    * [ ] The release changes the signature of public methods or functions
        * No, it doesn't.
    * [ ] The release affects filters or action hooks.
        * No, it doesn't.

* [x] Link to **testing instructions** for this release: [See them in the docs](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/release/2.7/docs/testing/releases/270.md).

* [ ] The release has a negative performance impact on sites.
    * We hadn't noticed any performance regression with the changes included in this release.

* [x] The release has positive performance impact on sites. If checked, please document these improvements here.
	* #2577 moved the preview images out of JS, heavily reducing the size of several block scripts.
	* #2664 made it so dashicons imports are ignored, giving huge bundle size gains.
	* Some other PRs brought some other positive gains like #2587 and #2597.

### CODE REVIEW

**Comment by Aljullu** [comment]
# Testing notes and ZIP for testing

Zip file for testing: [in progress] 

## Cart and Checkout styles

- Create pages with the Cart and Checkout blocks.
- Check the styles of both pages and verify:
	- The Cart and Checkout headings match the styles inherited from the theme (#2597)
	- In Checkout, step progress indicators match the heading style and they don't have a background circle (#2649).
imatge
	- In Checkout, the item quantity badges are visible with dark backgrounds (with Storefront, you can change the background color in Appearance > Customize > Background) (#2619).
imatge
		- Try adding the code snippet from the [Cart and Checkout theming](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/theming/cart-and-checkout.md#item-quantity-badge) docs (you can do it via a child theme or directly in the browser devtools) and verify the item quantity badge styles update accordingly.
	- In general, verify there were no regressions introduced after 2.6.0.
- The Cart block title should be `Your cart (X items)` (#2615).
imatge
- Introduce an invalid credit card number and verify there is enough padding around the validation errors (#2662).
imatge
- In the editor, add the Cart block and verify the headings have the proper font size and there is margin below the `Proceed to Checkout` button (#2486).

| 2.6.0 | 2.7.0 |
| --- | --- |
| imatge | imatge |

### Specific themes
- [Hello theme](https://elementor.com/hello-theme/):
	- Verify the text inside the selects is visible on hover (#2647).
imatge
- Twenty Twenty:
	- Add the All Products block and the Hand-picked Products block in a page and verify (#2573):
		- That with the All Products block you can add the On Sale badge and it's correctly aligned in the editor and the frontend (before, it was always shown on top of the image).
imatge
		- The Hand-picked Products block discounted prices are not underlined.
imatge
	- Go to the Checkout block and verify font sizes look correct (they are inherited from the theme) (#2533).

## Cart and Checkout error flow (#2655)

### Scenario One: initial report fixed

1. On Checkout introduce an invalid card number `4000 0000 0000 0002`.
2. Try to place the order and notice the error `The card was declined`.
3. Replace the credit card number with a valid one (`4242 4242 4242 4242`).
4. Try to place the order again and verify the process works.

### Scenario Two: Trying to break via validation errors.

You'll need to be logged in with a user that has saved payment methods.

1. On checkout, select CC payment method and then select a saved payment method again.
2. Leave one of the required fields empty.
3. Submit the checkout which should cause a validation error on the field.
4. Fix the validation error
5. Submit again and checkout should complete using the selected saved payment method.

### Scenario Three: Variation of trying to break via validation errors.

1. On checkout, select CC payment method.
2. Fill out cc number that will trigger declined card (`4000 0000 0000 0002`).
3. After server response (with error), clear a required field.
4. Select saved payment method.
5. Submit the checkout -> this should produce a validation error.
6. Fix the field.
7. Submit the checkout and this should result in the purchase completing successfully.

### Scenario Four: Payment with Cheque after failed CC.

1. On Checkout, select CC payment method.
2. Fill out cc number that will trigger declined card (`4000 0000 0000 0002`).
3. After server response (with error), select cheque payment method.
4. Submit the checkout and this should result in the purchase completing successfully for the cheque payment method.

## No shipping methods placeholder when they are all disabled (#2543)
1. Disable all shipping methods from your store.
2. Edit a page with the _Checkout_ block and verify the 'no shipping methods' placeholder appears.

## Feature flags
* Verify you can't add the Single Product block.

## Single Product page regression (#2648)
* Go to a product page.
* Verify you can see the product images as usual.
imatge

### Product grid inconsistencies (#2428)
- Update a product so it has a very small image (100px or less).
- Add the All Products block and a PHP-based product grids block (Hand-picked products, for example) and verify:
	- Both of them have the same styles for prices.
	- Both of them scale up the small image.
_Handpicked products on top, All Products below:_
imatge
- Add the [code snippets](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/theming/product-grid-270.md#product-grid-blocks-style-update-in-270) from the theming docs to undo the changes and verify:
	- Hand-picked products block doesn't scale up the image anymore.
	- All Products block shows discounted prices in two lines.
_Handpicked products on top, All Products below:_
imatge

**Comment by nerrad** [comment]
Everything seems to check out in testing (the only thing I didn't test was using this [code snippet](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/theming/product-grid-270.md#product-grid-blocks-style-update-in-270)). 

However, I noticed a couple more things that I created issues for (I don't think they block this release - if someone is using twenty twenty for Woo, it's a horrible experience imo - and it's not even in our top list of theme usage):

- #2668 
- #2669

**Comment by Aljullu** [comment]
Thanks for testing @nerrad!

> However, I noticed a couple more things that I created issues for (I don't think they block this release - if someone is using twenty twenty for Woo, it's a horrible experience imo - and it's not even in our top list of theme usage):

Agree. We made some improvements to the blocks display in Twenty Twenty, but there is still a long way to go. The situation is better now than in previous releases, so I don't think it should block.

**Comment by Aljullu** [comment]
2.7.0 has been released in [GitHub](https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v2.7.0) and [WordPress.org](https://wordpress.org/plugins/woo-gutenberg-products-block/).

@nerrad should we merge this PR into `master` and after that update the versions to `2.8.0-dev`? Another options would be to close this PR and cherry-pick the changelog & testing instructions commits into `master`.

**Pull request merged**
