### PR TITLE
Remove minConstraint and maxConstraint from price filter state

### PR DESCRIPTION
**Pull request by Aljullu**
`minConstraint` and `maxConstraint` could be directly inferred from `results`, so there was no need to save them in the state.

### How to test the changes in this Pull Request:

1. Create a post with a _Price Filter_ block, an _Attributes Filter_ block and an _All Products_ block.
2. Preview the post.
3. Modify the filtered attributes and verify the _Price Filter_ min and max values update accordingly (there are no regressions).

### CODE REVIEW

**Comment by senadir** [comment]
I cannot seem to test this because of some bug in master that breaks the Filter by Price block when you select an attribute, not sure if related, reported it in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1194

**Comment by nerrad** [comment]
Don't merge this yet, I may have discovered a regression.

**Comment by Aljullu** [comment]
> I think this may be a case where implementing `useMemo` here might be unnecessary overhead though (the calcs are fairly performant) so we should probably remove usage?

Yes, I was wondering the same... Removed them in 4a81feb5b91188bda127a7f4ae79e27dcc5dab0e.

> Don't merge this yet, I may have discovered a regression.

Oh, let me know what's that about. I will leave this PR on-hold until then.

**Comment by nerrad** [comment]
@Aljullu I think removing this entire block will fix things (which means you can remove the implementations of `usePrevious` too):

```js
// Track min constraint changes.
useEffect( () => {
	if (
		minPrice === undefined ||
		minConstraint > minPrice ||
		minPrice === prevMinConstraint
	) {
		setMinPrice( minConstraint );
	}
}, [ minConstraint ] );

// Track max constraint changes.
useEffect( () => {
	if (
		maxPrice === undefined ||
		maxConstraint < maxPrice ||
		maxPrice === prevMaxConstraint
	) {
		setMaxPrice( maxConstraint );
	}
}, [ maxConstraint ] );
```

**Comment by mikejolley** [comment]
@nerrad That block is important and we discussed this before. It prevents the user set range being "stuck" if the min and max constraint grows. e.g. If I am filtering and it's showing 10-50, my range will be 10-50. If I remove a filter and the constraints become 0-100, without this block of code, my selected range will remain as 10-50.

**Comment by nerrad** [comment]
>  e.g. If I am filtering and it's showing 10-50, my range will be 10-50. If I remove a filter and the constraints become 0-100, without this block of code, my selected range will remain as 10-50.

Right, but that was also before we added the active filters.  In playing around with things I think the ux is a bit better in _keeping_ the selected range between filter selections (only bumping when the range is outside min max constraints for the selected queries).  Still should be put through the ringer of course but it seems to work nicely now that active filters are available.

**Comment by Aljullu** [comment]
> Notice how the max constraint is lost in this branch when selecting another attribute.

Good catch with that @nerrad! It turned out `minConstraint` and `maxConstraint` were assigned to `null` while loading and that messed up with the `useEffect()`. I did some refactoring and could get rid of that `useEffect()`, but would love somebody to take a look to verify I don't miss any regression.

There is a small behavior change, however. I tried explaining it with my own words, but I'm sure it will be clearer with two gifs, so here they go:

`master`:
Peek 2019-11-18 15-52-master

This branch:
Peek 2019-11-18 15-53-branch

I think this new behavior makes more sense, but don't mind changing it if it doesn't look good (it might require adding the `useEffect()` again, however).

**Comment by nerrad** [comment]
Hmm ya I see, so basically since max restraint less than 80 it gets automatically constrained to 50 via:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/83161d94960537de825696605070e2589650e56c/assets/js/blocks/price-filter/block.js#L107-L109

But since that is not saved to state (it's not an actual _selected_ value), removing that filter will restore what the previous constraint was with the attribute item de-selected. 

Other behaviour worth noting:

- The actual query run is affected (instead of running the price query using `min=10` and `max=50` when selecting "green", it runs a query using `min=10` and `max=80` because the max price wasn't updated for the actual query.  That's a problem because it leads to caching a query that will never get hit if the user changes a selection.

**Comment by Aljullu** [comment]
> But since that is not saved to state (it's not an actual selected value), removing that filter will restore what the previous constraint was with the attribute item de-selected.

Right, that's what I tried to showcase in the gifs above, I think the min/max prices shouldn't get stacked to the constraints every time the constraints change but only when the user intentionally moves the price sliders to match those constraints (not sure if I'm explaining it good enough :sweat_smile: , happy to continue in Slack if that would be easier for discussion).

> The actual query run is affected (instead of running the price query using `min=10` and `max=50` when selecting "green", it runs a query using `min=10` and `max=80` because the max price wasn't updated for the actual query.  That's a problem because it leads to caching a query that will never get hit if the user changes a selection.

Good point with that! If I'm not wrong that's happening also in `master`, right? I could reproduce it there, at least:
Peek 2019-11-19 10-44

Right after selecting _Green_ this query is made:
image
_(notice `max_price` is persisted from the previous query because when doing the first request we don't know the new `maxConstraint` so we can't set it to `undefined`)_

I agree this is a performance improvement we should try to fix, and I would be happy working on it, but probably it shouldn't block this PR?

**Comment by nerrad** [comment]
> I think the min/max prices shouldn't get stacked to the constraints every time the constraints change but only when the user intentionally moves the price sliders to match those constraints

It depends.  If the new constraints are the _same_ or inside the range of the previous selected values, then yes the new selection should stack to the new limits.  Example:  User selects 10 an 80 in a range from 0 to 100.  They select a filter that only has prices between a range of 10 to 40.  The _new_ selections for the price filter should be 10 and 40 (stacked to the constraints).  I think that's the behaviour we want.

> I agree this is a performance improvement we should try to fix, and I would be happy working on it, but probably it shouldn't block this PR?

Yes let's address this in another pull if necessary - if it's something you don't think we'll get to right away, then make sure there's an issue so we don't forget.

**Comment by Aljullu** [comment]
> It depends. If the new constraints are the same or inside the range of the previous selected values, then yes the new selection should stack to the new limits. Example: User selects 10 an 80 in a range from 0 to 100. They select a filter that only has prices between a range of 10 to 40. The new selections for the price filter should be 10 and 40 (stacked to the constraints). I think that's the behaviour we want.

Isn't this branch already working like this from a user perspective? After the steps you described, the internal component state would still be 10-80, but the UI would show 10-40. The user is not aware of the internal component state but this allows us to persist the price filter when other filters change if constraints get wider.

I think that's a better user experience than resetting the price filter every time the constraints match (or are narrower) than the selected price.

To give an example use case:
- On a price range of 0-100, I select 10-80.
- I select the _Green_ filter which returns products between 20 and 50.
- I select the _Purple_ filter. With both filters selected, there are products between 20 and 90.
- As a user, I would expect the price slider to be 20-80 (like in this PR) instead of 20-90 (like in `master`). If I didn't modify the price slider, I would expect my previous preference of 10-80 to be persisted even though I activated/deactivated attribute filters.

> Yes let's address this in another pull if necessary - if it's something you don't think we'll get to right away, then make sure there's an issue so we don't forget.

Issue created: #1232.

> There's a regression here compared with master.

What happened is that this PR was based on an old version of `master`. :smile: I merged the last version of `release/2.5` and that should work as expected.

**Pull request merged**
