### PR TITLE
add cursor:pointer to checkbox and radio fields

### LINKED ISSUE #8424: Cart and Checkout Blocks: Fix cursors for radio and checkbox inputs
## Describe the bug

All the checkbox and radio inputs used in the Cart and Checkout blocks don't have the correct cursor for hover states.

## To reproduce

1. Go to the Checkout Block, and make sure you have shipping and payments declared
2. Hover the checkbox input for billing and shipping addresses. Hover the label next to it.
3. Notice that the cursor does not change.
4. Scroll down to the shipping section and hover over one shipping radio input. Hover the corresponding label.
5. Notice the cursor does not change

## Expected behavior

The cursor should change to a pointer when hovering over a checkbox & radio input, as well as over their corresponding labels.
Disabled inputs and their labels should have the default cursor.

### PR DESCRIPTION
**Pull request by Sidsector9**
Fixes #8424 

Adds pointer cursor whenever radio and checkbox fields are hovered.

#### Steps to test

1. Add multiple shipping methods and enable multiple payment methods so that multiple radio input fields are shown on the Checkout page.
2. Add the Checkout block to the checkout page.
3. In the fix branch, observe all the radio/checkbox input fields on the Checkout page, hover over them and their associated labels and observe that the mouse cursor shows as a pointer.
4. Observe in the trunk branch, the cursor was shown as a mouse pointer instead.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add: pointer cursor to checkbox and radio input fields on the Checkout page.

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.2 
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.6.0
* PHP: 8.0.22
* Web Server: Nginx
* Browser: Chrome - Version 111.0.5563.64 
* OS: macOS Monterey V 12.3.1


</Details>

**Steps to Test-** 
1. Navigate to the page where you have added the Checkout block.
2. Add a product to your cart by going to your website's shop page, selecting a product, and clicking "Add to Cart."
3. Click the "Checkout" button to test the checkout block. 
4. Fill in the required fields in the checkout form, such as billing and shipping information, payment options, and order summary.
5. Hover the mouse over all radio buttons, checkboxes, and check the cursor changes to a hand pointer.




**Test Results -**  
 
The cursor pointer functionality on the WooCommerce Checkout block has been tested and works correctly. Therefore, this feature is considered to be working as expected. 



**Functional Demo /  Screencast -**

https://user-images.githubusercontent.com/6384299/233110955-e280d0ec-8757-4660-b460-88a30324a93f.mp4


**QA Status-**  Pass ✅

**Comment by ankitguptaindia** [comment]
🤚🏼 Discussion Item - 
----


This PR fulfills the requirement and fix the issue mentioned in the connected issue. https://github.com/woocommerce/woocommerce-blocks/issues/8424

For some better UX, can we add cursor pointer to the input fields like "Country / Region" and "State" on the checkout block?



**Currently -** 


https://user-images.githubusercontent.com/6384299/233116534-7e404e31-1f43-4e30-b65a-50939b807cc7.mp4


**Expected -** 

https://user-images.githubusercontent.com/6384299/233117298-14c4d822-4042-4bda-8ff1-64361724d2ec.mp4


In the above screencast, you can see the difference, all country names have cursor pointers. 
Please let me know if we will fix this in a separate PR. If yes, I will report as a separate issue.

**Comment by opr** [comment]
> For some better UX, can we add cursor pointer to the input fields like "Country / Region" and "State" on the checkout block?

Hi, thanks for the suggestion and the discussion point! I would love to hear more of thoughts on this.

Personally, I don't agree that this would be a better UX. The input fields we are using are a "combobox", i.e. a text input that shows some options that narrow down as the user types. I don't think there's any benefit to having the cursor change to a pointer here. What do you think?

**Review by opr — APPROVED** [review]
Hey, I tested this out and it's working well! Thank you for contributing to WooCommerce Blocks!

I am wondering if you could add some testing steps to your PR, they can be super simple, but should definitely include necessary steps to get radio/checkbox inputs showing in both the Cart and Checkout blocks. (e.g. enabling the shipping calculator and having more than one shipping method).

Could you also confirm you carried out the checks listed in the body, relating to accessibility? The "Other checks" section does not need to be completed as the questions are all false.

Besides this, I will approve the PR, and await your changes to the description before merging.

**Comment by wavvves** [comment]
Hi @Sidsector9, thank you so much for working on this 👏🏼 

Following @opr 's comment, maybe you can copy the testing steps @ankitguptaindia mentioned on his QA testing to the description:

> 1. Navigate to the page where you have added the Checkout block.
> 2. Add a product to your cart by going to your website's shop page, selecting a product, and clicking "Add to Cart."
> 3. Click the "Checkout" button to test the checkout block.
> 4. Fill in the required fields in the checkout form, such as billing and shipping information, payment options, and order summary.
> 5. Hover the mouse over all radio buttons and checkboxes, and check the cursor changes to a hand pointer.

I also reviewed the PR, and everything works as expected. As soon as the description is updated, we can proceed to merge and close this 🎉

**Review by wavvves — APPROVED** [review]

**Review by nielslange — COMMENTED** [review]
Hallo @Sidsector9 👋 Thank you so much for your contribution. Do you think it's possible to add testing steps to the PR description? This will help a lot in the future when this PR will get merged into the WooCommerce core. 😀

**Comment by Sidsector9** [comment]
@nielslange I added the testing steps.

**Comment by nielslange** [comment]
> @nielslange I added the testing steps.

Thanks a lot for adding the testing steps, @Sidsector9. I just merged the PR, and you'll see the change in an upcoming WooCommerce Blocks release! 🎉

**Comment by ankitguptaindia** [comment]
>Personally, I don't agree that this would be a better UX. The input fields we are using are a "combobox", i.e. a text input that shows some options that narrow down as the user types. I don't think there's any benefit to having the cursor change to a pointer here. What do you think?

Hi @opr Thanks for your review. That makes sense, I agree with you if this is ''Combobox"

**Pull request merged**
