### PR TITLE
[Store Customization MVP] Ensure the AI-generated content in patterns is updated on plugin update

### LINKED ISSUE #11166: Store Customization > Schedule an action to update the wc_blocks_patterns_content option
We need to ensure that an action is scheduled on plugin update to ensure the AI-generated content in patterns is updated within the `'wc_blocks_patterns_content'` option, ensuring it is always in sync with the default content within the patterns dictionary.

### Details

With this change we can avoid the following problem:

* User updated the content in patterns using AI: now all content is fetched from the `'wc_blocks_patterns_content'` option.
* We change one of our patterns and add a new title to it in the patterns dictionary (in the `dictionary.json` file) & update the reference on the pattern itself.
* User with AI-generated content updates the Woo Blocks plugin and is now immediately greeted with a PHP warning of undefined index since AI content was never generated for the newly introduced title in the pattern (the DB is not in sync with the patterns dictionary).

Complementing this change, we also have to update all patterns to ensure they have an empty fallback and prevent the warning in case something prevents the scheduled action from running (we can adopt an approach similar to what was made on https://github.com/woocommerce/woocommerce-blocks/pull/11158 ).

### PR DESCRIPTION
**Pull request by albarin**
## What

This PR updates the patterns content when a plugin update happens.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11166

## Why

We need to refresh the content of the pattern in case there was any change to the patterns in the `dictionary.json` to avoid errors. For more content check #11166.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

**Initial setup**
1. Create a Jurassic Ninja site with WooCommerce.
2. Connect JetPack.
3. Install the plugin zip from this PR (https://wcblocks.wpcomstaging.com/wp-content/uploads/woocommerce-gutenberg-products-block-11210.zip)
5. Install the [woo-ai](https://github.com/woocommerce/woocommerce-blocks/files/12882468/woo-ai.zip) plugin.
6. Go to your store `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features` and enter a description for your store (like `A store selling books and magazines`).

**Simulating plugin update**
1. Go to the file editor and in WooCommerce Blocks plugin, in the `woocommerce-gutenberg-products-block.php` file modify the `woocommerce-gutenberg-products-block.php` plugin file and change the `* Version: 11.4.0-dev` comment to some lower version `* Version: 10`.
2. Go to your store plugin's page, you should see the `WooCommerce Blocks` plugin with the version you just changed and a message to update the plugin.
3. Click on it to update the plugin.
4. Go to the Scheduled Actions and make sure a new `woocommerce_update_patterns_content` action is scheduled.

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Update the patterns content after a plugin update.

### CODE REVIEW

**Comment by nefeline** [comment]
Hey @albarin ! 

Regarding:

> Note: the original idea was to schedule an action after the plugin update, but it seems to be to early to use the action scheduler, I was getting an error was called before the Action Scheduler data store was initialized.

We can rely on https://developer.wordpress.org/reference/hooks/upgrader_process_complete/ for this purpose: I hope you don't mind: I went ahead and pushed a commit for this over here :)  https://github.com/woocommerce/woocommerce-blocks/pull/11210/commits/bef445954dda02aecaf22b1440157cae909dd83e

I tested and it works as expected, do you mind running a test as well to confirm? We could then clear out the previous changes made and merge the PR if things are working as expected.

**Comment by tjcafferkey** [comment]
The action was scheduled but had a status of `Failed`. I don't know whether this was expected, but if it _was_ then feel free to approve & merge.

Screenshot 2023-10-14 at 10 33 59

**Comment by albarin** [comment]
> The action was scheduled but had a status of `Failed`. I don't know whether this was expected, but if it _was_ then feel free to approve & merge.
> 
> Screenshot 2023-10-14 at 10 33 59

It was not expected to fail, I could reproduce this as well. After some investigation, I saw that when installing the plugin from the zip file, the plugin folder is called `woocoomerce-gutenberg-products-block`, but after the update the folder name is changed to `woo-gutenberg-products-block` and then we get this error:
Screenshot 2023-10-16 at 11 42 16
The action was scheduled but since the plugin is disabled it fails.

I tried renaming the plugin zip to `woo-gutenberg-products-block` before installing the plugin (that way it has the same name it will have after updating) and it works just fine.

I'm not sure what we can do or if this will be a problem in real installation or if it's just because we do this hacky thing to simulate the update. 🤔

**Comment by nefeline** [comment]
Hey team!

Regarding:

> I'm not sure what we can do or if this will be a problem in real installation or if it's just because we do this hacky thing to simulate the update. 🤔

I believe this problem is associated with how we are attempting to update the plugin in this case: How about we just ensure the WP install has an older version of WooCommerce core and update it instead as a confirmation that things are working as they should?

Considering the `'upgrader_process_complete'` action is fired only **after** the upgrader process is complete, it is expected for the action to be scheduled only after the newest version is already in place, not before.

quick sidenote: the scheduled action will naturally fail if the WP install is not connected to Jetpack or if for some reason there's a problem with this connection.

**Comment by albarin** [comment]
> I believe this problem is associated with how we are attempting to update the plugin in this case: How about we just ensure the WP install has an older version of WooCommerce core and update it instead as a confirmation that things are working as they should?

Sorry, I'm not sure I'm following how you are proposing to test the update 😅 
I think the scheduling in the PR works, it's just hard to test.

**Review by nefeline — APPROVED** [review]
> Sorry, I'm not sure I'm following how you are proposing to test the update 😅
I think the scheduling in the PR works, it's just hard to test.

I'm sorry I wasn't super clear earlier. Sharing here a video recording as an example:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/1fd7f5f2-4a83-41a6-89a6-e2afdc328cb9

As defined here:
https://github.com/woocommerce/woocommerce-blocks/blob/4e3e81f265692ad9d7b0295c4e0046e41a67c291/src/BlockPatterns.php#L227

We are scheduling the action when the WooCommerce Blocks plugin is updated **and** when WooCommerce itself is updated as well. So for testing this PR in particular, the easiest route is to install an outdated version of WooCommerce via WP-CLI (or any other preferred way): `wp plugin install woocommerce --version=8.2.0 --activate --force` and update it via user interface to confirm the action was scheduled.

Since I've just confirmed things are working as expected, I'm going ahead and approving the PR: great work @albarin!

**Pull request merged**
