### PR TITLE
Performance: preload store pages

### LINKED ISSUE #6498: Call `prime_post_caches` in `get_store_pages` method.
## Describe the bug

In `AssetDataRegistry` [get_store_pages](https://github.com/woocommerce/woocommerce-blocks/blob/83a3e648834ee400db41281e5cdff6d3c118b490/src/Assets/AssetDataRegistry.php#L141), an array of posts objects are loaded using array map. This results in a single database query per post. Instead of doing it this way, call the [_prime_post_caches](https://developer.wordpress.org/reference/functions/_prime_post_caches/). This can be done simple like this.

```
	protected function get_store_pages() {
                $page_list = [
				'myaccount' => wc_get_page_id( 'myaccount' ),
				'shop'      => wc_get_page_id( 'shop' ),
				'cart'      => wc_get_page_id( 'cart' ),
				'checkout'  => wc_get_page_id( 'checkout' ),
				'privacy'   => wc_privacy_policy_page_id(),
				'terms'     => wc_terms_and_conditions_page_id(),
		];
                 $post_ids = array_values( $page_list );
                 _prime_post_caches( $post_ids );
		return array_map( [ $this, 'format_page_resource' ], $page_list);
	}
```

### WordPress (please complete the following information):

-   Core version: [e.g. 5.9]
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1]
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #6498

This PR implements the @spacedmonkey's suggestion of using `_prime_post_caches` to improve the plugin performance.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

<table>
<tr>
	<td> trunk (without `_prime_post_caches`)
	<td> with `_prime_post_caches`
<tr>
	<td> image
	<td> image

</table>

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Install and activate Query Monitor.
2. Open a Cart page (using Cart block) on the front end.
3. Observe the number of queries called by `WP_Post`.
4. Check out the `trunk`, and load the Cart page again.
5. See more queries called by `WP_Post` than this PR.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Improve performance for `get_store_pages` method.

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
While I understand the rationale of the change, when testing with Query Monitor I see this branch makes one additional query compared to `trunk`, that's because I get an extra query produced by `update_meta_cache()`. Then, there is another query from `WP_Post->get_instance()` that is not done but instead it's done by `_prime_post_caches()`, so in the end there is no win in this side.

Am I look at the wrong things?

**Comment by dinhtungdu** [comment]
> Then, there is another query from WP_Post->get_instance() that is not done but instead it's done by _prime_post_caches(), so in the end there is no win in this side.

@Aljullu I have similar doubts as yours, you can see it from my comments on that linked issue. The reason I create this PR is, in my test, this PR saves two queries called by `WP_Post::get_instance`, this doesn't help much for sites with persistence cache installed but will help the sites that don't. I consider saving `WP_Post::get_instance` queries is a win.

**Comment by peterwilsoncc** [comment]
It's possible to prevent the meta caches from being warmed by setting the third parameter to `false`:

```php
_prime_post_caches( array_values( $store_pages ), true /* term cache */, false /* meta cache */ );
```

I'm not familiar enough with the WooCommerce code base to advise whether it's wise to warm the meta and term caches or not.

**Comment by Aljullu** [comment]
Honestly, I'm not 100% sure about this PR, another thing that worries me is that [`_prime_post_caches()`](https://developer.wordpress.org/reference/functions/_prime_post_caches/) is a private function and I don't know if we should be using it in a plugin.

> I consider saving `WP_Post::get_instance` queries is a win.

Just curious, why do you think saving a `WP_Post::get_instance` query is a win over other queries?

To keep moving this forward, and given that this PR modifies code maintained by Rubik, I think it would be useful to hear from them as well. So tagging them for review. :slightly_smiling_face:

**Comment by peterwilsoncc** [comment]
> another thing that worries me is that [`_prime_post_caches()`](https://developer.wordpress.org/reference/functions/_prime_post_caches/) is a private function and I don't know if we should be using it in a plugin.

FYI, this was changed last week in https://github.com/WordPress/wordpress-develop/commit/541b4eb6462c8f48e235590a9be79ebc4954f66e for [WP#56386](https://core.trac.wordpress.org/ticket/56386)-- cache priming functions are now considered public functions and plugin devs are encouraged to use them. This will be mentioned in the field guide for WordPress 6.1

**Comment by nerrad** [comment]
Tagging in @mikejolley here as you may be able to provide some guidance around whether there's value in using this to warm meta & term caches or not.

**Comment by mikejolley** [comment]
> Tagging in @mikejolley here as you may be able to provide some guidance around whether there's value in using this to warm meta & term caches or not.

In this application, we're only interested in ID, post_status, Title, and Permalink—we don't seem to be concerned with meta and term data, so turning those off could save some time when priming.

That said, it's unclear if anything else in WooCommerce or Blocks is using that data, so it might be worth toggling them on/off and seeing how it impacts the total number of queries in an average request.

Other than that, it's only a small change, so I'm happy to see `_prime_post_caches` used here 👍🏻 To be extra cautious, you could wrap it as we do here: https://github.com/woocommerce/woocommerce-blocks/blob/9f9acf943a8fad682428fd6ab2201910379c0c81/src/BlockTypes/AbstractProductGrid.php#L363-L365

**Review by mikejolley — APPROVED** [review]

**Review by spacedmonkey — APPROVED** [review]

**Review by tarunvijwani — APPROVED** [review]

**Comment by dinhtungdu** [comment]
Merging with failed E2E tests which are related to the translation of the Cart and Mini Cart blocks.

**Pull request merged**
