### PR TITLE
Add new `Product collection banner` pattern

### LINKED ISSUE #9934: Add new `Product collection banner` pattern
Maybe think of a better name. We need to find an image, since the link in this one was broken.
Screenshot 2023-06-21 at 11 26 53

### PR DESCRIPTION
**Pull request by albarin**
This PR adds the new `Product collection banner` pattern.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9934

### Screenshots
Note: the link in this screenshot was broken.

#### User-Facing Testing

1. Create a new post or page.
2. Insert the `Product collection banner` pattern and save.
3. In the front end, check the pattern looks like the image above and the `Shop now` button links to the shop page.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add new `Product collection banner` pattern

### CODE REVIEW

**Review by nefeline — COMMENTED** [review]
Nice work 🎉 !

Confirmed everything works, although the image on this pattern is not matching the one in the PR description: is that expected?

Screenshot 2023-06-23 at 13 27 46

**Review by thealexandrelara — COMMENTED** [review]
Code looks good and it is working as expected. Just want to make sure that the image is correct as pointed out by Patricia

**Comment by albarin** [comment]
@nefeline @thealexandrelara I've updated with a new image from pxhere, same place where Shaun got the other ones, let me know what you think about it, it may be a better fit than the other one :)

**Comment by nefeline** [comment]
> I've updated with a new image from pxhere, same place where Shaun got the other ones, let me know what you think about it, it may be a better fit than the other one :)

Was the decision for us to use our best judgment and select another image until @shaunandrews is back? I saw the convo with @danielwrobert on Slack but wanted to double-check. If that's the case, all good!

**Comment by albarin** [comment]
> > I've updated with a new image from pxhere, same place where Shaun got the other ones, let me know what you think about it, it may be a better fit than the other one :)
> 
> Was the decision for us to use our best judgment and select another image until @shaunandrews is back? I saw the convo with @danielwrobert on Slack but wanted to double-check. If that's the case, all good!

I know Dan was searching for images but he didn't say if he found anything in the end. I don't think we agreed on anything concrete, I'll ping Jarek to have his opinion as well.

Screenshot 2023-06-26 at 11 33 42

**Comment by nefeline** [comment]
> I know Dan was searching for images but he didn't say if he found anything in the end. I don't think we agreed on anything concrete, I'll ping Jarek to have his opinion as well.

👍 Sounds good!

**Comment by jarekmorawski** [comment]
Hi there! I think Shaun intended to showcase travel services or leisure products in this block, so [this image](https://pxhere.com/en/photo/647934) could fit well. We should center it to keep the composition. Please send me the dimensions if you need it cropped.

**Review by roykho — APPROVED** [review]
LGTM!

**Pull request merged**
