### PR TITLE
Add product hero pattern

### LINKED ISSUE #9109: Create `Product details: product hero` pattern
Product Hero (Wide)

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33716 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9109

This PR adds the `Product Hero` pattern.

Note that the image supplied is more portrait than landscape so it will not look exactly like the one https://github.com/woocommerce/woocommerce-blocks/issues/9109

#### User Facing Testing

1. Create a page/post and use the block inserter->patterns->WooCommerce->Product Hero | Wide
2. Update/save and ensure the design is close to the suggested design seen below.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add product hero pattern

### CODE REVIEW

**Comment by albarin** [comment]
> Another issue is in the WP editor, this pattern's preview shows a list of products to choose which is not ideal. This happens because the block doesn't have reference to what product to use and therefore will not show any specific product.

I'm not sure what to do with that, it's not great, it's unlikely anyone will choose the pattern without the preview. The only way I see right now it's not to use the `Single Product` block and build the patterns just with rows, columns, images, buttons, etc.

> Another thing I was not able to accomplish is making the product image landscaped mode. I don't believe you can change the product image ratio/size in the single product block.

Maybe for this we can try to use the `Post featured image` block instead, I think it provides more options in terms of dimensions (aspect ratio, etc).

**Comment by roykho** [comment]
If we don't use the single product block then I am not seeing this pattern as very useful other than giving them an visual idea which then we don't actually need a pattern and a simple example documentation would do.

If we used only WP core blocks, they would have to remove almost everything to either put in a single product block or add their own individual parts of single product block (which I don't think we support?). WDYT? cc @shaunandrews 

Also note that I believe the Single Product Block is still in experimental and many things are not ironed out yet. Perhaps when it is complete, it will have more options to manipulate the image size/ratio... show/hide quantity etc?

**Comment by roykho** [comment]
I've updated the pattern to use WP core blocks instead of the Single Product Block.

**Review by albarin — APPROVED** [review]
Good job! 👏

**Pull request merged**
