### PR TITLE
Product Image Gallery block: Fix overflow when multiple images are used

### LINKED ISSUE #9944: Product image gallery overflow (?) to the next one
## Describe the bug

when the blockified single product template is turned on, depending on the column width, the second image may overflow into the first one.
Screenshot 2023-06-21 at 7 19 56 PM

I managed to fix the issue by setting the column width of the product image to 40%

Screenshot 2023-06-21 at 7 22 33 PM

Screenshot 2023-06-21 at 7 21 02 PM

## To reproduce

1. enable the blockified product template
2. create a new product 
3. set a cover image and gallery images

## Expected behavior

Every photo should stay in its own slide.

This behavior may depend on the image size, but it's never mentioned how big the images should be.

### PR DESCRIPTION
**Pull request by thealexandrelara**
## Description
Fix a bug that was causing images to overflow when using the Product Image Gallery block.

### <samp>🤖 Generated by Copilot at 5d8c36a</samp>

* Fix product image responsiveness and overflow issue by changing CSS selector and width property ([link](https://github.com/woocommerce/woocommerce-blocks/pull/10013/files?diff=unified&w=0#diff-8832fcfeefd6161e24404f8912dab1c267c44243bc00c1fdc67ff923d154dfceL21-R23))

Fixes #9944

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
| image  | image |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Log in to your WordPress dashboard.
2. Navigate to the "Products" tab in the left-hand sidebar and click on "All Products."
3. Locate and select the product you want to edit from the list of existing products.
4. Scroll down to the "Product Image" section. If the product already has a primary image, you can replace it by clicking on the "Set product image" link. If there is no existing image, you will see an "Add product image" button instead.
5. You'll be presented with options to upload an image. `Select an image with size 512 x 640 pixels`. Click on the "Set product image" button to confirm.
6. To add additional images to the product gallery, scroll down further to the "Product Gallery" section. Click on the "Add product gallery images" link.
7.  Follow Step 5 to upload or select the additional images for the product. You can use the same image used in step 5.
8. Click on the "Update" button to save your changes.
9. From your WordPress dashboard, go to Appearance > Themes. Make sure you have a block-based theme installed and activated. If not, you can install one from the Add New option. Block-based themes include "Twenty-twenty Two," "Twenty-twenty Three," etc.
10. On the left-hand side menu, click on Appearance > Editor. This will open the Site Editor.
11. On the left-hand side menu, click on Templates. This will open the list of available templates.
12. Find and select the 'Single Product' template from the list.
13. When the Classic Product Template renders, click on Transform into Blocks. This will transform the Classic template in a block template if you haven't done it before.
14. On the top-right side, click on the Save button.
15. Visit the product that you edited the image and check that the Product Image Gallery block is being displayed correctly and without any overflow.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Review by danieldudzic — CHANGES_REQUESTED** [review]
The fix does address the issue but alters behavior for images that are smaller than the container width. The image gets stretched to match the container width and gets pixelated.

| Before | After |
| ------ | ----- |
|  V-Neck_T-Shirt_–_kirigamii-2 | V-Neck_T-Shirt_–_kirigamii |

I'm not sure we should be doing this. I'm happy to look into this further tomorrow :)

**Comment by thealexandrelara** [comment]
> The fix does address the issue but alters behavior for images that are smaller than the container width. The image gets stretched to match the container width and gets pixelated.
> 
> I'm not sure we should be doing this. I'm happy to look into this further tomorrow :)

Interesting, it seems the image that you used is really small, and that is causing the image to stretch to occupy all the available space. I think it's going to take more time for me to investigate it, and test different scenarios, I'll continue tomorrow, Thank you for quickly reviewing this 🙌 .

**Comment by thealexandrelara** [comment]
Hey @danieldudzic,
I was looking at the implementation for the Product Image Gallery in WooCommerce and here is what I found:
- The width of the gallery is set to 48% of the parent component;
- The Product Image Gallery was designed to work inside the classic Single Product page, and the content width for that page is 1064px. If we get 48% of the page width, we get the maximum image gallery width size: 510,72px

Considering that, I came up with the following solution:
- The max-width for the Product Image Gallery block was set to 512px - this matches the Single Product template and allow images to have different sizes without breaking the layout and without the need to scale them to fit the whole space
- The default width for the column that wraps the Product Image Gallery block in the Single Product template was set to 512px - to match the width size of the gallery

Let me know what you think, or if you have a better solution than that. Right now, after testing multiple combinations of properties and values I couldn't figure out a simpler and better way to fix this

**Review by gigitux — APPROVED** [review]
LGTM

**Pull request merged**
