### PR TITLE
Add previews to some Product grid blocks

### LINKED ISSUE #1030: On Sale Products - add preview
Add an example preview to the block in the Inspector.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1030.

This PR adds previews to: _Products on Sale_, _Best Selling Products_, _Newest Products_ and _Top Rated Products_ blocks and make it easy to add previews to other product grid blocks.

### Screenshots

Peek 2019-10-23 14-41

### How to test the changes in this Pull Request:

1. Create a post and, using the top bar inserter, hover the _Products on Sale_, _Best Selling Products_, _Newest Products_ and _Top Rated Products_ blocks.
2. Verify all of them show a preview of the block.

### Changelog

> Added Previews to  Products on Sale, Best Selling Products, Newest Products and Top Rated Products blocks.

### CODE REVIEW

**Comment by mikejolley** [comment]
I've updated this PR with some different handling of previews so that they only render sample products when no results are returned.

There is an issue with alignment of long content which I'm reporting on the Gutenberg repo.

**Comment by nerrad** [comment]
Just changed the sharedExamples object to use 1 row and this keeps the margins looking a _little_ bit better... at least there is no overflow.

**Comment by nerrad** [comment]
Okay so this pull needs a decision we could use some feedback on what route to go for this pull (cc @jwold and @pmcpinto ).  The issue is identified by @mikejolley [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1064#issuecomment-546959779).

Essentially, there's a big with the GB previews where the viewport size is not recalculated when a block changes it's content in rendering (surfaces predominantly with Server Side Rendered blocks).

There's some options we have:

A. Limit the preview to one row for these blocks and keep live previews (when a site has products).

Example:

example preview with one row

- This _could_ still have issues with long product titles that can make the top and bottom margins appear more unequal.
- when the GB bug is fixed, things will "just work" and we wouldn't need to revisit this.
- From the end-user's perspective, they won't know this is a GB bug, it'll just appear as something wrong with our block previews.
- There is a bit of a performance hit with SSR in that everytime one of these blocks is previewed there is a network request (we might be able to cache the results to prevent this but it could be tricky).

B. Just show a static image.

- it should look much better in the preview.
- we have more control over it's appearance
- eliminate the performance issues of SSR with no extra coding.
- down the road we can swap this out for something else (as the preview feature in GB matures we likely will have more options).

I'm leaning towards Option B - if we go that route, it'd be great to get an image to use from you @jwold for each of the blocks in this pull (see the original pull description for the affected blocks).

**Comment by jwold** [comment]
I prefer option B for right now. Based on the description at the top, it looks like these are the ones:

- Products on Sale
- Best Selling Products
- Newest Products
- Top Rated Products blocks

Is that correct @nerrad?

**Comment by pmcpinto** [comment]
I also agree that option B seems to be the best path.

**Comment by mikejolley** [comment]
Marking this as blocked since it's awaiting images cc @woocommerce/blocks

**Comment by mikejolley** [comment]
@jwold There are some others too - products by attributes, product category. They are appear the same using a grid.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1118 for updated PR.

**Pull request closed without merging**
