### PR TITLE
Update to node 16/npm 8

### PR DESCRIPTION
**Pull request by alexflorisca**
This PR updates the repo to use the current LTS of node and syncs .nvmrc and `package.json` engines to the same version (v16.13.0). I've moved away from `lts/*` in order to avoid automatically switching major versions. I think it's good practice to do these upgrades manually and cautiously but if anyone feels the opposite let's discuss :)

I've tested with install, build, run and test scripts and everything seems fine. The only problem I can foresee is releasing which I don't know too much about yet, so thoughts around that would be appreciated.

### Manual Testing

How to test the changes in this Pull Request:

1. Check that all the Github actions are green
2. Pull this branch to your local machine
3. `nvm install` or `nvm use` should switch you to use version ^16.13.0 and npm version ^v8.0.0
3. `npm run build` should build successfully
4. `npm run start` should run successfully
5. `npm run test` should run successfully

### Changelog

> Updated to node version ^16.13.0 and npm version ^v8.0.0

### CODE REVIEW

**Comment by senadir** [comment]
This should wait until we merge https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5223

**Comment by ralucaStan** [comment]
ℹ️  woocommerce/woocommerce-blocks#5223 was merged.

**Comment by alexflorisca** [comment]
@ralucaStan Thanks for letting me know it's been unblocked, I've fixed the merge conflict and just needs your review :)

**Review by ralucaStan — COMMENTED** [review]
The steps in Manual Testing test out fine. 
I've noticed that `npm run storybook` does not work.

I see that we now are adding npm 8 to the project, but [npm 7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) actually brings a new lockfile format (v2), which is backwards compatible with npm 6 users. 

> Running npm install with npm 7 in a project with a v1 lockfile will replace that lockfile with the new v2 format. To avoid this, you can run npm install --no-save.

This means that running `npm i` will also change the `package-lock.json` file for each contributor locally. 
I wonder how we should avoid this? Should we include the `package-lock.json` file here as well?

**Comment by alexflorisca** [comment]
> I've noticed that npm run storybook does not work.

This is an issue on trunk I've noticed yesterday and I will try to fix today, it's not related to this PR, but to [this one](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5223) I think.

> 	"lockfileVersion": 2,

Looks like the [package-lock.json](https://raw.githubusercontent.com/woocommerce/woocommerce-gutenberg-products-block/trunk/package-lock.json) file on trunk is already the v2 format, probably because renovateBot updated it at some point. If anyone uses npm < 7 to `npm install`, a warning is thrown:

> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

We just need to make sure that the whole team knows to upgrade to node 16/npm 8 when working on the repo. I think we can do that with a P2 or in slack?

**Comment by ralucaStan** [comment]
We also need to wait for this p1639053028462100-slack-C8X6Q7XQU before merging

**Comment by ralucaStan** [comment]
> Looks like the package-lock.json file on trunk is already the v2 format

I've tried rebasing trunk locally into this branch and there is a conflict in package-lock.json. Maybe we should rebase the PR as well and fix this conflict before merging

**Comment by ralucaStan** [comment]
> I think we can do that with a P2 or in slack?
A P2 sounds better, we could also mention it in the Weekly Async meeting

**Comment by alexflorisca** [comment]
> I've tried rebasing trunk locally into this branch and there is a conflict in package-lock.json. Maybe we should rebase the PR as well and fix this conflict before merging

Yep, I've already re-based once but I guess there must have been more changes to trunk since then which change the package-lock.json. We should do this just before we merge to make sure we don't have to do it multiple times.

**Comment by alexflorisca** [comment]
@ralucaStan Ok this should be good to go. I've rebased trunk on this branch, ran `npm install` and commited the newly generated `package-lock.json` which now has `version: 2`. 

One thing to mention is that the `eslint-plugin-woocommerce` package is restricted to `node < v15` and `npm v6.x.x ` and we get a warning (not an error) when we run `npm install`. Everything seems to work regardless, but maybe we could see if we could update the dependencies in that package too?

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-woocommerce@0.0.2',
npm WARN EBADENGINE   required: { node: '>=12.0.0', npm: '>=6.14.0 <7' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

**Comment by ralucaStan** [comment]
> One thing to mention is that the `eslint-plugin-woocommerce` package is restricted to `node < v15` and `npm v6.x.x ` and we get a warning (not an error) when we run `npm install`. Everything seems to work regardless, but maybe we could see if we could update the dependencies in that package too?

From the errors I receive it looks like it does not like npm >= 7 : `required: { node: '>=12.0.0', npm: '>=6.14.0 <7' }`
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-woocommerce@0.0.2',
npm WARN EBADENGINE   required: { node: '>=12.0.0', npm: '>=6.14.0 <7' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

From what I saw this is an [internal package ](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/bin/eslint-plugin-woocommerce/package.json#L8-L11). @mikejolley was the last one to modify the requirements from this package, maybe he can help here. Can we also update the npm version. Is there a reason this is restricted to `npm < 7`? 

I'm ok with also handling this in another PR.

**Comment by mikejolley** [comment]
@ralucaStan I understood these were the only supported versions. I had issues building with newer versions. They need to change with this PR.

**Comment by alexflorisca** [comment]
@mikejolley How come we have the `eslint-plugin-woocommerce` file hardcoded in the repo and not using the [@woocommerce/eslint-plugin](https://www.npmjs.com/package/@woocommerce/eslint-plugin) package? A quick test of installing that package and running `npm run lint` seems to work for me.

**Comment by mikejolley** [comment]
@alexflorisca Custom rules? https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1696

**Comment by alexflorisca** [comment]
After some failed github actions and some back and forth, it looks like everything builds successfully with `npm 8`. I think this is good to go now unless you can think of anything I've missed @ralucaStan @mikejolley 
- [x] latest trunk merged in this branch
- [x] package-lock.json updated to v2 
- [x] upgraded `/bin/eslint-plugin-woocommerce/package.json` and `./package.json` to use `node v16` and `npm v8`

**Review by ralucaStan — APPROVED** [review]
This installs and works as expected.

**Comment by ralucaStan** [comment]
> @alexflorisca Custom rules? woocommerce/woocommerce-blocks#1696

I've noticed that this custom rules don't work on trunk at all. I'll open a [new issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5401).

**Pull request merged**
