### PR TITLE
Remove h1 from atomic title

### LINKED ISSUE #1101: A11y: Remove H1 option from ProductTitle block in the context of a grid.
For a11y reasons, I think we should consider removing H1 from the options for `ProductTitle` component in the context of the grid?  Probably should explore _what_ options should be available.  We could also look into giving an a11y notice when user's select a heading level that would break a11y guidelines in content instead?

### PR DESCRIPTION
**Pull request by senadir**
This PR removes the option to have H1 as a level for the atomic Product Title block.

Fixes #1101 

### Screenshots

image

### How to test the changes in this Pull Request:

1. Create a new All Products block
2. Go to edit mode and select the title
3. See that H1 is not there anymore

### Changelog
- remove H1 svg
- remove ability to select H1

### CODE REVIEW

**Comment by senadir** [comment]
@nerrad the only problem I can see is if the block is used in the future in a single product page, being the only and the prominent product in that page, it makes sense for it to be H1, but for us to account for that case requite contextual information of how is this block being used.

**Comment by nerrad** [comment]
> @nerrad the only problem I can see is if the block is used in the future in a single product page, being the only and the prominent product in that page, it makes sense for it to be H1, but for us to account for that case requite contextual information of how is this block being used.

Right, and even then, only when full site editing is active and the Product Title is used AS the title for the page.  Right now in the existing editor, H1 should only be the post title.

**Comment by nerrad** [comment]
I forgot there already _is_ a way to get the context via `useProductLayoutContext`, so that might be a way in which you can discover the context here.  I still think it should be done in a followup because I'd like there to be an exploration on how some a11y feedback can be given to the user based on what other heading levels might have already been used.  So not a pressing issue.

**Comment by mikejolley** [comment]
I don't think we should totally prohibit the use of `1` since this component could be reused in other places (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1169), however, I agree in this context we should prevent 1 being chosen.

**Pull request merged**
