### PR TITLE
Improve transform classic product template UX

### LINKED ISSUE #9300: Improve Transform Classic Product Template UX
It is necessary to improve the UX of the `Classic Template Product` block. We want to redesign the block following this mockup:

image

Also, when hovering over the primary action button, we should render a preview of the blockified template:

image

Furthermore, when the transform happens, we should be sure to select the parent Group block:

image

### PR DESCRIPTION
**Pull request by gigitux**
This PR improves the layout of the classic product. Futhermore, it improves the UX to migrate to the blockified templates. 

Please, during the review, check the mockup to see if I missed something: p6riRB-8yQ-p2

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9300 and https://github.com/woocommerce/woocommerce-blocks/issues/8853.

### Screenshots

| Template | Before | After | Video |
|----------|--------|-------|-------|
|Single Product|image|image| <video src="https://user-images.githubusercontent.com/4463174/236873848-8eeff08a-bc58-44f5-95f3-d963606e405d.mp4" />  |
|Archive Templates|image|image|<video src="https://user-images.githubusercontent.com/4463174/236874706-1636379f-68ca-4994-b422-688daca01629.mov" />|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Open the Single Product Template.
2. Be sure that the description is: "Transform this template into multiple blocks so you can add, remove, reorder, and customize your **single product template** (for other templates, this should correspond to the name of the template)."
3. Hover the button "transform into blocks".
4. Ensure the preview corresponds to the "blockified template".
5. Click the button.
6. Ensure that the group block around the blockified product is selected.
7. Ensure the snackbar is visible and the undo button works correctly.

*Testing Instructions for developer - not include in the testing notes*
1. Enable Gutenberg trunk.
2. Open the Single Product Template.
3. Remove the Classic Product block.
4. Ensure that in the right sidebar, in the template section, appears a new button with the label: "Revert to the Classic Product Template".
5. Click on the button.
6. Ensure that the button restores the Classic Product Block. 

##### Repeat the instructions for those templates:
- Single Product Template.
- Product Catalog.
-  Products By Category.
-  Products By Tag.
- Product By Attribute.
- Product Search Results.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Classic Product Block: Improve layout and user experience to migrate to blockified templates.

### CODE REVIEW

**Comment by albarin** [comment]
Is this the expected message on other templates aside from the `Single Product`? Is not the one you mention on step 2.
Screenshot 2023-05-09 at 14 30 52

**Comment by albarin** [comment]
> 6. Ensure that the focused block is the group block.

@gigitux Does this mean that after clicking the transform button, the group block around the blockified product should be selected?

**Comment by gigitux** [comment]
> Is this the expected message on other templates aside from the `Single Product`? Is not the one you mention on step 2. Screenshot 2023-05-09 at 14 30 52

You're right, there was some issue with the label. I didn't update some logic! I fixed with 954335b600d928f8e650e54981986332496b0223.

**Comment by gigitux** [comment]
> > 6. Ensure that the focused block is the group block.
> 
> @gigitux Does this mean that after clicking the transform button, the group block around the blockified product should be selected?

Yes, I will update the testing instructions to be more precise!

**Comment by albarin** [comment]
> Yes, I will update the testing instructions to be more precise!

Thanks! @gigitux 
That's not working for me, see this example, it's selecting the `Related products` block.


https://github.com/woocommerce/woocommerce-blocks/assets/186112/77965202-8e3f-474e-93b4-3a166d1620e7

**Comment by gigitux** [comment]
> > Yes, I will update the testing instructions to be more precise!
> 
> Thanks! @gigitux That's not working for me, see this example, it's selecting the `Related products` block.
> 
>  CleanShot.2023-05-10.at.09.19.01.mp4

I introduced a regression with https://github.com/woocommerce/woocommerce-blocks/commit/954335b600d928f8e650e54981986332496b0223. Fixed with [b986324](https://github.com/woocommerce/woocommerce-blocks/pull/9386/commits/b9863242721f9cdbb16e5f6fa5ed2064ffe0277e).

**Review by albarin — APPROVED** [review]
Thanks for the updates, looking good! 👍

**Comment by gigitux** [comment]
> Thanks for the updates, looking good! 👍

Thanks for your great review! 🚀

**Pull request merged**
