### PR TITLE
React warning about javascript: URLs in `CheckoutOrderError`

### LINKED ISSUE #9663: React warning about `javascript:` URLs in `CheckoutOrderError`
When rendering `CheckoutOrderError` a React warning is shown in the console:

```
React will block javascript: URLs as a security precaution.
Use event handlers instead if you can.
If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead.
React was passed "javascript:window.location.reload(true)".
```

This is caused by the URL used to reload the page when the cart errors:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/checkout/checkout-order-error/index.js#L122

To fix this, we should use an `onClick` handler and navigate/reload as appropriate.

### LINKED ISSUE #42354: React warning about `javascript:` URLs in `CheckoutOrderError`
When rendering `CheckoutOrderError` a React warning is shown in the console:

```
React will block javascript: URLs as a security precaution.
Use event handlers instead if you can.
If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead.
React was passed "javascript:window.location.reload(true)".
```

This is caused by the URL used to reload the page when the cart errors:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/checkout/checkout-order-error/index.js#L122

To fix this, we should use an `onClick` handler and navigate/reload as appropriate.

### PR DESCRIPTION
**Pull request by Sadaf-A**
Fixes woocommerce/woocommerce#42354 
This PR adds `onClickHandler` in assets/js/block/checkout/checkout-order-error/index.js

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by opr — CHANGES_REQUESTED** [review]
Hi @Sadaf-A thanks for making this PR!

Just a couple of comments:
- Instead of enclosing `window.location.href = CART_URL;` in parentheses on line 126, why don't we wrap it in curly braces, making the function return void.
- The PR lacks a description and detailed testing instructions, these are important to include as we use them when testing the release. We can't accept the PR without them.

Please could you fix the above?

By the way, it looks like the error code is always `unknown` because the preloaded **checkout** data from the API is not set when the cart is invalid, therefore it won't be possible to test that branch of code. However you could apply these changes to get the error code from the `wc/store/cart` data store instead:

```patch
diff --git a/assets/js/blocks/checkout/checkout-order-error/index.js b/assets/js/blocks/checkout/checkout-order-error/index.js
index f9e7a2ebc..ac65aa78d 100644
--- a/assets/js/blocks/checkout/checkout-order-error/index.js
+++ b/assets/js/blocks/checkout/checkout-order-error/index.js
@@ -7,6 +7,8 @@ import { removeCart } from '@woocommerce/icons';
 import { Icon } from '@wordpress/icons';
 import { getSetting } from '@woocommerce/settings';
 import { decodeEntities } from '@wordpress/html-entities';
+import { CART_STORE_KEY } from '@woocommerce/block-data';
+import { useSelect } from '@wordpress/data';
 
 /**
  * Internal dependencies
@@ -28,8 +30,6 @@ const cartItemErrorCodes = [
        GENERIC_CART_ITEM_ERROR,
 ];
 
-const preloadedCheckoutData = getSetting( 'checkoutData', {} );
-
 /**
  * When an order was not created for the checkout, for example, when an item
  * was out of stock, this component will be shown instead of the checkout form.
@@ -38,16 +38,14 @@ const preloadedCheckoutData = getSetting( 'checkoutData', {} );
  * checkout block.
  */
 const CheckoutOrderError = () => {
-       const checkoutData = {
-               code: '',
-               message: '',
-               ...( preloadedCheckoutData || {} ),
-       };
+       const cartErrors = useSelect( ( select ) => {
+               return select( CART_STORE_KEY ).getCartData().errors;
+       } );
 
        const errorData = {
-               code: checkoutData.code || 'unknown',
+               code: cartErrors[ 0 ]?.code || 'unknown',
                message:
-                       decodeEntities( checkoutData.message ) ||
+                       decodeEntities( cartErrors[ 0 ]?.message ) ||
                        __(
                                'There was a problem checking out. Please try again. If the problem persists, please get in touch with us so we can assist.',
                                'woo-gutenberg-products-block'
```

Please let me know if you need help with any of the above!

**Comment by Sadaf-A** [comment]
@opr Hey, I haven't worked with WordPress before is there a step-by-step guide on how I can run the plugins

**Comment by opr** [comment]
Hey @Sadaf-A no problem, I'd definitely recommend having a testing site set up and working correctly so you can test your changes. I've added some instructions here that will hopefully help, they're not super in-depth but if you need help with any additional points please let me know and I'll do my best to clarify anything!

To get set up with the project, I'd recommend installing https://localwp.com/ and setting a website up using that. On this new WordPress, you should install and configure the [WooCommerce plugin](https://wordpress.org/plugins/woocommerce/).

You'll also need to install [Composer](https://getcomposer.org/download/) (v2) and [Node](https://nodejs.org/en/blog/release/v16.16.0) (v16).

Then I would recommend following the [Getting Started Guide](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/contributors/getting-started.md) we have. This should contain everything you need to get running.

Once you've done this, please review my comment from above and make the changes if you feel confident doing so. Good luck!

**Comment by masteradhoc** [comment]
@Sadaf-A can u update the PR and also write "Fixes woocommerce/woocommerce#42354" in description so relationship works correctly?

**Comment by Sadaf-A** [comment]
@masteradhoc sure, I'll add "Fixes woocommerce/woocommerce#42354" right now. Will make other necessary changes as soon as possible.

**Pull request closed without merging**
