### PR TITLE
[Patterns] Add new `Footer with Simple Menu and Cart` pattern

### LINKED ISSUE #9056: Create `Footer with Simple Menu and Cart` pattern
Footer with Simple Menu and Cart

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1543_34641 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by albarin**
This PR implements the `Footer with Simple Menu and Cart` pattern.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9056

#### Design
Centered Search
#### Implementation
Screenshot 2023-04-24 at 12 36 24

#### User-Facing Testing

1. Create a new page or post
2. Make sure the `Footer with Simple Menu and Cart` pattern appears under the WooCommerce category dropdown.
3. Insert in and make sure it shows as expected on the design.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by kmanijak — APPROVED** [review]
Thanks for working on the patterns! 💪

I checked this one and it works nicely on desktop, but I was wondering if there are plans on covering the mobile layout 🤔 Is it possible to change the pattern layout between desktop and mobile?

image

I'm approving as it's a bigger discussion including other patterns too, cc: @shaunandrews for visibility 🙌

**Comment by albarin** [comment]
@shaunandrews should we merge this one, wdyt? 🤔

**Comment by shaunandrews** [comment]
Can we do anything to fix that mobile view? I'd expect it to stack like in the design:

CleanShot 2023-05-08 at 12 50 34@2x

**Comment by albarin** [comment]
> Can we do anything to fix that mobile view? I'd expect it to stack like in the design:

I've pushed a change to improve the cart's position in the mobile view. What I haven't been able to do is:
- Stack the menu vertically on mobile (you can choose horizontal or vertical, but cannot change it only for mobile)
- Show the price next to the `Mini Cart` (it automatically hides on smaller screens)
Screenshot 2023-05-09 at 12 35 55

@shaunandrews Do you think is enough? 🤔

**Comment by shaunandrews** [comment]
Its slightly better, but still not ideal. I guess we can merge and maybe work towards improvements to the navigation block (allow mobile stacking, like columns) and the mini-cart (allow showing price on mobile.)

**Pull request merged**
