### PR TITLE
Product Gallery: fix 'Block woocommerce/product-gallery-large-image is already registered' error

### LINKED ISSUE #11123: Product Gallery: Block "woocommerce/product-gallery-large-image" is already registered
## Describe the bug

When the user lands on the Site Editor, `Block "woocommerce/product-gallery-large-image" is already registered` error is shown in the console.

## To reproduce

1. Open the Site Editor.
2. Open the console.
3. See error.

## Expected behavior

No error should be shown.

## Screenshots

image

### PR DESCRIPTION
**Pull request by gigitux**
## What

Fixes #11123

## Why

Given that we register the assets with the function `register_block_type_assets`, the block is already registered on the PHP side.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Open the Site Editor.
2. Ensure that the `Block woocommerce/product-gallery-large-image is already registered` isn't visible.
3. Smoke test the Product Gallery block.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by tjcafferkey** [comment]
>Given that we register the assets with the function register_block_type_assets, the block is already registered on the PHP side.

For my own understanding, please can you elaborate on this? Why is this change necessary for this block but not others (e.g. `product-gallery-large-image-next-previous`)?

**Comment by gigitux** [comment]
> > Given that we register the assets with the function register_block_type_assets, the block is already registered on the PHP side.
> 
> For my own understanding, please can you elaborate on this? Why is this change necessary for this block but not others (e.g. `product-gallery-large-image-next-previous`)?

For other blocks (like `product-gallery-large-image-next-previous`), we don't ship any assets (https://github.com/woocommerce/woocommerce-blocks/blob/948b0fa10ec66da4c5ffa7584dacd2353f143781/src/BlockTypes/ProductGalleryLargeImageNextPrevious.php/#L17-L23), so all the logic about registration assets doesn't run. (https://github.com/woocommerce/woocommerce-blocks/blob/948b0fa10ec66da4c5ffa7584dacd2353f143781/src/BlockTypes/AbstractBlock.php/#L125-L154)

**Comment by tjcafferkey** [comment]
The next/prev buttons aren't currently working on the frontend for me but I know this is still under development and experimental so I'm assuming that's expected?

The error this PR is supposed to fix is no longer present. I will wait for your reply before approving.

**Comment by gigitux** [comment]
> The next/prev buttons aren't currently working on the frontend for me but I know this is still under development and experimental so I'm assuming that's expected?
> 
> The error this PR is supposed to fix is no longer present. I will wait for your reply before approving.

Yes! There is a PR to fix the next/prev buttons: https://github.com/woocommerce/woocommerce-blocks/pull/10938

**Review by tjcafferkey — APPROVED** [review]
Approving, thanks for fixing Luigi! Only note I have is that we should start adding a little information under the "What" heading, not just the issue. Even if it is just 1 sentence for context would be helpful. Thanks! 🚀

**Pull request merged**
