### PR TITLE
Change the button text in the pattern to make it matching the content

### PR DESCRIPTION
**Pull request by kmanijak**
Recently the Featured Category pattern has been changed (photo and heading). But the button text remained the same and wasn't matching the content.

Also, the size of the image has been changed so the image is not skewed but keeps the original ratio.

This PR changes the button text from "Shop shoes" to neutral "Shop now".

### Screenshots

Keep in mind the differences of styling comes from a theme and are not part of the PR, just the button text change.

| Before | After |
| ------ | ----- |
|    image    |    image |

#### User Facing Testing

1. Create a page and use the block inserter->patterns->WooCommerce and to insert the Featured Category Focus.
2. Notice the preview shows per design screenshot shown above.
3. Insert the pattern and then update/save and check the frontend and ensure it is displaying as the screenshot above.
4. Make sure the button text says "Show now" and the image is not skewed

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by imanish003** [comment]
Hi @kmanijak,
I can confirm that the button text is now "Shop now" and the image is also looking better. I just wanted to share that on smaller devices, the padding on the right and left seems a bit large. Perhaps we should consider decreasing it. What do you think?

image

**Comment by kmanijak** [comment]
> I just wanted to share that on smaller devices, the padding on the right and left seems a bit large. Perhaps we should consider decreasing it. What do you think?

I'd like to avoid fixing it in this PR considering its purpose is to address the most crucial issues (wrong button text and skewed image). I think padding improvement could be handled in the Patterns project scope (cc: @roykho).

**Comment by imanish003** [comment]
@kmanijak, that makes sense. I will go ahead and approve the PR.

**Review by imanish003 — APPROVED** [review]
LGTM! Thanks for improving this pattern so quickly. 🚀

**Pull request merged**
