### PR TITLE
Add new `Discount banner with image` pattern

### LINKED ISSUE #9932: Add new `Discount banner with image` pattern
Maybe think of a better name.
Screenshot 2023-06-21 at 11 26 29

### PR DESCRIPTION
**Pull request by albarin**
This PR adds new `Discount banner with image` pattern

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9932

#### User-Facing Testing

1. Create a new post or page.
2. Insert the `Discount banner with image` pattern and save.
3. In the front end, check the pattern looks like the image above and the `Shop now` button links to the shop page.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add new `Discount banner with image` pattern.

### CODE REVIEW

**Review by roykho — CHANGES_REQUESTED** [review]
I am seeing the text squishing together on smaller viewports.

**Comment by albarin** [comment]
> I am seeing the text squishing together on smaller viewports.
> 
> 

Did you pull the latest changes? In theory I fixed that issue in my last commit.

**Comment by roykho** [comment]
> Did you pull the latest changes? In theory I fixed that issue in my last commit. 

I did but I will check it again.

**Review by roykho — CHANGES_REQUESTED** [review]
I am seeing the text "Off" on a separate line in desktop viewport. I believe that should be inline with `40%` text on wide screen size.

**Review by roykho — APPROVED** [review]
The increase in width size fixed it for me. LGTM!

**Pull request merged**
