### PR TITLE
Use GITHUB_TOKEN as the env variable for the changelog script

### LINKED ISSUE #8955: Replace instances of GH_API_TOKEN with GITHUB_TOKEN so we use the same variable across scripts
From pdToLP-ti-p2:

> I had to run `npm run changelog` to manually generate the changelog and found out that it reads the GitHub token from a different variable than `npm run deploy`: `GH_API_TOKEN` and `GITHUB_TOKEN`.

This issue is about unifying those scripts, so they all read the token from `GITHUB_TOKEN`.

### PR DESCRIPTION
**Pull request by samueljseay**
## What

Rename the environment variable / arg for the changelog script to `GITHUB_TOKEN`/`githubToken`.

Fixes #8955

## Why

The deploy script expects `GITHUB_TOKEN` so this is to maintain consistency.

## Testing Instructions

1. Check the documentation, does it make sense with the new arg name/env var name
2. Create a github token in the Github UI that has access to `public_repo, admin:org, and user`
3. Run the script on this branch, setting the env var e.g. `GITHUB_TOKEN="ghp.." npm run changelog` and see that it runs correctly, it will inform you the token is set and once you choose a milestone it will successfully output a changelog list.
4. Also test the arg style: `npm run changelog --githubToken "ghp..."` and confirm it also successfully outputs a changelog list.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

### CODE REVIEW

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @samueljseay. The PR is working as expected, so I'm pre-approving it. 

I just noticed the following minor things:
- You changed `github` to `Github`. Shouldn't we use the official spelling, which is `GitHub`?
- In the PR description, feel free to remove all obsolete sections, e.g. `Screenshots or screencast ` and `Changelog` as this increases the readability.
- I cannot speak for @woocommerce/woo-fse, but @woocommerce/rubik we add estimates both to issues and PRs to track our velocity over time.

That said, these three points are nitpicks. Please don't hesitate to address or skip them. 😀

---

Oh, one thing I noticed: There are two failing E2E tests. Please make sure that they pass or skip them, before merging this PR, thus, please only merge a PR when all E2E tests are passing. You can find more information about this on pdToLP-ve-p2.

**Comment by samueljseay** [comment]
All great feedback thanks @nielslange ! I'm not sure about estimates, but I'll ask my team for future issues/work.

I've renamed Github to GitHub very good point. I checked Zenhub for sanity but it is indeed Zenhub and not ZenHub.

as for CI checks don't worry I certainly understand the importance of having required checks pass. 

Thanks again!

**Comment by kmanijak** [comment]
> I cannot speak for https://github.com/orgs/woocommerce/teams/woo-fse, but https://github.com/orgs/woocommerce/teams/rubik we add estimates both to issues and PRs to track our velocity over time.

> All great feedback thanks @nielslange ! I'm not sure about estimates, but I'll ask my team for future issues/work.

We do the same! So feel free to add the estimate to PR as well (even if it's merged already) and you can also assign issues/PRs you work on to the sprint "Sprint: Aug 14 - Oct 6, 2023". I assigned a sprint for this PR already. 🙌

**Comment by samueljseay** [comment]
@kmanijak Thank you! It looks like I might need Zenhub access to add to sprints, just working out how to get a license for that. But for now while I work on getting that I'll add estimates to everything.

**Comment by imanish003** [comment]
> • In the PR description, feel free to remove all obsolete sections, e.g. Screenshots or screencast and Changelog as this increases the readability.
> 

In reference to this point, I believe we had a discussion and decided not to remove any sections, as outlined in the [PR template](https://github.com/woocommerce/woocommerce-blocks/blob/233328056702e3ea7171d43cae138ed0121973df/.github/pull_request_template.md?plain=1#L1C1-L2C1):

> Please do not remove any information from this pull request. Instead, add N/A or leave blank if not applicable 
> 

This change was introduced in PR #10549, where @tjcafferkey updated the PR template. As this is a recent alteration, it's possible that not everyone may be aware of it. 🙂

**Pull request merged**
