### PR TITLE
Mini Cart block: display a compatibility notice when the user first adds the block in the editor

### LINKED ISSUE #4917: Mini Cart block: display a compatibility notice when the user first adds the block in the editor
Cart and Checkout blocks display a compatibility notice the first time they are added to the page:

Cart and Checkout compatibility notice

We want to do the same for the Mini Cart block.

See same issue for Cart and Checkout blocks (#3017) and the PR that implemented it (#3937).

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #4917.

This PR adds a compatibility notice which reuses the one added for cart and checkout block. I also updated the E2E test for the mini cart to account the notice.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)
- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.

### Screenshots

image

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Add a new page.
2. Add the Mini cart block to the page.
3. See the notice.
4. Dismiss the notice.
5. Add a new page.
6. Add the Mini cart block to the page.
7. See no notice.

### CODE REVIEW

**Comment by frontdevde** [comment]
@Aljullu @tjcafferkey This PR got assigned to me for review shortly before heading out for AFK. I had hoped to still get to it but I didn't get around to properly test/review it anymore. If one of you could review this one, it'd be highly appreciated. Thank you! 🙏

**Comment by Aljullu** [comment]
> @Aljullu @tjcafferkey This PR got assigned to me for review shortly before heading out for AFK. I had hoped to still get to it but I didn't get around to properly test/review it anymore. If one of you could review this one, it'd be highly appreciated. Thank you! 🙏

I can take care of it. :+1:

**Review by Aljullu — APPROVED** [review]
This is working well and thank you for updating the tests!

I noticed the Compatibility notice doesn't look good in the Site Editor. I think it doesn't need to block this PR, so I created a separate issue (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4954) and added it to the Mini Cart epic.

**Comment by tjcafferkey** [comment]
@dinhtungdu is there anything further that needs to be done on this PR or is it good to go? Let me know if you need any assistance with progressing this. Happy to help!

**Comment by dinhtungdu** [comment]
@tjcafferkey Thanks for checking out, I was focusing on other tasks and missed this. I merged the PR to `trunk`.

**Pull request merged**
