### PR TITLE
Product Gallery Pager: Remove unnecessary margin

### LINKED ISSUE #11285: Product Gallery Pager: Unnecessary margin present
## Describe the bug

Currently, the Product Gallery **Pager** has unnecessary top & bottom margins:

**Frontend**
V-Neck_T-Shirt_–_newproductgallery

**Editor**
Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress

### PR DESCRIPTION
**Pull request by danieldudzic**
## What

Fixes #11285

## Why

This PR removes the excess **top** & **bottom** margins from the **Product Gallery Pager**.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Ensure the **Pager** is enabled.
6. Verify that there's no Pager top or bottom margin both in the editor and frontend.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

**Editor:**

| Before | After |
| ------ | ----- |
|Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress|Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress|

**Frontend:**

| Before | After |
| ------ | ----- |
|V-Neck_T-Shirt_–_newproductgallery|V-Neck_T-Shirt_–_newproductgallery|

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Gallery Pager: Remove unnecessary margin.

### CODE REVIEW

**Comment by sunyatasattva** [comment]
Hey @danieldudzic, I don't see the `Product Gallery` block in the inserter. I'm on `trunk` in development mode. I see the `Product Image Gallery`, but not the `Product Gallery` 🤔

**Review by thealexandrelara — CHANGES_REQUESTED** [review]
Thank you for working on this @danieldudzic, I just tested and can confirm that the margin was successfully removed from the block; however, I noticed that when the Pager display mode is set to "Dots" the icons the icons get cut off:

image

Is this happening to you as well?

> I don't see the Product Gallery block in the inserter. I'm on trunk in development mode. I see the Product Image Gallery, but not the Product Gallery 🤔

Is there any error appearing in the console? I'm not sure if it's the cause, but the Product Gallery block is currently working only within the Single Product template.

**Comment by danieldudzic** [comment]
> Thank you for working on this @danieldudzic, I just tested and can confirm that the margin was successfully removed from the block; however, I noticed that when the Pager display mode is set to "Dots" the icons the icons get cut off:
> 
> image

👋 @thealexandrelara I'm struggling to replicate.

It seems that a cut-off like that would be caused by incorrect icon sizing (or its container) rather than a lack of margin.

Can you please share details of the browser, and specific block setup with which you were able to replicate?

**Review by thealexandrelara — APPROVED** [review]
> 👋 @thealexandrelara I'm struggling to replicate.
> 
> It seems that a cut-off like that would be caused by incorrect icon sizing (or its container) rather than a lack of margin.
> 
> Can you please share details of the browser, and specific block setup with which you were able to replicate?

I was testing it again and the problem was fixed, maybe when you merged trunk into this branch, the issue was fixed because I'm not able to reproduce it anymore. Thank you for working on this, I'm approving the PR 🚀

**Pull request merged**
