### PR TITLE
Rename commands and directories for Playwright and JEST e2e tests

### PR DESCRIPTION
**Pull request by mikejolley**
This PR just does some housekeeping to rename JEST and Playwright tests given the emphasis on switching to playwright.

1. `e2e` directory becomes `e2e-jest`
2. `e2e-pw` directory becomes `e2e`
3. `npm run e2e` becomes `npm run e2e:jest`
4. `npm run e2e-pw` becomes `npm run e2e`
5. `npm run e2e:report` will run playwright tests with a html report
6. `npm run e2e` will fail with a notice if Docker and wp env is not active.

### Testing

1. CI should pass
2. `npm run e2e:jest` should run old e2e tests
3. `npm run e2e` should run new playwright tests

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by mikejolley** [comment]
Ill rebase this if it gets approval because it will be stale again quickly.

**Review by nielslange — APPROVED** [review]
All tests are passing, and the changes look good. Let's ⛴️ this change, @mikejolley.

**Comment by mikejolley** [comment]
Tests are passing. @woocommerce/rubik be aware of the new commands if you're running tests locally. CI is not affected.

**Comment by dinhtungdu** [comment]
>  be aware of the new commands if you're running tests locally. CI is not affected.

cc @woocommerce/woo-fse as well.

**Pull request merged**
