### PR TITLE
WIP: Update Babel to 7.22.5

### LINKED ISSUE #10166: Cannot build upon fresh clone
## Describe the bug

Using a fresh clone of the repo, running the build aborts with failures.

## To reproduce

1. Check out a fresh clone of the repo.
2. `npm i`
3. `composer install`
4. `npm run build`

## Expected behavior

The build fails with a long list of `Module parse failed: Unexpected token` errors (furthermore stating that `You may need an additional loader to handle the result of these loaders`). The following are the three errors at the top (but the list goes on much longer):

```
    ERROR in ./assets/js/middleware/store-api-nonce.js 12:29
    Module parse failed: Unexpected token (12:29)
    File was processed with these loaders:
     * ./node_modules/babel-loader/lib/index.js
    You may need an additional loader to handle the result of these loaders.
    |   const storedNonceValue = window.localStorage.getItem('storeApiNonce');
    |   const storedNonce = storedNonceValue ? JSON.parse(storedNonceValue) : {};
    >   currentNonce = storedNonce?.nonce || '';
    |   currentTimestamp = storedNonce?.timestamp || 0;
    | } catch {
    
    ERROR in ./assets/js/base/components/block-error-boundary/index.tsx 13:8
    Module parse failed: Unexpected token (13:8)
    File was processed with these loaders:
     * ./node_modules/babel-loader/lib/index.js
    You may need an additional loader to handle the result of these loaders.
    | import './style.scss';
    | class BlockErrorBoundary extends Component {
    >   state = {
    |     errorMessage: '',
    |     hasError: false
    
    ERROR in ./assets/js/settings/blocks/constants.ts 16:41
    Module parse failed: Unexpected token (16:41)
    File was processed with these loaders:
     * ./node_modules/babel-loader/lib/index.js
    You may need an additional loader to handle the result of these loaders.
    | export const WC_BLOCKS_BUILD_URL = blocksConfig.pluginUrl + 'build/';
    | export const WC_BLOCKS_PHASE = blocksConfig.buildPhase;
    > export const SHOP_URL = STORE_PAGES.shop?.permalink;
    | export const CHECKOUT_PAGE_ID = STORE_PAGES.checkout.id;
    | export const CHECKOUT_URL = STORE_PAGES.checkout.permalink;
```

## Environment

- Node 16.19.1
- npm 8.19.3

## Additional context

Looks like it's complaining about ES6+ constructs? 🤔

### PR DESCRIPTION
**Pull request by Aljullu**
This PR updates `@babel` dependencies.

Starting from 7.19.0, our config was broken. I'm not 100% sure why, yet, but explicitly listing the required plugins fixes it. This will unlock [other dependabot PRs](https://github.com/woocommerce/woocommerce-blocks/pulls/app%2Fdependabot).

Supersedes https://github.com/woocommerce/woocommerce-blocks/pull/9797.

Fixes #10166.

#### User Facing Testing

1. Run `rm -rf node_modules/ && npm ci && npm run build` and verify the project is built correctly.
2. Run some other commands to verify everything works correctly as well (ie: `npm run start`, `npm run storybook`, `npm run test`...).

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by danieldudzic — APPROVED** [review]
I have verified that:
- `rm -rf node_modules/ && npm ci && npm run build` builds correctly

And the following run correctly:
- npm start
- npm run storybook
- npm run test

According to ChatGTP the reason for the plugins needing to be explicitly defined is that Babel made changes to the way it handles plugin loading and configuration in `7.19.0`.

Starting from `7.19.0`, you need to explicitly list all the plugins in the config.

That said, I wasn't able to confirm the above reading through the `7.19.0` release notes.

**Comment by Aljullu** [comment]
@danieldudzic that's weird. For some reason `npm run test` and `npm run storybook` fail for me. `npm run test` seems to fail in the automation as well. :confused:

**Comment by danieldudzic** [comment]
@Aljullu Just tested again.

`npm run test`, `npm run storybook` and `npm run test` all run fine.

The `npm run test` produced:
```
Test Suites: 9 failed, 106 passed, 115 total
Tests:       59 failed, 693 passed, 752 total
Snapshots:   60 passed, 60 total
Time:        18.652 s
```
But the process itself didn't fail.

**Comment by Aljullu** [comment]
@danieldudzic thanks! Yes, now I get the same. I will be looking into those failing tests and e2e tests, which are failing as well.

**Comment by Aljullu** [comment]
I'm going to close this PR as we will focus our efforts on https://github.com/woocommerce/woocommerce-blocks/pull/8013 (see discussion here: https://github.com/woocommerce/woocommerce-blocks/issues/10166#issuecomment-1632437052).

**Pull request closed without merging**
