### PR TITLE
Featured Product block: Allow custom background image selecton

### LINKED ISSUE #320: Featured Product: Allow user to customize the background image
Users should be able to use the Media Library to swap out another image for the block's background.

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #320 – Add the ability to override the background image on the Featured Product block. This PR adds an icon to the block toolbar that opens the media library, and if an image is selected it is set as the background image for the block.

### Screenshots

screen shot 2019-01-14 at 4 00 02 pm

### How to test the changes in this Pull Request:

1. Add a Featured Product block
2. Select a product, see the image in the preview
3. Click the image icon, select a new image
4. Expect: your preview should update with the new image.
5. Publish the post, view it
6. Expect: The image you selected should be used in the block, not the product's featured image.

### CODE REVIEW

**Review by LevinMedia — COMMENTED** [review]
Looking good! Couple comments:

Found a bug - when switching between different products, the image should default to the original product image. Now if you upload a new image, it follows you between products.

screen recording 2019-01-14 at 01 22 pm


In the case that you upload an image to flying ninja, then switched to finger painting, then back to flying ninja, you'd have the original product image visible again, and you'd have to re-add the override photo.

**Comment by ryelle** [comment]
> Found a bug - when switching between different products, the image should default to the original product image. Now if you upload a new image, it follows you between products.

Oh, hah, I thought that was expected :) I can change that.

**Comment by ryelle** [comment]
@LevinMedia Updated the image so it resets when you pick a new product.

**Review by jeffstieler — APPROVED** [review]
Code looks good and tests well! 🛳 it.

**Pull request merged**
