### PR TITLE
Enable Product Collection as a core feature

### LINKED ISSUE #10430: Product Collection - enable the beta version
Product Collection block is nearly ready to be used.

This issue is about enabling the block:
- remove the experimental flag
- add `(Beta)` to the block name
- enable manual migration ([here](https://github.com/woocommerce/woocommerce-blocks/pull/10267/files#diff-e9517b2fd3bcc6d45a42d1f2eea15b221e8d7285a41c4f3df6fa2eb8db2de3acR7))

### PR DESCRIPTION
**Pull request by kmanijak**
- Enable Product Collection as a Core feature
- Add "(Beta)" to block title
- Prevent duplicated Product Title and Product Summary blocks in the inserter (https://github.com/woocommerce/woocommerce-blocks/pull/10548)

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10430

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

Product Collection has E2E and PHP Unit Tests covering some parts of the functionalities.

#### User Facing Testing

This PR enables a block that's been developed for a couple of months. Product Collection includes many functionalities and each of the changes at the moment of merging the particular functionalities. I don't think we should test ALL of them again, especially since the testing steps would be unreadable. However, I believe the major paths should be re-tested.

In some cases, I linked PRs. In that case, please refer to the testing scenarios from respective PR:

###### Inserting
0. This PR should be tested in production build, so use `npm run build:deploy` if you test locally. Ignore this step when testing plugin as a whole.
1. Go to Editor 
2. Type "Product Collection" and "Products (Beta)"
3. In both cases Product Collection (Beta) should appear in the inserter
4. Try to insert it
5. It should appear correctly in the Editor
6. Save and make sure it displays correctly in the Frontend

###### Inherit from query template
1. https://github.com/woocommerce/woocommerce-blocks/issues/9358

###### Filters
1. Add Product Collection and Products (Beta) block side by side
2. Disable "Inherit query from template" in both
3. Set of filters should appear in the Inspector Controls
4. Play around with the filters setting up the same conditions in both cases (be aware Product Collection offers more filters than Products (Beta), so you may not be able to recreate all of the scenarios in Products (Beta) block)
5. Treat Products (Beta) block as a reference - the results in product grid should be the same in both cases. We look for discrepancies between blocks. Keep in mind in some scenarios filters may be mutually exclusive or there may be some existing bugs. If they occur in both blocks, feel free to report it but it's not a blocker to release Product Collection.

Here is the list of filters for reference if you prefer to follow some specific scenarios:
- https://github.com/woocommerce/woocommerce-blocks/issues/9361
- https://github.com/woocommerce/woocommerce-blocks/issues/9362
- https://github.com/woocommerce/woocommerce-blocks/issues/9363
- https://github.com/woocommerce/woocommerce-blocks/issues/9364
- https://github.com/woocommerce/woocommerce-blocks/issues/9365
- https://github.com/woocommerce/woocommerce-blocks/issues/9722

###### Global Styles
1. Add Product Collection and Products (Beta) block side by side
2. Play around with the Global Styles of Product Collection/Products, Product Template and particular Product Elements.
3. As in case of Filters we look for discrepancies between blocks. If there's bug that occur in both blocks, feel free to report it but it's not a blocker to release Product Collection.

###### Product Elements
1. Make sure you're able to add all of the following blocks in Product Template of Products Collection
- Product Image
- Product Title
- Product Price
- Product SKU
- Product Summary
- Product Rating
- Product Stock Indicator
- On sale badge
- Add to Cart Button

###### Others - play with it
1. Play with Product Collection as you would as a merchant. Test it, try to break it. Think of stuff we didn't think of and try it out!

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Enable Product Collection block

### CODE REVIEW

**Review by nefeline — COMMENTED** [review]
Excellent work here @kmanijak and @imanish003 🎉 !

I've flagged one problem and left a few questions/suggestions.

# Test Results

## 1. Inserting ( ✅ All tests pass - 1 question)

> Type "Product Collection" and "Products (Beta)"
> In both cases Product Collection (Beta) should appear in the inserter 

❓ **Question:** When typing "Products (Beta)", both the **Products (Beta)** and the **Product Collection (Beta)** blocks are displayed: is that expected?

Screenshot 2023-08-17 at 17 51 47

> Try to insert it
> It should appear correctly in the Editor
> Save and make sure it displays correctly in the Frontend

✅ Confirmed the **Product Collection (Beta)** block can be inserted in the editor.
✅ Confirmed the **Product Collection (Beta)** block is correctly displayed on the front end.

## 2. Inherit from query template (✅  3 success, ❌  1 failure, 1 Suggestion)
1. https://github.com/woocommerce/woocommerce-blocks/issues/9358
(instructions copied from `9358`)

I would recommend porting over the instructions from `9358` to this issue to facilitate/expedite the work for reviewers.

> Testing with Product Archive templates
Open the Editor and navigate to the "Product Search Results"
Replace the existing 'Classic Template' block with the 'Product Collection' block.
After the 'Product Collection' block is successfully inserted, ensure that the 'Inherit query from template' option is enabled by default.

✅ Confirmed the 'Inherit query from template' option is enabled by default:

Screenshot 2023-08-17 at 20 50 43 1


> Save the changes.
Navigate to the frontend of your website. You can emulate a search for "shirt" by visiting the URL "/shop?s=shirt". Confirm that the search query shirt effectively displays related products.

✅ Confirmed the search results are returned correctly:

Screenshot 2023-08-17 at 20 53 18


> Head back to the Editor.
In the 'Product Collection' block, deactivate the 'Inherit query from template' option.
Subsequently, you should observe various settings and filters available in the inspector controls. Modify these filters and settings as required and validate immediately that the changes are visible within the Editor.

✅ Confirmed the settings are working as expected, and changes are visible in the editor.


https://github.com/woocommerce/woocommerce-blocks/assets/15730971/dfaa848b-1eab-4168-9675-3c1ae7e57032

> Save your modifications and return to the frontend of your website.
Ensure that the adjustments made to the 'Product Collection' block within the Editor are accurately displayed on the frontend of your website.

❌ When Inherit query from template is disabled in the editor, the search for products doesn't work anymore:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/4ee735f7-6e59-43c0-ab58-71e0b4684cdf

> Testing in Post
> Create a new post
> Add Product Collection block to the post
> With the 'Product Collection' block selected, open the Inspector Controls (located in the right sidebar). Confirm that the option inherit query from template does not appear in the list of options. This is because it's relevant only for Product Archive pages and should not be visible in this context.

✅ Confirmed the **inherit query from template** option is not displayed when inserting the block in the post editor:

Screenshot 2023-08-17 at 21 06 45

## 3. Filters ( ✅ Pass )
> 1. Add Product Collection and Products (Beta) block side by side
> 2. Disable "Inherit query from template" in both
> 3. Set of filters should appear in the Inspector Controls
> 4. Play around with the filters setting up the same conditions in both cases (be aware Product Collection offers more filters than Products (Beta), so you may not be able to recreate all of the scenarios in Products (Beta) block)
> 5. Treat Products (Beta) block as a reference - the results in product grid should be the same in both cases.

✅ Confirmed filters are working as expected.

## 4. Global Styles ( ✅ Pass, 1 Suggestion )
> 1. Add Product Collection and Products (Beta) block side by side
> 2. Play around with the Global Styles of Product Collection/Products, Product Template and particular Product Elements.
> 3. As in case of Filters we look for discrepancies between blocks. If there's bug that occur in both blocks, feel free to report it but it's not a blocker to release Product Collection.

✅ Confirmed styles are correctly applied. Tested with different global style variations and block level changes to color and typography.

Suggestion: can we add a few more details to the testing instructions for other folks going through this test step? While for us as a team, "Play around with the Global Styles" is very intuitive, I'm not sure if all folks on Global Step or anyone else testing have the same level of understanding.

## 5. Product Elements ( ✅ Pass, 1 Question )

> 1. Make sure you're able to add all of the following blocks in Product Template of Products Collection
> - Product Image
> - Product Title
> - Product Price
> - Product SKU
> - Product Summary
> - Product Rating
> - Product Stock Indicator
> - On sale badge
> - Add to Cart Button

❓ Question: The "**Product Summary**" block is not available anywhere: did we intentionally remove this block, or is this a regression? 

## 6. Others - play with it  ✅ 
1. Play with Product Collection as you would as a merchant. Test it, try to break it. Think of stuff we didn't think of and try it out!

✅ I did a few extra tests, such as checking mobile view and rearranging blocks within the Product Collection block and confirmed things are working as expected.

**Comment by kmanijak** [comment]
@nefeline thanks for a great review!

### 1. Inserting 
> Question: When typing "Products (Beta)", both the Products (Beta) and the Product Collection (Beta) blocks are displayed: is that expected?

Yes, it was added in: https://github.com/woocommerce/woocommerce-blocks/pull/10112 considering that eventually Products (Beta) block will be hidden from the inserter, hence I think it makes sense to display Product Collection (Beta) as an alternative already. But if you think it's confusing we can revert that change and add it only when hiding Products (Beta) from inserter. What's your opinion on that? 

### 2. Inherit from query template
> I would recommend porting over the instructions from 9358 to this issue to facilitate/expedite the work for reviewers.

Yeah, good suggestion, will do!

> ❌ When Inherit query from template is disabled in the editor, the search for products doesn't work anymore:

I think that's expected. When you disable the "Inherit query from template" Product Collection becomes a static product grid fully controlled by the merchant. It displays whatever you configure in Editor and only if the "Inherit query from template" option is enabled Product Collection will adapt to the context, in this case displaying search results. The same behavior can be reproduced with Products (Beta) or Query Loop (from which the behavior was adapted) blocks.

Please let me know if that makes sense.

Also, I glanced through the testing instructions checking if there was some misleading point but didn't find it. Do you recall if there's a point that made the impression it should work as you described? 🙏 

### 5. Product Elements
> ❓ Question: The "Product Summary" block is not available anywhere: did we intentionally remove this block, or is this a regression?

That's unexpected. The worst part being I cannot reproduce it:

Products (Beta) | Product Collection
-- | --
image | image
image | image

Are there any specific conditions under which you faced that issue? Was it a post or template editor? 🤔

**Comment by nefeline** [comment]
> Yes, it was added in: https://github.com/woocommerce/woocommerce-blocks/pull/10112 considering that eventually Products (Beta) block will be hidden from the inserter, hence I think it makes sense to display Product Collection (Beta) as an alternative already. But if you think it's confusing we can revert that change and add it only when hiding Products (Beta) from inserter. What's your opinion on that?

If hiding the **Products (Beta)** block from the inserter is something that we are planning to do sooner than later, then I think it's ok to keep it as is 👍 . In the long term, it can be confusing having the user look at two different options to insert products in their posts/templates, with the first one on the list being the one we are planning to retire **Products (Beta)** instead of the new one introduced here **Product Collection (Beta)**.

> Yeah, good suggestion, will do!

🙌 

> I think that's expected. When you disable the "Inherit query from template" Product Collection becomes a static product grid fully controlled by the merchant. It displays whatever you configure in Editor and only if the "Inherit query from template" option is enabled Product Collection will adapt to the context, in this case displaying search results. The same behavior can be reproduced with Products (Beta) or Query Loop (from which the behavior was adapted) blocks.

> Please let me know if that makes sense.

> Also, I glanced through the testing instructions checking if there was some misleading point but didn't find it. Do you recall if there's a point that made the impression it should work as you described? 🙏

IMO basically all arguments we used for making the filters contextual (which is now being addressed by @roykho and @dinhtungdu as part of https://github.com/woocommerce/woocommerce/issues/42255 ) are also applicable here. If the store owner decided to display only products in stock in their store, users on their site should still be able to search for these products. At a minimum, in this first moment, I'd recommend not allowing disabling the "Inherit query from template" option when the **Product Collection (Beta)** block is inserted within the Product Search Results template, otherwise, this is the experience users will have:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/25e57687-b76f-4f31-8e69-154c37a5755c

> That's unexpected. The worst part being I cannot reproduce it:

I can't reproduce what you are seeing 🤔 . As another example, here's a direct comparison between the Single Product block and the Product Collection (Beta) block when attempting to insert the Product Summary to them:


https://github.com/woocommerce/woocommerce-blocks/assets/15730971/94eed1ef-e520-4a98-b4ba-b320c9261855

I also tried the same approach as you did, add a paragraph and insert the summary in it, also doesn't work:

Screenshot 2023-08-18 at 14 55 12

> Are there any specific conditions under which you faced that issue? Was it a post or template editor? 🤔

Not really, the product summary is simply unavailable across the board (both in the post and template editors). I'm glad to jump on a call & help narrow down the cause if that helps!

**Comment by imanish003** [comment]
> Not really, the product summary is simply unavailable across the board (both in the post and template editors). I'm glad to jump on a call & help narrow down the cause if that helps!
> 

I've started investigating, and I'm encountering a slightly different issue. In template editing:

- Everything appears to be functioning correctly, with only one Summary block visible.

However, when it comes to posts, I'm noticing the presence of two Summary blocks within the Single Product as you can see in demo below:

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/7d2655d2-5f84-4701-af9b-95c590dfec6b

@kmanijak It seems that we'll need to find an alternative solution to address our challenge of duplicate Title and Summary blocks. The approach we implemented in woocommerce/woocommerce-blocks#10548 doesn't appear to be achieving the desired outcome. Can you reproduce this issue as well?

**Comment by imanish003** [comment]
Fixed in #10701.

**Comment by imanish003** [comment]
@kmanijak @nefeline I closed it by mistake 🤦‍♂️

**Comment by imanish003** [comment]
Hi @nefeline 👋🏻

> If the store owner decided to display only products in stock in their store, users on their site should still be able to search for these products. At a minimum, in this first moment, I'd recommend not allowing disabling the "Inherit query from template" option when the **Product Collection (Beta)** block is inserted within the Product Search Results template, otherwise, this is the experience users will have:
> 

As we discussed during our call, it would be beneficial to create a separate discussion for this matter. Additionally, as agreed upon in the call, we concluded that this issue doesn't act as a roadblock for the release of the Product Collection block because:

- It mirrors the behavior of Query Loop and Products beta block.
- The scope of this also includes Products by category, tag, etc., Based on the decision, we will need to make the same change for these templates too.

> I can't reproduce what you are seeing 🤔 . As another example, here's a direct comparison between the Single Product block and the Product Collection (Beta) block when attempting to insert the Product Summary to them:
> 

I've successfully replicated the issue you raised concerning the unavailability of the `Product Summary` block in the inserter. I've resolved this in PR woocommerce/woocommerce-blocks#10718 and incorporated it into this pull request. Could you please take another look at this?

I am extremely grateful for your comprehensive review of this pull request. Your efforts are highly appreciated! 🙌🏻

**Review by nefeline — APPROVED** [review]
Hi @imanish003,

Thanks for addressing all the feedback!

Regarding:

> as agreed upon in the call, we concluded that this issue doesn't act as a roadblock for the release of the Product Collection block because:
> It mirrors the behavior of Query Loop and Products beta block.
The scope of this also includes Products by category, tag, etc., Based on the decision, we will need to make the same change for these templates too.

Adding here that per @shaunandrews feedback, we will be removing this toggle, in favor of having "Collections" — one of which will be the default query. ref. p1692873557131709-slack-C02FL3X7KR6

> I am extremely grateful for your comprehensive review of this pull request. Your efforts are highly appreciated! 🙌🏻

Likewise! Thanks for your promptness in addressing the problems flagged here during the code review and your efforts in developing this block 🥇

**Pull request merged**
