### PR TITLE
Move paymentResult to the payment store

### PR DESCRIPTION
**Pull request by alexflorisca**
This moves the `paymentResult` property and associated actions & selectors into the `payment` data store - for obvious reasons.

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [x] E2E tests

#### User Facing Testing

1. Checkout successfully using the stripe payment method (4242 4242 4242 4242)
2. Checkout unsuccessfully using stripe (4000 000 000 0002)
3. Both should not throw any console errors and step 2 should display a "Something went wrong" error at the top of the Checkout block and a "Card declined" error in the payment method block.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Moved the payment result from the checkout store to the payment store

### CODE REVIEW

**Review by tarunvijwani — CHANGES_REQUESTED** [review]
Thank you for making the changes, @alexflorisca!

I'd love to know the usage of the `checkstyle.xml` file. Does it contains all the errors? 

Somehow, I'm still getting the console error when I enter the wrong card details:

image


I also notice that if I try again with wrong card it shows two errors, is that intentional?
image

**Comment by alexflorisca** [comment]
Thanks for the review @tarunvijwani. Both of those things are expected. I should have been a bit clearer in my testing instruction, the fetch to the `/checkout` endpoint will fail for a bad card, that's expected. I didn't realise it printed it in the console as well. And when a second payment attempt is made with the same card, another error will appear, that's correct.

**Comment by alexflorisca** [comment]
`checkstyle.xml` is used by the new `Monitor TypeScript errors` github action to check if a PR introduces new typescript errors. You can ignore this for the most part

**Review by tarunvijwani — APPROVED** [review]
Thank you for clarifying it! Let's 🚢  it. 👍

**Pull request merged**
