### PR TITLE
update all block one-line descriptions to match documentation

### PR DESCRIPTION
**Pull request by haszari**
This PR updates the description for each block (used in block inserter) to match the description used in the [documentation](https://docs.woocommerce.com/document/woocommerce-blocks/). ~~Also the old inline docs in readme.txt have been removed, and replaced with a link to official documentation.~~ See #1758 

See also #1749

### CODE REVIEW

**Comment by nerrad** [comment]
> I'm a bit worried about how this change might affect search. Currently, if you search for Featured Product Block in the .org repo we are the first result. Will it be the same after this change?

This change likely will affect search. If I remember correctly [the description carries some weight](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/libs/site-search/jetpack-search.php?rev=5199#L756) in the elasticpress search results (just unknown exactly how much weight as the algorithm isn't public knowledge, for good reason).

**Comment by nerrad** [comment]
@haszari I would break the readme.txt change out of this pull so you can merge the description updates (and they aren't blocked by the discussion around the potential impact of the readme.txt changes).

**Comment by haszari** [comment]
Thanks @Aljullu & @nerrad – I've split out the readme change to a new PR so we can discuss implications there. 

https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1758

This PR now only contains the one liners, so merging :)

**Comment by haszari** [comment]
Thanks @Aljullu & @nerrad – I've split out the readme change to a new PR so we can discuss implications there. 

https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1758

This PR now only contains the one liners, so merging :)

**Pull request merged**
