### PR TITLE
Rename Add to Cart

### PR DESCRIPTION
**Pull request by gigitux**
This PR renames "Add To Cart Option" to "Add To Cart with Options" following this suggestion: https://github.com/woocommerce/woocommerce-blocks/pull/9238#issuecomment-1530076537

#### User Facing Testing

1. Open the Site Editor.
2. Go to the Single Product Template.
3. Click on the button "Upgrade to Blockified Single Product Template".
4. Click on the `Add to Cart" button.
5. On the sidebar, check the name of the block. Be sure that the name is "Add to Cart with Options".

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by nefeline — COMMENTED** [review]
I'd recommend updating the name on `tests/e2e/specs/backend/add-to-cart-form.test.js` [as well](https://github.com/woocommerce/woocommerce-blocks/pull/9316/files).

**Comment by gigitux** [comment]
> I'd recommend updating the name on `tests/e2e/specs/backend/add-to-cart-form.test.js` [as well](https://github.com/woocommerce/woocommerce-blocks/pull/9316/files).

Good point! Updated via [ecd3a00](https://github.com/woocommerce/woocommerce-blocks/pull/9315/commits/ecd3a00504a48701d73615e8239d4069692bdc00)

**Review by nefeline — APPROVED** [review]
🚀

**Review by thealexandrelara — APPROVED** [review]
Nice! LGTM!  🚀

**Pull request merged**
