### PR TITLE
Ensure variation data is populated with unspecified default attribute values

### LINKED ISSUE #6774: Getting empty variation array when adding a variation item without providing attributes using the `/cart/add-item` endpoint
## Describe the bug

When adding a variation item with default attributes (see image below) to the `Cart Block` via the `/cart/add-item` endpoint without providing the `variation` attribute we get a [Cart Response](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#cart-response) instead of an [Error Response](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#error-response) and the variation field of the `Cart Response` is empty.

image

## To reproduce

I created a new local WordPress environment and imported the WooCommerce sample products.

1. Via a rest client, make request for your store with` /wp-json/wc/store/v1/cart` in order to fetch valid Store nounce (or [Disable Nonces for Development](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/nonce-tokens.md#disabling-nonces-for-development))
2. Copy the ID of a variation from `the Hoodie` variable product.
3. Add variation item to cart with:
```
/wp-json/wc/store/v1/cart/add-item?id=31&quantity=1&variation[0][attribute]=Logo&variation[0][value]=No
```

4. You will get a `Cart Response` containing the item with a correct variation field:

image

5. Add the same item, but this time without providing its attribute:

```
http://dev-store.local/wp-json/wc/store/v1/cart/add-item?id=31&quantity=1
```

7. You will get `Cart Response` (success), but with missing variation info:

image

8. We end up with two different cart items with the same ID. One has variation info, and the other doesn't! 

## Expected behavior

If it is possible to add item to cart only by product id (no matter if it is variation or not), then Cart Response should return valid information about that product (eg. return product variation info), or add item to cart should not work for ID's of variation. 
I expected Cart Response to return valid information, or Error Response.

### PR DESCRIPTION
**Pull request by wavvves**
When adding items to the cart via `/wp-json/wc/store/v1/cart/add-item` supplying variation id, the response's variation data mirrors the submitted request variation data, and does not reflect full variation data, including unspecified attributes that have default values, hence not being required on the request.
This PR fixes that, ensuring not only the response gets said data populated but also that two requests with or without optional attributes don't generate different cart ids.

Fixes #6774

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Import the WooCommerce sample products and find the Hoodie's variation ids. 
2. Via a rest client, make request for your store with /wp-json/wc/store/v1/cart in order to fetch valid Store nonce (or [Disable Nonces for Development](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/nonce-tokens.md#disabling-nonces-for-development))
3. Make a POST request with the nonce header set to `/wp-json/wc/store/v1/cart/add-item` with and without specifying an attribute with a default value:
With:
image
Without:
image
4. Ensure the `variation`  object returned with the response is populated with all the variations attributes in both cases: Example:
image

* [X] Do not include in the Testing Notes 

### WooCommerce Visibility

* [X] WooCommerce Core
* [X] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Resolved a bug that prevented full variation data from being returned in the response.

### CODE REVIEW

**Review by nielslange — APPROVED** [review]
Works as expected! 

<table>
<tr>
<td>Response from `trunk`
<br><br>

Screenshot 2023-01-18 at 18 50 27
</td>
<td>Response from this PR:
<br><br>

Screenshot 2023-01-18 at 18 51 39
</td>
</tr>
</table>

**Review by tarhi-saad — CHANGES_REQUESTED** [review]
Hello, @wavvves! Thank you for working on the fix! 🙌 I believe the attributes get inverted when they are omitted:

### Current behavior

| Added with attributes | Added without attribute |
| ------ | ----- |
| image | image |
| image | image |

I'm not sure, but I suspect that because the attributes of this product are inverted, it's seen as a distinct product when added without setting the default attributes:

image
This should be the same product!

### Expected behavior

If we add a product with default attributes via the API, whether we define these attributes or not, it should be regarded as the same product, and the quantity should be increased instead:

image

**Comment by wavvves** [comment]
> I believe the attributes get inverted when they are omitted

Awesome catch @tarhi-saad, I'll quickly fix that

**Review by tarhi-saad — APPROVED** [review]
Thank you, @wavvves, for the fix! 🙌 It works great! 🎉 Let's 🚢 it!

**Pull request merged**
