### PR TITLE
Product button: sync temporary number of items on instantiation

### PR DESCRIPTION
**Pull request by luisherranz**
## What

I've fixed a sync problem between the number of items in the cart (`state.woocommerce.cart`) and the number of items that we show in the Product Button (`context.woocommerce.temporaryNumberOfItems`).

## Why

We use two values to be able to trigger an animation when those values are different (for example, when updated from the MiniCart).  When using client-side navigation, we want to show the number in `state.woocommerce.cart`, not in `context.woocommerce.temporaryNumberOfItems` because the cart is the source of truth. Also, we don't want to trigger an animation, we want to show it right away.

## How

I've used a `useLayoutEffect` to sync the `temporaryNumberOfItems` with the cart items when the element is instantiated and the cart (`state.woocommerce.cart`) has already loaded. I don't love it because it means manually syncing both states, which is something we should try to avoid whenever possible.

Anyway, I'll think more about this pattern, but this should fix it for now.

It also adds `key`'s to the Product Collection array.

### Screenshots

<div>
    <a href="https://www.loom.com/share/c43275ccb80d4286b96da2c3b75e9280">
      
    </a>
  </div>

https://www.loom.com/share/c43275ccb80d4286b96da2c3b75e9280

### Testing

1. Add a Product Collection block
2. Add items to the cart
3. Paginate to a different page
4. Add more items to the cart
5. Check that when paginating back and forth, it shows the correct number of items
6. Open the MiniCart block
7. Change the number of items of products that are in the same page
8. Check that the animation is triggered
9. Change the number of items of products that are not in the same page
10. Navigate to the page that has those products and check that the number of items is correct
11. Use a cache plugin (or simulate a cached page)
12. Check everything again

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Fixed a sync problem between the number of items in the car and the number of items that we show in the Product Button

### CODE REVIEW

**Review by imanish003 — APPROVED** [review]
Hey @luisherranz,

Appreciate the prompt resolution of the issue. I've tested the modifications, and it seems the problem is resolved 🚀.

Additionally, the code changes look good to me. As I'm still acquainting myself with the intricacies of coding related to the Interactivity API, it would be helpful if either @DAreRodz or @gigitux could review the code as well. 

Thanks! 🙌🏻

**Comment by luisherranz** [comment]
> I don't love it because it means manually syncing both states, which is something we should try to avoid whenever possible.

I guess this is ok to merge because it fixes the pagination issue, but we need to make `state.woocommerce.cart` the source of truth at some point (i.e., the one that reads on idle) or we're going to keep bumping into syncing problems like this:


https://github.com/woocommerce/woocommerce-blocks/assets/3305402/b90228a7-b576-4208-b123-fe9e2c32ed2c

**Comment by luisherranz** [comment]
By the way, I just checked and it seems to work fine with the Products (beta) block as well because the Products Template block is the same, but it'd be great if someone could confirm this 🙂

**Comment by gigitux** [comment]
> By the way, I just checked and it seems to work fine with the Products (beta) block as well because the Products Template block is the same, but it'd be great if someone could confirm this 🙂

I tested with the Products beta block and it doesn't work:
<video src=https://github.com/woocommerce/woocommerce-blocks/assets/4463174/ae093cda-3611-4c05-8107-116ef2506a2f />

On the `Products (beta)` block, the Products Template block is just a variation of the Post Template core block. ([source code](https://github.com/woocommerce/woocommerce-blocks/blob/9bcd7f49fed5fab433fdf96d6d2964a371e2bda0/assets/js/blocks/product-query/variations/elements/product-template.tsx/#L13-L25)). So this means that the `data-wc-key` isn't added. I suspect that adding this attribute to the post template could be complex.

Since we will migrate all the Products (beta) blocks to the Product Collection and deprecate the Products (beta) block, I would enable https://github.com/woocommerce/woocommerce-blocks/pull/10200 only for the Product Collection.

Thoughts? cc @kmanijak @imanish003

**Comment by luisherranz** [comment]
Ok. Thanks for checking this out, @gigitux 🙂

**Comment by imanish003** [comment]
Hey @gigitux,

> Since we will migrate all the Products (beta) blocks to the Product Collection and deprecate the Products (beta) block, I would enable https://github.com/woocommerce/woocommerce-blocks/pull/10200 only for the Product Collection.
> 

If it's not feasible to include `data-wc-key` in the post template, then it would be logical to enable it solely for the Product Collection block.

@luisherranz FYI `Products (Beta)` block is a variation of Query Loop block. It uses variation of `post-template` block, as you can see [here](https://github.com/woocommerce/woocommerce-blocks/blob/9bcd7f49fed5fab433fdf96d6d2964a371e2bda0/assets/js/blocks/product-query/variations/elements/product-template.tsx). Therefore, I am not sure how we can add `data-wc-key` to it. The PHP file of `post-template` can be found [here](https://github.com/WordPress/gutenberg/blob/4388c487ab896f9fb2e06a97ddbc94d5a3d2e0f5/packages/block-library/src/post-template/index.php) on GB repo.

If it’s not possible to add `data-wc-key` to Post Template, then:

- We will need to revert https://github.com/woocommerce/woocommerce-blocks/pull/10200 which adds client-side navigation for Products beta block.
- You have added `data-wc-key` to `src/BlockTypes/ProductTemplate.php`, which is used by Product Collection block, that we need to keep because client-side navigation was also introduced for Product Collection block in https://github.com/woocommerce/woocommerce-blocks/pull/10361. We are going to release Product Collection block in 1-2 weeks.

**Comment by luisherranz** [comment]
> I am not sure how we can add data-wc-key to it. The PHP file of post-template can be found here on GB repo

I'm not saying that you should, but in theory you could add it using the WP_HTML_Tag_Processor and the `render_block_core/post-template` filter, although I'm not sure where you could get the post id.

Anyway, I think it'd be simpler to add it to the new block only if the old one is going to be deprecated soon.

> We are going to release Product Collection block in 1-2 weeks.

By the way, we still need to figure out the (auto) opt-in/out mechanism.

**Comment by imanish003** [comment]
@luisherranz 
> By the way, we still need to figure out the (auto) opt-in/out mechanism.

May I know what you mean by `(auto) opt-in/out mechanism.`? 🤔

**Comment by gigitux** [comment]
> > I am not sure how we can add data-wc-key to it. The PHP file of post-template can be found here on GB repo
> 
> I'm not saying that you should, but in theory you could add it using the WP_HTML_Tag_Processor and the `render_block_core/post-template` filter, although I'm not sure where you could get the post id.
> 

Yeah, we can follow this approach, but Product Collection will be released soon so I don't see any advantages to do this kind of work.

> Anyway, I think it'd be simpler to add it to the new block only if the old one is going to be deprecated soon.
> 
> > We are going to release Product Collection block in 1-2 weeks.
> 
> By the way, we still need to figure out the (auto) opt-in/out mechanism.

Can you expand this?

**Comment by luisherranz** [comment]
The client-side router knows how to hydrate interactive blocks that use the Interactivity API (like the Product Button block), but it doesn't know how to hydrate interactive blocks that rely on DOM ready events or other methods for hydration. Therefore, if people add external interactive blocks to the Product Template, they won't work after the first client-side navigation.

We need to figure out an opt-in or an opt-out mechanism to enable/disable the client-side navigation. It can be manual or we may try to do something that is more automatic. Either way, the site owner should be able to overwrite its value, so probably the options should be `"on"`, `"auto"` and `"off"`.

We could start with an `"off"` by default that users can turn `"on"` (opt-in). Then try to figure out if there's a way to make it automatic in a way that is reliable, and if there is, switch to `"auto"` by default (opt-out).

**Review by DAreRodz — APPROVED** [review]
I see it great codewise. 😄 ✅ 

BTW, @luisherranz, what do you think of moving the `layout-init` logic to the regular `init` directive in the future? E.g., `init` could also accept an object, which would contain the callback path and if it's going to do a layout change.

```html
<button data-wc-init='{ "path": "init.ItemsOnLoad", "layout": true }'>
```

I'm aware that this would make directives bigger; I'm just curious about your opinion on this.

**Comment by DAreRodz** [comment]
@gigitux @imanish003, regarding the (auto) opt-in/out mechanism and the `data-wc-key` issue, are they blockers that prevent merging this PR? 🤔

**Comment by luisherranz** [comment]
> I'm just curious about your opinion on this.

It's an interesting alternative. Would you mind sharing it in this discussion?

- https://github.com/WordPress/gutenberg/discussions/51863

**Comment by gigitux** [comment]
I think that we can merge this PR, right? cc @imanish003 @luisherranz

**Comment by imanish003** [comment]
> I think that we can merge this PR, right? cc @imanish003 @luisherranz

I think so. I plan to review it once more today to ensure that everything is functioning as intended.

**Review by imanish003 — APPROVED** [review]
I've tested the fix, and I can confirm that everything is working as expected. I greatly appreciate the video explanation, @luisherranz. It was incredibly helpful in comprehending the modifications made in this pull request. 🚀

**Comment by luisherranz** [comment]
> I think that we can merge this PR, right? cc @imanish003 @luisherranz

It's fine to me. We will improve it in the future.

**Comment by imanish003** [comment]
> > I think that we can merge this PR, right? cc @imanish003 @luisherranz
> 
> It's fine to me. We will improve it in the future.

@luisherranz I believe we're ready to proceed with merging this PR. If you're in agreement, could you please merge it?

**Comment by luisherranz** [comment]
Oh, I didn't realize it had to be me the one merging it. I'll merge it now.

**Pull request merged**
