### PR TITLE
Fix: Display the correct title for templates from theme

### LINKED ISSUE #5564: `archive-product` block template doesn't correctly show its title
## Describe the bug
The slug `archive-product` does not get parsed into the correct human readable title.

## To reproduce

1. Go to Appearance → Editor → Browse all templates
2. Make sure you have `archive-product.html` in your theme's templates directory
2. Notice how the slug is not parsed into a title

## Expected behavior
Slug should read "Product archive" if language is set to English.

## Screenshots
Screen Shot 2022-01-13 at 23 47 44

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #5564

This PR searches through all available templates for WC templates from themes that don't have the correct title and then fixes those template titles using `BlockTemplateUtils::convert_slug_to_title()`.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
| image | Screen Shot 2022-05-25 at 12 14 58 |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to Appearance → Editor → Browse all templates
2. Make sure you have `archive-product.html` in your theme's templates directory
2. Notice the `archive-product.html` template shows the correct title and description.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Ensure WooCommerce templates show correct titles.

### CODE REVIEW

**Comment by gigitux** [comment]
Thanks for working on this!

@dinhtungdu There is a similar PR about this issue (#6345). Could you take a look?

**Comment by dinhtungdu** [comment]
> There is a similar PR about this issue (#6345). Could you take a look?

@gigitux two PRs are similar but different. #6345 handle the template from the plugin while this PR fixes the title for templates from themes that don't exist in the `theme.json` file. I tested #6345 with the `archive-template.html` from the 2022 theme, the template isn't listed in `theme.json`, and the slug still shows up:
 
image

**Comment by dinhtungdu** [comment]
We can wait for 6345 to be merged then update this PR to support both title and description.

**Comment by gigitux** [comment]
Ops, I didn't notice this! 

> We can wait for 6345 to be merged then update this PR to support both title and description.

It makes sense! Thanks :D

**Comment by gigitux** [comment]
Head-up to say that #6345 has been merged :D

**Comment by dinhtungdu** [comment]
> Head-up to say that #6345 has been merged :D

@gigitux Thanks for the head up! I update the PR, can you please give this another look?

**Review by gigitux — APPROVED** [review]
Thanks for working on this! LGTM! 🚢

**Pull request merged**
