### PR TITLE
Align local pickup and shipping selector heights

### LINKED ISSUE #8393: Local Pickup/Shipping selector should have same height regardless of content
There are some cases in which Local Pickup selector have a different height from the shipping one, however, both should have the same height regardless of content.

image

### Reproduce Steps

1. Enable Local Pickup.
2. In the editor settings of Local Pickup, disable price.
3. In WooCommerce -> Settings -> Shipping -> Shipping Options set ` Hide shipping costs until an address is entered` to true.
4. In Checkout, you should see an unbalanced view.

### PR DESCRIPTION
**Pull request by senadir**
This PR fixes some height issues in Local Pickup and Shipping selector height when they mismatch

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8393

### Screenshots

| Before | After |
| ------ | ----- |
|image|Screenshot 2023-02-07 at 15 45 23Screenshot 2023-02-07 at 15 41 54Screenshot 2023-02-07 at 15 41 10|

#### User Facing Testing

1. Enable Local Pickup.
2. In the editor settings of Local Pickup, disable price.
3. In WooCommerce -> Settings -> Shipping -> Shipping Options set  Hide shipping costs until an address is entered to true.
4. In Checkout, you should see a balanced view.

### CODE REVIEW

**Review by alexflorisca — CHANGES_REQUESTED** [review]
The front-end looks good, but the editor styles are broken. Think you just need to add the `height: 100%` property back in

Screenshot 2023-02-08 at 10 16 50

**Comment by elizaan36** [comment]
@senadir Does this fix only the height, or does it make sure that the price text is either visible or not for both? Just checking because even when the height is consistent, the space with missing text looks odd in the pickup toggle. (In this example from the original comment) 
image

**Comment by senadir** [comment]
This simply fixes the height, it doesn't check for both. A check is indeed better.

**Comment by nielslange** [comment]
> The front-end looks good, but the editor styles are broken. Think you just need to add the `height: 100%` property back in
> 
> Screenshot 2023-02-08 at 10 16 50

Given that @senadir is working on a different project currently, I took over this task. I looked into this and noticed that adding  `height: 100%` would fix the height in the editor, but would break it in the frontend again. I solved the problem by adding `height: unset`. This ensures that the buttons have the same height both in the editor and in the frontend.

**Comment by nielslange** [comment]
> @senadir Does this fix only the height, or does it make sure that the price text is either visible or not for both? Just checking because even when the height is consistent, the space with missing text looks odd in the pickup toggle. (In this example from the original comment)
image

@elizaan36 Given that @senadir is working on another project, I took over this issue from him. As Nadir mentioned in https://github.com/woocommerce/woocommerce-blocks/pull/8394#issuecomment-1443978676, there's no check if the price text exists. However, if both buttons do not have a price, their height automatically shrinks:

Screenshot 2023-03-01 at 14 11 22

**Comment by elizaan36** [comment]
@nielslange Thanks for picking this up.

> there's no check if the price text exists

To clarify, sounds like the problem to solve is when Local pickup doesn't have a defined price. However, if there's no defined price isn't it 0/Free by default?

There shouldn't be a use case where one toggle has a price and one doesn't. There should always be some default text there to solve for what otherwise looks like a visual bug. What do you think?

**Review by tarunvijwani — APPROVED** [review]
<strike>Works great! 🎉 </strike>

@nielslange Sorry, I didn't check the last comment and approve the PR. I'll wait to finish the additional changes requested above and review it again.

**Comment by tarunvijwani** [comment]
>There shouldn't be a use case where one toggle has a price and one doesn't. There should always be some default text there to solve for what otherwise looks like a visual bug. What do you think?

@elizaan36 If we haven't entered the address or the address differs from the local pickup address, it will show an empty box. 

I think we should also add placeholder text such as "Calculated with an address" for local pickup like we have one for the shipping. 

A placeholder like "Calculated with an address" or if the address has been entered, then "Local pickup not available for given address" might help. Let me know your thoughts. 🙂


| Before | After |
|---|---|
|image|image|

**Comment by opr** [comment]
@nielslange I _believe_ Tarun has fixed this in https://github.com/woocommerce/woocommerce-blocks/pull/8623 but I'm not 100% sure!

**Comment by tarunvijwani** [comment]
> @nielslange I _believe_ Tarun has fixed this in #8623 but I'm not 100% sure!

Yes, this was happening due to incorrect local pickup rates. We can close this issue now as this is being fixed in #8623. 
Thank you for pointing that out, @opr. 😃

**Comment by nielslange** [comment]
@opr and @tarunvijwani Thanks for pointing out #8623. 🙏 I just tested that other PR and it makes this PR obsolete. I'm closing this one now.

**Pull request closed without merging**
