### PR TITLE
Add default currency value for Storybook

### LINKED ISSUE #8145: ProductPrice story is broken
## To reproduce

1. Run `npm run storybook` and open the Storybook page.
2. Go to any of the _ProductPrice_ stories.
3. Notice an error appears:

imatge

## Expected behavior

The component should be displayed correctly without an error.

### PR DESCRIPTION
**Pull request by roykho**
This PR fixes the `can't access property "minorUnit", currency is not defined` error on the ProductPrice story.

Fixes #8145 

#### User Facing Testing

1. Checkout this branch.
2. Run `npm run storybook` and open up the Storybook page.
3. Go to the ProductPrice stories.
4. Ensure you don't see any errors in the console and that the price is correctly displaying on the page.

* [ ] Do not include in the Testing Notes 

### Changelog

> Fix ProductPrice story in Storybook.

### CODE REVIEW

**Comment by roykho** [comment]
~~There seems to be failing JS Unit tests -- Looking into this.~~

This is fixed.

**Review by Aljullu — COMMENTED** [review]
Confirming it fixes the issue, thanks @roykho! It looks like this happened because when the component was loaded in the Story Book, it didn't have a currency by default.

I'm not sure about fixing it in the components itself instead of fixing it in the story, though. :thinking: If we do expect all currencies to have `minorUnit`, I don't think we need to add a guard in the component code. Instead, we could fix it in the [story control](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/storybook/custom-controls/currency.ts#L36) setting `defaultValue: currencies.USD,`. What do you think?

**Comment by roykho** [comment]
@Aljullu - Yeah I agree. Good catch. I just pushed up the changes.

**Comment by sunyatasattva** [comment]
Sorry I just saw this now. Just to let you folks know, there was already a PR open for this [here](https://github.com/woocommerce/woocommerce-blocks/pull/8049). I'm not sure why the GitHub interface didn't pick it up. We were discussing with @thealexandrelara some type issues within the story, and I kind of deprioritized it.

Not sure if we should continue the work on the Storybook default there, and perhaps leave this PR as adding a default currency, if we want.

**Comment by roykho** [comment]
Ah ok, since a lot of conversation has been had in your other [PR](https://github.com/woocommerce/woocommerce-blocks/pull/8049) I think any changes to fix this should be done there to prevent future confusions. So I will close this one.

**Comment by sunyatasattva** [comment]
Sorry @roykho for not catching this earlier! I hope the work on Storybook was anyways somehow instructive and propaedeutic to your knowledge of the repo 🙏

**Pull request closed without merging**
