### PR TITLE
Add to Cart Form: Replace Notice with Skeleton component

### LINKED ISSUE #8818: Add to Cart Form: improve preview on the editor side
## Describe the bug

The Add to Cart Form block shows a notice inside the canvas. We have to render a skeleton instead of a notice.

## To reproduce

1. Edit the Single Product Template.
2. Edit the template via code editor and insert [this markup](https://gist.github.com/gigitux/e9323d6d280313f528996e34d62ae626).

https://user-images.githubusercontent.com/4463174/226871234-4c43b148-ba46-4949-8cc6-0c77a7f435d6.mov

## Expected behavior

The notice has to be replaced with a skeleton.

## Screenshots

|Current|To be implemented|
|--------|--------|
|image|image|

### PR DESCRIPTION
**Pull request by thealexandrelara**
This PR replaces the Notice component of the Add To Cart Form block with a Skeleton component

Fixes #8818

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
| image | image  |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to Appearance > Themes and activate a Blockfied theme, such as: Twenty-twenty Three;
2. After the theme is activated, go to Appearance > Editor (Beta);
3. Inside the Design section, click on Templates;
4. Select the Single Product template;
5. On the top left of the page, click on the Edit button;
6. On the top right of the page, click on the three dots icon and open the Code Editor (or just hit Shift + Option + Command + M on the Mac);
7. Replace the default `wp-group` section with the `wp-group` section inside the [templates/templates/blockified/single-product.html file of this PR](https://github.com/woocommerce/woocommerce-blocks/blob/ae3d39f15a62fa2d9fe559bffd245fbbaf601881/templates/templates/blockified/single-product.html).
8. Click on the Save button;
9. Check that the Skeleton component appears above the Add To Cart button

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Replace the Notice component with the Skeleton component for the Add to Cart Form block

### CODE REVIEW

**Review by gigitux — CHANGES_REQUESTED** [review]
We should add the popover that says: "The customer will see the..."

image

**Comment by thealexandrelara** [comment]
> We should add the popover that says: "The customer will see the..."
> 

I think we have a limitation to do that, because the block wrapper disables some mouse events, so if we put a popover inside the block wrapper it wouldn't trigger the mouseover event. In that case, we could put it around the block wrapper, but I don't know if it would be the best solution, what do you think?

**Comment by gigitux** [comment]
Hey, @thealexandrelara, I added the tooltip and also updated the class names on the editor site to follow the CSS guidelines via [41c2aa7](https://github.com/woocommerce/woocommerce-blocks/pull/8842/commits/41c2aa7a0f8ad56cd829f277561cc7b4770e3d52).
Could you take a look?

**Comment by thealexandrelara** [comment]
> Hey, @thealexandrelara, I added the tooltip and also updated the class names on the editor site to follow the CSS guidelines via [41c2aa7](https://github.com/woocommerce/woocommerce-blocks/pull/8842/commits/41c2aa7a0f8ad56cd829f277561cc7b4770e3d52).
Could you take a look?

Looking great, thank you! Just a question regarding the Tooltip position, on the image you shared the tooltip appears at the top, but in the current implementation it is appearing at the bottom, is that expected?

**Comment by gigitux** [comment]
> > Hey, @thealexandrelara, I added the tooltip and also updated the class names on the editor site to follow the CSS guidelines via [41c2aa7](https://github.com/woocommerce/woocommerce-blocks/pull/8842/commits/41c2aa7a0f8ad56cd829f277561cc7b4770e3d52).
> > Could you take a look?
> 
> Looking great, thank you! Just a question regarding the Tooltip position, on the image you shared the tooltip appears at the top, but in the current implementation it is appearing at the bottom, is that expected?

Good observation! If we put the tooltip on the top, it will be on top of the quick controls, for this reason, I preferred to move it at the bottom!

**Comment by thealexandrelara** [comment]
> Good observation! If we put the tooltip on the top, it will be on top of the quick controls, for this reason, I preferred to move it at the bottom!

Great! I agree with the change, if it's okay to you, we can approve this PR and merge it

**Comment by gigitux** [comment]
I added the different cursor style as design specs via [3c4a05b](https://github.com/woocommerce/woocommerce-blocks/pull/8842/commits/3c4a05b367201bb209a76e6140df14a6dd6de9d7).

**Review by gigitux — APPROVED** [review]
LGTM

**Comment by opr** [comment]
@thealexandrelara I have added the correct labels to this PR.

**Pull request merged**
