### PR TITLE
Product Collection: Transfer layout options from Toolbar to Inspector controls

### LINKED ISSUE #42225: Product Collection: Implement layout options (Stacked, Grid, Scroll)
Related Github Discussion: https://github.com/woocommerce/woocommerce-blocks/discussions/10692 

### **Summary**:
- Implement layout options (Stacked, Grid, Scroll) in the Product Collection block

### **Background**:
- The existing Product Collection block allows users to toggle between two layout types: grid and list. @shaunandrews proposes an updated "Layout" selector in the block's inspector, introducing a new layout type "Scroll," and renaming the existing ones to "Stacked" and "Grid."

### **Acceptance Criteria**:
- A new "Layout" dropdown should exist in the Collection block's inspector.
  - "Stacked" should map to the existing list layout.
- Implement a new "Scroll" layout that allows products to extend out of the viewport and be horizontally scrollable/draggable, with next/prev buttons for navigation.
- The implementation should be responsive.

### **Designs**:
- Figma: zx83mG5ZnDiacPdH6GlO2j-fi-5_13995
image

### **Feedback Loop**:
- The task will undergo a review by the UX designer to evaluate the implementation against the designs and propose possible refinements.
```[tasklist]
### Tasks
- [x] **Transfer layout options** from the Toolbar to the Inspector controls. Currently, we have Grid view and List view in the Toolbar.
- [ ] **Scroll Layout**: Add the Scroll layout option to the Product Collection block.
```

### PR DESCRIPTION
**Pull request by imanish003**
## What

This PR Transfer layout options from the Toolbar to the inspector controls. Here is what result looks like:
image

Part of woocommerce/woocommerce#42225

## Why

- This PR is the initial step in a broader effort to enhance the layout options available in the Product Collection block, as detailed in this [Github discussion](https://github.com/woocommerce/woocommerce-blocks/discussions/10692). In this installment, we focus on transferring the layout options from the toolbar to the inspector controls and updating the terminology used to describe these layouts. For more info check woocommerce/woocommerce#42225.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

#### **Case 1: Normal flow**
1. Create a new post.
2. Add the product collection block.
3. **Verify:** In the sidebar settings, the options for layout should be visible with 'Grid' being the default selection. Refer to this screenshot for guidance:  
image
4. **Verify:** The products in the editor should be displayed in a grid view by default. Publish the post and ascertain that the grid view is maintained on the frontend.
5. Change the layout setting to 'Stack'. Ensure that in the editor, products now appear in a single column. Save or update the post and check the frontend to confirm the single column display is applied there as well.

#### **Case 2: Reset button**
1. Create a new post and add the product collection block.
2. Open the sidebar settings and note the absence of a 'RESET' option in the layout menu, indicated in the screenshot:  
image
3. Change the layout from 'Grid' to 'Stack'. Open the settings menu again to find the 'RESET' button now visible, as shown here:  
image

4. Verify that clicking the 'RESET' button changes the layout back to 'Grid'. Similarly, clicking the 'Reset all' button should revert the layout to 'Grid'.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [X] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Collection: Transfer layout options from the Toolbar to the Inspector controls

### CODE REVIEW

**Review by sunyatasattva — APPROVED** [review]
Code looks great! Well done @imanish003 ! Clean and easy to ready and well split!

I just have a couple of concerns regarding the actual experience:

1. [Minor] When I add the block, I see an animation on the inspector control selecting “Grid” (the default), is that unavoidable?
2. I'm a a bit concerned about the names of these options and about the disregard of responsive controls. The “GRID” layout effectively is stacked on smaller viewports, making the distinction effectively meaningless (it even feels weird, as when I switch between them, the only thing that happens is a slight change in the margins: so it doesn't even feel consistent). Personally, I'm concerned about our lack of support for mobile use-cases, when they are such a big part of the eCommerce ecosystem. I fear that we, as developers, testing on our desktop devices, often forget of the needs of real world merchants.

I have already expressed my concern during my rotation for Ghetto Gastro (p6q8Tx-3ei-p2), in which I found that to be a huge limitation of FSE tools.

I'm approving this PR as I think this is part of a bigger conversation, but I wanted to flag it to you.

**Comment by imanish003** [comment]
> [Minor] When I add the block, I see an animation on the inspector control selecting “Grid” (the default), is that unavoidable?  

- From what I know, this animation appears to be the default whenever `ToggleGroupControl` renders.
    - I've confirmed that the value is only set once, meaning we don't first set it to 'stack' and then to 'grid'.
- One possible solution is to rearrange the order, putting Grid before Stack. However, this would not align with the designs. Therefore, I believe it's best to leave it as it is. Perhaps it will be fixed upstream in the future. What are your thoughts?

> I'm a a bit concerned about the names of these options and about the disregard of responsive controls. The “GRID” layout effectively is stacked on smaller viewports, making the distinction effectively meaningless (it even feels weird, as when I switch between them, the only thing that happens is a slight change in the margins: so it doesn't even feel consistent). Personally, I'm concerned about our lack of support for mobile use-cases, when they are such a big part of the eCommerce ecosystem. I fear that we, as developers, testing on our desktop devices, often forget of the needs of real world merchants.  

Thank you for initiating this conversation 🙏🏻
I agree that GRID and STACK might behave similarly on small devices, which is the expected behavior if we want to maintain block responsiveness. We've also created a new issue woocommerce/woocommerce-blocks#10827 focused on improving the responsiveness of the Product Collection block. We plan to add a toggle labeled "Shrink columns to fit" to make the number of columns responsive while still allowing merchants to set a "max columns." Here's a screenshot of the new design:

image


I will merge this PR, and we can continue our conversation here 💪🏻

**Comment by sunyatasattva** [comment]
> One possible solution is to rearrange the order, putting Grid before Stack. However, this would not align with the designs. Therefore, I believe it's best to leave it as it is. Perhaps it will be fixed upstream in the future. What are your thoughts?

I stupidly hadn't thought of changing the order. Honestly—and it might be my LTR bias—I think getting the default option on the left would make more sense. It's tough since Shaun rotated away, but maybe we can check how Gutenberg does it in other situations? Are the default values usually on the left?

> I agree that GRID and STACK might behave similarly on small devices, which is the expected behavior if we want to maintain block responsiveness. 

I think it is “expected” as in our “intended” behavior. I don't think, personally, it is expected by the user for “grid” and “stack” to be the same thing. But, then again, it's a bigger topic and definitely the screenshot you sent and the issue you mentioned would pave the way for better UX! 🙌

**Comment by imanish003** [comment]
> but maybe we can check how Gutenberg does it in other situations? Are the default values usually on the left?

I think it typically makes sense to keep the default option on the left, but it's more of a UX decision. I found one example in Gutenberg where the Default option is on the right. Take a look at the 'Orientation' setting in the 'Stack' block below:

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/24aa4d0e-2474-48e8-b413-68d4d14f59e7

> But, then again, it's a bigger topic and definitely the screenshot you sent and the issue you mentioned would pave the way for better UX! 🙌

💯

**Pull request merged**
