### PR TITLE
Add back ToggleButtonControl component in WC Blocks 8.9 so it supports WP 5.9

### PR DESCRIPTION
**Pull request by Aljullu**
This PR adds back the `ToggleButtonControl` component and uses it instead of `ToggleGroupControl` from GB. The reason is that the GB component is not available in WP 5.8, and we need to support it in WC 7.2. In practice, this PR reverts #5967.

The plan is to merge this PR only in `release/8.9.x`, so we only revert #5967 in the 8.9.x branch, but not in `trunk`.

#### User Facing Testing

1. In WP 5.8.
2. Create a post or page.
3. Add the Filter by Attribute block.
4. Select one of the attributes.
5. Verify the block is added correctly, you can publish the post/page and there is no error.
6. Play around with the block display settings and verify the block honors them:

7. Test also these blocks (in all of them, interact with the toggles on the sidebar of the editor and verify the block doesn't crash and the settings are applied correctly):
   * Feature Product
   * Featured Category
   * Product Image (you will need to add the All Products block, click on the pencil icon to edit its inner blocks, and select the image)
   * Active Product Filters (you will need to select the Controls inner block)
   * Filter by Price (you will need to select the Controls inner block)
   * Product Categories List

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix Filter by Attribute block crashing in the editor of WordPress 5.8.

### CODE REVIEW

**Review by sunyatasattva — APPROVED** [review]
Tested and works as intended!

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
@Aljullu Featured Products and Featured Category are still using `ToggleGroupControl`, which is broken when editing in the Editor. We should fix it there too IMO. Otherwise, this is LGTM.

image

**Comment by Aljullu** [comment]
Good catch, @dinhtungdu! I fixed it in c31b3c71ff071c8b0cf7ad06e55255d2c6ecbec6 and updated the PR testing steps.

**Review by dinhtungdu — COMMENTED** [review]
@Aljullu Look like we discovered another error. After choosing a category to display for the Featured Category block, I got this, can you reproduce in your end?

image


image

**Comment by Aljullu** [comment]
> @Aljullu Look like we discovered another error. After choosing a category to display for the Featured Category block, I got this, can you reproduce in your end?

This should be fixed in addac8e25c1fd4f8904ecbffdd8d2e4b212bb1de. Thanks for catching it, @dinhtungdu!

I noticed there is an issue with the button alignment when inserting the block: it defaults to left alignment.

imatge

This can be changed directly from the editor, so I consider it not a blocker. Also, I'm uncertain whether there is an easy way to fix it without breaking it in newer WP installs.

**Review by sunyatasattva — APPROVED** [review]
Alright, as discussed in Slack, all provided testing steps work for me as intended. Thanks for this patch!

**Pull request merged**
