### PR TITLE
fix/8651: Use body background color as the Cart block sticky footer background color

### LINKED ISSUE #8651: Cart block sticky footer in mobile should have the same background as the main content
## To reproduce

1. Set your theme to a dark style (ie TT3 with Pilgrimage styling).
2. Go to the Cart block page on mobile.
3. Notice the sticky footer has white background.

## Expected behavior

The sticky footer should honor the background of the main content.

For reference, the Mini Cart bock does something similar for the drawer background, see https://github.com/woocommerce/woocommerce-blocks/pull/7510. Ideally we should be able to reuse the same logic.

### PR DESCRIPTION
**Pull request by iamdharmesh**
PR adds a dynamic background-color style to the sticky footer container div to make it match with the body background color.

Fixes #8651 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Set your theme to a dark style (ie TT3 with Pilgrimage styling).
2. Go to the Cart block page on mobile.
3. Verify the sticky footer background (available on a mobile view) match the body background color.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Use body background color as the Cart block sticky footer background color

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
Thanks for your contribution, @iamdharmesh! This is the kind of enhancement that will dramatically improve how the Cart block looks in themes with background colors different than white. :clap: 

I tested it and it's working as expected, the code looks good as well. My only concern is that the box-shadow looks a bit out of place if the background color is dark:

imatge

I wonder if we should reduce its opacity (`$alpha` value in [this line](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss#L36)) a bit. IMO `$alpha: -0.7` looks a bit better in dark themes while not having a huge impact on dark themes. What do you think? cc @nielslange.

**Comment by iamdharmesh** [comment]
Hi @Aljullu, Thanks for reviewing PR.

> I wonder if we should reduce its opacity ($alpha value in [this line](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss?rgh-link-date=2023-04-19T12%3A54%3A28Z#L36)) a bit. IMO $alpha: -0.7 looks a bit better in dark themes while not having a huge impact on dark themes. What do you think?

Sure thing. let me update it.

**Comment by nielslange** [comment]
Thanks for working on this, @iamdharmesh! As @Aljullu mentioned, this contribution is very helpful. Besides what Albert mentioned, I noticed a tiny problem, which is unrelated to the initial issue. On my end, the `Proceed to Checkout` button is cut off:

Screenshot 2023-04-19 at 20 03 13

It appears that this problem is related to the CSS box model and caused in https://github.com/woocommerce/woocommerce-blocks/blob/d0c1f9806220bd9e9513eddc9e6e4cb9f9468df5/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss#L25-L32.

I believe changing 
```css
width: 100%;
```
to
```css
width: calc(100% - 2 * $gap);
```
should fix this problem. Usually, I'd not suggest adding things that are unrelated to the initial issue. Given that this is a minor adjustment, I'd make an exception in this case. 

@Aljullu What do you think?

**Comment by Aljullu** [comment]
> @Aljullu What do you think?

I could reproduce the same. I think your suggestion makes sense. I don't have any preference whether this should be done as part of this PR or in a separate one. :slightly_smiling_face:

**Comment by iamdharmesh** [comment]
Hi @nielslange Thanks for the review.

> I noticed a tiny problem, which is unrelated to the initial issue. On my end, the Proceed to Checkout button is cut off:

Yes, I also noticed this issue but ignored it by considering the theme's issue. Because the button was showing fine on the "storefront". 

Updating to width to `calc(100% - 2 * $gap);` will break UI on some themes like "storefront" (See screenshot below). However, the issue has been fixed by `box-sizing: border-box;`.

image


@nielslange @Aljullu Please help to re-review once. 

Thanks

**Comment by nielslange** [comment]
> Yes, I also noticed this issue but ignored it by considering the theme's issue. Because the button was showing fine on the "storefront".
> 
> Updating to width to `calc(100% - 2 * $gap);` will break UI on some themes like "storefront" (See screenshot below). However, the issue has been fixed by `box-sizing: border-box;`.

Great catch, @iamdharmesh. In this case, please disregard my earlier comment.

**Review by nielslange — APPROVED** [review]
Thanks for the adjustment, @Aljullu suggested. The PR now works as expected. Thank you so much for your contribution, @iamdharmesh! 🙌

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 
-------------

Theme - Storefront
image


Theme -  Twenty Twenty-One
image


Theme -  Twenty Twenty-Two
image


Theme -  Twenty Twenty-Three
image

QA Status- Pass ✅

**Review by wavvves — APPROVED** [review]
Thank you so much for your contributions @iamdharmesh and @qasumitbagthariya! Approving and merging this 👏🏼

**Pull request merged**
