### PR TITLE
Use Server Side Rendering for Product Category List block

### LINKED ISSUE #1005: Performance of Block Settings on every page load without caching
This was reported in https://github.com/woocommerce/woocommerce/issues/24590

Blocks requires certain settings/data to function, and this needs to be present anywhere a block may be used (so admin and frontend, regardless of user type). This is output to JSON inline on every page load.

This can be problematic if doing large queries such as getting terms, and counting post types.

Currently, the JSON is generated in Assets.php here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/Assets.php#L86-L123

Most of this is harmless, with the exception of:

1. get_terms - this is querying all categories in the store and generating links for each.
2. wp_count_posts - less intensive but could still be cached.

We should look at either caching this data, using APIs instead as needed instead of grabbing data that may not be used, or making some of this conditonal.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR updates the Product Category List Block to use SSR instead of client side rendering in order to avoid passing a full list of terms via the `wcSettings` implementation on most page loads. As a result of this, `get_terms` is only invoked during the **rendering of the block**.

There is one gotcha however which I was unable to rectify, and perhaps @nerrad can confirm if this is a bug in SSR in Gutenberg. You'll notice I added `deprecation` to ensure existing blocks do not invalidate in the editor - this all works fine editor side, but if you view an existing block on the frontend, the saved attributes are not respected and defaults get used. This is only fixed by saving. @nerrad ideas on this one? 

Closes #1005

### Screenshots

Screenshot 2019-10-07 at 17 25 16

### How to test the changes in this Pull Request:

1. Create some product category list blocks (dropdown and list) before using this PR
2. Use PR. Confirm they transform/save correctly.
3. Confirm dropdown + list appearance is unchanged on frontend.
4. Test the dropdown navigates to the correct page on click.
5. Confirm hierarchy/count toggles update the list correctly.

### Changelog

> Use Server Side Rendering for Product Category List block to remove the need to pass large amounts of data around when not needed.

### CODE REVIEW

**Comment by nerrad** [comment]
> There is one gotcha however which I was unable to rectify, and perhaps @nerrad can confirm if this is a bug in SSR in Gutenberg. You'll notice I added deprecation to ensure existing blocks do not invalidate in the editor - this all works fine editor side, but if you view an existing block on the frontend, the saved attributes are not respected and defaults get used. This is only fixed by saving. @nerrad ideas on this one?

I'm not sure what you mean by "this is only fixed by saving".  Do you mean that before SSR works on the frontend, that content containing a block must be saved in the editor first?  Wouldn't that need to happen anyways, or do you mean that existing blocks in content will stop working how they were before on the frontend in this branch because _existing_ attributes aren't used?

**Comment by mikejolley** [comment]
@nerrad 

Before checking out this PR, create a category list block configured to display a dropdown
Check out PR
View frontend. You won't see a dropdown, you'll see a list (default)
View editor. You'll see a dropdown (works).
Save the post. Now view frontend. You'll see a dropdown (works).

**Comment by nerrad** [comment]
This isn't a bug with SSR.  The problem is how the attribute data was stored for the product categories block when serialized to post content in master vs in this branch.  Here's how it was stored:

```
<!-- wp:woocommerce/product-categories -->
<div class="wp-block-woocommerce-product-categories is-loading" data-has-count="true" data-is-dropdown="true" data-is-hierarchical="true"><span aria-hidden="true" class="wc-block-product-categories__placeholder"></span></div>
<!-- /wp:woocommerce/product-categories -->
```

That means that when the php block parser restores that, it will not get a list of attributes because they were not stored as an array of json attributes on the `wp:woocommerce/product-categories` expression (which after updating in this branch looks like:)

```
<!-- wp:woocommerce/product-categories {"isDropdown":true} /-->
```

This is an inherent flaw with switching between non-dynamic to dynamic blocks if an alternative mechanism was used for persisting data other than the built-in attributes json.

So "How do we resolve?"

Good question.  The data is there in the actual post content, it's just not accessible in the block renderer.

I think the one option we may have here if we want a straightforward transform for end users is to hook into the `render_block_data` filter found in `wp-includes/blocks.php` and apply a transform via detecting what is in the saved data-attributes (regex?).  The downside of this approach is the filter is only available since WordPress 5.1 so that bumps version requirements.

Another option if version requirements are a problem would be to hook in on the `render_block` filter (in that same code block) which is available with WordPress 5.0+.  However, an issue there is that filter runs AFTER everything has already gone through block renderers so you'd basically have to run the same logic twice :/

Another option is to do an upgrade routine that parses through all post_content and "upgrades" any  blocks detected in post_content needing transformed (probably expensive and not sure its' worth the effort here).

Another option is to still load the frontend js that handled transforming the block (probably less than ideal because it doesn't solve the issue the prompted this pull in the first place right?).

So... those are some options I can think of for now.  I'll leave it so you can get the wheels turning for yourself too.  I'll also mull on this and if something else comes to mind I'll ping you or update the pull.

**Comment by nerrad** [comment]
One thing we may want to consider going forward is ensuring that when have custom save output, we still persist attributes as well (that way any future migrations to a different rendering process can be a bit easier).

**Comment by mikejolley** [comment]
@nerrad Added some handling in the render callback to set values that differ from the defaults. Ready for re-review.

**Comment by mikejolley** [comment]
Tested in 5.0.6, spotted no issues.

**Pull request merged**
