### PR TITLE
All Products: Re-add alignment controls for Product Rating and Price

### LINKED ISSUE #3049: Product Price block: alignment options don't work consistently (when `Align last block` is enabled)
## To reproduce
1. Add a product price block.
2. In the block toolbar, change the alignment option to center or right.
3. Notice the price stays left-aligned.

### Update (discovered in 3.3.0 testing)
The alignment options don't work when `Align last block` is enabled.

1. Edit a page with an All Products block. Click pencil icon to edit item layout.
2. Add or select a product price block.
2. In the block toolbar, change the alignment option to left or right.
3. Click `Done`.
4. Select the All Products block and toggle the `Align last block` option. 
5. Notice that alignment only works correctly if `Align last block == off`. Issue affects editor preview and front end.

## Screenshots
Peek 2020-08-25 10-58

### PR DESCRIPTION
**Pull request by danieldudzic**
Since https://github.com/woocommerce/woocommerce-blocks/pull/8140 fixed the issue with **All Products** not saving settings correctly, this PR re-adds alignment settings for **Product Rating** and **Product Price** inside of the **All Products** block.

Fixes #3049

### Screenshots

| Before | After |
| ------ | ----- |
|Edit_Page_“Producs”_‹_ratings_—_WordPress|Edit_Page_“Producs”_‹_ratings_—_WordPress|

#### User Facing Testing

1. Create a new Page and add the **All Products** block.
2. Add the **Product Rating** and **Product Price**.
3. Confirm that the `Alignment` toolbar option is available for both blocks and works correctly (both in the editor and the frontend). 

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> All Products: Add alignment settings for the Product Rating and Product Price blocks.

### CODE REVIEW

**Review by sunyatasattva — CHANGES_REQUESTED** [review]
Thanks for this PR, @danieldudzic and sorry for the delay. The code works alright, however, the blocks are aligned on the center by default, but when adding the block for the first time and checking the alignment toolbar, none of the options are selected.

It feels like the correct option should be selected, no?

**Comment by tjcafferkey** [comment]
>It feels like the correct option should be selected, no?

@sunyatasattva I've updated the default values for these elements so they are now selected like expected. https://github.com/woocommerce/woocommerce-blocks/pull/8264/commits/e9f3320945d362dd8269b32cbbfce394b48357aa

**Review by sunyatasattva — APPROVED** [review]
Thanks for taking this, Tom! Works for me!

**Comment by haszari** [comment]
Nice work getting this old chestnut fixed @danieldudzic @tjcafferkey 🙌!

**Comment by dinhtungdu** [comment]
Checking `Do not include in the Testing Notes` for this PR in favor of more detailed testing instruction of #8526.

**Pull request merged**
