### PR TITLE
Remove order and checkout order endpoints experimental flag

### PR DESCRIPTION
**Pull request by hsingyuc**
## What
This PR removes the experimental flag for the order and checkout order endpoints.  

Fixes # N/A

## Why
The pay-for-order flow is compatible with WooPay now and is ready to launch so we are ready to remove the experimental flag on the endpoints.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Build the WC Blocks plugin
2. Test the https://github.com/woocommerce/woocommerce-blocks/pull/8960 and [checkout order ](https://github.com/woocommerce/woocommerce-blocks/pull/10287)endpoints

* [ ] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [x] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Remove order and checkout order endpoints feature flag.

### CODE REVIEW

**Comment by hsingyuc** [comment]
Hi @nielslange!  We are hoping to merge this PR for version `11.2.0`.  Can you take a look before the release?  Thank you!

**Review by nielslange — COMMENTED** [review]
Thank you for your message, @hsingyuc. This is the inaugural request we've received to graduate an experimental flag from someone outside the @woocommerce/rubik and @woocommerce/woo-fse teams. To ensure alignment among our teams regarding the process, I've initiated an internal discussion in p1695394188283659-slack-C02UBB1EPEF.

~Upon reviewing the PR, the changes appear sound; however, I’ve identified a couple of points that require attention:~

- ~The title employs the term feature flag, yet the modifications in the code reference the experimental flag.~
- ~The [Feature Flags and Experimental Interfaces](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md#features-flags-and-experimental-interfaces-) document continues to enumerate the [Experimental flags](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md#experimental-flag) for both the Order Route ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/b4a9dc9334f82c09f533b0f88c947b5c34e4e546/src/StoreApi/RoutesController.php#L65-L67)) and the Checkout Order Route ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/b4ba06a6242cbb6a64d2ec554a263ebe60d8d3af/src/StoreApi/RoutesController.php#L67)).~

~Could you please modify the PR title and update the documents to facilitate a swift merger of the PR once consensus is reached within our teams?~

I took care of these two points.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @hsingyuc. I've successfully tested the changes and in p1695631755430759-slack-C02UBB1EPEF, we agreed on graduating these two experimental endpoints. I'll merge this PR now, and it should be shipped with the WooCommerce Blocks 11.2.0 release.

**Comment by hsingyuc** [comment]
Thank you for your help, @nielslange!

**Comment by ralucaStan** [comment]
@hsingyuc Considering these endpoints are now public we should document them under https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/README.md#resources-and-endpoints. When do you think you could follow up with a PR for this addition?

**Comment by hsingyuc** [comment]
Thank you for the reminder @ralucaStan! PR opened here https://github.com/woocommerce/woocommerce-blocks/pull/11157

**Pull request merged**
