### PR TITLE
Move surrounding blocks from Products block when converting the Classic Template to Blockified one

### LINKED ISSUE #8872: Blockified Product Archive: Move the surrounding blocks outside of Products block
### Description
When converting the Classic Template to Blockified template the surrounding blocks (Btreadcrumbs, Store Notices, Product Result Count and Catalog Sorting) were included as inner blocks of Products block. But that has a consequence that if user changes pattern of Products block, the other blocks are removed.
To avoid this confusing behaviour, surrounding blocks should be moved outside of the Products block.

### Notes
Change must be applied in:
- [Product Archive conversion](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/classic-template/archive-product.ts)
- [Product Search Result conversion](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/classic-template/product-search-results.ts)
- [Product Archive Template](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/blockified/archive-product.html)
- [Product Search Results Template](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/blockified/product-search-results.html)

### PR DESCRIPTION
**Pull request by kmanijak**
When converting the Classic Template to Blockified template the surrounding blocks (Breadcrumbs, Store Notices, Product Result Count and Catalog Sorting) were included as inner blocks of Products block. But that has a consequence that if user changes pattern of Products block, the other blocks are removed.
To avoid this confusing behaviour, surrounding blocks are moved outside of the Products block in this PR.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8872

### Screenshots
Blockified template after conversion. Before all the blocks were inside the Products block, now they are moved outside.

| Before | After |
| ------ | ----- |
|    image    |   image    |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing
There are two parts, one can be tested in an experimental build and the second can be only tested with the manual code change:

**Experimental**

###### Prerequisites:
- WordPress: >=6.1
- Make sure Product Catalog/Products by Category/Products by Attribute/Products by Tag/Product Search Results templates are cleared out to the default state. To achieve that:
    - Go to (/wp-admin/site-editor.php?postType=wp_template)
    - Click three dots next to template and click "Clear customizations"

###### Steps to reproduce:
1. Enter the Product Catalog template
2. Open List View of the blocks
3. Click "Upgrade to Products block" button
4. **Expected:** WooCommerce Product Grid Block is replaced with blocks in such hierarchy (see screenshot)
image

5. Repeat the above for Products by Category/Products by Attribute/Products by Tag
6. **Expected:** WooCommerce Product Grid Block is replaced with blocks in such hierarchy (see screenshot - mind additional "Term Description" block)
image

7. Repeat the above for Product Search Result
8. **Expected:** WooCommerce Product Grid Block is replaced with blocks in such hierarchy (see screenshot)
image

**Requiring manual code change - do not include in the Testing Notes**
1. Follow the same prerequisites as above
2. Uncomment [these](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L391) and [these](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L482-L484) lines (don't forget to remove the trailing dot)
3. Go to Product Catalog, Products by Category/Products by Attribute/Products by Tag and Product Search Result
4. **Expected:** Blockified template is loaded automatically with the same hierarchy as above (be mindful about differences between templates

* [] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### CODE REVIEW

**Review by thealexandrelara — COMMENTED** [review]
Thank you for working on this @kmanijak! Looking good, I have just a question regarding the manual testing step, you said to uncomment [this line](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L391), the [line above](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L390) we have the following piece of code commented:

```
// $this->package->is_experimental_build() &&
```

Should I uncomment this part as well?

**Comment by kmanijak** [comment]
> `// $this->package->is_experimental_build() &&`
> Should I uncomment this part as well?

Hi @thealexandrelara, yes, you should for now. I mean, initially, we would like to keep it behind the experimental flag and then expose it as a feature plugin.
But for the sake of testing, you should uncomment that line as well (I'll update the testing steps).

**Review by thealexandrelara — APPROVED** [review]
Awesome work @kmanijak, thank you for your work on this. 🚀 

Not a blocker, but I noticed that there is a `.` (dot) left [at the end of this line](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L484) so when I removed the comment it was displaying an error

**Comment by kmanijak** [comment]
> Not a blocker, but I noticed that there is a . (dot) left [at the end of this line](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L484) so when I removed the comment it was displaying an error

Yes, the dot is forced by the linter (every comment must end with a dot), hence it's mentioned in the testing steps:

> 2. Uncomment [these](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L391) and [these](https://github.com/woocommerce/woocommerce-blocks/blob/001685f6f89cb43e9341e76ca1124c60db62c110/src/BlockTemplatesController.php#L482-L484) lines **(don't forget to remove the trailing dot)**

But you spotted that! 👍 thanks for a review 💪

**Pull request merged**
