### PR TITLE
Add a default attribute to the pattern if exists

### LINKED ISSUE #7190: Filter patterns preview showing Filter by Attribute in Edit view.
## Describe the bug

When you search the Block Inserter > Patterns library for WooCommerce patterns, when you come to the WooCommerce Product Filters pattern you are able to see in the preview that the Filter by Attribute block is rendered in Edit mode. Because of this the preview does not look appealing.

## To reproduce

1. Go to Appearance > Editor > All Templates > Product Catalogue
2. Open the Block Inserter, then select Patterns tab
3. On the dropdown click WooCommerce to view WC available patterns.
4. See the pattern rendering the Filter by Attribute block in Edit mode.

## Expected behavior

The Filter by Attribute block should render an example preview.

## Screenshots

Screenshot 2022-09-21 at 12 35 40

### PR DESCRIPTION
**Pull request by albarin**
This PRs gets the current attributes in the store and uses the first one (if any) to render the filters by attribute preview and as default in the filters pattern.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/7190
### Screenshots

| Before | After |
| ------ | ----- |
|image|image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Create a new page or post.
2. Open the block inserter and search for the `WooCommerce Product Filters` pattern.
3. Check the preview image of the pattern in the inserter and make sure you see one attribute selected and not the "edit" view of the filter by attribute block (see screenshot above).
4. If the store does not have any attributes you should still see the "edit" view though.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> WooCommerce Product Filters pattern: improve the preview of the Filter by Attribute block.

### CODE REVIEW

**Review by Aljullu — APPROVED** [review]
Nice improvement, thanks @albarin! LGTM, but one small thought: should we use `intval()` or `esc_attr()` instead of `esc_html()` to print the attribute id? What do you think?

**Comment by albarin** [comment]
> Nice improvement, thanks @albarin! LGTM, but one small thought: should we use `intval()` or `esc_attr()` instead of `esc_html()` to print the attribute id? What do you think?

Sure, you are right, I just pushed the change, thanks!

**Comment by Hakenstein** [comment]
Show more missing on frontend (Gutenberg Block Editor). Appears in the Widget Dashboard section.

Fix issue "limit" in attribute-filter-wrapper--stock-filter-wrapper-frontend.js

**Comment by Aljullu** [comment]
Hi there, @Hakenstein, it's not clear to me what exactly you are describing. Would you mind opening a [new issue](https://github.com/woocommerce/woocommerce-blocks/issues/new/choose) with testing steps so we can investigate it further? Attaching some screenshots would be super helpful. Thanks in advance.

**Pull request merged**
