### PR TITLE
Fix white background on Block Title 

### LINKED ISSUE #1203: Inconsistent background color for pagination in 2020 theme
**Describe the bug**
Pagination seems to have a background in the frontend but doesn’t have any background in the editor.

**To Reproduce**

1. install 2020 theme
2. see a page with All Products
3. Pagination has a background
4. See the color

**Expected behavior**
Pagination buttons shouldn’t have a background color

**Screenshots**
Screen Shot 2019-11-19 at 9 22 59 AM

**How to fix**
this code in 2020 is overriding the block styling, even though this selector seems more generic than `.wc-block-pagination-page` because of the `:not` coupled with a class, we can enter a specificity war with the theme or we can submit a patch to 2020.

```css
button:not(.toggle) {
    background-color: #cd2653;
}
```

### PR DESCRIPTION
**Pull request by senadir**
This PR builds on #1240 by removing the background color on title blocks so it works well with 2020 and any theme that defines a background color for the editor.

Fixes #1203

### Screenshots
image

### How to test the changes in this Pull Request:

1. Activate 2020
2. Insert a filter related block
3. No background

### Changelog

> fix white background bug on 2020 theme inside the editor

### CODE REVIEW

**Comment by nerrad** [comment]
Has testing included making sure this doesn't cause regressions or unexpected side-effects on other themes?

**Comment by senadir** [comment]
> Has testing included making sure this doesn't cause regressions or unexpected side-effects on other themes?

@nerrad This was tested in 2020, 2019 and Storefront, changes should be scoped to the editor in future, maybe introduce an editor only stylesheet in the future?

**Comment by Aljullu** [comment]
> Has testing included making sure this doesn't cause regressions or unexpected side-effects on other themes?

This PR is changing the styles of a CSS added in #1240. And that PR only changes a class that was added in 2.5. So only themes that added styles to 2.5 blocks might be affected, which I imagine are very few if not 0.

> @nerrad This was tested in 2020, 2019 and Storefront, changes should be scoped to the editor in future, maybe introduce an editor only stylesheet in the future?

Actually, if you name the CSS file as `editor.scss` it will only be loaded in the editor.

**Comment by nerrad** [comment]
> changes should be scoped to the editor in future, 

So that raises another thought, how does this affect how things look in earlier WP versions.  For some blocks we currently support back to WP 5.0, has that been tested?

> maybe introduce an editor only stylesheet in the future?

If you think it would be useful and have a measurable impact on devex and bundle sizes in different contexts, sure :). Can be done separately from this pull.

**Comment by senadir** [comment]
>So that raises another thought, how does this affect how things look in earlier WP versions. For some blocks we currently support back to WP 5.0, has that been tested?

For now, these changes only affect the following blocks
- Filter by Price
- Filter by Attribute
- Active Filters

All require 5.3 so it’s safe in that side
Also, this class targets the textarea inside the `h*` element, that textarea is only present in the editor, nothing is leaking to the frontend

**Comment by senadir** [comment]
>Actually, if you name the CSS file as editor.scss it will only be loaded in the editor.
TIL, changed.

**Pull request merged**
