### PR TITLE
Add Product Collection Grid pattern

### LINKED ISSUE #9368: Product Collection - Patterns: Grid
### Description
Implement the pattern

### Image
image

### PR DESCRIPTION
**Pull request by kmanijak**
## What

Add Product Collection Grid pattern

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9368

## Why

This is one of the patterns from a set of patterns we'd like to provide for Product Collection

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

0. At this moment Product Collection is still experimental feature (PR to make it Core feature: https://github.com/woocommerce/woocommerce-blocks/pull/10524), hence the pattern is not included in the inserter. In order to test the pattern please remove this line: https://github.com/woocommerce/woocommerce-blocks/pull/10660/files#diff-d26dedf0a7efa88eae30cbe732192f2769376839845875e6e57505d33f19653cR6.
1. Go to Editor
3. Insert "Product Collection Grid" pattern
4. Save and go to frontend
5. Verify it looks like in the screenshots below

Known limitations:
- Product Price cannot be styled according to designs. This work is being covered in https://github.com/woocommerce/woocommerce-blocks/pull/9398

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

Reference | Editor | Frontend |
| ------ | ----- | ---|
| image |    image    |    image   |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Collection: new pattern "Product Collection Grid"

### CODE REVIEW

**Review by dinhtungdu — APPROVED** [review]
The PR was tested correctly according to the instruction, so I'm approving this PR!

But I have a question, is the missing of the add to cart button intentional?

**Review by dinhtungdu — COMMENTED** [review]
Do we want the pagination and no products found blocks for this pattern?

**Comment by kmanijak** [comment]
> is the missing of the add to cart button intentional?

According to the designs, yes 👍 

> Do we want the pagination and no products found blocks for this pattern?

I think "No Products" should be included. I'm not sure about pagination if the expectation is to keep one page only? @shaunandrews , could you clarify that part regarding Grid pattern (and other patterns) for Product Collection (AtfOeZIFizx7ASmoSUbNjD-fi-55-9579&t=rnEPoeIr070VybIn-0)?

**Comment by kmanijak** [comment]
> Do we want the pagination and no products found blocks for this pattern?
> I think "No Products" should be included. I'm not sure about pagination if the expectation is to keep one page only? @shaunandrews , could you clarify that part regarding Grid pattern (and other patterns) for Product Collection

I'm merging this PR. I think it's better to include the pagination by default and in case it's not expected, we can always amend the pattern to display single page only.

**Pull request merged**
