### PR TITLE
added code in ExperimentalOrderShippingPackages

### PR DESCRIPTION
**Pull request by Harshal662**
## What
added code in ExperimentalOrderShippingPackages

Fixes #
#10895

### CODE REVIEW

**Review by nielslange — CHANGES_REQUESTED** [review]
Thank you for your contribution, @Harshal662. We appreciate this very much. 

While reviewing this PR, I noticed a few things, that should be changed:
- Please replace _"added code in ExperimentalOrderShippingPackages"_ with a speaking title such as _"ExperimentalOrderShippingPackages: Add code snippet"_, which is the title of the corresponding issue.
- I see that you added `#10895` below `Fixes #`. Please replace these two lines with `Fixes #10895`. `Fixes` is one of several keywords that connects a PR with its corresponding issue. On https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue, you can find further information on this.
- I noticed that your PR description only shows the section _"What"_ and that all other sections have been removed. When in doubt, it's good not to delete them. For example, the following sections _"Why"_ and _"Testing Instructions"_ are essential for reviewers so that they know why a change was necessary and how the change can be tested. You can find a good example on #10930.
- I noticed that the format of the code snippet changed, e.g. some spaces went missing, other spaces have been added, and a line break had been introduced. Please use the original snippet, that is visible on #10895, without applying changes to it.
- Please define the language of the code example in the code fence block. On https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting, you can find an example. While the example is using `ruby`, in our case, we should use `js`. Doing so results in syntax highlighting, which increases the readability of the code example.
- Please remove the text `Code:`, which had been placed before the code fence block.
- Please move the code fence block between the texts _"This slot renders inside [...]"_ and _"Cart:"_, and make sure that there's a line break between the texts and the code fence block.

---

That's all for now. I hope my review is helpful. For any clarifications, please don't hesitate to ask. 😀

**Comment by nielslange** [comment]
Hello @Harshal662, I just want to double-check if my feedback in https://github.com/woocommerce/woocommerce-blocks/pull/10929#pullrequestreview-1625971408 was clear and if you're still working on this issue.

**Comment by Harshal662** [comment]
So sorry I am busy with some work cant complete it. Again Sorry for not able to do it.

**Comment by nielslange** [comment]
> So sorry I am busy with some work cant complete it. Again Sorry for not able to do it.

Thanks for letting me know, @Harshal662. In this case, I'll close this PR and unassign you from the issue #10895 so that someone else can be assigned. Nevertheless, thanks for volunteering to work on this issue in the first place, and it would be nice for future contributions from you when you have more time. 😀

**Pull request closed without merging**
