### PR TITLE
Products: Update product element margins in patterns

### PR DESCRIPTION
**Pull request by danieldudzic**
Based on @vivialice feedback on the product elements spacing, I have decided to decrease the bottom margins to `12px` (`0.75rem`) and reset top margins to `0` (where possible) in order to improve consistency.

This PR is a part of #7954

### Screenshots

| Before | After |
| ------ | ----- |
|before-6|after-6|

#### User Facing Testing

1. Add the **Products** block.
2. Add WooCommerce Products patterns:
	- WooCommerce 1:1 Image 4-Column Products Row
	- WooCommerce 3-Column Product Row
	- WooCommerce 4-Column Product Row
	- WooCommerce Large Image Product Gallery
	- WooCommerce Minimal 5-Column Products Row
	- WooCommerce Minimal Product List
	- WooCommerce Product Gallery
	- WooCommerce Product list with 1:1 images
	- WooCommerce Product list with full product description

3. Ensure all margins are displaying correctly both in the editor and the frontend.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Products: Improve spacing consistency of product elements in patterns.

### CODE REVIEW

**Comment by gigitux** [comment]
Code side looks okay. Not sure how I can be sure that the outcome layout is the desirable one. 
@vivialice do you want take a look?

**Comment by imanish003** [comment]
Hi @gigitux,

After comparing the updated patterns in this pull request with the trunk, I believe everything looks good. In my opinion, we can go ahead and merge this PR instead of waiting for a design review, which is currently a blocker. Additionally, as mentioned in the PR description, these changes were discussed between Danny and Viv in a zoom call, which gives us more confidence in the changes.

@gigitux @tjcafferkey What do you think?

**Comment by tjcafferkey** [comment]
@imanish003 thanks for taking a look at this, if we have tested against multiple themes and we're confident in the changes I don't see why these can't be merged.

**Comment by gigitux** [comment]
Yep, I agree with you, folks!

**Review by gigitux — APPROVED** [review]
LGTM!

**Pull request merged**
