### PR TITLE
Suggest using `git cherry-pick` instead of `hub am -3` in release docs

### PR DESCRIPTION
**Pull request by Aljullu**
In PRs, we use `squash and merge` to keep history clean, but in release notes we were suggesting to use `hub am -3`, which does exactly the opposite and cherry-picks PRs commit-by-commit.

I noticed it when importing #1841 to `release/2.5`:
* `hub am -3 https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1841` was adding 3 commits.
* `git cherry-pick 51fbff74c7ed04a61658055ebf9d61720eaee586` was adding 1 commit with the same title and description as it has in `master`.

I think we should try to keep the release branches history as similar to master as possible so it's easy to track which PR added each change.

### CODE REVIEW

**Comment by mikejolley** [comment]
Hub also supports cherry picking by URL https://hub.github.com/hub-cherry-pick.1.html

**Comment by Aljullu** [comment]
> Hub also supports cherry picking by URL https://hub.github.com/hub-cherry-pick.1.html

@mikejolley Is there any benefit on using Hub over vanilla git if both commands are equivalent? I don't have any preference, just wondering. :slightly_smiling_face:

**Comment by mikejolley** [comment]
@Aljullu doesn't git require a specific sha?

**Comment by Aljullu** [comment]
@mikejolley It requires the same hash that is already contained in the URL:

* URL: `https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/51fbff74c7ed04a61658055ebf9d61720eaee586`

* Hash: `51fbff74c7ed04a61658055ebf9d61720eaee586`

**Comment by mikejolley** [comment]
@Aljullu Ultimately it doesn't matter because it's down to the user, but since we recommend hub anyway, and it works well, using it's cherry picking functionality has the advantage of allowing you to lazy paste the URL rather than a SHA.

There is also https://hub.github.com/hub-merge.1.html with the `--squash` flag I think would do what you want?

**Comment by Aljullu** [comment]
> @Aljullu Ultimately it doesn't matter because it's down to the user, but since we recommend hub anyway, and it works well, using it's cherry picking functionality has the advantage of allowing you to lazy paste the URL rather than a SHA.

Makes sense. :+1: 

> There is also https://hub.github.com/hub-merge.1.html with the `--squash` flag I think would do what you want?

I couldn't get it to work as I expected. It was merging the PR but changes were not committed. Also it seems to auto-close PRs, which shouldn't be a problem but might be something unexpected in some cases.

So I ended up going with `hub cherry-pick` as you initially suggested. Done in 3bf0b57682d7b59339398ba0ed9221484cb19540.

**Pull request merged**
