### PR TITLE
Add/featured category focus pattern

### LINKED ISSUE #9101: Create `Featured category: focused` pattern
The `Featured category` block does not allow to move the text & button to the bottom of the image, we can use the `Cover` block with a `Paragraph` and `Button` or maybe add more customization options to the `Featured category` block.

Check Figma designs F5AAbRJOGbTeEweXPFtHgf-fi-1540_33407 for the latest updates and mobile views.

### PR DESCRIPTION
**Pull request by roykho**
Closes https://github.com/woocommerce/woocommerce-blocks/issues/9101

This PR adds the Category Focus pattern.

#### User Facing Testing

1. Create a page and use the block inserter->patterns->WooCommerce and to insert the Featured Category Focus.
2. Notice the preview shows per design screenshot shown above.
3. Insert the pattern and then update/save and check the frontend and ensure it is displaying as the screenshot above.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Add Featured Category pattern

### CODE REVIEW

**Comment by albarin** [comment]
@roykho shouldn't this be a `Featured Category` block? But in that case, it would be the same as this one since we cannot move the text & button 🤔

**Comment by roykho** [comment]
@albarin - I just commented in the other https://github.com/woocommerce/woocommerce-blocks/pull/9284 where I will redo that with core blocks so we can make it as designed.

**Comment by albarin** [comment]
> @albarin - I just commented in the other #9284 where I will redo that with core blocks so we can make it as designed.

Got it!

I'm not seeing the bottom margin as in the screenshot you added to the description 🤔 
Screenshot 2023-05-02 at 15 45 48

**Comment by roykho** [comment]
Strange as this is what I see

**Comment by roykho** [comment]
@albarin - I push up a change to explicitly set the padding. Maybe this will show better on your end. I also reduced the image a bit to align more with the proposed design.

**Review by albarin — APPROVED** [review]

**Pull request merged**
